### ISSUE TITLE
Target gets duplicated depending on transformation input

### ISSUE THREAD

**Issue by bart1** [ropensci/drake#1010]
Sorry for reporting all these strange edge cases, it took me a while to reduce the plan as much as possible from the large plan of the original analysis. It seems the bug is not reproduces if the targets `br` or `dataTrainList` are not included even though they seem independent. In this case depending on the input to the crossing of `data` the target `dataTestList` gets duplicated. It seems this duplication only occurs if the second element of `cvo` can be interpreted as a numeric (see the first two of the examples below). I expected in all cases below that only two targets for `dataTestList` would be generated.

``` r
require(drake)
#> Loading required package: drake
p<-drake_plan(trace=T,tidy_eval = T, transform = F,
  data = target(
    command = crossValOmit(radar, crossValOmission),
    transform = cross(radar=!!'dd',
      crossValOmission = !!cvo,
      .id = c(radar, crossValOmission)
    )
  ),
  br = target(
    command = annotate_model(data),
    transform = combine(data, 
                        .by = data)
  ),
  b = target(
    command = list(crossValId, data),
    transform = cross(data,
      crossValId = !!1,
      .id = c(radar, crossValOmission, crossValId)
    )
  ),
  a = target(
    command = list(b),
    transform = combine(b, .by = data)
  ),
  dataTrainList = target(
    command = list2(a, data),
    transform = map(a, data,
      .id = c(crossValOmission, radar)
    )
  ),
  dataTestList = target(
    command = list(a, data),
    transform = map(a, data,
      .id = c(crossValOmission, radar)
    )
  )
)
cvo<-c('a3', "2")
grep('dataTestList', transform_plan(p)$target, value=T)
#> [1] "dataTestList_2_dd"    "dataTestList_a3_dd"   "dataTestList_2_dd_2" 
#> [4] "dataTestList_a3_dd_2"
cvo<-c('3', "2")
grep('dataTestList', transform_plan(p)$target, value=T)
#> [1] "dataTestList_2_dd"   "dataTestList_3_dd"   "dataTestList_2_dd_2"
#> [4] "dataTestList_3_dd_2"
cvo<-c('3', "a2")
grep('dataTestList', transform_plan(p)$target, value=T)
#> [1] "dataTestList_3_dd"  "dataTestList_a2_dd"
```

<sup>Created on 2019-09-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
Where is the variable `dd`?

**Comment by wlandau** [comment]
Oh, it's supposed to be just a string. Never mind...

**Comment by bart1** [comment]
yes sorry that was a quick hack to reduce the multiplication that was in the original plan

**Comment by wlandau** [comment]
The problem actually has to do with `NA` values. We need to remove them from the grid before we apply `map()`. Working on a patch, but a meeting is about to interrupt me...

**Comment by bart1** [comment]
No problem your amazingly responsive in any case.

**Comment by wlandau** [comment]
Should be fixed now. `map()` is now better at respecting the graph topology (e.g. nestings) of old grouping variables.
