### ISSUE TITLE
dry-run option for `clean()`

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#1014]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

Would it makes sense to have a `dry_run` argument to `clean()` to be able to check which targets will be removed from the cache? Especially when using `tidyselect` helpers it is unclear which targets will be affected.

**Comment by wlandau** [comment]
Something like it, sure. `make()` has `outdated()` and `recoverable()`, and unmaking targets is high-stakes too. Trying to decide between `clean(dry_run = TRUE)` and `cleanable()`...

**Comment by wlandau** [comment]
Hmm... the word "cleanable" does not actually get at the idea, and `dry_run` would make the return value of `clean()` less consistent than I would like. Some other possible names:

- `dry_clean()`
- `mock_clean()`
- `predict_clean()`
- `list_clean()`
- `peek_clean()`

Any sound good to you? Got a better idea for a name?

**Comment by wlandau** [comment]
Let's go with `which_clean()`.

**Comment by pat-s** [comment]
I am used to `clean(dry_run = TRUE)` from other tools but I am fine with any. :+1: 

I even thought if this might server as a default to prevent undesirable events of people deleting important things - but I vaguely remember there is another option to undo cache cleaning, isn't it?

**Comment by wlandau** [comment]
Yes, to undo `clean(garbage_collection = FALSE)`, run `make(recover = TRUE)`. It's not a perfect inverse transformation (it could recover additional targets and build others) but it does the job.

What other tools support `clean(dry_run = TRUE)`? It would be nice to be consistent with what other developers do, but I just feel like `clean(dry_run = TRUE)` would return a character vector and have no side effects  whereas regular `clean()` has large side effects and an empty return value. I would rather be internally consistent than externally consistent. The alternative to returning a character vector is printing to the console, and that does not seem ideal.

**Comment by pat-s** [comment]
> What other tools support clean(dry_run = TRUE)? 

Some shell and python tools AFAIR. Not sure if I've seen this in R before.

> I would rather be internally consistent than externally consistent. 

Totally understandable! I am totally fine with an extra function for it.
