### ISSUE TITLE
Return plan dataframe with r_plan() or such?

### ISSUE THREAD

**Issue by meowcat** [ropensci/drake#1016]
## Prework

- [X] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [X] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

For complex plans where a `target(..., transform=...)` generates a large list of targets, it is sometimes tedious to find the target names and load them using `loadd(mytarget_small_basicSettings_sensitive)` or such. For this I use:

```R
#' Find all targets generated from large plan logic
#' 
#' Returns all targets generated from a proto-target using
#' `target(..., transform=...)` and `map(), split(), cross(), combine()`.
#' 
#' 
#' @param plan The result of drake_plan(..., trace = TRUE)
#' @param name the "base target" for which to find all subtargets
#'
#' @return A character vector of all corresponding target names.
#' @export
#'
#' @examples
findMultipleTargets <- function(plan, name) {
  plan %>% 
    dplyr::select(target, tn = name) %>%
    dplyr::filter(target == tn) %>%
    dplyr::pull(target)
}
```

Then e.g. `findMultipleTargets(plan, "mytarget")`. 

However I have to run the `_drake.R` file by hand to get the plan back, which fills my R session with all the functions, environment things, and more stuff I don't necessarily need for this purpose (when I just quickly want to look into the targets to see whether they ran well, or try out a new workflow step offline). It would be convenient to get the plan back without running this in the session itself. 

Are there potentially more applications?

**Comment by wlandau** [comment]
I like your `findMultipleTargets()` function. This is part of what the trace was designed to do well.

I hesitate to implement `r_plan()`, though. `drake_config()` does not actually hold onto the plan itself, so `r_plan()` would need to assume something about how you generate the plan in your scripts and what you call it in memory. For you own workflows, you could consider defining an `r_plan()` function in your `.Rprofile` file that returns `source("R/plan.R")$value`.

As another stopgap, you could use [`tidyselect` functions](https://tidyselect.r-lib.org/reference/index.html) in `loadd()`. It does not use the trace, but it does the next best thing.

``` r
library(drake)
plan <- drake_plan(
  x = target(i, transform = map(i = !!seq_len(4))),
  y = target(i, transform = map(i = !!letters[seq_len(4)]))
)

plan
#> # A tibble: 8 x 2
#>   target command
#>   <chr>  <expr> 
#> 1 x_1L   1L     
#> 2 x_2L   2L     
#> 3 x_3L   3L     
#> 4 x_4L   4L     
#> 5 y_a    "a"    
#> 6 y_b    "b"    
#> 7 y_c    "c"    
#> 8 y_d    "d"

make(plan)
#> target x_1L
#> target x_2L
#> target x_3L
#> target x_4L
#> target y_a
#> target y_b
#> target y_c
#> target y_d

ls()
#> [1] "plan"

loadd(starts_with("x"))

ls()
#> [1] "plan" "x_1L" "x_2L" "x_3L" "x_4L"
```

<sup>Created on 2019-09-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
