### ISSUE TITLE
How to show file name only and not whole path with vis_drake_graph?

### ISSUE THREAD

**Issue by matthieugold** [ropensci/drake#1017]
Hi,

Following [this question](https://stackoverflow.com/questions/50725436/r-drake-file-out-name-with-variable) I understand that to save the results of an .Rmd file to a custom location (ie not the root of the .Rproj), a full path must be specified. For example to run an .Rmd and save it in the `docs` subfolder of my analysis i would do something like this for it to be tracked correctly:

``` r
  analysis_doc = render(
    knitr_in("docs/analysis_doc.Rmd"),
    output_file = file_out(!!str_c(here("docs", "sensitivity_analysis.html"))),
    quiet = TRUE
  )
```

This works fine.

The only inconvenient is that the whole file path appears on the `vis_drake_graph` which is not very nice...

Is there a way for the file name only to appear?

If not never mind...

Thank you for your help.
Matthieu

**Comment by wlandau** [comment]
`drake` currently shows the full path name, which I think is the right thing to do in most cases, but would it help if we wrapped the text? Wrapping long file paths seems okay.

**Comment by wlandau** [comment]
Yup, paths are currently out of control.

``` r
library(drake)
plan <- drake_plan(
  x = rmarkdown::render(
    knitr_in("/home/me/documents/files/projects/dissertation/artifacts/reports/chapter1.Rmd"),
    file_out("/home/me/documents/files/projects/dissertation/artifacts/reports/chapter1.html")
  )
)
config <- drake_config(plan)
#> Warning: knitr/rmarkdown report '/home/me/documents/files/projects/
#> dissertation/artifacts/reports/chapter1.Rmd' does not exist and cannot be
#> inspected for dependencies.
vis_drake_graph(config)
```

![](https://i.imgur.com/5pl8fhm.png)

<sup>Created on 2019-09-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
I think hard wrapping is the best we can do without losing important information. Now implemented.

``` r
library(drake)
plan <- drake_plan(
  x = rmarkdown::render(
    knitr_in("/home/me/documents/files/projects/dissertation/artifacts/reports/chapter1.Rmd"),
    file_out("/home/me/documents/files/projects/dissertation/artifacts/reports/chapter1.html")
  )
)
config <- drake_config(plan)
#> Warning: knitr/rmarkdown report '/home/me/documents/files/projects/
#> dissertation/artifacts/reports/chapter1.Rmd' does not exist and cannot be
#> inspected for dependencies.
vis_drake_graph(config)
```

![](https://i.imgur.com/KyQVohZ.png)

<sup>Created on 2019-09-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by matthieugold** [comment]
Yes wrapping is a great improvement, thanks! How do I get to do it?

**Comment by wlandau** [comment]
Development `drake` now has it. You can install it with `devtools::install_github("ropensci/drake")`. Then, the graph should hard-wrap labels longer than 49 characters.

**Comment by matthieugold** [comment]
Thanks!!

**Comment by matthieugold** [comment]
Dear M. Landau,

Related to this previous question, I noticed that when using absolute paths in the `output_file` argument, the maximum accepted length is 96 characters. Are you aware of this? Is there a way around it? Do you need a reproducible example?

All the best,
Matthieu

**Comment by wlandau** [comment]
Are you talking about the kind of warnings below?

``` r
library(drake)
plan <- drake_plan(
  x = rmarkdown::render(
    knitr_in("/home/me/documents/files/projects/dissertcts/rdissertation/artifacts/rdissertation/artifacts/rdissertatiacdissertation/artifacts/rts/rdissertation/artifacts/reports/chapter1.Rmd"),
    file_out("/home/me/docudissertatadsfasdflajksdfl;jkasldfkjlsion/artifacts/artifacts/rdissertation/artifacts/rdissertation/artifacts/rdissertation/artifacts/rdissertation/artifr1.html")
  )
)
config <- drake_config(plan)
#> Warning: knitr/rmarkdown report '/home/me/documents/files/projects/
#> dissertcts/rdissertation/artifacts/rdissertation/artifacts/
#> rdissertatiacdissertation/artifacts/rts/rdissertation/artifacts/reports/
#> chapter1.Rmd' does not exist and cannot be inspected for dependencies.
vis_drake_graph(config)
#> Warning in file.rename(tmp, filename): cannot rename file '/
#> private/var/folders/k3/q1f45fsn4_13jbn0742d4zj40000gn/T/
#> RtmpCHExnh/reprex14573557e4db6/.drake/scratch/file169f119579428'
#> to '/private/var/folders/k3/q1f45fsn4_13jbn0742d4zj40000gn/
#> T/RtmpCHExnh/reprex14573557e4db6/.drake/keys/objects/p-
#> F5UG63LFF5WWKL3EN5RXK3LFNZ2HGL3GNFWGK4ZPOBZG62TFMN2HGL3ENFZXGZLSORRXI4ZPOJSGS43TMVZHIYLUNFXW4L3BOJ2GSZTBMN2HGL3SMRUXG43FOJ2GC5DJN5XC6YLSORUWMYLDORZS64TENFZXGZLSORQXI2LBMNSGS43TMVZHIYLUNFXW4L3BOJ2GSZTBMN2HGL3SORZS64TENFZXGZLSORQXI2LPNYXWC4TUNFTGCY3UOMXXEZLQN5ZHI4ZPMNUGC4DUMVZDCLSSNVSA',
#> reason 'File name too long'
#> Warning in file.rename(tmp, filename): cannot rename file '/
#> private/var/folders/k3/q1f45fsn4_13jbn0742d4zj40000gn/T/
#> RtmpCHExnh/reprex14573557e4db6/.drake/scratch/file169f1fc8e644'
#> to '/private/var/folders/k3/q1f45fsn4_13jbn0742d4zj40000gn/
#> T/RtmpCHExnh/reprex14573557e4db6/.drake/keys/meta/p-
#> F5UG63LFF5WWKL3EN5RXK3LFNZ2HGL3GNFWGK4ZPOBZG62TFMN2HGL3ENFZXGZLSORRXI4ZPOJSGS43TMVZHIYLUNFXW4L3BOJ2GSZTBMN2HGL3SMRUXG43FOJ2GC5DJN5XC6YLSORUWMYLDORZS64TENFZXGZLSORQXI2LBMNSGS43TMVZHIYLUNFXW4L3BOJ2GSZTBMN2HGL3SORZS64TENFZXGZLSORQXI2LPNYXWC4TUNFTGCY3UOMXXEZLQN5ZHI4ZPMNUGC4DUMVZDCLSSNVSA',
#> reason 'File name too long'
```

![](https://i.imgur.com/t7DG05C.png)

<sup>Created on 2019-10-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This is an issue with `storr`, and it has been referenced at https://github.com/richfitz/storr/issues/94.

**Comment by matthieugold** [comment]
No it's not that. 

Actually it seems to be a windows specific issue. I have been trying to replicate the error on my Linux PC on which I have been working since I posted the issue and it works fine. I won't be back on my windows PC before 10 days. I will let you know at that moment.

**Comment by matthieugold** [comment]
Hi,

Sorry for the delay.

I set the path as specified in the initial questrion, and the error I get is the following:
`Error in file.rename(tmp, filename) : expanded 'to' name too long`

Does not happen for total length paths < 96 chars...

Let me know if you have a clue...

Best,
Matthieu

**Comment by wlandau** [comment]
Would you post a traceback?

**Comment by matthieugold** [comment]
```
20: file.rename(tmp, filename)
19: try_write_lines(text, filename, ..., scratch_dir = scratch_dir)
18: withCallingHandlers(try_write_lines(text, filename, ..., scratch_dir = scratch_dir), 
        error = function(e) unlink(filename))
17: write_lines(hash, self$name_key(key, namespace), scratch_dir = self$path_scratch)
16: self$driver$set_hash(key, namespace, hash)
15: .self$storr$set(key = key, value = value, ...)
14: dcst_set.default(value = value, key = key, ..., .self = .self)
13: dcst_set(value = value, key = key, ..., .self = .self)
12: config$cache$set(key = target, value = value, use_cache = FALSE)
11: store_object(target = target, value = value, meta = meta, config = config)
10: store_file(target = target, meta = meta, config = config)
9: store_single_output(target = file, meta = meta, config = config)
8: store_output_files(layout$deps_build$file_out, meta, config)
7: store_outputs(target = target, value = value, meta = meta, config = config)
6: conclude_build(build = build, config = config)
5: local_build(target = targets[i], config = config, downstream = targets[-seq_len(i)])
4: get(paste0("backend_", parallelism), envir = getNamespace("drake"))(config)
3: run_native_backend(config)
2: process_targets(config)
1: make(phthalates_descriptive)
```

**Comment by wlandau** [comment]
storr uses key files to represent drake objects, including the names of file_in() files. In order for the key file names of file_in() files to have legal characters and be unique on all systems, drake encodes them with Base32 encoding, which unfortunately produces long strings. Unfortunately, there is nothing we can do about it.

**Comment by matthieugold** [comment]
OK thanks. That's a shame!
