### ISSUE TITLE
Maintainer out of office

### ISSUE THREAD

**Issue by wlandau-lilly** [ropensci/drake#102]
I am attending the [RStudio Conference](https://www.rstudio.com/conference/) from January 31 through February 3, and I will be in transit back for most of February 4.

**Comment by wlandau-lilly** [comment]
I will open and close this issue for future vacations.

**Comment by wlandau** [comment]
Attending [R in Pharma](http://rinpharma.com/) (and presenting `drake`!) Conference + travel = Aug 14-17.

**Comment by wlandau** [comment]
On vacation September 15 through October 1. Posting this one early before I forget.

/ooo 9/15 until 10/2

**Comment by wlandau** [comment]
It worked!

**Comment by wlandau** [comment]
/ooo 2019-01-14 through 2019-01-24.

Attending [RStudio::conf(2019)](https://www.rstudio.com/conference/) and then giving [this talk](https://wlandau.github.io/drake-datafest-2019/#/) at [DataFest 2019](https://projects.iq.harvard.edu/datafest2019/home).

**Comment by wlandau** [comment]
I will be preoccupied with COVID-19 work for the next several weeks, and development of `drake` will slow down. I will still try to answer questions and fix bugs, but my responses will be slower than usual.

**Comment by wlandau** [comment]
Much of the work mentioned in https://github.com/ropensci/drake/issues/102#issuecomment-605740859 is wrapping up, so I am closing this issue for the present moment.

**Comment by wlandau** [comment]
This month will be another busy one for covid work.

**Comment by wlandau** [comment]
This time I really am out of office. Taking some time off between now and July 6.
