### ISSUE TITLE
Rethink the memoization strategy of drake_config()

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#1028]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [x] Advanced users: verify that the bottleneck still persists in the current development version (i.e. `remotes::install_github("ropensci/drake")`) and mention the [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity) of the [Git commit you install](https://github.com/ropensci/drake/commits/master).

## Description

Related: #504. The code analysis is currently memoized in an all-or-nothing fashion. The advantage is that we avoid creating a swarm of tiny files in the cache, but it is also brittle: if a single command changes, we reanalyze *all* the commands. The bottleneck is serious.

![config](https://user-images.githubusercontent.com/1580860/66651616-74c99080-ec01-11e9-93f4-e79e57257a2f.png)

A simple alternative is to memoize every single call to `analyze_code()` in `create_drake_layout()`, but we have thousands of those calls every `make()`, so that has its own efficiency issues. @gmbecker suggested storing this information in the plan itself. Maybe that's worth exploring more.

**Comment by wlandau** [comment]
Compared to `outdated()` (which is always called from `make()`) `drake_config()` is not the bottleneck. 

![Screen Shot 2019-10-11 at 3 26 50 PM](https://user-images.githubusercontent.com/1580860/66679225-ba0ab400-ec3b-11e9-8ce5-2b339fbecaa5.png)

**Comment by gmbecker** [comment]
So id need to know a bit more before I could comment super in detail, but I have thought some about this. If interested you can see chap 4 of my thesis [here](https://pqdtopen.proquest.com/pubnum/3685178.html?FMT=AI), in particular The limitations and drawbacks section 4.2 for some discussion about issues related to this. 

The crux is that yes, individual expression caching can be cumbersome, but its also (often) more or less the right thing to do. Or rather, less wrong. Changing a graphical parameter in the final visualization step of an involved analysis shouldn't require any sort of rerunning or reprocessing of the steps before it, where as a change at the beginning /sometimes/ (but not always!) should cascade through some or all of the handling of the expressions that follow.

Happy to chat more here or via a different medium if you want to talk about the issues youer' trying to tackle in more detail

**Comment by wlandau** [comment]
Thanks, Gabe! I actually prefer GitHub threads like this for extended discussions.

Have you explored memoization in batches? If we memoize the static code analysis of every single expression, there seems to come a point where the expression is too small to be worth it. Here is a benchmark on my home Linux desktop, which has an M.2 NVMe drive. (It seems to be faster than the hardware at work, though I have not tested the file system rigorously.)

``` r
define_model <- function(rec, units1, units2, act1, act2, act3) {
  input_shape <- ncol(
    juice(rec, all_predictors(), composition = "matrix")
  )
  keras_model_sequential() %>%
    layer_dense(
      units = units1,
      kernel_initializer = "uniform",
      activation = act1,
      input_shape = input_shape
    ) %>%
    layer_dropout(rate = 0.1) %>%
    layer_dense(
      units = units2,
      kernel_initializer = "uniform",
      activation = act2
    ) %>%
    layer_dropout(rate = 0.1) %>%
    layer_dense(
      units = 1,
      kernel_initializer = "uniform",
      activation = act3
    )
}

# similar to drake:::memo_expr()
memo_expr <- function (expr, cache, ...) {
  if (is.null(cache)) {
    return(force(expr))
  }
  lang <- drake:::safe_deparse(match.call(expand.dots = FALSE)$expr)
  key <- digest::digest(list(lang, ...), algo = cache$hash_algorithm)
  if (cache$exists(key = key, namespace = "memoize")) {
    return(cache$get(key = key, namespace = "memoize", use_cache = FALSE))
  }
  value <- force(expr)
  cache$set(
    key = key,
    value = value,
    namespace = "memoize", 
    use_cache = FALSE)
  value
}

cache <- drake::new_cache(tempfile())

tmp <- memo_expr(
  drake:::analyze_code(define_model),
  cache = cache
)

microbenchmark::microbenchmark(
  reanalyze = drake:::analyze_code(define_model),
  memoize = memo_expr(
    drake:::analyze_code(define_model),
    cache = cache
  )
)
#> Unit: microseconds
#>       expr    min       lq     mean  median       uq       max neval
#>  reanalyze 648.45 689.8360 813.1703 731.231 908.4610  2383.181   100
#>    memoize 265.93 282.7995 498.1892 297.443 345.2145 15062.763   100

f <- function() {}

tmp <- memo_expr(
  drake:::analyze_code(expression()),
  cache = cache
)

microbenchmark::microbenchmark(
  reanalyze = drake:::analyze_code(expression()),
  memoize = memo_expr(
    drake:::analyze_code(define_model),
    cache = cache
  )
)
#> Unit: microseconds
#>       expr     min       lq     mean   median       uq     max neval
#>  reanalyze  70.778  84.0945 102.2990 100.7495 111.5045 221.902   100
#>    memoize 266.421 283.1535 311.7134 294.3290 331.8620 586.990   100
```

<sup>Created on 2019-10-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

By the way, I also share the concerns you mention in 4.2 about total cache size,  and I agree that garbage collection would be handy here.

**Comment by gmbecker** [comment]
So there were some allusions in that section, though I'm a bit surprised I didn't make it more explicit anywhere from the look of it, but yeah I did some things.  When processing sets of expressions RCacheSuite had a few mechanisms to try and figure out when to "clump" them together in a single cache. 

One was if multiple expressions in a row were modifying a symbol "in place" (ie an expression takes an object as an input and assigns the output back into the same symbol, a la `x <- x^2` then I had a heuristic that would figure those could be grouped together. I don't recall if I made that the default or not, and I never had a lot of data on its usage because RCacheSuite was never widely used, but intuitively it still seems seems like a pretty good guess in "non adverserial" natural code. The clumping behavior was user-definable as well, which is another thing that drake could benefit from if done right, I'd think. I apologize I'm not super familiar with the eux/API of drake in detail as I haven't used it myself, but some way of declaring "cache group" or similar when defining a workflow seems to me that it could be quite handy for users.

**Comment by wlandau** [comment]
Interesting. In script-based workflows, it seems reasonable for in-place modifications to form groupings. In `drake`, the most comparable thing I can think of is the natural of targets clusters in the dependency graph. Unfortunately, because of how users tend to interact with the DSL, these clusters tend to vary a lot in cardinality.

On reflection, for the purposes of speeding up `drake`'s preprocessing, it does not seem too bad to overestimate batch size. I tend to notice that `drake_config()` starts to slow down on slow file systems at around 1000 targets, so memoization batch sizes of 1000 commands seem reasonable to me.

**Comment by wlandau** [comment]
Ultimately, though, I think the best solution is going to be #685.

**Comment by wlandau** [comment]
We want memoization batches to be independent, deterministic, and similar in size. Proposal: use a hash function with intentional collisions.

``` r
library(drake)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

get_one_batch <- function(target, mod = .Machine$integer.max) {
  hash <- digest::digest(target, algo = "murmur32", serialize = FALSE)
  hexval <- paste0("0x", hash)
  utils::type.convert(hexval) %% mod
}

get_batch <- Vectorize(get_one_batch, "target")

plan <- drake_plan(y = target(f(x), transform = map(x = !!seq_len(1e4)))) %>%
  mutate(batch = get_batch(target, mod = 10))

plan
#> # A tibble: 10,000 x 3
#>    target command batch
#>    <chr>  <expr>  <dbl>
#>  1 y_1L   f(1L)       2
#>  2 y_2L   f(2L)       2
#>  3 y_3L   f(3L)       2
#>  4 y_4L   f(4L)       2
#>  5 y_5L   f(5L)       3
#>  6 y_6L   f(6L)       7
#>  7 y_7L   f(7L)       6
#>  8 y_8L   f(8L)       9
#>  9 y_9L   f(9L)       6
#> 10 y_10L  f(10L)      5
#> # … with 9,990 more rows

table(plan$batch)
#> 
#>    0    1    2    3    4    5    6    7    8    9 
#> 1012 1006  993 1012  933  984 1000 1032 1017 1011

plot(plan$batch)
```

![](https://i.imgur.com/ezqNqIp.png)

<sup>Created on 2019-10-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
The modulus is the number of possible batches, so unfortunately, it changes when we change the number of targets and fix the batch size. This is another reason to stick with a large batch size.

``` r
get_modulus <- function(x, batch_size) {
  out <- floor(x / batch_size) + (x > batch_size && x %% batch_size > 0)
  out + as.integer(out < 1)
}
get_modulus(1, batch_size = 1000)
#> [1] 1
get_modulus(999, batch_size = 1000)
#> [1] 1
get_modulus(2000, batch_size = 1000)
#> [1] 2
curve(get_modulus(x, batch_size = 1000), 0, 23100)
```

![](https://i.imgur.com/4YrlJIg.png)

<sup>Created on 2019-10-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
I think I am starting to see why batches should group the code together in an order that makes sense to the user.

I tried out an implementation in https://github.com/ropensci/drake/tree/1028, and the batches turned out to not be useful because targets are uniformly scattered over all the batches.

Suppose we start with this plan:

```r
plan <- drake_plan(
  x = target(i, transform = map(i = !!seq_len(2e3))),
  y = target(j, transform = map(j = !!seq_len(2e3)))
)
```

and modify it to 

```r
plan <- drake_plan(
  x = target(i, transform = map(i = !!seq_len(2e3))),
  y = target(j, transform = map(j + 1 = !!seq_len(2e3)))
)
```

Ideally this should only invalidate the preprocessing of the y's. But in https://github.com/ropensci/drake/issues/1028#issuecomment-543806973, *all* the batches get invalidated.

So batches should ideally be determined by graph topology. Unfortunately, at this stage in the preprocessing, we don't have graph topology yet. We could do text analysis on the target names to try to guess how the user invoked the DSL, but that does not seem likely to work very well.

This issue is starting to seem like a lot of work for not much gain in performance. And whatever we do, #685 will be superior because there will be dramatically fewer commands to analyze.

Tabling for now. May revisit.

**Comment by gmbecker** [comment]
I seem to be missing something here. Why use a hash and then batch in a way
that obfuscates the existing ordering drake already knows about (I assume?)

If you want similar batch deterministic batches just take the workflow
ordering and chunk it, in order, with whatever batch size that you want.
Where is the benefit of pseudo (but not really) randomizing what batches a
particular expression/call/whatever is placed in?

**Comment by wlandau** [comment]
> I seem to be missing something here. Why use a hash and then batch in a way
that obfuscates the existing ordering drake already knows about (I assume?)

The code analysis happens prior to the ordering. First we analyze commands, then we construct the graph. 

https://github.com/ropensci/drake/blob/570081975af518556bcd6d6cacb08a960bac34ea/R/drake_config.R#L571-L586

> Where is the benefit of pseudo (but not really) randomizing what batches a
particular expression/call/whatever is placed in?

I just thought it would help distributed the commands roughly evenly across the batches. I thought this would help invalidate stuff less often and improve the load balancing of parallel preprocessing. But as I found out first hand, this produces extremely brittle batches, so I no longer believe in the idea.

**Comment by gmbecker** [comment]
One thing you can consider, which might be a bit counter intuitive but I
suspect MAY actually turn out to help (potentially quite a bit) in the end
is doing two passes.

First, upon initial drake workflow creation, you analyze and order it.
Then, as a *second* pass, you process and cache it using the ordering. Yes,
the upfront cost will be somewhat larger (exactly how much larger depends a
bit on how you'er doing things). Thinking in terms of CodeDepends, which I
know you're not using but thats the framework my mind uses when talking
about code analysis, it seems like it would be relatively
straightforward to write code that "merges" two analyzed ScriptNodeInfo
objects in a way that I *think* we could be guaranteed will be correct.
Outputs are the union of the outputs of all the nodes being merged, inputs
would be more complicated but still straightforward (inputs is the union of
all inputs MINUS any inputs that were outputs of earlier expressions in the
merge set).

There are definitely some details that it would be important to get right,
and some sitting on hands and thinking about corner cases to make sure that
merge would be fully safe, again depending on exactly what you'er doing now
and what info you need, but i'm pretty confident it would be doable.

**Comment by wlandau** [comment]
Interesting. Yes, it does sound involved, but I think the up-front runtime overhead could be the same if done properly. I will think about it.

**Comment by wlandau** [comment]
Somewhat related: https://stackoverflow.com/questions/59167441/faster-alternative-to-deparse. It would be nice to somehow deparse lots of expressions while avoiding repeated calls to `.deparseOpts()`.
