### ISSUE TITLE
Mention .id_chr n in file_out(in) documentation

### ISSUE THREAD

**Issue by smingerson** [ropensci/drake#1029]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description
The only place I have seen `.id_chr` is a single sentence and example in the [manual](
https://ropenscilabs.github.io/drake-manual/plans.html#target-names).

The usage is clear, my gripe is how long it took me to find this when I was trying to generate a file per target. 

## Suggested improvement
Mention `.id_chr` symbol  in `?file_out()`, perhaps in `...` documentation, and/or adding an example to `file_out()` showcasing use. Same could be mentioned in `...` for `?file_in()` if appropriate.

I'd be happy to put together a PR for this if you agree.

**Comment by wlandau** [comment]
Thanks, a PR would be great! `.id_chr` can go anywhere in a command, but it is most useful in `file_out()` and `file_in()`. Perhaps the help file `@examples` would also be a good place for a mention.

**Comment by wlandau** [comment]
Fixed in #1032
