### ISSUE TITLE
Incorrect hyperlink in drake manual toc

### ISSUE THREAD

**Issue by johnbaums** [ropensci/drake#1030]
The Chapter 12 heading (**12 Storage**) in the manual's table of contents is hyperlinked to a subsection of Chapter 9 (**9.7.3 Storage**, https://ropenscilabs.github.io/drake-manual/hpc.html#storage).

**Comment by wlandau** [comment]
Should be fixed in https://github.com/ropenscilabs/drake-manual/commit/53c1a6dc2b589e467e36dea4a991094da928102f.

Could we move issues like these to the manual's issue tracker? It is at https://github.com/ropenscilabs/drake-manual/issues.

**Comment by johnbaums** [comment]
Thanks - my bad, will post there in future.
