### ISSUE TITLE
 Undefined control sequence in manual pages

### ISSUE THREAD

**Issue by jeroen** [ropensci/drake#1040]
When I run `R CMD build` on drake, it errors as follows (both on linux and mac):

```
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
LaTeX errors found:
! Undefined control sequence.
<argument> Rfn.\lifecycle
                          .Rlbrace.maturing.Rrbrace.
l.7394 ...s}{\lifecycle.Rlbrace.maturing.Rrbrace.}

```

It seems to pass on travis. Any idea what I am doing wrong?

**Comment by wlandau** [comment]
I just started getting is error too, and [here it is on Travis](https://travis-ci.org/ropensci/drake/builds/604810233#L1389-L1398). I am not sure why, but I expect they are related to my use of lifecycle badges.

**Comment by wlandau** [comment]
My apologies: there is one place where I put `\lifecycle{}` under `@aliases` instead of `@title`. Patch forthcoming.
