### ISSUE TITLE
Feature request: Improved handling of seeding for parallel processes (reproducibility)

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#1048]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

First: Tremendous work closing all issues here and having a clean repo. A maintainers dream :star:!

I was just browsing in my what might be future directions for _drake_ and came across the topic of reproducibility when using parallel functions.

You might be aware of the fact that `set.seed()` does not guarantee reproducibility when using "PSOCK" or "multicore" approaches in R.

To achieve this, one needs to use `clusterSetRNGStream()` (PSOCK) or `set.seed(123456, "L'Ecuyer-CMRG")` (multicore). See https://stackoverflow.com/a/51347058/4185785. 

In practice I see that many user are not aware of that and just naively go with `set.seed()` and hope for R taking care.
Since _drake_ explicitly checks whats being handed over in `prework`, I was wondering if there could be little pointer such as 

"oh hey, you are using socket-based parallelization but we haven't found any call to `clusterSetRNGStream()`. You might want to add it for reproducibility reasons."

_Why do I think that something like this should live in _drake_?_ 

Because _drake_ operates like a wrapper around user code anyways and has the ability to easily check what's supplied via `prework`. This is not possible for other packages where users operate on a script base so other packages are not aware of what seed has been set by the user in the script.

In addition I was wondering if there could be a global check for any parallelization calls within targets that have been placed there by accident by the user (and not supplied via `prework`). This would be another "safeguard" to prevent _drake_ and reproducibility issues.

**Comment by wlandau** [comment]
It's a good thought, but I do not think this is something `drake` could do well. It would have to detect parallel calls with either static code analysis or by querying the operating system for new R processes, and both seem unreliable for this. For static code analysis specifically, we would only be able to catch explicit mentions of known HPC functions. Not only could we miss a large number of use cases, we would also have to constantly maintain it to keep up with new tools that come out. And if we try to catch a lot of tools, the extra code analysis could slow down performance.

I feel this belongs in https://github.com/ropenscilabs/drake-manual/issues/49. In fact, it could really help round off `drake`'s own seed handling and provide enough content for a full chapter.
