### ISSUE TITLE
drake project on multiple machines with github

### ISSUE THREAD

**Issue by nschiett** [ropensci/drake#1053]
Hi,

I am using drake for a project with some long calculations. All works well, except when I pull the project from github onto another computer. I would like to be able to use the loadd() function to retrieve targets on any computer when pulling the project from github without having to rerun make(). Is this possible?

I now get the following error: 
Error: drake failed to get the storr::storr_rds() cache at /media/nschiettekatte/DATA/phd/3.Global/global_proc/.drake. Something is wrong with the file system of the cache. If you downloaded it from an online repository, are you sure all the files were downloaded correctly? If all else fails, remove the folder at /media/nschiettekatte/DATA/phd/3.Global/global_proc/.drake and try again.
In addition: Warning message:
In file(file, "r") :
  cannot open file '/media/nschiettekatte/DATA/phd/3.Global/global_proc/.drake/config/hash_algorithm': No such file or directory

I checked and indeed the config folder inside .drake is not there. 
How do I force git to follow these hidden files so that I can load targets anywhere without rerunning everything? 

Thanks!

**Comment by wlandau** [comment]
`drake` assumes most people do not commit the cache to git, so it creates a `.gitignore` whenever it creates a new cache. However, it does not create a new `.gitignore` for old caches. So if you remove `.drake/.gitignore` without removing `.drake`, you should be able to commit the cache. Please let me know if that does not work.
