### ISSUE TITLE
Encoding problems with fst_dt

### ISSUE THREAD

**Issue by adamaltmejd** [ropensci/drake#1054]
Haven't been able to reproduce this yet on my local machine (Mac) but in my work I use a drake plan to build and process large amounts of data and since almost all targets are data.tables i recently switched to the `fst_dt` format which seems to have increased speeds a bit (although I think I'm limited by all storage being network storage).

Now I discovered that some files suffer from encoding problems after the switch. I think its related to how fst assumes constant encoding (see option `uniform_encoding` to `write_fst()`) but basically when I run the code to build a target manually everything looks good, but when I load the very same target from cache i get lots of garbled characters. Running `Encoding()` on the character string built manually yields c("unknown", "UTF-8") while the same on the one loaded from cache is just "unknown". Any suggestions? Can one pass uniform_encoding = TRUE to `format = "fst_dt"` somehow?

**Comment by adamaltmejd** [comment]
All the garbled characters are from strings with `stringi::stri_enc_mark()=="native"`. Maybe since its on windows, the file is saved with UTF-8 encoding and then read with windows encoding?

**Comment by wlandau** [comment]
From @MarcusKlik at https://github.com/fstpackage/fst/issues/155:

> The current behavior of fst is that it checks the encoding of the first element in a column. The encoding of that first element is stored and it's assumed that the remainder of the column uses identical encoding.

So perhaps the first element of your `data.table` has an unknown encoding and is throwing off the UTF-8 elements.

By the way, the default `uniform_encoding` argument of `write_fst` is already `TRUE`, and `drake` format specifications cannot accept custom arguments`.

**Comment by adamaltmejd** [comment]
Exactly, that was my though as well. So maybe the first rows are ASCII-characters, so write_fst does not set encoding to UTF-8 and then when its read it just assumes everything is native/Latin-1. Ah sorry meant setting `uniform_encoding=FALSE`.

**Comment by wlandau** [comment]
How hard would it be to prepend a row with an encoding that works everywhere?

**Comment by adamaltmejd** [comment]
Just tried and it actually doesn't help. Seems like the problem is that there are multiple character encodings in the same vector actually, so maybe something I have to fix already when loading the data. Running `write_fst` and then `read_fst` on the final data.table that I generated manually also produces the same problem. So seems like its not really a drake bug. Also setting `uniform_encoding=FALSE` just produces an error. Thanks for the help though!
