### ISSUE TITLE
Create `drake::target` with custom order of its arguments

### ISSUE THREAD

**Issue by mik3y64** [ropensci/drake#1056]
We have complex and large plans and there are certain patterns of `drake::target` we use on a daily basis. One solution we think of is creating a clone of `drake::target` with custom order of its arguments. 

```r
library(drake)

drake_plan(
  alphabets = letters[1:2],
  to_upper = target(
    toupper(alphabets),
    dynamic = map(alphabets)
  )
)

# # A tibble: 2 x 3
#   target    command            dynamic       
#   <chr>     <expr>             <expr>        
# 1 alphabets letters[1:2]       NA            
# 2 to_upper  toupper(alphabets) map(alphabets)

# custom `target` in our internal package and overwrite the original `drake::target`
target <- function(command, dynamic, ...) {
  drake::target(command = command, dynamic = dynamic, ...)
}

drake_plan(
  alphabets = letters[1:2],
  to_upper = target(  # custom `target` is called here
    toupper(alphabets),
    map(alphabets)    # omit `dynamic` parameter name
  )
)
# # A tibble: 2 x 2
#   target    command                                          
#   <chr>     <expr>                                           
# 1 alphabets letters[1:2]                                     

# Warning message:
# A grouping or splitting variable for target "to_upper" is missing or undefined. Transformation skipped and target deleted. 
```

Ideally, we would like to put this custom `target` in our internal package and overwrite the original `drake::target`

```r
target <- function(command, dynamic, format, trigger, ...) {
  drake::target(command = command,
                dynamic = dynamic,
                format = format,
                trigger = trigger,
                ...)
}
```

`drake::target` does not seem to be working the same way as
```r
custom_paste0 <- function(collapse, ...) paste0(collapse = collapse, ...)
paste0(letters[1:5], collapse = '_')
# [1] "a_b_c_d_e"
custom_paste0('_', letters[1:5])
# [1] "a_b_c_d_e"
```

**Comment by wlandau** [comment]
> drake::target does not seem to be working the same way as

`target()` is not a true function, just a part of the `drake_plan()` domain-specific language.

``` r
library(drake)
target(Sys.sleep(x), transform = map(x))
#> Warning: target() in drake is not a standalone user-side function.
#> It must be called from inside drake_plan(). Details: https://
#> ropenscilabs.github.io/drake-manual/plans.html#large-plans
#>        command transform
#> 1 Sys.sleep(x)    map(x)
```

<sup>Created on 2019-11-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

> One solution we think of is creating a clone of drake::target with custom order of its arguments.

I would advise a different tactic. If your team works with a special fork of `drake`, it will be difficult to keep up with the constant stream of bug fixes, and the plans you create will not be valid elsewhere. There is probably a metaprogramming solution that does not require hacking into `drake` itself.

**Comment by wlandau** [comment]
If you absolutely must promote `dynamic` in the signature of `target()`, something like the `reprex` below will let you avoid hacking into `drake`. However, **I strongly suggest that you stick to the original `drake_plan()` and write "dynamic" explicitly**. Compared to the confusion and dangers of forcing `dynamic` to swap places with `transform`, it is really not so bad.

``` r
library(drake)

mik3y64_plan <- function(...) {
  dots <- match.call(expand.dots = FALSE)$...
  args <- lapply(dots, match_target_call)
  do.call(drake_plan, args)
}

match_target_call <- function(arg) {
  if (drake:::is_target_call(arg)) {
    arg <- match.call(mik3y64_target, arg)
  }
  arg
}

# For match.call() only. Body does not matter.
mik3y64_target <- function(command, dynamic = NULL, transform = NULL, ...) {
  NULL
}

mik3y64_plan(
  alphabets = letters[1:2],
  to_upper = target(toupper(alphabets), map(alphabets))
)
#> # A tibble: 2 x 3
#>   target    command            dynamic       
#>   <chr>     <expr>             <expr>        
#> 1 alphabets letters[1:2]       NA            
#> 2 to_upper  toupper(alphabets) map(alphabets)
```

<sup>Created on 2019-11-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
