### ISSUE TITLE
rmarkdown::render output path depending on file name

### ISSUE THREAD

**Issue by kulinar** [ropensci/drake#1075]
Hi,

I absolutely love your work and the package is incredibly helpful. Thank you so much!

Today I came across the following very confusing behaviour:
 
Depending on the file name (with/without space) the knit directory of `rmarkdown::render()` will be different:

### Example:

```r
my_drake_plan <- drake_plan(
  knit_my_report = rmarkdown::render(
    drake::knitr_in("my_subdir/my_report.Rmd"),
    output_file = "my_report.html"
  ),
  knit_my_other_report = rmarkdown::render(
    drake::knitr_in("my_subdir/my report.Rmd"),
    output_file = "my report.html"
  )
)
```
Files `my_report.Rmd` and `my Report.Rmd`
```r
---
title: "my_report"
output: html_document
---
This is the current path `r getwd()`.

```

### Results:

`make(my_drake_plan)` will now yield two different results:

1. target `knit_my_report` yields the file `my_subdir/my_report.html` and `getwd()` gives `./my_subdir`
2. target `knit_my_other_report ` yields the file `./my report.html` and `getwd()` gives `./`

**Comment by wlandau** [comment]
Thanks, @kulinar.

I am afraid this behavior is due to `rmarkdown`, not `drake`. Perhaps post a question to the [RStudio Community forum](community.rstudio.com)?

In `drake`, I recommend using `file_out()` on the output HTMl files when you can, as in the example from `drake`'s README.

``` r
library(magick)
#> Linking to ImageMagick 6.9.9.39
#> Enabled features: cairo, fontconfig, freetype, lcms, pango, rsvg, webp
#> Disabled features: fftw, ghostscript, x11
library(magrittr)
library(rmarkdown)
library(webshot)

# Write the report sources.
lines <- c(
  "---",
  "title: \"my_report\"",
  "output: html_document",
  "---",
  "current path: `r getwd()`"
)

dir.create("dir")
writeLines(lines, "dir/my_report.Rmd")
writeLines(lines, "dir/my report.Rmd")

# Render the reports.
render("dir/my_report.Rmd", output_file = "my_report.html", quiet = TRUE)
render("dir/my report.Rmd", output_file = "my report.html", quiet = TRUE)

# The reports are in different places.
list.files()
#> [1] "dir"                    "my report.html"         "reprex_reprex.R"       
#> [4] "reprex_reprex.spin.R"   "reprex_reprex.spin.Rmd"
list.files("dir")
#> [1] "my report.Rmd"  "my_report.html" "my_report.Rmd"

# Display the reports.
webshot("my report.html", "my report.png", vheight = 200)
```

![](https://i.imgur.com/IpU41ZK.png)

``` r
webshot("dir/my_report.html", "my_report.png", vheight = 200)
```

![](https://i.imgur.com/7KWJzIC.png)

<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kulinar** [comment]
@wlandau Thank you for taking your time and the effort! It is much appreciated!
