### ISSUE TITLE
Prohibit concurrent calls to `make()` and `outdated(skip_imports = FALSE)` on the same cache?

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#1081]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

`make()` modifies the cache, so it might be a good idea to prevent two different calls to `make()` from fighting over each other. Likewise, `outdated()` (and functions that call it, such as `vis_drake_graph()` overwrite imported functions etc. in the cache as well. In the case of `outdated()`, maybe it would be enough to enforce `skip_imports` and throw an informative warning.

**Comment by brendanf** [comment]
I was doing this (in order to invoke groups of targets on different cluster nodes) but found that it corrupted my cache sometimes.  So I stopped, and I wouldn't recommend it to others.

**Comment by wlandau** [comment]
Yeah, I have heard reports of other users doing the same thing. Hopefully now with cache locking and an extremely verbose error message, we can educate users early on.
