### ISSUE TITLE
Feature Request: Allow dynamic branching work with parts of targets

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#1088]
## Prework

- [X] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [X] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

Would it be feasible to allow dynamic branching work with parts of targets (e.g. list elements or data.frame columns)?  The `test_plan` example below is similar to what I'm thinking, but it doesn't work while `test_plan2` (having the mapped item as a target) does work.

```r
library(drake)

list_plus <- function(x, y) x[[1]] + y
test_plan <-
  drake_plan(
    foo=as.list(1:10),
    baz=list(zop=foo),
    bar=
      target(
        list_plus(foo, 1),
        dynamic=map(foo)
      ),
    bat=
      target(
        list_plus(baz$zop, 1),
        dynamic=map(baz$zop)
      )
  )

test_plan2 <-
  drake_plan(
    foo=as.list(1:10),
    baz=list(zop=foo),
    bar=
      target(
        list_plus(foo, 1),
        dynamic=map(foo)
      ),
    newdata=baz$zop,
    bat=
      target(
        list_plus(newdata, 1),
        dynamic=map(newdata)
      )
  )

make(test_plan)
make(test_plan2)
```

Related to #1087.

**Comment by wlandau** [comment]
I knew this would come up eventually. `drake` does a lot of work under the hood to load and unload the correct dependencies and sub-dependencies into memory at the right times. To accomplish all that, each (sub-)dependency needs a formal name of its own. Some examples where names are necessary:

https://github.com/ropensci/drake/blob/687ee98c91a3d1cb8e1a6fb75e42fbf9703af577/R/manage_memory.R#L210-L312

https://github.com/ropensci/drake/blob/687ee98c91a3d1cb8e1a6fb75e42fbf9703af577/R/dynamic.R#L613-L638

A workaround looks something like this.

```r
drake_plan(
  foo = as.list(seq_len(10)),
  baz = list(zop = foo),
  bar = target(
    list_plus(foo, 1),
    dynamic = map(foo)
  ),
  baz_zop = baz$zop, # One extra target.
  bat = target(
    list_plus(baz_zop, 1),
    dynamic = map(baz_zop)
  )
)
```

**Comment by billdenney** [comment]
"I knew this would come up eventually." And, I bring it up on day 2.  :)

Thanks again for the quick response.  I am using the work-around.
