### ISSUE TITLE
Use getVDigest()

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#1092]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

Re https://github.com/eddelbuettel/digest/issues/139. Should speed up #1089.

**Comment by wlandau** [comment]
Between https://github.com/ropensci/drake/commit/c51d229cd55ad25805d74521f2a4d0ac3ee43d6d and development digest, stuff that relies on hashes should now be faster. @billdenney, please let me know if #1089 crops up again.

**Comment by billdenney** [comment]
Thanks!
