### ISSUE TITLE
Strange behaviour when targetname is "target"

### ISSUE THREAD

**Issue by feinmann** [ropensci/drake#1093]
## Description

In my pipeline I got an error and strange behaviour and figured that I should probably not use "target" as targetname (because I am coming from a machine learning context).

I tried then to build a reproducible example, but using reprex::reprex(), everything works fine. When I execute the following code in RStudio, however, `plan_1` fails with error ` ``target`` must be a vector, not a function`. Can someone confirm? What am I missing? Thx

## Reproducible example

```
library(drake)
#> Warning: Paket 'drake' wurde unter R Version 3.5.3 erstellt

plan_1 <- drake_plan(
    target = "my_target",
    test = testthat::expect_vector(target)
    )

make(plan_1)
#> target target
#> target test

plan_2 <- drake_plan(
    my_target = "my_target",
    test = testthat::expect_vector(my_target)
    )

make(plan_2)
#> target my_target
#> target test

sessioninfo::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  German_Germany.1252         
#>  ctype    German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2019-12-05                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.0   2017-04-11 [1] CRAN (R 3.5.1)
#>  backports     1.1.2   2017-12-13 [1] CRAN (R 3.5.0)
#>  base64url     1.4     2018-05-14 [1] CRAN (R 3.5.3)
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.5.3)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.1)
#>  digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.1)
#>  drake       * 7.7.0   2019-10-15 [1] CRAN (R 3.5.3)
#>  evaluate      0.12    2018-10-09 [1] CRAN (R 3.5.1)
#>  filelock      1.0.2   2018-10-05 [1] CRAN (R 3.5.3)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.1)
#>  igraph        1.2.2   2018-07-27 [1] CRAN (R 3.5.1)
#>  knitr         1.20    2018-02-20 [1] CRAN (R 3.5.1)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.1)
#>  pillar        1.4.2   2019-06-29 [1] CRAN (R 3.5.3)
#>  pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.5.1)
#>  R6            2.4.0   2019-02-14 [1] CRAN (R 3.5.3)
#>  Rcpp          1.0.2   2019-07-25 [1] CRAN (R 3.5.3)
#>  rlang         0.4.0   2019-06-25 [1] CRAN (R 3.5.3)
#>  rmarkdown     1.10    2018-06-11 [1] CRAN (R 3.5.1)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.1)
#>  rstudioapi    0.8     2018-10-02 [1] CRAN (R 3.5.1)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.1)
#>  storr         1.2.1   2018-10-18 [1] CRAN (R 3.5.3)
#>  stringi       1.2.4   2018-07-20 [1] CRAN (R 3.5.1)
#>  stringr       1.3.1   2018-05-10 [1] CRAN (R 3.5.1)
#>  testthat      2.1.1   2019-04-23 [1] CRAN (R 3.5.3)
#>  tibble        2.1.3   2019-06-06 [1] CRAN (R 3.5.3)
#>  txtq          0.1.5   2019-08-19 [1] CRAN (R 3.5.1)
#>  vctrs         0.2.0   2019-07-05 [1] CRAN (R 3.5.3)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.2)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.1)
#>  zeallot       0.1.0   2018-01-28 [1] CRAN (R 3.5.3)
```

Created on 2019-12-05 by the reprex package (v0.2.1)

**Comment by wlandau** [comment]
Odd, when I run this example in RStudio on my end, I do not get the error. If I make some modifications though, I can reproduce something like it.

``` r
library(drake)

expose_imports(drake)
#> <environment: R_GlobalEnv>

plan_1 <- drake_plan(
  target = "my_target",
  test = testthat::expect_vector(target)
)

make(plan_1)
#> unload targets from environment:
#>    target
#> Warning: knitr/rmarkdown report 'report.Rmd' does not exist and cannot be
#> inspected for dependencies.
#> target target
#> target test

clean(test)

make(plan_1)
#> target test
#> fail test
#> Error: Target `test` failed. Call `diagnose(test)` for details. Error message:
#>   ``target`` must be a vector, not a function
```

<sup>Created on 2019-12-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

There is currently an exported function in `drake` called `target()`, and I suspect that is what is causing problems. `target()` is really only supposed to be called inside `drake_plan()`, and it should not be exported to the user, but to abruptly remove it would confuse people in other ways. What I can do now is change [this warning](https://github.com/ropensci/drake/blob/b1f7e23adc8f0bad3bc4049d312b0ea0532aa2b4/R/drake_plan_helpers.R#L62-L67) to an error and then un-export it altogether once people have had enough time to adjust.

**Comment by wlandau** [comment]
I forgot to ask: when you restart your R session and run `plan_1` immediately, do you still get the error? It could be that a `target()` function was somehow leftover in an old workspace.

**Comment by feinmann** [comment]
Hi Will,

I tried also with fresh workspace. Could it have something to do with that I setup my RStudio project as a package?

Thank you very much.

**Comment by wlandau** [comment]
It is possible. Do you load it like a package, e.g. with `devtools::load_all()`? If so, your functions will be in a special package namespace instead of the global environment. Maybe something in your `.Rprofile` could be causing problems. If you post more of the surrounding code and more details about how you interact with it, I can take a look.

**Comment by feinmann** [comment]
Didn't `load-all` and .Rprofile should be clean. I have to come back to this tomorrow. I will run in a clean RStudio on my side and post more information. Thank you.

**Comment by feinmann** [comment]
In a complete fresh RStudio (no project) I cannot reproduce my error. So reprex::reprex() really works as expected ;)

But in a RStudio package-project (freshly restarted) the error occures:

```
In drake, consider r_make() instead of make(). r_make() runs make() in a fresh R session for enhanced robustness and reproducibility.
target test
fail test
Error: Target `test` failed. Call `diagnose(test)` for details. Error message:
  ``target`` must be a vector, not a function
```

So there must be something on, that I don't understand. But {drake} should be fine. Thank you very much.

**Comment by wlandau** [comment]
Hmm... in your workspace, what is the value of `target()`? And what happens if you use `r_make()` instead of `make()`?

**Comment by feinmann** [comment]
In my workspace, there is no value for `target` (or am I missing something?) but when I call `target()` I get:

```
  command
1      NA
Warning message:
target() in drake is not a standalone user-side function. It must be called from inside drake_plan(). Details: https://ropenscilabs.github.io/drake-manual/plans.html#large-plans 
```

I cannot successfully use `r_make()` with: `Error: callr subprocess failed: RStudio not running`. I don't know what information I could provide to solve this problem. Also `traceback` doesn't help me.

**Comment by wlandau** [comment]
> In my workspace, there is no value for target (or am I missing something?) but when I call target() I get:

Good, that is expected. No strangeness there.

> I cannot successfully use r_make() with: Error: callr subprocess failed: RStudio not running

Are you running `drake` inside R Markdown? Possible explanation: https://github.com/rstudio/rstudio/issues/1738

**Comment by feinmann** [comment]
Oh, thank you so much. No Rmarkdown on my side, but the problem reminded me that I use rstudioapi to input a password for a database connection. I will fix this and provide the `r_make()` output.

**Comment by feinmann** [comment]
`r_make()` working without problems.

**Comment by wlandau** [comment]
Awesome!
