### ISSUE TITLE
Standardising drake project workflows

### ISSUE THREAD

**Issue by lorenzwalthert** [ropensci/drake#1097]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Challenge

As [others pointed out](https://twitter.com/MilesMcBain/status/1203084231250833408), starting with drake is not trivial for people who have never used it. Even for experienced users, diving into a new drake project can be complicated because different projects are organised differently: 

- different file naming / folder conventions. 
- structured as R package or not (incl. documentation and testing).
- different function name conventions. 
- different target name conventions. 

and so on. Basically, there is no standard "way to do it" in drake, so every project is organised differently. There are no `usethis`-like helpers to organise and facilitate this workflow. Project components such as logging are not standardized and so on. I have recently used [`scrapy`](https://docs.scrapy.org/en/latest/intro/tutorial.html), a python library for web scraping, which initialises a whole file structure for you, gives functions and global variables standard names  and achieves a great degree of standardisation across projects. So easy for people to board the project.

## Proposal

Hence, I propose to discuss

- how standardised workflows could be established in drake from a conceptual point of view.
- how their implementation could be facilitated by `usethis` like helper functions.
- if these should be implemented in the drake package itself or in another package or if they should be developed independently of drake.

I believe the more the drake community grows, the more conventions will evolve naturally. The question is only if we should actively promote *one way* to do it, to make life simpler for everyone. Of course we should not over-specify how to do things, because projects can be very different in terms of many things, but they all have things in common and I believe these should be standardised. I believe when comparing to other communities, fragmentation is a weakness of the R ecosystem in general (just think about how the predict methods are different in every statistical package) and we should work actively against it.

cc: @MilesMcBain

**Comment by wlandau** [comment]
I agree, people have been asking about this since `drake`'s inception.

> how standardised workflows could be established in drake from a conceptual point of view.

For most projects, I have found most of the setup falls into 3 categories: packages, functions, and the plan. I try to talk about that at https://books.ropensci.org/drake/projects.html and https://wlandau.github.io/learndrake/#15.

> how their implementation could be facilitated by usethis like helper functions.

There is a `use_drake()` function based on `use_template()`, but `use_template()` can only generate a single script at a time (https://community.rstudio.com/t/usethis-use-template-and-directories/26109). Maybe `use_drake()` should write the whole folder structure at https://books.ropensci.org/drake/projects.html. A PR on that would help.

> if these should be implemented in the drake package itself or in another package or if they should be developed independently of drake.

Miles has https://github.com/MilesMcBain/dflow. Before that, ergonomic project organization was one of the goals of https://github.com/krlmlr/redrake, but it seems like `redrake` is no longer active.

**Comment by tjmahr** [comment]
For what its worth, I have my own [usedrake](https://github.com/tjmahr/usedrake/blob/master/R/usedrake-package.R) which writes out 

- R/packages.R 
- R/functions.R 
- R/plan.R 
- _drake.R 
- Makefile
- analysis/example.Rmd (with a target to spellcheck this file too)
- data/

I also have my own notebook thing in that package for creating a notebook with bookdown and drake but you can ignore that.

**Comment by wlandau** [comment]
I just added all the scripts to `use_drake()`. With `use_drake()`, https://books.ropensci.org/drake/projects.html, and several examples at https://github.com/wlandau/drake-examples downloadable with `drake_example()`, I think we have done all we can in `drake` itself. Beyond that, I think we just need to keep helping people on forums.

**Comment by wlandau** [comment]
...and talking about it in presentations when the opportunities arise.
