### ISSUE TITLE
Automatically handle dynamic dependencies of static targets

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#1107]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

At https://github.com/ropensci/drake/issues/685, https://github.com/ropensci/drake/issues/1064, https://github.com/ropensci/drake/issues/1090, and  https://github.com/ropensci/drake/issues/1103, I said that downstream targets of dynamic targets must be dynamic except if you use `readd()` to turn a dynamic target into a static one. This was always problematic because it required the user to understand the internals of dynamic branching. I just had an idea about how to avoid this problem. It has to do with the internals of memory management, and if it works, we will be able to write plans like this:

```r
drake_plan(
   raw = mtcars[seq_len(4), ],
   rows = target(raw[, c("mpg", "cyl")], dynamic = map(raw)),
   means = colMeans(rows) # no readd()
)
```

Currently it fails because `drake` thinks `rows` is a vector of hashes (i.e. how it represents dynamic targets). The goal for this example is to get `drake` to understand that `rows` should be a data frame for `means`.

cc @dpmccabe, @keondonB, @billdenney, @brendanf

**Comment by brendanf** [comment]
Is there still an exported function to get the vector of keys to the subtargets? Here I'm thinking of my `combine_dynamic_diskframe` in https://github.com/ropensci/drake/issues/1076#issuecomment-555884118.

**Comment by wlandau** [comment]
Yes, the `subtargets()` function does this and is still available.
