### ISSUE TITLE
The cache uses a lot of space. / How does the latest cache work?

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#1109]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Question

How does the latest cache work? What are the individual folders for? I couldn't find this info in the docs.

I'm also having trouble with the cache taking up a lot more space than I think it should. Particularly the `./config/drake/tmp`, `./config/drake/return`, `./drake/tmp`, and `./drake/return` folders. These are the sizes after a `drake_gc()`:
```
2.5G	./scratch
1.2G	./config/scratch
3.0K	./config/config
258K	./config/drake/history
52G	./config/drake/tmp
46G	./config/drake/return
98G	./config/drake
1.0K	./config/keys/progress
384K	./config/keys/meta
374K	./config/keys/objects
2.5K	./config/keys/session
389K	./config/keys/recover
512K	./config/keys/memoize
3.0K	./config/keys/common
1.7M	./config/keys
6.1G	./config/data
105G	./config
258K	./drake/history
40G	./drake/tmp
26G	./drake/return
65G	./drake
257K	./keys/progress
493K	./keys/meta
489K	./keys/objects
2.0K	./keys/session
481K	./keys/recover
380K	./keys/memoize
2.1M	./keys
6.2G	./data
```

**Comment by kendonB** [comment]
Looks related to `disk.frame`:

https://github.com/ropensci/drake/blob/f6e3e45e33601634ecefdb8ca03faea71f7fc259/R/local_build.R#L411

**Comment by kendonB** [comment]
Is there between `./config/data` and `./data`?

**Comment by wlandau** [comment]
It looks like `.drake/config` has its own `.drake` sub-directory. I have never seen that before, and I am not sure how it happened. (Can you reproduce it?)

When I run this plan,

```r
drake_plan(x = 1, y = target(mtcars, format = "fst"))
```

here is what the directory structure looks like from this

```
config/ # just a bunch of flat text files to configure storr
  compress
  hash_algorithm
  mangle_key
  mangle_key_pad
  version
data/
  0ef54954e6b32bfa.rds
  0f8195dda65e0e1a.rds
  # ...
drake/
  history/ # txtq inside
  return/
    f5feaaffdeba774a
  tmp/
keys/
  memoize/
  meta/
  objects/
  progress/
  recover/
  session/
scratch/
```

Files in `return/` are for custom formats, e.g. `format = "fst"`. You can safely remove everything inside `tmp/` and `scratch/`.

**Comment by wlandau** [comment]
Files should not theoretically not persist in `tmp/` or `scratch/` unless you interrupt the process of saving them. Related: https://github.com/richfitz/storr/issues/114.

**Comment by wlandau** [comment]
In https://github.com/ropensci/drake/commit/68434b382aac990327981f5285f2e09dcbaaf9d4, I added some extra precautions to automatically remove files in `.drake/drake/tmp/`. However, `on.exit()` is still unavoidably ignored if you kill R with CTRL-c, so `tmp/` may still build up.

**Comment by kendonB** [comment]
Can we add these folders to `drake_gc`?

**Comment by kendonB** [comment]
> For you, it looks like .drake/config has its own .drake sub-directory, which should not happen. I have never seen that before. Can you reproduce it?

I have no idea how this happened! I will let you know if I see it again.
