### ISSUE TITLE
Utility for clean()ing everything but the contents of a plan

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#1110]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

Why dynamic branching, it's now a bit of work to subset the `cached()` targets to only those not in a plan, given many of the targets in `cached()` have a hash suffix (i.e. they're expanded) and the `plan$target` names have the unexpanded target name.

It would be neat to be able to run something like `clean(plan_to_exclude = myplan)` and the system would only clean those targets that wouldn't get built from `myplan`.

**Comment by wlandau** [comment]
Good idea. Added `cached_unplanned()` and `cached_planned()` in  https://github.com/ropensci/drake/commit/99a2926fe26ab4fb1158cde914822cc3b3f8072a.

``` r
library(drake)
plan <- drake_plan(w = 1)
make(plan)
#> target w
plan <- drake_plan(
  x = seq_len(2),
  y = target(x, dynamic = map(x))
)
make(plan)
#> target x
#> dynamic y
#> subtarget y_0b3474bd
#> subtarget y_b2a5c9b8
#> aggregate y
cached()
#> [1] "w"          "x"          "y"          "y_0b3474bd" "y_b2a5c9b8"
clean(list = cached_unplanned(plan))
cached()
#> [1] "x"          "y"          "y_0b3474bd" "y_b2a5c9b8"
```

<sup>Created on 2019-12-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
