### ISSUE TITLE
Utility functions that do not require drake_config() objects

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#1118]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Please chime in!

This is a great opportunity for user feedback, especially to come up with a solid set of function names. I would love to hear from you all.

## The role of `drake_config()`

In `drake`, `make()` has two stages:                                        

1. Configure a workflow to your environment and plan.                                  
2. Build targets.                                                                      

The `drake_config()` function just does step (1). It returns a configured workflow, which serves as input to utility functions like `outdated()` and `vis_drake_graph()`.

Originally, there were two reasons to expose `drake_config()` to the user.

1. It helps manage all the arguments of `make()` that are also required for `vis_drake_graph()` and friends.
2. Originally, `drake_config()` was slow enough that uses benefitted from having a pre-configured workflow on hand.

A third reason that came up later: `r_make()` and friends require it.

## Drawbacks of `drake_config()`

1. It is annoying to type `drake_config()` all the time before `vis_drake_graph()`.
2. Configured workflow objects are brittle. They depend on the state of your environment, so if you add or change any functions in your session, you will need to rerun `drake_config()` all over again.

## Proposal

All the functions that accept configured workflows (e.g. `vis_drake_graph()`, `outdated()`, etc.) are not going to change or disappear. It is far too late for anything so drastic. But I do propose we add new API functions that compute their own `drake_config()` objects internally without making the user do it. Sketch:

```{r}
d_vis_drake_graph <- function(plan, envir, ...) {
  config <- drake_config(plan, envir, ...)
  vis_drake_graph(config)
}
```

The trouble is coming up with the names. `d_vis_drake_graph()` probably isn't a good one, but I think there should be sensible prefixes, and I think the original names should still be there somehow (e.g. "vis_drake_graph").

## Functions

I am not sure what the prefix should be, only that it should be as small and evocative as possible.

r_make()-like function | original function | config-less function
--- | --- | ---
r_make | make | ??_make
r_drake_build | drake_build | ??_drake_build
r_outdated | outdated | ??_outdated
r_missed | missed | ??_missed
r_vis_drake_graph | vis_drake_graph | ??_vis_drake_graph
r_sankey_drake_graph | sankey_drake_graph | ??_sankey_drake_graph
r_drake_ggraph | drake_ggraph | ??_drake_ggraph
r_drake_graph_info | drake_graph_info | ??_drake_graph_info
r_predict_runtime | predict_runtime | ??_predict_runtime
r_predict_workers | predict_workers | ??_predict_workers

**Comment by vkehayas** [comment]
Couldn't you just add an extra class to drake plans which you can test for inside `vis_drake_graph`, for example?

```r
# Define a new function that works with either a plan or a config
vis_drake_graph = function(plan_or_config, envir, ...) {
    
    inputClass = class(plan_or_config)
    
    if (drake_plan_class %in% inputClass) {
      # drake_plan_class will be the class that defines drake plans
        configObj = drake_config(plan_or_config, envir, ...)
    } else { 
        configObj = plan_or_config
    }
    
    # Use the old vis_drake_graph
    vis_drake_graph_old(configObj)
    
}
```
Would that be a breaking change?

**Comment by wlandau** [comment]
Yeah, I actually like that more. And the transition will be graceful. I think we just need a nice name for config_or_plan. Maybe just "plan"? That will make it clear that we want people to supply plans. We can move the existing config argument to the end and deprecate it. With a similar change to make(), the interface will end up being more consistent.

**Comment by wlandau** [comment]
To make this make more sense, we could think about canonizing the term "configured plan". Might not be such a good idea though because some functions can accept only unconfigured plans. On that note, we should look for an even better first argument name that is neither "config_or_plan" nor just "plan".

**Comment by wlandau** [comment]
Yet another option is to append a plan argument, but let "config" stay first.

**Comment by wlandau** [comment]
Regardless, we should let the API changes sit in dev for a while, so I probably won't start an implementation until after the next CRAN release at the earliest.

**Comment by wlandau** [comment]
A couple options (feedback requested):

## The "plan first" option

- Do the following for all the "original functions" in the table at https://github.com/ropensci/drake/issues/1118#issue-539473537.
- Change the first argument to `plan`.
- Move `config` to the end of the argument list and deprecate it with a warning.
- Use `...` to accept the non-plan arguments we pass to `drake_config()` internally.
- Update the documentation, especially for `r_make()` and friends.

## The "config first" option

- Do the following for all the "original functions" in the table at https://github.com/ropensci/drake/issues/1118#issue-539473537.
- Deprecate the `config` argument with a warning.
- Use `...` to accept *all* arguments we pass to `drake_config()` internally.
- Update the documentation, especially for `r_make()` and friends.

## Comparison

"Plan first" understands `vis_drake_graph(plan)`, while "config first" requires the plan to be named, e.g. `vis_drake_graph(plan = plan)`. Perhaps this will be the deciding factor since it makes most use cases super easy. But the awkward thing about "plan first" is that the plan is not part of `...` like the rest of the arguments to `drake_config()`. :thinking:

**Comment by wlandau** [comment]
## The "dots first" option

Like "config first" except with the arguments rearranged.

```r
outdated <-  function(
  ..., # arguments to drake_config() (plan, etc.)
  make_imports = TRUE,
  do_prework = TRUE,
  config = NULL
) 
```

**Comment by wlandau** [comment]
The implementation of "dots first" should be clean and should not break old code. Sketch:

```r
# new function
outdated <-  function(
  ...,
  config = NULL,
  make_imports = TRUE,
  do_prework = TRUE
) {
  args <- list(...)
  force(args$envir)
  config <- config %|||% unnamed(args)[[1]]
  fun <- sys.call()[[1]]
  config <- force_config(config, fun, ...)
  outdated_impl(
    config = config,
    make_imports = make_imports,
    do_prework = do_prework
  )
}

# exact same as old function
outdated_impl <- function(
  config,
  make_imports = TRUE,
  do_prework = TRUE
) {
  # old outdated() code
}

force_config <- function(config, fun, ...) {
  UseMethod("force_config")
}

force_config.drake_config <- function(config, fun, ...) {
  warning(
    "the config argument of drake function ", fun, "() is deprecated. ",
    "The plan and other make() arguments should be supplied directly, ",
    "e.g. ", fun, "(plan).",
    call. = FALSE
  )
  config
}

force_config.default <- function(config, ...) {
  drake_config(...)
}
```

**Comment by wlandau** [comment]
No, that won't work. We need to match calls. I still think "dots first" is the best. See below.

```r
#' @export
outdated <-  function(
  ...,
  make_imports = TRUE,
  do_prework = TRUE,
  config = NULL
) {
  force(list(...)$envir)
  config <- config %|||% unnamed(list(...))[[1]]
  if (is_config(config)) {
    call <- match.call(definition = outdated_impl, expand.dots = TRUE)
    call[[1]] <- quote(outdated_impl)
    return(eval(call))
  }
  outdated_impl(
    config = drake_config(...),
    make_imports = make_imports,
    do_prework = do_prework
  )
}

is_config <- function(config) {
  inherits(config, "drake_config")
}

outdated_impl <- function(
  config,
  make_imports = TRUE,
  do_prework = TRUE
) {
  # code from the previous outdated()
}
```
