### ISSUE TITLE
Submit version 7.9.0 to CRAN

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#1122]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

`drake` 7.9.0 is released on GitHub, but it will not appear on CRAN until after the CRAN maintainers come back from vacation on Jan 6.

**Comment by wlandau-lilly** [comment]
On CRAN.
