### ISSUE TITLE
Unnested grouping variables in static branching

### ISSUE THREAD

**Issue by tcornwall** [ropensci/drake#1128]
I'm getting weird behavior from a plan I'm trying to create (code attached below). I get the following warnings when I run drake_plan (drake_7.8.0, R 3.5.3):
```
Warning in min(vapply(out, length, FUN.VALUE = integer(1))) :
  no non-missing arguments to min; returning Inf
Warning: A grouping or splitting variable for target 'badTarget' is missing or undefined. Transformation skipped and target deleted.
```
Not surprisingly, 'badTarget' is not created, but I'm not sure why. 'badTarget' depends on three inputs that have the same grouping variables. Removing any one of these inputs makes the warning go away. In addition, removing 'affectsBadTarget' makes the warning even though  'badTarget' does not depend on 'affectsBadTarget'. Code is below. The example is relatively complicated - I did remove as many targets as I could before the problem went away.

```
library(drake)
library(data.table)
#install.packages("visNetwork")

## Declare plan ---------------------------------------------------------

debuggingGrid <- data.table(dataFunc = c("func1"), name = c("gauss"))

newPlan <- drake::drake_plan(

  ## 2.3.X) Declare the data as a target
  f = target(
    x,
    transform = map(
      x = !!c(1))
  ),

  dtFunc = target(
    dataFunc,
    transform = map(
      .data = !!debuggingGrid,
      .id = c(name))
  ),

  data = target(
    dtFunc(f),
    transform = cross(dtFunc, f, .id = c(name, f)
    )
  ),

  ## 2.3.X) Create train/test fold splits
  trainIdx = target(
    index.splitGenerator(data),
    transform = map(data, .id = c(name, f))
    ),

  modelTestBool = target(
    modelTestBool.splitFromIdx(tB = trainIdx),
    transform = map(trainIdx, .id = c(name, f))
    ),

  #' Boolean for test observations used to evaluate performance of ensemble, by
  #' fold.
  ensembleTestBool = target(
    ensembleTestBool.split(trainIdx, modelTestBool),
    transform = map(trainIdx, modelTestBool, .id = c(name, f))
    ),

  ## 2.3.X) Split X and Y by train/test

  yTrain = target(
    y.split(data, trainIdx),
    transform = map(data, trainIdx, .id = c(name, f))
  ),


  XTrain = target(
    X.split(data, trainIdx),
    transform = map(data, trainIdx, .id = c(name, f)
                    )
    ),

  fullModel = target(
    fullModel.fit(XTrain, yTrain),
    transform = map(XTrain, yTrain, .id = c(name, f)
                    )
    ),

  XTest = target(
    X.split(data, ensembleTestBool),
    transform = map(data, ensembleTestBool, .id = c(name, f))
  ),

  #' 'badTarget' does not depend on this target, but removing it allows
  #' 'badTarget' to be created correctly.
  affectsBadTarget = target(
    ensemble.fit(fullModel, XTest),
    transform = map(fullModel, XTest, .id = c(name, f))
    ),

  XByRowTest = target(
    dataFrame.rowSplit(XTest),
    transform = map(XTest,
                    .id = c(name, f)
                    )
    ),

  # Removing any one of the inputs makes the warning go away.
  badTarget = target(
    ensemble.predictProba(XTrain, XTest, XByRowTest),
    transform = map(XTrain, XTest, XByRowTest,
                    .id = c(name, f)
                    )
    ),

  trace = TRUE
  )

config <- drake::drake_config(newPlan)

vis_drake_graph(config, targets_only = TRUE)
```

**Comment by wlandau** [comment]
A small case that reproduces the issue:

``` r
suppressPackageStartupMessages(library(dplyr))
library(drake)
drake_plan(
  b1 = target(1, transform = map(a1 = 1, a2 = 1, .id = FALSE)),
  b2 = target(1, transform = map(a1 = 1, a3 = 1, .id = FALSE)),
  b3 = target(1, transform = map(a2 = 1, a3 = 1, .id = FALSE)),
  c1 = target(1, transform = map(a1, a2, a3, .id = FALSE)),
  trace = TRUE
)
#> Warning in min(vapply(out, length, FUN.VALUE = integer(1))): no non-missing
#> arguments to min; returning Inf
#> Warning: A grouping or splitting variable for target 'c1' is missing or
#> undefined. Transformation skipped and target deleted.
#> # A tibble: 3 x 8
#>   target command a1    a2    b1    a3    b2    b3   
#>   <chr>  <expr>  <chr> <chr> <chr> <chr> <chr> <chr>
#> 1 b1     1       1     1     b1    <NA>  <NA>  <NA> 
#> 2 b2     1       1     <NA>  <NA>  1     b2    <NA> 
#> 3 b3     1       <NA>  1     <NA>  1     <NA>  b3
```

<sup>Created on 2020-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It happens because `drake` assumes grouping variables are strictly nested inside one another. The plan above tries to nest `a1` inside `b1` and then nest the same `a1` again inside `c1`. Sometimes, you can redefine `a1` for `c1` to get the answer you want.

``` r
suppressPackageStartupMessages(library(dplyr))
library(drake)
drake_plan(
  b1 = target(1, transform = map(a1 = 1, a2 = 1, .id = FALSE)),
  b2 = target(1, transform = map(a1 = 1, a3 = 1, .id = FALSE)),
  b3 = target(1, transform = map(a2 = 1, a3 = 1, .id = FALSE)),
  c1 = target(1, transform = map(a1 = 1, a2 = 1, a3 = 1, .id = FALSE)),
  trace = TRUE
)
#> # A tibble: 4 x 9
#>   target command a1    a2    b1    a3    b2    b3    c1   
#>   <chr>  <expr>  <chr> <chr> <chr> <chr> <chr> <chr> <chr>
#> 1 b1     1       1     1     b1    <NA>  <NA>  <NA>  <NA> 
#> 2 b2     1       1     <NA>  <NA>  1     b2    <NA>  <NA> 
#> 3 b3     1       <NA>  1     <NA>  1     <NA>  b3    <NA> 
#> 4 c1     1       1     1     <NA>  1     <NA>  <NA>  c1
```

<sup>Created on 2020-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Your use case might be more difficult since `XTrain`, `XTest`, and `XByRowTest` are already targets.

I am not sure we can make `drake_plan()` output the exact plan you want here. You may have to call `drake_plan()` separately for different subcollections of targets and then combine the plans together at the end using `bind_plans()`. Unlike [static branching](https://books.ropensci.org/drake/static.html) (what you are using now) [dynamic branching](https://books.ropensci.org/drake/dynamic.html) is myopic when it comes to grouping variables, so you might have better luck there.

As for development, I think we can improve the error message, and I think we can document this as a limitation of static branching.

**Comment by tcornwall** [comment]
Great explanation, thanks Will! I didn't understand how the grouping variables worked - it should be easy to rewrite the plan or use `bind_plans()` now that I do.

**Comment by wlandau-lilly** [comment]
Glad it helped. I improved the warning in https://github.com/ropensci/drake/commit/df5577ebeb4aee9d6e8ab8d2da9c09011c39a9d6, and I updated documentation in the manual in https://github.com/ropensci-books/drake/commit/6cb1ca27963f10f150d0962328b27b5b909df98b and https://github.com/ropensci-books/drake/commit/3c802b7b686066b26b63a9e39e4d1236d8a33599. Improved guidance should soon appear at https://books.ropensci.org/drake/static.html#grouping-variables.
