### ISSUE TITLE
Include hashes in `deps_code` and `deps_target`

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#1134]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

I am trying to understand why a project goes out of date on one machine when made on a second. `deps_profile` tells me it's the `depend` category but I don't seem to have any way of digging deeper. It would be good to include hashes in the output of `deps_target` and `deps_code` so users could work something like this out. Or is there another way?

**Comment by wlandau** [comment]
Good call on `deps_target()`, let's add a `hash` column to the output. `deps_code()` isn't a great fit though because it does not assume a cache.

**Comment by kendonB** [comment]
> `deps_code()` isn't a great fit though because it does not assume a cache.
And thereby doesn't have a known hash? Assume the default if no cache is passed? Or don't display if no cache is passed?

**Comment by kendonB** [comment]
Without having hashes in `deps_code`, how would one solve the above problem of getting to the bottom of why something is out of date?

**Comment by wlandau** [comment]
`deps_target()` plays that role. `deps_code()` just previews what `drake` does in the code analysis.

**Comment by kendonB** [comment]
Ah I see now - the code dependencies are still included in there. Great!

**Comment by kendonB** [comment]
This comes from a real example where a function dependency in a command (`clean_data`) shows that it has changed but the target shows that it's up to date. 

```r
> deps_profile("target_1", config = config)
# A tibble: 5 x 4
name       changed old                                new                               
<chr>      <lgl>   <chr>                              <chr>                             
1 command  FALSE   "ce24dfbdfd377ef3596321a45a9b1f82" "ce24dfbdfd377ef3596321a45a9b1f82"
2 depend   FALSE   "fb79bf8299edcb09e8b3b5fdb581ff94" "fb79bf8299edcb09e8b3b5fdb581ff94"
3 file_in  FALSE   "b038fdd841f84054f2813be605111091" "b038fdd841f84054f2813be605111091"
4 file_out FALSE   ""                                 ""                                
5 seed     FALSE   "393455556"                        "393455556"                       
> deps_profile("clean_data", config = config)
# A tibble: 5 x 4
name       changed old                                new                               
<chr>      <lgl>   <chr>                              <chr>                             
1 command  TRUE    "d4cd0dabcf4caa22ad92fab40844c786" "d41d8cd98f00b204e9800998ecf8427e"
2 depend   FALSE   "4accd39b6c5f2fccd83f26bebe7dc75f" "4accd39b6c5f2fccd83f26bebe7dc75f"
3 file_in  FALSE   ""                                 ""                                
4 file_out FALSE   ""                                 ""                                
5 seed     NA       NA                                "2033891863"                      
> deps_target("target_1", config = config)
⠴# A tibble: 4 x 2
name          type   
<chr>         <chr>  
1 shp         globals
2 clean_data  globals
3 file1.csv   file_in
4 file2.csv   file_in
```

**Comment by kendonB** [comment]
Ah if I actually change the function `clean_data` the hash under `depend` changes, not `command` as I expected. When the argument passed to `deps_profile` is actually a function import, what is getting hashed for the `command` row?

**Comment by wlandau** [comment]
You can ignore `command` for imports. It's a bug in `deps_profile()`. I should probably just remove that row for non-targets.

**Comment by kendonB** [comment]
The documentation for `deps_profile` also doesn't say anything about imports, despite it working. Want me to open a separate issue for that?

**Comment by wlandau** [comment]
No need. In d2c65ff9d731124ba2df3db52d1911f632e6dc31, I removed information irrelevant for imports. Now there should just be rows for `"depend"` and `"file_in"`.

**Comment by wlandau** [comment]
Also, I just realized I forgot to de-config `deps_profile()`, re #1123. Fixed in daceaa83d4c2e218a87100fff1084295309b68a5.

**Comment by kendonB** [comment]
Should I be able to use `deps_profile` on file imports? Like this:
```
deps_profile("file1.csv", config = config)
```

**Comment by wlandau** [comment]
Nope, `deps_target()` is for true objects only. For incidental files, I recommend `diagnose()`.

``` r
library(drake)
load_mtcars_example()
make(my_plan, verbose = 0L)

# pretty print method added in 6f148ea3bcdab712dda8364d93c6393382f74a5c
diagnose(report)
#> drake metadata for report:
#>  $ name            : chr "report"
#>  $ target          : 'target' chr "report"
#>  $ imported        : logi FALSE
#>  $ missing         : logi TRUE
#>  $ file_out        : chr "p-OJSXA33SOQXG2ZA"
#>  $ format          : chr "none"
#>  $ dynamic         : logi FALSE
#>  $ isfile          : logi FALSE
#>  $ seed            : int 1296268377
#>  $ dependency_hash : chr "b64b2f294f465822"
#>  $ input_file_hash : chr "c49bb1c184979642"
#>  $ output_file_hash: chr "c18fdf62dc4ab0fb"
#>  $ hash            : chr "f3bb623354b52fa1"
#>  $ size_vec        : int 1
#>  $ command: chr "knit(knitr_in(\"report.Rmd\"), file_out(\"report.md\"), quiet =..."
#>  $ date   : chr "2020-01-11 07:36:30.014525 -0500 GMT"
#>  $ trigger :       drake_triggers drake 
#>  $ time_command :  list 
#>  $ time_build :    list
```

<sup>Created on 2020-01-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Forgot to mention that `drake_history()` might be useful in combination with `deps_target()` to figure out what is invalidating your targets. It's the only way `drake` keeps track of past hashes on a target-by-target basis.
