### ISSUE TITLE
broken link to saythanks.io in readme

### ISSUE THREAD

**Issue by idavydov** [ropensci/drake#1137]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [x] Advanced users: verify that the bug still persists in the current development version (i.e. `remotes::install_github("ropensci/drake")`) and mention the [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity) of the [Git commit you install](https://github.com/ropensci/drake/commits/master).

## Description

Link in the README file [saythanks.io](https://saythanks.io/to/drake-r-package-feedback) is broken.

https://github.com/ropensci/drake/blob/613f77592905aee4b0e2897b27d7ac77a90b8de3/README.Rmd#L93

Cross-references: https://github.com/BlitzKraft/saythanks.io/issues/60 and #638.

**Comment by wlandau** [comment]
Let's follow https://github.com/BlitzKraft/saythanks.io/issues/60. There is nothing I can do on `drake`'s side except remove the badge, and I suspect it is too soon for that.
