### ISSUE TITLE
More info on reason targets are out of date

### ISSUE THREAD

**Issue by jennysjaarda** [ropensci/drake#1149]
## Prework

- [X] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [X] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal
Hi Will, 

Just an idea: sometimes I find my targets are outdated when I don't expect them to be. I am 100% convinced this is my own fault and no issue with `drake`, but I find it difficult to determine *why* they are outdated and what needs to change in my plan so they are up to date. I know there is a [section](https://books.ropensci.org/drake/debugging.html) in the manual directly dedicate to this question, but if I understand correctly, it requires having a `cache_log_file` created, which is not a default option. I think it would be really nice if somehow drake could tell you explicitly why your targets are out of date where the options could be: 
- Files changed in the `file_in()` folder. 
- Your function XX changed. 
- An upstream target is out of date. 

Are there other reasons a target would be out of date? 

Thanks,
Jenny

**Comment by wlandau** [comment]
One function not mentioned in that section is `deps_profile()`. It looks at some of the most common triggers and tells you which ones, if any, invalidate a target. It is not very granular, but  increasing granularity would decrease storage efficiency and potentially speed (#497).

**Comment by jennysjaarda** [comment]
Thanks for the feedback and tip!

**Comment by jennysjaarda** [comment]
Hi Will,

I've been using this function quite a bit - thanks! I am having an issue
though (unfortunately I can't figure out how to reproduce it).

When I run deps_profile(my_target, my_plan), everything is false.
Similarly, when I run outdated(my_plan), it returns an empty character,
however when I view the graph many targets are shown as outdated:

I've tried visualizing with/without config because I'm unsure the
difference, but I'm getting the same result either way.

vis_drake_graph(my_plan)
config <- drake_config(my_plan)
vis_drake_graph(config)

Any ideas why this would happen?

**Comment by jennysjaarda** [comment]
Actually to clarify: when I simply visualize it everything is updated and
looks good. BUT when I render as a markdown, it is outdated. I'm using
workflowr.

wflow_build("analysis/plans.Rmd"). Where plan.Rmd is simply:




```{r setup, include = FALSE}
options(scipen=999)
source("code/packages.R")
source("code/settings.R")
source("code/plan.R")
library(R.utils)
library(kableExtra)
```


```{r plans}
getwd()
outdated(pre_pipeline)
vis_drake_graph(pre_pipeline)
config <- drake_config(pre_pipeline)
vis_drake_graph(config)

```

**Comment by wlandau** [comment]
> Any ideas why this would happen?

If `outdated()` appears to disagree with `vis_drake_graph()`, there is nothing I can say for certain without a full reprex. What I can say is that `r_outdated()` and `r_vis_drake_graph()` are more robust and more likely to agree. (See <https://books.ropensci.org/drake/projects.html#safer-interactivity>.)

> I've tried visualizing with/without config because I'm unsure the
difference...

`vis_drake_graph(config)` is the old API, and I am trying to move `drake` away from it. (`drake_config()` is confusing and brittle). `vis_drake_graph(plan)` is the new API, and I encourage people to use it for new code.

**Comment by wlandau** [comment]
Re https://github.com/ropensci/drake/issues/1149#issuecomment-582943798, it could be that the R Markdown is running in a different working directory (which makes it hard to find the `.drake/` cache) or with a different environment (in which case you can try writing a `_drake.R` file and use `r_make()` as described at <https://books.ropensci.org/drake/projects.html#safer-interactivity>).

**Comment by jennysjaarda** [comment]
Hmm, OK I did a bit more digging: 

In a fresh R session: 
```

# Load packages ----
source("code/packages.R")

# Load functions and plans  ----
source("code/settings.R")
source("code/functions.R")
source("code/plan.R")

outdated(pre_pipeline)
#character(0)
rmarkdown::render("plans.Rmd", "html_document")
## produces a markdown document with outdated plans
outdated(pre_pipeline)
## many targets are now outdated.
```

**Comment by jennysjaarda** [comment]
There is clearly one target that is posing a problem: 

![image](https://user-images.githubusercontent.com/36084054/73955505-c1994b80-4903-11ea-9dad-d856a44c4690.png)

I'm not sure if it helps, but if run `deps_profile` on this target I see that the dependencies have changed: 
```
# A tibble: 5 x 4
  name     changed old                new               
  <chr>    <lgl>   <chr>              <chr>             
1 command  FALSE   "d1c3aef9a4850981" "d1c3aef9a4850981"
2 depend   TRUE    "81d29951590c7249" "c2af3c315fb54718"
3 file_in  FALSE   "55aa1e0a0ef93e36" "55aa1e0a0ef93e36"
4 file_out FALSE   ""                 ""                
5 seed     FALSE   "802092204"        "802092204"      
```

**Comment by wlandau** [comment]
I'm not sure exactly what the problem is, but I suspect that `analysis/plans.Rmd` is somehow populating your global environment differently than when you ran `outdated()` outside the R Markdown. This is more support in favor of using `r_make()` and `r_outdated()` and friends as in https://books.ropensci.org/drake/projects.html#safer-interactivity.

**Comment by jennysjaarda** [comment]
I was able to solve it: it was this line that was a problem in the
rmarkdown: options(scipen=999) (to avoid scientific notation). I think as
long as I include this line after all drake plans are evaluated it should
be fine.
