### ISSUE TITLE
How to define targets with list.files with and without importing

### ISSUE THREAD

**Issue by jl5000** [ropensci/drake#1151]
Most of the examples I see online are about importing a single file, whereas my use case is a bit more complex. I want to:

- Import a single file (easy)
- Import a list of files using list.files() and a regex pattern (not one at a time, but with map_dfr)
- Create a dataframe based on the file paths of a different list of files (to above) using list.files() and a regex pattern (not import them)

I think each of these do need to be targets because they need to be regenerated anytime any of the files change. This is what I have so far:

```r
analysis_plan <- drake_plan(
  #Define crop areas dataset as a target
  crop_areas_path = read_csv(file_in("K:/Sentinel-2/crop_areas.csv")),

  #List all metadata files in the Sentinel-2 directory as a target
  metadata_filepaths = file.path("K:", "Sentinel-2") %>%
                     list.files(pattern = "*.csv",
                               full.names = TRUE,
                               recursive = TRUE) %>%
                      keep(str_detect(., "dataset.csv")) %>%
                      file_in(),

  #List all tif files as a target
  tif_filepaths = file.path("K:", "Sentinel-2") %>%
               list.files(pattern = "*.tif",
                          full.names = TRUE,
                          recursive = TRUE) %>%
              file_in(),

  tif_metadata = create_master_metadata(tif_filepaths, metadata_filepaths, crop_areas_path)
)
```

I realise that putting file locations as targets is not good practice and I'm not sure if I have to use dynamic branching to get this to work.

The problem with the recommended transform/map paradigm is that it reads each file individually and stores it as a (sub) target, whereas in the 2nd target I want to read and combine them all in one go. With the 3rd target I want the files to be targets, but I don't want to import them, I just need to build a df with their filepaths.

**Comment by wlandau** [comment]
> I think each of these do need to be targets because they need to be regenerated anytime any of the files change.

But if they return only file paths, then downstream targets like `tif_metadata` will only update if the paths change, not if the contents of the files change. To trigger an update if the file contents change, the `file_in()` statement needs to be part of the target that calls `create_master_metadata()`.

Also, `file_in()` needs a literal character of file paths / directory paths inside the parentheses, e.g. `file_path("your_file")`. `drake` will detect those files using static code analysis. To check if the file was registered properly, I recommend checking `deps_target()` and `vis_drake_graph()`.

``` r
library(drake)
file.create("x")
#> [1] TRUE
  
good_plan <- drake_plan(y = file_in("x"))
bad_plan <- drake_plan(y = "x" %>% file_in())

# using GitHub dev version
deps_target(y, good_plan)
#> # A tibble: 1 x 3
#>   name  type    hash 
#>   <chr> <chr>   <chr>
#> 1 x     file_in <NA>

deps_target(y, bad_plan)
#> # A tibble: 0 x 3
#> # … with 3 variables: name <chr>, type <chr>, hash <chr>

vis_drake_graph(good_plan)
```

![](https://i.imgur.com/0hN7ldl.png)

``` r

vis_drake_graph(bad_plan)
```

![](https://i.imgur.com/giR0eSF.png)

<sup>Created on 2020-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And targets are super flexible. They are whatever you need them to be. If file processing/gathering is super fast, you can put all that in one target and put all files under a single `file_in()` statement. Related: https://books.ropensci.org/drake/plans.html#how-to-choose-good-targets. Yes, target invalidation becomes all or nothing, but depending on what happens downstream, that may not matter. Here is a sketch:

```r
drake_plan(
  metadata_df = get_metadata( # user-defined
    csf = file_in(!!list_csv_files()),
    tif = file_in(!!list_tif_files())
  ),
  downstream_processing = target(
    process_row(metadata_df),
    dynamic = map(metadata_df) # https://books.ropensci.org/drake/dynamic.html
  )
)
```

Here, `metadata_df` changes if you change any file, but that target should be cheap. The downstream row-by-row processing on the metadata, however, only invalidates a dynamic sub-target if the corresponding row of `metadata_df` changes.

**Comment by jl5000** [comment]
> Also, file_in() needs a literal character of file paths / directory paths inside the parentheses, e.g. file_path("your_file"). drake will detect those files using static code analysis.

Roger. I won't use the pipe with file_in().

I've simplified your sketch to something that I think will work in my case:

`crop_areas_path <- file.path("crop_areas.csv")
metadata_filepaths <- list.files(...)
tif_filepaths <-  list.files(...)

analysis_plan <- drake_plan(  # Create a drake_plan object called analysis_plan

  tif_metadata = create_master_metadata(file_in(!!tif_filepaths),
                                                                   file_in(!!metadata_filepaths),
                                                                   file_in(!!crop_areas_path))
)`

I've read and re-read the chapters of the book several times, but it's not clicking for me yet.

When I try to visualise this I get the following error: "Error in file.rename(tmp, filename) : expanded 'to' name too long". I have a feeling it's because there are hundreds of files.

**Comment by jl5000** [comment]
I think this has resolved my original question.

**Comment by wlandau** [comment]
> I've read and re-read the chapters of the book several times, but it's not clicking for me yet.

Got any more questions?

**Comment by jl5000** [comment]
I think the book would benefit from an example of the list.files() issue above (if it hasn't already).

I've also had trouble creating on-disk targets from a rasterVis::levelplot(). It has no return value so I've used the dev.off() thing, but I can't make it work without first assigning the plot to a target and then writing it to disk using print(plot_object). It would be good if I could combine the two steps somehow. This issue would probably be worth an explicit mention in the book too.

I've been showing this package to people in my office, and even a senior manager came over to find out what the network graph was all about.

**Comment by wlandau** [comment]
> I think the book would benefit from an example of the list.files() issue above (if it hasn't already).

The manual is certainly under development. If you feel strongly about it, feel free to post to https://github.com/ropensci-books/drake/issues so we don't lose the idea.

> I've also had trouble creating on-disk targets from a rasterVis::levelplot(). It has no return value so I've used the dev.off() thing, but I can't make it work without first assigning the plot to a target and then writing it to disk using print(plot_object). It would be good if I could combine the two steps somehow. This issue would probably be worth an explicit mention in the book too.

You can put a standalone `file_out()` in the command, wherever it's convenient for you. Sketch:

```r
drake_plan(
  file_step = {
    plot_object <- reasterVis::levelplot() # not sure if this is the correct usage.
    print(plot_object)
    dev.off()
    file_out("name_of_plot")
  }
)
```

Or better yet, wrap it all in a function. Another sketch:

```r
save_file <- function(filename) {
  plot_object <- reasterVis::levelplot() # not sure if this is the correct usage.
  print(plot_object)
  dev.off()
  NULL
}

drake_plan(
  file_step = save_file(file_out("name_of_plot")) # file_out() cannot be in the function.
)
```

> I've been showing this package to people in my office, and even a senior manager came over to find out what the network graph was all about.

Nice!
