### ISSUE TITLE
Issue with r_make() and mclapply()

### ISSUE THREAD

**Issue by nschiett** [ropensci/drake#1162]
##  Description

Using `parallel::mclapply()` works fine with `make()`, but r_make() gives back the following error:
"Error while shutting down parallel: unable to terminate some child processes"

## Reproducible example

_drake.R file:
```
library(drake)

plan <- drake_plan(
  test = parallel::mclapply(1:100, sqrt, mc.cores = 2))

config = drake_config(plan = plan, lock_envir = FALSE)
```
Then running `r_make()` returns: 
"target test
Error while shutting down parallel: unable to terminate some child processes",
while 
```
library(drake)
plan <- drake_plan(
  test = parallel::mclapply(1:100, sqrt, mc.cores = 2))
make(plan = plan, lock_envir = FALSE)` 
```
works fine. 

## Session info

R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8       
 [4] LC_COLLATE=en_GB.UTF-8     LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidyselect_1.0.0 drake_7.2.0     

loaded via a namespace (and not attached):
 [1] fansi_0.4.1      ps_1.3.0         assertthat_0.2.1 digest_0.6.23    crayon_1.3.4    
 [6] R6_2.4.1         backports_1.1.5  storr_1.2.1      magrittr_1.5     pillar_1.4.3    
[11] cli_2.0.1        rlang_0.4.4      rstudioapi_0.10  callr_3.4.1      tools_3.6.1     
[16] glue_1.3.1       purrr_0.3.3      igraph_1.2.4.1   parallel_3.6.1   yaml_2.2.1      
[21] compiler_3.6.1   processx_3.4.1   pkgconfig_2.0.3  base64url_1.4    tibble_2.1.3

**Comment by wlandau** [comment]
Despite the error message, the target builds just fine.

``` r
library(drake)

lines <- c(
  "library(drake)",
  "plan <- drake_plan(",
  "  test = parallel::mclapply(seq_len(100), sqrt, mc.cores = 2)",
  ")",
  "config <- drake_config(plan = plan, lock_envir = FALSE)"
)
writeLines(lines, "_drake.R")

r_make()
#> [32mtarget[39m test
#> Error while shutting down parallel: unable to terminate some child processes

unlist(readd(test))
#>   [1]  1.000000  1.414214  1.732051  2.000000  2.236068  2.449490  2.645751
#>   [8]  2.828427  3.000000  3.162278  3.316625  3.464102  3.605551  3.741657
#>  [15]  3.872983  4.000000  4.123106  4.242641  4.358899  4.472136  4.582576
#>  [22]  4.690416  4.795832  4.898979  5.000000  5.099020  5.196152  5.291503
#>  [29]  5.385165  5.477226  5.567764  5.656854  5.744563  5.830952  5.916080
#>  [36]  6.000000  6.082763  6.164414  6.244998  6.324555  6.403124  6.480741
#>  [43]  6.557439  6.633250  6.708204  6.782330  6.855655  6.928203  7.000000
#>  [50]  7.071068  7.141428  7.211103  7.280110  7.348469  7.416198  7.483315
#>  [57]  7.549834  7.615773  7.681146  7.745967  7.810250  7.874008  7.937254
#>  [64]  8.000000  8.062258  8.124038  8.185353  8.246211  8.306624  8.366600
#>  [71]  8.426150  8.485281  8.544004  8.602325  8.660254  8.717798  8.774964
#>  [78]  8.831761  8.888194  8.944272  9.000000  9.055385  9.110434  9.165151
#>  [85]  9.219544  9.273618  9.327379  9.380832  9.433981  9.486833  9.539392
#>  [92]  9.591663  9.643651  9.695360  9.746794  9.797959  9.848858  9.899495
#>  [99]  9.949874 10.000000

r_make()
#> All targets are already up to date.
```

<sup>Created on 2020-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The problem apparently has to do with signal handler clashes between `processx` and `parallel`.  When I first reported this in https://github.com/r-lib/processx/issues/113, the decision was to just live with it. But now that I look back, we have https://github.com/r-lib/processx/issues/236 and https://github.com/r-lib/processx/pull/237. So perhaps `drake` should set `PROCESSX_NOTIFY_OLD_SIGCHLD`, re https://github.com/r-lib/processx/issues/236#issuecomment-582367736.

**Comment by wlandau** [comment]
I attempted a solution in https://github.com/ropensci/drake/commit/ec78daf929f2a4a7ebeb56df032054bf537e5d5f, but it does not work yet. I will need advice on https://github.com/r-lib/processx/pull/237#issuecomment-582970317 before it does.

**Comment by wlandau** [comment]
Requires https://github.com/r-lib/callr/issues/144. Not sure if there will be anything in `drake` to do. Will reopen if there is.

**Comment by wlandau** [comment]
Context: https://github.com/r-lib/processx/pull/237#issuecomment-582994948

**Comment by wlandau** [comment]
@nschiett, sorry I lost track of this issue. Should be fixed with https://github.com/ropensci/drake/commit/c0aee49a19e7c0db03a5aea825d77e1213cf732a and `callr` 3.4.2.
