### ISSUE TITLE
Allow for non-default cache to be supplied to rs_addin_loadd()

### ISSUE THREAD

**Issue by joelnitta** [ropensci/drake#1169]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

Right now I can't see any way to provide `rs_addin_loadd()` with a non-default cache. It would be great to be able to specify a different cache, for example if I have a `make.R` file set up with something like

```
# Load cache
my_cache <- new_cache("my_cache")
# Make plan
make(plan, cache = my_cache)
```

**Comment by wlandau** [comment]
Not sure this is a common use case, but I fixed it anyway. As of 8d19c41e57ee4ba5a935448d5153c76877a10f6c, you should be able to set `options(rstudio_drake_cache = new_cache("my_cache"))` and the `loadd()` addin should know where to look for targets.

**Comment by joelnitta** [comment]
I don't know either, but I happen to use them a lot (handy for zipping and sending caches across machines). Thanks!
