### ISSUE TITLE
Always Run Code with `browser()` or similar

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#1172]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

During development, I sometimes will use `browser()` to simplify development.  And, occasionally, I forget to remove the `browser()` calls.  Code with `browser()` is never certain to be reproducible.

Could `drake` detect `browser()` calls and always run those functions?  (Partly as a reminder to the author to remove the `browser()` calls.  Partly because it's not reproducible.)

**Comment by wlandau** [comment]
Sorry, I think that's out of scope for `drake`. But you may be interested in `drake_debug()` as an alternative to `browser()`.

**Comment by billdenney** [comment]
Thanks!
