### ISSUE TITLE
404 for "say thanks" on README.md

### ISSUE THREAD

**Issue by csgillespie** [ropensci/drake#1174]
## Prework

- [X ] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [ X] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [ X] Advanced users: verify that the bug still persists in the current development version (i.e. `remotes::install_github("ropensci/drake")`) and mention the [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity) of the [Git commit you install](https://github.com/ropensci/drake/commits/master).

## Description

On the README, the link to "Say thanks"  returns a 404

https://github.com/ropensci/drake/blob/master/README.Rmd#L93

**Comment by wlandau** [comment]
Thanks for catching that. As far as I know, however, Say Thanks is down until further notice. From https://github.com/BlitzKraft/saythanks.io/issues/60#issuecomment-586656574, it looks like it's only a matter of time. Related: #1137.
