### ISSUE TITLE
max_expand argument to target()?

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#1175]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

Currently, `max_expand` as an argument to `make` expands all dynamic targets in the plan using this rule. Users may want finer control and want to expand only certain targets. I propose that `max_expand` becomes a possible argument to `target(...)` which would control the expansion for just that target.

**Comment by wlandau** [comment]
Good idea. Now implemented.
