### ISSUE TITLE
Dynamic URLs

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#1179]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

From #1178, `drake` can handle dynamic files, but those files have to be local.

```{r}
plan <- drake_plan(
  upload_step = target(
    write_some_files_and_return_paths(),
    format = "file"
  )
)
```

What about dynamic URLs? 

```{r}
plan <- drake_plan(
  upload_step = target(
    upload_some_files_and_return_urls(),
    format = "url"
  )
)
```

## Challenge

`drake` needs some general way of verifying that the file completed uploading before it moves on to the next targets. This is easy with `format = "file"` because `drake` already has its own way of computing HPC checksums. But can we compute a local ETag and trust that the ETag from the website is the same? I am not sure. @noamross, what do you think?

**Comment by wlandau-lilly** [comment]
Questioning this issue. I do not think there is a general enough way to check if or when a file completes its upload.
