### ISSUE TITLE
Formal data structure validators

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#1180]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

Given the flexible, low-tech approach to `drake`'s [internals](https://books.ropensci.org/drake/design.html), maybe we should validate the main data types.

## Proposal

Create a `validate()` S3 generic and a method for each type.

```{r}
validate <- function(x, ...) {
  UseMethod("validate")
}

validate.drake_plan <- function(x, ...) {
  stopifnot(is.data.frame(x))
  # ...
}

validate.drake_config <- function(x, ...) {
  stopifnot(is.list(x))
  # ...
}
```

Many of these checks already exist in other places.

## Classes to validate

* `drake_plan`
* `drake_config`
* `drake_spec`
* `drake_meta`

Those are the most flexible and most important ones.

**Comment by wlandau-lilly** [comment]
Closing in favor of #1183 and issues to come afterwards. We should not tackle all the validators at once.
