### ISSUE TITLE
Warning for missing or ill-defined grouping variable should be an error

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#1182]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [x] Advanced users: verify that the bug still persists in the current development version (i.e. `remotes::install_github("ropensci/drake")`) and mention the [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity) of the [Git commit you install](https://github.com/ropensci/drake/commits/master).

## Description

Currently, if the user messes up a grouping variable, the target gets deleted with a warning. I can't imagine a use case where a user would want to actually continue with a deleted target. So, this warning should really be an error.

## Reproducible example

``` r
drake::drake_plan(mytarget = target(a, map(b)))
#> Warning: A grouping or splitting variable for target 'mytarget' is missing or
#> undefined. Transformation skipped and target deleted.
#> # A tibble: 0 x 2
#> # … with 2 variables: command <list>, target <chr>
```

<sup>Created on 2020-02-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## Expected result

An error.

**Comment by wlandau** [comment]
Fair enough. Now fixed.
