### ISSUE TITLE
Directories (folders) are not reproducibly tracked.

### ISSUE THREAD

**Issue by wlandau-lilly** [ropensci/drake#12]
Yes, you can declare a file target or input file by enclosing it in single quotes in your workflow plan data frame. But entire directories (i.e. folders) cannot yet be tracked this way. This is a trickier problem to solve, and lots of individual edge cases need to be ironed out before I can deliver a clean, reliable implementation.

**Comment by wlandau-lilly** [comment]
Now documented in the [caution vignette](https://github.com/wlandau-lilly/drake/blob/master/vignettes/caution.Rmd).

**Comment by wlandau-lilly** [comment]
Not sure if it is reasonable to expect this sort of behavior. Will keep open for now.

**Comment by wlandau-lilly** [comment]
I do not think this is necessary, and the existing behavior is mentioned in the caution vignette. That should be enough.

**Comment by wlandau-lilly** [comment]
Will reopen on request.

**Comment by krlmlr** [comment]
Now we could add a `dir_output()`. There are some output formats that consist of multiple files (e.g., ESRI shapefiles). When working with *remake* I sometimes wanted this feature but always found a way to work around it. I'd say, low priority but may be helpful in some cases.

**Comment by wlandau** [comment]
I think the existing `file_output()` would supply enough information to `drake`. Currently, `drake` analyzes and fingerprints output files, and it is easy to check if an output file is a directory. But how do you suggest we hash entire directories recursively? Should this be the responsibility of `digest`? Related: #257.

**Comment by krlmlr** [comment]
For writing shapefiles, we need to specify the path to the `.shp` file, other files have (by convention) the same name and are in the same directory. This is easy with `dir_output()`, it also has other advantages:

- *drake* knows what to expect, a file or a directory, and can fail if it's something else
- We could specify which files are part of the hash
- We could create the directory for the user if it's missing

I suggest we record paths, timestamps/sizes and hashes for all files and invalidate downstream targets if any of these differ.

**Comment by wlandau** [comment]
I think I still need convincing on this. From my perspective, it seems as though a recursive directory hash and a recursive max timestamp would capture all the information we need to treat a directory as a file target and invalidate downstream targets correctly. I suppose we could expand the metadata for directories for the sake of user-side diagnostics, but we might risk overly complicating sensitive internals. And some versions of this approach (but not all) clash with `drake`'s [current bijectivity restriction](https://github.com/ropensci/drake/issues/232#issuecomment-366308196) from #232.

**Comment by krlmlr** [comment]
To write shapefiles, we need:

```r
write_shapefile(shp, dir_out(file = "path/to/dir/file.shp"))
```

This creates `file.shp` (which is returned by `dir_out()`) and a bunch of other `file.*` files, but the entire directory is the artifact.

Max timestamp is brittle (won't track removed files), but a hash of the directory listing (names + sizes + timestamps) will do.

**Comment by wlandau** [comment]
I see. How far up the directory tree would `dir_out()` go?

**Comment by krlmlr** [comment]
Perhaps one level by default, it could also gain a `dir` argument or semantics like `dir_out("path/to/dir", file = "file.shp")` .

**Comment by wlandau** [comment]
Sounds reasonable. Will reopen if we figure out a way to solve #266 with a persistent class.

**Comment by krlmlr** [comment]
We could add a terminal slash to drake's internal representation of targets:

- `file_in("path/file")` -> '"path/file"'
- `dir_in("path")` -> '"path/"'

But if we assume that we need `dir_in()` and `dir_out()`, we have many combinations to think about:

- `dir_out()` inside `dir_in()`
- `dir_out()` inside `dir_out()`
- `dir_in()` inside `dir_out()`
- `dir_in()` inside `dir_in()`
- `file_out()` inside `dir_in()`
- `file_out()` inside `dir_out()`
- `file_in()` inside `dir_out()`
- `file_in()` inside `dir_in()`

So this may even be a more difficult problem than multi-file targets (#283).

**Comment by wlandau** [comment]
@billdenney reminded me of this thread in #794. With #283 solved and with more mature internals in `drake`, I think we can revisit the conversation.

**Comment by wlandau** [comment]
I think we gain a lot by designing for #794 so users do not need to declare the individual files in the directory. This could even compensate for #685 etc., situations where we do not know the output in advance.

This approach is more appealing to me than https://github.com/ropensci/drake/issues/12#issuecomment-367042903 or https://github.com/ropensci/drake/issues/12#issuecomment-367357409. Regarding shapefiles, #283 already allows us to write `write_shapefile(shp, file_out("path/to/dir/file.shp", "path/to/dir/file.shx", "path/to/dir/file.prj", "path/to/dir/file.dbf"))`.

I say we just appropriate `file_in()` and `file_out()` to deal with directories. As long as we use a different hash for `dir/file.xyz` than `file.xyz`, I think we will be fine. There are fewer checks and safeguards than https://github.com/ropensci/drake/issues/12#issuecomment-367042903, but I think that is okay.

**Comment by bpbond** [comment]
👍 for this–would be a huge bonus for our workflows.
