### ISSUE TITLE
Dynamic branching: Use tribble as `.data` input for `map()`

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#1202]
In [mlr3-leardrake]() I want to switch from static branching to dynamic branching to save the custom aggregation functions and have all benchmark runs aggregated in one target.

[Back in the days](https://github.com/mlr-org/mlr3-learndrake/blob/db4556538b3e82292ff13851d9554e3d39e764ac/02-benchmark/R/benchmark.R#L40-L41) you used `.data` within `transform` to hand over a `tribble` which was then used by `map()` (btw I haven't found this approach in the drake manual - is it really undocument?).

Apparently the same does not work with `dynamic` instead of `transform`.
I tried various options but was not successful. Is it even possible?

If so, how could I map over the tribble in a rowwise fashion using dynamic branching?

PS: If you want to check out the repo and try it locally, `devtools::install_dev_deps()` and `r_make()` should get you there quickly.

**Comment by wlandau** [comment]
Dynamic branching lets you map over the rows of the data frame. I think this does what you need as long as you are willing to select the appropriate elements. Oversimplified reprex:

``` r
library(drake)
library(tibble)

settings <- tribble(
  ~x, ~y,
  11, 1,
  12, 2,
  13, 3,
  14, 4
)

plan <- drake_plan(
  sums = target(
    settings$x + settings$y,
    dynamic = map(settings)
  )
)

make(plan)
#> ℹ Consider drake::r_make() to improve robustness.
#> ▶ dynamic sums
#> > subtarget sums_37e9d817
#> > subtarget sums_35a037e3
#> > subtarget sums_1bf2035b
#> > subtarget sums_39438924
#> ■ finalize sums

readd(sums)
#> [1] 12 14 16 18

readd(subtargets(sums)[2], character_only = TRUE)
#> [1] 14
```

<sup>Created on 2020-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pat-s** [comment]
Thanks Will. While I am able to map over the vector inputs, mapping over the symbolic parts causes issues, even when using `[[1]]` combined with `rlang::eval_tidy()`:

https://github.com/mlr-org/mlr3-learndrake/blob/6cde76668930f18eade12bb08a7cfbbe6ac7f73a/02-benchmark/R/benchmark.R#L29-L40

https://github.com/mlr-org/mlr3-learndrake/blob/6cde76668930f18eade12bb08a7cfbbe6ac7f73a/02-benchmark/R/00-functions.R#L30

```r
Error: callr subprocess failed: target bm_08b47883 failed.
diagnose(bm_08b47883)error$message:
  object 'param_set_knn1' not found
```

Is there any specific way how to unsym the object so that drake can map over it / that `vctrs` likes it? Sorry, I am really not yet into {vctrs} and its details.

**Comment by wlandau** [comment]
Dynamic branching tries to get away from the metaprogramming that made static branching so confusing. So I recommend you move away [creating symbols](https://github.com/mlr-org/mlr3-learndrake/blob/6cde76668930f18eade12bb08a7cfbbe6ac7f73a/02-benchmark/R/benchmark.R#L11) from the start. Downstream of `param_sets_plan`, you could gather all your param sets into a list, put that list into the `param_set` column of a `benchmark_grid`, and then map over `benchmark_grid` with the actual param sets included.

**Comment by pat-s** [comment]
Thanks! Got it working now. Still making my way through dynamic branching - thanks for your help 🤗
