### ISSUE TITLE
show something when starting to build targets when verbose = 2

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#1203]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

Would be good to have something show before the first target is done to indicate that building has started when verbose = 2. Maybe even a fake progress bar with 1000 ticks and one tick done so that it shows 0%?

**Comment by wlandau** [comment]
Good call, now an empty progress bar should appear right before targets start.
