### ISSUE TITLE
Trigger whenever another target is rebuilt

### ISSUE THREAD

**Issue by adamaltmejd** [ropensci/drake#1213]
Working with a really large project where some of the final parts are run in Stata. I've written a script to source Stata do files using the processx which works really well. But what I cannot figure out is how to get the dependencies working correctly in drake. The Stata scripts use data produced by the R project to output files. So I've just set up file_in() and file_out() with all files that are being used and produced. But with the number of files it is starting to get really messy. Instead of keeping track of files I thought I might just set up these targets to run whenever any of a number of other targets are rebuilt. Sounds really simple but couldn't find anything about it in the manual. Any hints would be appreciated! Importantly, the Stata targets themselves are just NULLs in Drake after having been built successfully.

Toy example:

```
plan <- drake_plan(
  data = build_huge_dataset(file_in("input.csv"),
  save_stata = write_dta(data, file_out("output.dta"),
  main_estimation = stata("main_estimation.do", file_in("output.dta"), file_out("estimates.dta")),
  robustness_estimation = stata("robustness_estimation.do", file_in("output.dta"), file_out("robustness.dta")),
  graphs = stata("graphs.do", file_in(c(<lots of files>), file_out(c(<lots of files>))
)
```

How can I set the `graphs` target to rebuild whenever `main_estimation` or `robustness_estimation` is rebuilt (when `readd(main_estimation)` returns NULL)? Also, how can I set `main_estimation` to rebuild whenever `save_stata` is rebuilt without including `save_stata` as an object in the `main_estimation` command (then Drake loads this large object it into memory)?

**Comment by wlandau** [comment]
> How can I set the graphs target to rebuild whenever main_estimation or robustness_estimation is rebuilt

You can declare the `file_out()` files from `main_estimation` and `robustness_estimation` as `file_in()` files on the command of `graphs`, and you can check `vis_drake_graph(plan)` to make sure `drake` understands the connections induced by `file_out()`/`file_in()` connections. Also, I recommend you use `file_in()` on your Stata `.do` scripts.

**Comment by adamaltmejd** [comment]
That is exactly how I'm doing it now. The problem is that the estimation scripts generate a large number of files that are then all used as file_in() for graphs and file_out() in graphs has a couple of hundred rows. Could keep it like this but since it is supposed to run every time I thought maybe I could use a trigger.

**Comment by wlandau** [comment]
`file_in()` and `file_out()` work on directories too. You could tell Stata to write those hundreds of files to a single directory and then declare `file_out("your_dir")`. Later on, you would write `file_in("your_dir")`.

Dynamic files are also an option: https://books.ropensci.org/drake/plans.html#dynamic-files

**Comment by adamaltmejd** [comment]
Oh, didn't know about the directories. Thanks!
