### ISSUE TITLE
Target progress not shown

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#1219]
In [mlr3-learnerdrake](https://github.com/mlr-org/mlr3-learndrake) no target progress is shown (no matter the verbose setting) since drake v7.11.0.
I only see the spinner - no progress bar, no target names which finished.

I suspect that the {lgr} package, which we use internally, interfers?
I haven't digged deeper yet. Maybe you have an idea before I put too much time in?

**Comment by wlandau** [comment]
Even with `verbose = 1`? That's odd because the default console logging system just uses `cli` and `message()`. Would you check what happens if you disable `lgr` on your end?

https://github.com/ropensci/drake/blob/13c0539f0597455de052b4ab9a2b5d4d5ef3108a/R/logger.R#L110-L164

**Comment by wlandau** [comment]
`lgr` alone + `drake` looks okay on my end.

``` r
library(drake)
library(lgr)
f <- function() {
  lgr$info("msg")
}
plan <- drake_plan(x = f())
make(plan)
#> ▶ target x
#> INFO  [15:17:10.292] msg
```

<sup>Created on 2020-03-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pat-s** [comment]
Yeah probably its not {lgr} but something else.
I realized the issues for `verbose = 2` come down to `make()` vs. `r_make()`:

## r_make()

- `verbose = 1`: works fine
- `verbose = 1` + within-target parallelization with {future}: No target progress output
- `verbose = 2` (for both scenarios with reported for verbose = 1): No target progress output

## make()

- `verbose = 1` works fine
- `verbose = 1` + within-target parallelization with {future}: works fine
- `verbose = 2` + within-target parallelization with {future}: works fine

**Comment by wlandau** [comment]
So the issue is with `r_make()` and `verbose = 2`. I reproduced it with the following `_drake.R`:

```r
library(drake)
f <- function(i) {
  Sys.sleep(1)
}
plan <- drake_plan(x = target(f(i), transform = map(i = !!seq_len(10))))
drake_config(plan, verbose = 2)
```

**Comment by wlandau** [comment]
I just remembered that I saw this before and it is actually due to https://github.com/r-lib/progress/issues/101. Unfortunately there is nothing else we can do on `drake`'s end.
