### ISSUE TITLE
readd upon RStudio click 

### ISSUE THREAD

**Issue by rsangole** [ropensci/drake#1221]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

This one is really out there, but...

Wouldn't it be wonderful if we could run a `readd()` upon clicking on a target in the source window? Just like `cmd+click` opens the source code for a function in Mac... what if we could do `cmd+option+click` to quickly do a `readd` on a target? It would be so quick to look at targets without having to type `readd` and (often long) target names.

I know this is probably not in your control - might need some RStudio hacking - but throwing it out there to have a conversation about it.

**Comment by wlandau** [comment]
@MilesMcBain actually wrote an [RStudio addin](https://rstudio.github.io/rstudioaddins/) that calls `loadd()` on the target at your cursor: #763, #825. `drake` also has addins for `r_make()`, `r_vis_drake_graph()`, and `r_outdated()`.

<img width="963" alt="Screen Shot 2020-03-20 at 7 21 20 PM" src="https://user-images.githubusercontent.com/1580860/77213394-0a3a4c00-6ae1-11ea-859d-d89fe0909c88.png">

**Comment by wlandau** [comment]
Meant to attach this plot:

<img width="1678" alt="Screen Shot 2020-03-20 at 7 26 52 PM" src="https://user-images.githubusercontent.com/1580860/77213410-1aeac200-6ae1-11ea-9f6d-13389d419987.png">
