### ISSUE TITLE
Increase guardrails on file_out() and knitr_in()

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#1229]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

`file_out()` and `knitr_in()` should not be used inside imported functions, and they should not be used in dynamic branching. `drake` should make both impossible, and the errors should be informative.

**Comment by wlandau-lilly** [comment]
Let's also throw warnings if people try to use dynamic paths, e.g. `file_in(paste(var, ".html"))`

**Comment by wlandau** [comment]
In the case of dynamic branching, the existing prohibition on `file_out()` should be enough. (`knitr_in()` is always paired with `file_out()` in practice.)
