### ISSUE TITLE
drake/lock permissions

### ISSUE THREAD

**Issue by danwwilson** [ropensci/drake#1232]
## Prework

- [X] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [X] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

When creating a new drake project that is stored on a network drive the `.drake/drake/history/lock` file doesn't have group read permissions. This tends to cause issues for backup jobs (run under a backup user), as it isn't able to read the lock file.

What it means for me personally is needing to adjust the permissions for the lock file for each new drake project. While it's not a deal breaker, I was wondering if there might be something in the way that `use_drake()` creates objects that might allow the read permissions for the group to be applied.

**Comment by wlandau** [comment]
`use_drake()` actually just creates script files. The cache gets created when you run `make()`, `new_cache()` or `drake_config()`. If you do not need `drake_history()`, you can set `history = FALSE` in `make()` or `drake_config()` to prevent `history/lock` from being generated at all. All the files in `history/` are a [`txtq`](https://github.com/wlandau/txtq), and the `lock` file is generated by [`filelock`](https://github.com/r-lib/filelock). It will probably be easier on your end to troubleshoot similar issues with only those lighter packages.

**Comment by wlandau** [comment]
You could also try and install https://github.com/wlandau/txtq/commit/ba15026515887591c02461bb9b436273a460b591. That commit forces `txtq` to remove the lockfile periodically. It should solve this issue except if the `drake` session crashes at the wrong time and does not clean up.

**Comment by wlandau** [comment]
Hmm... that turns out to not work on Windows for some reason. Try https://github.com/wlandau/txtq/commit/4bf88769facacbcf9f2350831824c6b086e6450c. In that commit, the lockfile is created in advance and outside `filelock`, which just might resolve permissions issues. I don't know.

**Comment by wlandau** [comment]
From https://github.com/r-lib/filelock/issues/26, it looks like this error came from the fact that some file systems do not support file locking. Should be fixed for `drake` in 2ffd42af9d9d14f8f1e9482eee03bc24bfbdbb7b. Feel free to give it a try.
