### ISSUE TITLE
Error in specialized format option

### ISSUE THREAD

**Issue by jennysjaarda** [ropensci/drake#1242]
## Prework

- [X] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [X] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [X] Advanced users: verify that the bug still persists in the current development version (i.e. `remotes::install_github("ropensci/drake")`) and mention the [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity) of the [Git commit you install](https://github.com/ropensci/drake/commits/master).

## Description

Describe the bug clearly and concisely. 
I'm trying to run the example here: https://github.com/ropensci/drake/pull/1178 and I am getting an error, I have the latest version of drake installed.
## Reproducible example

```
packageVersion("drake")
# ‘7.12.0.9000’

good_plan <- drake_plan(
  upstream = target({
      writeLines("one line", "my file") # Make sure the file exists.
      "my file" # Must return the file path.
    },
    format = "file" # Necessary for dynamic files
  ),
  downstream = readLines(upstream) # Use the target name.
)

plot(good_plan)
```

Error: the format column of your drake plan can only have values "fst", "fst_dt", "diskframe", "keras", "qs", "rds", or NA. Illegal values found:
  file

**Comment by wlandau** [comment]
Looks like you may have gotten unlucky with the commit you installed. I cannot reproduce it with either https://github.com/ropensci/drake/commit/85ea21fc7d3ab2a0b80b3206adfece5be698c9c9 or the CRAN version. The problem should go away if you update `drake`. Let me know if it persists.

``` r
library(drake)

packageDescription("drake")$GithubSHA1 # 2020-04-09
#> [1] "85ea21fc7d3ab2a0b80b3206adfece5be698c9c9"

good_plan <- drake_plan(
    upstream = target({
        writeLines("one line", "my file") # Make sure the file exists.
        "my file" # Must return the file path.
    },
    format = "file" # Necessary for dynamic files
    ),
    downstream = readLines(upstream) # Use the target name.
)

plot(good_plan)
```

![](https://i.imgur.com/uQSIpPn.png)

``` r

make(good_plan)
#> ▶ target upstream
#> ▶ target downstream
```

<sup>Created on 2020-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
By the way, in the latest version of `drake`, the error message for illegal formats changed.

``` r
library(drake)
packageVersion("drake")
#> [1] '7.12.0'
plan <- drake_plan(
  x = target(123, format = "UNKNOWN")
)
make(plan)
#> Error: illegal format UNKNOWN. Read https://docs.ropensci.org/drake/reference/drake_plan.html#formats
```

<sup>Created on 2020-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Did you start with an older `drake` (< 7.12.0), update to >= 7.12.0, and then try the example again in the same session? If so, it could have been that you still had the old version loaded into memory while the new version was in storage. Restarting your R session usually solves the issue, and the [`reprex`](https://reprex.tidyverse.org/) package helps avoid those sorts of gotchas.

**Comment by jennysjaarda** [comment]
Sorry you are right - it was that exactly! I will install reprex for the next time

**Comment by jennysjaarda** [comment]
One other question using the format = "file" feature. Does it work properly
with a function that writes more than one file? Such as the following:

write_two_files <- function(file_one, file_two){

  writeLines("one line", file_one)
  writeLines("another line", file_two)
}

good_plan <- drake_plan(

  upstream = target({

    write_two_files("file_one", "file_two") # Make sure the file exists.

    "file_one" # Must return the file path.
    "file_two"

  },

  format = "file" # Necessary for dynamic files

  ),

  downstream = readLines(upstream) # Use the target name.

)

make(good_plan)

It seems to only read the second file. I am guessing that a better way to
do this is just split up the write function so each function only writes
one file. This is possible for user defined functions, but sometimes
package function or non R-code related functions (using processx) will
write many files per function and there is no logical workaround (that I
can see) for this. Any suggestions?

**Comment by jennysjaarda** [comment]
I think I solved it, is this the right approach?


good_plan <- drake_plan(

  upstream = target({

    write_two_files("file_one", "file_two") # Make sure the file exists.

    c("file_one", "file_two") # Must return the file path.

  },

  format = "file" # Necessary for dynamic files

  ),

  downstream = read.table(upstream[1]), # Use the target name.
  downstream2 = read.table(upstream[2]) # Use the target name.

)

**Comment by wlandau** [comment]
That seems correct. The only issue is downstream2 will change when the file at `upstream[1]` changes. Same with target `downstream` and the file at `upstream[2]`. This may not be desirable from a time-saving perspective. You might instead want to have different `downstreams` for different files so each `downstream` object will ignore updates to the files that are not ultimately used.

```{r}
drake_plan(
  file_names <- c("file_one", "file_two"),
  upstream = target({
      write_one_file(file_names)
      file_names
    },
    dynamic = map(file_names),
    format = "file"
  ),
  downstream = target(
    read.table(upstream),
    dynamic = map(upstream)
  )
)

```

**Comment by jennysjaarda** [comment]
Makes sense. So first define the file_names as a separate target and then apply dynamic map using this target.

**Comment by wlandau** [comment]
Exactly. Or `file_names` could be a global variable. Either way works.

```{r}
file_names <- c("file_one", "file_two"),

drake_plan(
  upstream = target({
      write_one_file(file_names)
      file_names
    },
    dynamic = map(file_names),
    format = "file"
  ),
  downstream = target(
    read.table(upstream),
    dynamic = map(upstream)
  )
)
```
