### ISSUE TITLE
Force unlock message in Windows shows \ instead of / in the path

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#1243]
In this line:

https://github.com/ropensci/drake/blob/c02f19e6ef3d698e7f46cf78bdf2b391823c334a/R/decorate_storr.R#L235

The error message is shown with backslashes (\) instead of forward slashes (/) in Windows, so it cannot be simply pasted.

The message looks like:
```
drake::drake_cache("C:\some_path\.drake")$unlock()
```

When it should look like:
```
drake::drake_cache("C:/some_path/.drake")$unlock()
```

Using `normalizePath()` should make it work as desired.  (PR coming shortly.)

**Comment by wlandau** [comment]
Both should work even on Windows, but the second version is clearer.

**Comment by billdenney** [comment]
The first message gave an error like:

"\." is not a recognized escape sequence.

Thanks for merging!
