### ISSUE TITLE
tidy_eval before transform in drake_plan to allow meta-programming

### ISSUE THREAD

**Issue by rich-payne** [ropensci/drake#1251]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

When `drake` workflows are used routinely for similar applications, it's nice to write functions which use meta-programming to create drake plans.  However, I've found one case where this meta-programming is not possible.  If meta-programming is used to create drake targets (using tidy evaluation) and a transformation, the transformation happens before the tidy evaluation and the transformation does not work as desired. 

Here's an example:

``` r
library(drake)
create_meta_drake <- function(
  my_code,
  my_transform
) {
  my_code <- substitute(my_code)
  drake_plan(
    target1 = target({
        !!!my_code
      },
      transform = map(.data = !!my_transform)
    )
  )
}

plan <- create_meta_drake(
  my_code = {
    data.frame(a = rnorm(abc))
  },
  my_transform = data.frame(abc = 1:2)
)

plan
#> # A tibble: 2 x 2
#>   target     command                           
#>   <chr>      <expr>                            
#> 1 target1_1L {     data.frame(a = rnorm(abc)) }
#> 2 target1_2L {     data.frame(a = rnorm(abc)) }
```
<sup>Created on 2020-05-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

In the above, I would like `abc` to be replaced with 1 and 2.  Would it be possible to move tidy evaluation before the transformation occurs in `drake_plan()` as in https://github.com/rich-payne/drake/commit/13fa883a54abc1610749096a419818f4bbe3fd39 ? This allows the desired result.

Or is there a better way to accomplish this?

**Comment by wlandau** [comment]
With a couple tricks, it is possible.

1. Call `drake_plan()` with `transform = FALSE` to suppress the transformation. Keep `tidy_eval = TRUE` (default) so the command gets substituted.
2. Then, call `transform_plan()` with `tidy_eval = TRUE` (not the default).

``` r
library(drake)
create_meta_drake <- function(
  my_code,
  my_transform
) {
  my_code = substitute(my_code)
  plan <- drake_plan(
    target1 = target(
      {!!!my_code},
      transform = map(.data = !!my_transform)
    ),
    transform = FALSE
  )
  transform_plan(plan, tidy_eval = TRUE)
}

create_meta_drake(
  my_code = {
    data.frame(a = rnorm(abc))
  },
  my_transform = data.frame(abc = seq_len(4))
)
#> # A tibble: 4 x 2
#>   target     command                          
#>   <chr>      <expr>                           
#> 1 target1_1L {     data.frame(a = rnorm(1L)) }
#> 2 target1_2L {     data.frame(a = rnorm(2L)) }
#> 3 target1_3L {     data.frame(a = rnorm(3L)) }
#> 4 target1_4L {     data.frame(a = rnorm(4L)) }
```

<sup>Created on 2020-05-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rich-payne** [comment]
Excellent!  Many thanks.
