### ISSUE TITLE
.bib dependency in Rmarkdown

### ISSUE THREAD

**Issue by ha0ye** [ropensci/drake#1254]
I know that `drake` will look through code chunks in a Rmarkdown to identify dependencies, but it doesn't seem to automatically detect that a .bib file associated with an Rmarkdown report is a dependency when using `knitr_in()`.

Even for an edge case, this seems a bit niche... should I just set a manual trigger on the `.bib` file for rendering the Rmarkdown target instead of, e.g. filing this as a bug or feature request?

**Comment by wlandau** [comment]
I would prefer to draw the line between `drake` targets and R Markdown niche cases when it comes to tracking dependencies. You can use `file_in("your_bibliography.bib")` in either the command of the target or in an active code chunk in the R Markdown report itself.
