### ISSUE TITLE
Track dependencies at the level of individual columns of data

### ISSUE THREAD

**Issue by hughjonesd** [ropensci/drake#1259]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

My problem can be simply described with the picture below:

![Screenshot 2020-05-20 at 19 27 07](https://user-images.githubusercontent.com/5818871/82483229-f8b8f480-9acf-11ea-9039-8592b09ef9e7.png)

In other words, I have a single huge data frame, and all my analyses depend on it. Whenever I tweak a column, all the analyses rerun. This is painful.

I should probably split my data frame into separate columns, and have separate "preparation" stages for each analysis. But it's difficult to keep track of that in my head. When I'm working with data I want one big object with everything available.

It would be nice if drake had a mechanism to track columns in data, rather than entire objects. Perhaps this is impossible. (Presumably, static code analysis of which columns a function uses, or which columns it affects, is a hard problem.) Still, if it were possible, something manual like

```
columns_of(my_data, col1, col2, col3)
```

might be an equivalent of `file_in()` for data frame columns.

If it's impossible, then my fallback proposal is for the documentation to discuss solutions to my anti-pattern. I looked, but didn't find anything quite relevant.

**Comment by wlandau** [comment]
`drake` itself is not really in a position to add new features to make this easier, but there are workarounds in how you use it. For column-wise workflows, you can break up the data into individual columns and then pass those columns to downstream targets.

```r
drake_plan(
  data = iris[, seq_len(3)],
  col1 = data$Sepal.Length,
  col2 = data$Sepal.Width,
  col3 = data$Petal.Length,
  mean1 = mean(col1),
  mean2 = mean(col2),
  mean3 = mean(col3)
)
```

[Static branching](https://books.ropensci.org/drake/static.html) could help you automate some of this.

```r
drake_plan(
  data = iris[, seq_len(3)],
  col = target(
    data[[colname]],
    transform = map(colname = !!cols)
  ),
  mean = target(
    mean(col),
    transform = map(col)
  )
)
```

Or [dynamic branching](https://books.ropensci.org/drake/dynamic.html):

```r
drake_plan(
  data = as.list(iris[, seq_len(3)]),
  col = names(data),
  mean = target(
    mean(data[[col]]),
    dynamic = map(col)
  )
)
```

These techniques usually involve duplicating the data in storage, so be sure to check out [specialized data formats](https://books.ropensci.org/drake/plans.html#special-data-formats-for-targets) if your dataset is large.
