### ISSUE TITLE
error with clustermq?

### ISSUE THREAD

**Issue by jennysjaarda** [ropensci/drake#1264]
Hello, 
I am using clustermq backend with slurm and some of my `out` files have the following error message... any ideas? 

```
clustermq:::worker("tcp://node13:6442")
2020-05-27 22:46:37.471007 | Master: tcp://node13:6442
2020-05-27 22:46:37.481924 | WORKER_UP to: tcp://node13:6442
2020-05-27 22:47:57.235075 | 
Error in switch(msg$id, DO_CALL = { : EXPR must be a length 1 vector
Calls: <Anonymous>
Execution halted
```

**Comment by wlandau** [comment]
I'm not sure how to investigate using just this information. Can you reproduce the error without `drake`?

**Comment by jennysjaarda** [comment]
Sorry I have no idea how to reproduce, I just wondered if you had come across it before. It doesn't seem to be causing any major issues so I think we can close it...

**Comment by wlandau** [comment]
I will keep an eye out now that you mentioned it. I have not encountered it before. Just curious, what version of `clustermq` were you running?
