### ISSUE TITLE
Add a verbose level to only show bullet point targets

### ISSUE THREAD

**Issue by mattwarkentin** [ropensci/drake#1265]
Hi @wlandau,

This package is amazing. It has transformed the way I work on R projects.

Anyway, I was wondering if it would be possible to add a verbosity level that shows the bullet points for which target is being executed without printing any messages from inside the target script? Something in between `verbose = 0` and `verbose = 1`.

I like to know where my plan is at, but without necessarily seeing all of the minutia going on underneath the hood. Maybe there is already a way to do this that I haven't figured out, I am new to `{drake}`.

Thanks!

**Comment by wlandau** [comment]
Glad to hear `drake` is useful for you.

Do those messages come from your own custom code? If so, hiding them is outside the scope of `drake`, and based on other feedback, I think few other users would find this desirable. In fact, `drake` takes extra steps to relay and print messages in high-performance computing situations.

**Comment by wlandau** [comment]
But you can call `suppressMessages()` in your custom code.
