### ISSUE TITLE
Move away from the iris dataset

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#1271]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

Background: https://armchairecology.blog/iris-dataset/

**Comment by wlandau-lilly** [comment]
Started a branch for this: https://github.com/ropensci/drake/tree/1271
