### ISSUE TITLE
RMarkdown dependency not detected automatically with code_to_function

### ISSUE THREAD

**Issue by robitalec** [ropensci/drake#1278]
## Prework

- [X] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [X] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [X] Advanced users: verify that the bug still persists in the current development version (i.e. `remotes::install_github("ropensci/drake")`) and mention the [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity) of the [Git commit you install](https://github.com/ropensci/drake/commits/master).

## Description

Unlike the [basic example](https://books.ropensci.org/drake/plans.html#intro-to-plans) in the book, the dependencies are not detected automatically between an RMarkdown file and functions generated with `code_to_function`. 

## Reproducible example

`scripts/data-prep.R`

```r
library(data.table)

mtcars <- fread('data/mtcars.csv')

saveRDS(mtcars, 'data/mtcars.Rds')
```

`scripts/process.R`

```r
library(data.table)

cars <- readRDS('data/mtcars.Rds')
setalloccol(cars)

cars[, mpg100 := mpg * 100]

saveRDS(cars, 'data/cars100.Rds')
```

`md/report.Rmd`

```md
---
title: "Test Drake"
output: html_document
---

(triple backtick, curly braces, r, setup)
knitr::opts_chunk$set(echo = TRUE)
(triple backtick)


(triple backtick, curly braces, r)
cars <- readRDS('data/cars100.Rds')
summary(cars)
(triple backtick)

```

`scripts/plan.R`

```r
library(drake)

data_prep <- code_to_function('scripts/data-prep.R')
process <- code_to_function('scripts/process.R')

plan <- drake_plan(
  prepared = data_prep(),
  processed = process(prepared),
  report = rmarkdown::render(
    knitr_in('md/report.Rmd')
  )
)
```

`_drake.R`

```
source("scripts/plan.R")

drake_config(plan)
```

```r
r_vis_drake_graph()
```

![image](https://user-images.githubusercontent.com/16324625/84954432-f302fe80-b0cf-11ea-87ad-7f4b9b882b84.png)

## Expected result

If drake is expected to automatically detect dependencies for RMarkdown file, which the chapter linked above seems to indicate, it should've connected the report with the output from "processed". For example, out of the book: 

![image](https://user-images.githubusercontent.com/16324625/84954677-6ad12900-b0d0-11ea-90e5-5d6f9008091c.png)

I started a work around for this, I thought maybe I could wrap rmarkdown::render in another function, then setting the dependencies manually. For example:

`scripts/plan.R`

```r
library(drake)

data_prep <- code_to_function('scripts/data-prep.R')
process <- code_to_function('scripts/process.R')

render_report <- function(...) {
  rmarkdown::render(
    'md/report.Rmd',
    output_format = 'all'
  )
}

plan <- drake_plan(
  prepared = data_prep(),
  processed = process(prepared),
  report = render_report(processed)
)
```

This returned a graph as expected, and, at first, it didn't work to make because there weren't any arguments for the `render_report` function, but once I added `...`, it ran fine. 

![image](https://user-images.githubusercontent.com/16324625/84955400-d10a7b80-b0d1-11ea-9aba-b0d6abcca8e6.png)

This seems like a fine workaround, but wanted to mention it in case you didn't know about this side effect of `code_to_function`. An alternative, is to use a dedicated script for `rmarkdown::render` as you show in the [Script-based workflow](https://books.ropensci.org/drake/scripts.html) chapter. 

I could generalize the render function, to reuse it across render steps as well, eg with a filename argument:

```r
render_report <- function(filename...) {
  rmarkdown::render(
    filename,
    output_format = 'all'
  )
}
```

`scripts/plan.R`

```r
library(drake)

data_prep <- code_to_function('scripts/data-prep.R')
process <- code_to_function('scripts/process.R')

render_report <- function(filename, ...) {
  rmarkdown::render(
    filename,
    output_format = 'all',
    quiet = TRUE
  )
}

plan <- drake_plan(
  prepared = data_prep(),
  processed = process(prepared),
  report = render_report('md/report.Rmd',
                         processed),
  report2 = render_report('md/report2.Rmd',
                          processed)
)
```
![image](https://user-images.githubusercontent.com/16324625/84955918-b7b5ff00-b0d2-11ea-9781-51c66961f16b.png)

Thanks!

## Session info

```
R version 4.0.1 (2020-06-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS:   /usr/lib/libopenblasp-r0.3.9.so
LAPACK: /usr/lib/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_CA.UTF-8      
 [2] LC_NUMERIC=C              
 [3] LC_TIME=en_CA.UTF-8       
 [4] LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8   
 [6] LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8      
 [8] LC_NAME=C                 
 [9] LC_ADDRESS=C              
[10] LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_CA.UTF-8
[12] LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] data.table_1.12.8 drake_7.12.2.9000

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6       txtq_0.2.0        
 [3] lattice_0.20-41    ps_1.3.3          
 [5] visNetwork_2.0.9   prettyunits_1.1.1 
 [7] png_0.1-7          class_7.3-17      
 [9] assertthat_0.2.1   packrat_0.5.0     
[11] digest_0.6.25      R6_2.4.1          
[13] backports_1.1.7    stats4_4.0.1      
[15] evaluate_0.14      e1071_1.7-3       
[17] ggplot2_3.3.1      pillar_1.4.4      
[19] rlang_0.4.6        progress_1.2.2    
[21] rstudioapi_0.11    callr_3.4.3       
[23] raster_3.1-5       rmarkdown_2.2     
[25] webshot_0.5.2      stringr_1.4.0     
[27] htmlwidgets_1.5.1  igraph_1.2.5      
[29] munsell_0.5.0      compiler_4.0.1    
[31] xfun_0.14          pkgconfig_2.0.3   
[33] base64enc_0.1-3    htmltools_0.4.0   
[35] tidyselect_1.1.0   tibble_3.0.1      
[37] codetools_0.2-16   audio_0.1-7       
[39] mapview_2.7.8      fansi_0.4.1       
[41] viridisLite_0.3.0  crayon_1.3.4      
[43] dplyr_1.0.0        sf_0.9-3          
[45] grid_4.0.1         jsonlite_1.6.1    
[47] satellite_1.0.2    gtable_0.3.0      
[49] lifecycle_0.2.0    DBI_1.1.0         
[51] magrittr_1.5       storr_1.2.1       
[53] units_0.6-6        scales_1.1.1      
[55] KernSmooth_2.23-17 cli_2.0.2         
[57] stringi_1.4.6      leaflet_2.0.3     
[59] sp_1.4-2           ellipsis_0.3.1    
[61] filelock_1.0.2     generics_0.0.2    
[63] vctrs_0.3.1        tools_4.0.1       
[65] leafem_0.1.1       glue_1.4.1        
[67] purrr_0.3.4        hms_0.5.3         
[69] crosstalk_1.1.0.1  processx_3.4.2    
[71] parallel_4.0.1     yaml_2.2.1        
[73] colorspace_1.4-1   base64url_1.4     
[75] classInt_0.4-3     beepr_1.3         
[77] knitr_1.28   
```

**Comment by robitalec** [comment]
An update, this actually is not a functional workaround - the `...` passes all the declared (within drake) dependencies to the underlying `rmarkdown::render` call. At this point, the only workaround I see is matching a `code_to_function` call to a `rmarkdown::render` wrapper script like you show in the book.

**Comment by robitalec** [comment]
Another update, it appears that changes within the RMarkdown files are not detected when they are rendered with a separate render script, wrapped in `code_to_function`.

**Comment by robitalec** [comment]
If I switch back to the workaround, and replace the `...` with a "depends" argument, which doesn't do anything but collect the dependencies, I can declare dependencies and it detects changes in the RMarkdown file. 

```r
library(drake)

data_prep <- code_to_function('scripts/data-prep.R')
process <- code_to_function('scripts/process.R')
render <- code_to_function('scripts/render.R')
render2 <- code_to_function('scripts/render2.R')

render <- function(filename, depends) {
  rmarkdown::render(
    filename,
    output_format = 'all',
    quiet = TRUE
  )
}

plan <- drake_plan(
  prepared = data_prep(),
  processed = process(prepared),
  report = render(
    knitr_in('md/report.Rmd'),
    processed),
  report2 = render(
    knitr_in('md/report2.Rmd'),
    list(prepared, processed))
)
```

![image](https://user-images.githubusercontent.com/16324625/84958198-6bb98900-b0d7-11ea-929b-25d8d0b6a978.png)

**Comment by wlandau** [comment]
To connect an R Markdown report to its dependencies, there are two things that need to happen.

1. Somewhere in the target's command, write `knitr_in("path/to/your_report.Rmd")`, which you have already done. This tells `drake` to pay attention to the report and search the code for dependencies.
2. In the report itself, write calls to `loadd()` and `readd()` in the active R code chunks, e.g. `loadd(your_upstream_target_1)` and `readd(another_target)`. This is how `drake` detects individual dependencies of the report.

Please try (2) and let me know how it goes.

By the way, `code_to_function()` is nice for pedagogical purposes, but `drake` works better if you move to a more function-oriented approach rather than a traditional script-based approach. More on this at https://books.ropensci.org/drake/plans.html#functions.

**Comment by robitalec** [comment]
Apologies for the missed "trouble" label, that is definitely more suitable. 

This makes sense. So if we want to render RMarkdown documents along with `code_to_function` use the `rmarkdown::render` function directly, with `knitr_in` and `loadd`/`readd`. And using `loadd` works interactively as well in the RMarkdown, as long as the user has run drake to get the cached results. 


`md/report.Rmd`

```rmd
---
title: "Test Drake"
output: html_document
---

(triple backtick, curly braces, r, setup)
knitr::opts_chunk$set(echo = TRUE)
(triple backtick)


(triple backtick, curly braces, r)
drake::loadd(processed)
summary(cars)
(triple backtick)
```

`scripts/plan.R`

```r
library(drake)

data_prep <- code_to_function('scripts/data-prep.R')
process <- code_to_function('scripts/process.R')

plan <- drake_plan(
  prepared = data_prep(),
  processed = process(prepared),
  report =   rmarkdown::render(
    knitr_in('md/report.Rmd'),
    output_format = 'all',
    quiet = TRUE
  )
)
```

In the future, I'll setup projects in the drake-functional approach. Normally, I have been writing ordered scripts, wrapping functions used throughout into a package, and using a Makefile to build the package, Rscript scripts and `rmarkdown::render` manuscripts. So this time I'm trying to swap in drake's `code_to_function` since the project is nearly completed. Thanks @wlandau.
