### ISSUE TITLE
Could .id_chr 's definition be extended to all targets, not just transformations?

### ISSUE THREAD

**Issue by mstr3336** [ropensci/drake#1288]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

Hi there - 

From my experience, the symbol `.id_chr` seems to be defined in the scope of targets with a static transformation (Not sure about dynamic), but not for simple non-transformed targets. 

I understand the motivation for defining `.id_chr` in that scope, as it solves the problem of allowing us to access the current target name in a situation where the exact name of the current target is not explicit.

This is not exactly a problem in the non-transformed case, as the target name is explictly given as the argument to `drake::drake_plan`, and it is trivial to determine. 

That being said, I do thing for uniformity it would be really handly for `.id_chr` to also be defined in the single-target scope. The small gotcha of using `.id_chr` in a transformation command (its intended purpose) and it working fine, and then trying to use it in a direct target command and it not working surprised me.

There are use-cases for `.id_chr` outside of the context of transformations, mainly just avoiding DRY between referencing target name, and then referring to oneself in the target's command.

Thank you for your consideration!

**Comment by wlandau** [comment]
As you point out, `.id_chr` is for static branching only because it helps to drive the symbol substitution mechanism in transforms. But `drake` does have an `id_chr()` function that gets evaluated at runtime and does not need transforms. I think it does what you want. Please correct me if I am wrong.
