### ISSUE TITLE
changes in function code not detected when make() called in iteration

### ISSUE THREAD

**Issue by MilesMcBain** [ropensci/drake#1292]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [x] I am reasonably sure this is a genuine bug in `drake` and most likely not a user error. (If you run into an error and do not know the cause, please submit a "Trouble" issue instead.)
- [ ] Advanced users: verify that the bug still persists in the current development version (i.e. `remotes::install_github("ropensci/drake")`) and mention the [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity) of the [Git commit you install](https://github.com/ropensci/drake/commits/master).

## Description

When `make()` is called in an iteration, even if that iteration only executes once, changes to target functions are not detected, and the plan is not rebuilt.

Confusingly `drake::outdated()` will list these targets as outdated which can lead to output like this:

```
outdated() targets: result1 result2 
v All targets are already up to date.
```

In my reprex I've used `lapply` but I have also observed the behaviour with `for` and `purrr::walk`, so it seems not to matter. The choice of inline function vs named function object also makes no difference.

## Reproducible example

It's quite a specific setup that seems to rely on target expressions being defined in separate files so I have created a repository for the example that you can clone:

[https://github.com/MilesMcBain/drake_reprex](https://github.com/MilesMcBain/drake_reprex)

The instructions for reproducing are:

1. Run the plan in a terminal with:

```
$ Rscript drake.r
```

2. change the computation in the `calc_result2` function, e.g. `result1 * 3`

3. Run the plan in the terminal again. And observe this output:

```
outdated() targets: result1 result2 
v All targets are already up to date.
```

These are also in the repo readme.

## Expected result

Unless I am mistaken in my understanding of either `drake` or R's scoping rules, I expect a change in the definition of `calc_result2` to result in the `result2` target being rebuilt.

## Session info
 
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] drake_7.12.2     dotenv_1.0.2     conflicted_1.0.4

loaded via a namespace (and not attached):
 [1] txtq_0.2.3        prettyunits_1.1.1 fansi_0.4.1       crayon_1.3.4     
 [5] assertthat_0.2.1  digest_0.6.25     R6_2.4.1          lifecycle_0.2.0  
 [9] backports_1.1.7   storr_1.2.1       magrittr_1.5      pillar_1.4.4     
[13] progress_1.2.2    cli_2.0.2         rlang_0.4.6       ellipsis_0.3.1   
[17] filelock_1.0.2    vctrs_0.3.1       tools_3.6.3       glue_1.4.1       
[21] igraph_1.2.4.2    hms_0.5.3         parallel_3.6.3    compiler_3.6.3   
[25] pkgconfig_2.0.3   base64url_1.4     memoise_1.1.0     tibble_3.0.1     

```

**Comment by wlandau** [comment]
This is definitely  an environment scoping edge case. In fact, if you call `vis_drake_graph(the_plan)` from inside the `lapply()` lambda function, you will see that `drake` is not even detecting the function `calc_result2()`.

![Screenshot_20200630_225533](https://user-images.githubusercontent.com/1580860/86198095-d7aedf00-bb24-11ea-9d90-cdb51b24c2ad.png)

`drake` looks for functions and other global objects in the `envir` argument of `make()`. By default, `envir` is the parent frame of the `make()` call. This works in most situations, but we run into trouble if we `source()` our functions in the global environment and then call `make()` inside a child environment. Here, I would recommend you set the `envir` argument manually. The following `drake.R` works for me.

```r
source("./packages.R")
invisible(lapply(list.files("./R", full.names = TRUE), source))
vars <- 1
cat(paste("outdated() targets:", paste(outdated(the_plan), collapse = " "), "\n"))
envir <- environment()
invisible(lapply(vars, function(plan_var) {
  envir$plan_var <- plan_var # plan_var needs to be in drake's environment too.
  make(the_plan, envir = envir, lock_envir = FALSE)
}))
```

As expected, changes to `calc_result2()` trigger updates to `result2` and not `result1`.

Once again, I am super thankful you pushed me to implement `r_make()` all those months ago. For most use cases, it implements the guardrails we need to avoid these environment gotchas. The behavior of `make()` itself with respect to environments is unfortunately too deeply rooted in the package to change at this point.
