### ISSUE TITLE
expose the format argument for progress bars

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#1296]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal
The format argument here:
https://github.com/ropensci/drake/blob/e3ef6c9e8a3f28d14d1d76f0811b25eae682a0bf/R/logger.R#L6
has a lot of options in the `progress` package. Could these be exposed to the user via `make`?

**Comment by wlandau** [comment]
What sorts of formats do you plan to use?

**Comment by wlandau** [comment]
It's hard for me to see the value added for this feature. I guess `eta` might be nice, but it seems misleading when it comes to targets because they all take different amounts of time to complete, and I'm not sure I want users to get the wrong idea.
