### ISSUE TITLE
knitr options fig.process and loadd

### ISSUE THREAD

**Issue by charlesbaillie** [ropensci/drake#1297]
## Question

I'm writing a Sweave report, using knitr to weave the files. Normally, I use something like the following to determine how figures are processed:
```
knitr::opts_chunk$set(
  echo=F,
  message=F,
  warning=F,
  fig.path = "../figs/",
  cache = FALSE,
  fig.process = function(x) {
                      x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
                      if (file.rename(x, x2)) x2 else x
                      }
  )
```
This will write a figure produced within a named code chunk to `../figs` using the name of the code chunk for the filename of the figure (and adding the extension).

I thought that if I made a figure in the drake plan (`figure  = myFigFunction(x)`) and then in the named code chunk of my  report did:
```
loadd(figure)
figure
``` 
then the figure would be written out in the same way?  Is this not the case? 

## Session info

R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.0    zoo_1.8-8        readr_1.3.1      tidyr_1.0.3      stringr_1.4.0    scales_1.1.1     openxlsx_4.1.5   magrittr_1.5    
 [9] lubridate_1.7.8  knitr_1.28       janitor_2.0.1    here_0.1         gt_0.2.1         patchwork_1.0.0  govstyle_0.1.3   ggplot2_3.3.0   
[17] drake_7.12.1     dotenv_1.0.2     dplyr_1.0.0      conflicted_1.0.4

loaded via a namespace (and not attached):
 [1] storr_1.2.1           progress_1.2.2        tidyselect_1.1.0      xfun_0.14             purrr_0.3.4           lattice_0.20-41      
 [7] snakecase_0.11.0      colorspace_1.4-1      vctrs_0.3.1           generics_0.0.2        utf8_1.1.4            rlang_0.4.6          
[13] pillar_1.4.4          txtq_0.2.0            glue_1.4.1            withr_2.2.0           readxl_1.3.1          lifecycle_0.2.0      
[19] cellranger_1.1.0.9000 munsell_0.5.0         gtable_0.3.0          zip_2.0.4             evaluate_0.14         memoise_1.1.0        
[25] callr_3.4.3           ps_1.3.3              parallel_4.0.0        fansi_0.4.1           highr_0.8             Rcpp_1.0.4.6         
[31] backports_1.1.7       filelock_1.0.2        hms_0.5.3             packrat_0.5.0         digest_0.6.25         stringi_1.4.6        
[37] processx_3.4.2        grid_4.0.0            rprojroot_1.3-2       cli_2.0.2             tools_4.0.0           base64url_1.4        
[43] tibble_3.0.1          crayon_1.3.4          pkgconfig_2.0.3       ellipsis_0.3.1        data.table_1.12.8     prettyunits_1.1.1    
[49] assertthat_0.2.1      rstudioapi_0.11       R6_2.4.1              igraph_1.2.5          compiler_4.0.0

**Comment by wlandau** [comment]
Seems like it should work. Would you post a [minimal reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)? It's hard for me to speculate about what might be going wrong because the example I made works. `report.Rmd` file:


    ---
    title: "report"
    output: html_document
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(
      fig.path = "figs/",
      fig.process = function(x) {
        x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
        if (file.rename(x, x2)) x2 else x
      }
    )
    ```
    
    ```{r}
    library(drake)
    library(ggplot2)
    loadd(figure)
    figure
    ```

Code: 

```r
library(drake)
library(ggplot2)
library(rmarkdown)
plan <- drake_plan(
  figure = ggplot(mtcars) + geom_point(aes(x = wt, y = mpg)),
  report = render(knitr_in("report.Rmd"), output_file = file_out("report.html"))
)
make(plan)
```

When I run the code above, a `fig/` folder is created with the file `unnamed-chunk-1.png` with the plot.

**Comment by wlandau** [comment]
It is possible the issue has something to do with your working directory when you run `make()`. `drake` assumes you always run `make()` from the root directory of the project and that you never change working directories (e.g. with `setwd()`). The path `../fig` is in the parent directory, not at the root of the project itself, so I changed it to `fig/` for the example. This, i think, is better practice anyway. Please let me know if that does not fix the problem.

**Comment by charlesbaillie** [comment]
Thanks for getting back Will. You could be right about paths - could you advise if this works.
I have the project set up like this:
```
root
|--data
|--figs
|--R
|--doc
|     |__main.Rnw
|     |__chap1
|     |      |__chap1.Rnw
:     :      :
```
The plan looks like:
```
the_plan <-
  drake_plan(

data = read_csv("data/data.csv"),
myPlot = myPlot("data"),
report = knit(input="doc/main.Rnw")
)
```
Within main.Rnw I also use a code chunk to knit the individual chapter and `\include` them:

```
\documentclass{report}
\begin{document}

<<>>=
knitr::opts_chunk$set(
  fig.path = "figs/",
  fig.process = function(x) {
    x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
    if (file.rename(x, x2)) x2 else x
  }
)
@ 

<<knitting, include=FALSE>>=
sections <- c("chap1/chap1")
knitAll(files=sections)
@

\include{chap1/chap1}

\end{document}
```
Within chap1.Rnw I have:
```
\chapter{chap1}

<<myPlot, include=FALSE>>=
loadd(myPlot)
myPlot
@

\begin{figure}[htbp]
  \centering
  \includegraphics[width=1\textwidth]{../figs/myPlot} \hfill
  \caption{Blah.}
  \label{fig:myPlot}
\end{figure}
```

Although chap1 is a level down from doc, its main.Rns that is being called hence ../figs and not ../../figs. This all works fine in my normal latex setup. The code chunk in chap1 outputs the figure to figs, then I import that figure with the latex figure environment. It only doesn't work when this is all wrapped up in a drake pipeline.

Hope that makes sense!

**Comment by wlandau** [comment]
I tried to reproduce what you are seeing with the attached files.

[reprex.zip](https://github.com/ropensci/drake/files/4918071/reprex.zip)

Whether I knit with `make(plan)`, `knit(knitr_in("doc/main.Rnw"))` in the R console, or the "compile pdf" button in RStudio, the `figs/` folder always appears in `doc/`.

Nested LaTeX files like this are not easy to manage. I recommend the `bookdown` package for projects like this one. Also, if the physical plot files are really what you are after, you can use [dynamic files](https://books.ropensci.org/drake/plans.html#dynamic-files) in `drake`.

```r
my_plot_file <- function() {
  plot <- ggplot(mtcars) + geom_point(aes(x = wt, y = mpg))
  fs::dir_create("figs")
  ggsave("figs/plot.png", plot)
  "figs/plot.png"
}

plan <- drake_plan(
  myPlot = target(my_plot_file(), format = "file"),
  report = knit(knitr_in("doc/main.Rnw"))
)
```

Then in the report, you can continue to `loadd(myPlot)`, but `\includegraphics` can just use the physical figure you wrote and reproducibly tracked in the `myPlot` target.

If you have follow-up questions, please send a complete file system that I can run end-to-end as is. This could be an attached zip archive or a GitHub repo.
