### ISSUE TITLE
Unable to pass NULL as target value

### ISSUE THREAD

**Issue by odaniel1** [ropensci/drake#1299]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [] I am reasonably sure this is a genuine bug in `drake` and most likely not a user error. (If you run into an error and do not know the cause, please submit a "Trouble" issue instead.)
- [x] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

## Description

Passing NULL directly to drake as a target value returns a `safe_deparse` error.

## Reproducible example
```
library(drake)
plan <- drake_plan(a = NULL)
make(plan)
#> Error in safe_deparse(x, backtick = TRUE): argument "x" is missing, with no default
````
## Expected result

`drake` can handle NULL when returned as a value from a function; I had anticipated the same behaviour as the below:

```
library(drake)
f <- function(){return(NULL)}
plan <- drake_plan(a = f())
make(plan)
#> ▶ target a
```

## Session info
```
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.3 (2020-02-29)
#>  os       Ubuntu 18.04.4 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language en_GB:en                    
#>  collate  en_GB.UTF-8                 
#>  ctype    en_GB.UTF-8              
#>  date     2020-07-22 
```

**Comment by odaniel1** [comment]
I tried to re-tag as trouble but can't edit the label myself (I don't think!). Likely should be tagged as that instead - sorry!

**Comment by wlandau** [comment]
Thanks, should be fixed now.
