### ISSUE TITLE
I've written a package that extends drake_graphs by embedding a sidebar with per-target documentation, and target column docs

### ISSUE THREAD

**Issue by mstr3336** [ropensci/drake#1301]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

Hi there, I've written a package for inlining docs into the `drake::vis_drake_graph`. I've called it `{mandrake}`. 

A little while ago I contributed to `{drake}` by enablign onSelect behaviour for `vis_drake_graph` nodes.
This is a refinement/extension of that feature, whereby when users click a node, metadata about the node appears in-place of the legend, and they can see an overview of the node, including:
* a description (specified inline as an extra column in the `drake::target` defintion)
* The `command` for that target, highlighted and linked to documentation by [r-lib/downlit](https://github.com/r-lib/downlit)
* An overview of any names belonging to that target, as well as per-column documentation, which is specified using roxygen (and a lookup storr).

I've developed this to assist my own teams' workflow, and there are a few features (mostly on the roxygen column docstring side of things) that are still needed to be completed.

In saying that, I believe this is broadly useful to any `drake` user with a complex plan, or a need to communicate their workflow to other parties.

The following is a demonstration of the tool, using an adapted version of `{drake}`s mtcars example workflow:

https://mstr3336.github.io/mandrake/articles/Test_Usecase.html#graph

![image](https://user-images.githubusercontent.com/39424834/88406564-33af0f80-ce14-11ea-8457-7b6a5e76896c.png)

**Comment by mstr3336** [comment]
I don't really know what this issue is asking - I guess if you think it's worth mentioning in the manual, or if you have thoughts/suggestions @wlandau

**Comment by wlandau** [comment]
Wow, those graph annotations are so impressive! More than worth mentioning in `drake`'s documentation!

**Comment by wlandau** [comment]
Just added the mentions cross-referenced in these docs. Super exciting!
