### ISSUE TITLE
Feature request: If memory allocation fails, try to autoclean and retry

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#1304]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

(As a preface, I did search for duplicates, but I'm not certain that my search hit the right elements.  This is somewhat related to #930, but I'm pretty sure that it is distinct from that and other items that I see.)

I'm running a plan that without garbage collection runs right at the edge of available memory on the system.  With extensive garbage collection (`memory_strategy = "autoclean"`), it works, but it takes notably longer due to loading and unloading data repeatedly.

I wonder if there is a way to detect memory allocation errors ((mine is "Error: cannot allocate vector of size 9.7 Gb") and if that happens, retry the target after `"autoclean"`, and if it still fails, stop.  In case that's not clear, the request is:

* If everything is running normally, just run.
* If a memory allocation error occurs (I'm not sure how to detect that, especially since it could occur either when drake loads data or when a target allocates more space), give a warning to the user, try to autoclean and rerun the same target.
* If the target succeeds after the autoclean, continue to run normally (with the same possible autoclean behavior if another target fails for memory allocation issues).
* If the target fails after the autoclean, stop.

Overall, this would be a new `memory_strategy` to something that would be a hybrid between the default, `"speed"`, and `"autoclean"` (`"speed_clean"`?).  I don't know if this would make sense to be a new `memory_strategy` or if it would replace `"speed"`.  I do think that this new strategy would make sense as the new default (at least for me 😃).

P.S.  Since there are zero open issues now, it almost pains me to open this one.  😃

**Comment by wlandau** [comment]
I understand where you are coming from, but I do not think we should try to automate this in `drake`. As you mentioned, it is hard to detect when a memory error happens. We would pretty much have to grep the error message, which is brittle. Also, consuming memory right up until an error may not be the right decision either, and utilities like `pryr::mem_used()` are more for exploratory purposes. Reliable information about memory usage needs to be monitored outside the R process, which is system dependent and would force `drake` to work outside R, which it was not designed to do. Ultimately, the memory strategy and garbage collection choice should be made by a human based on the capabilities and etiquette of the available system.

**Comment by billdenney** [comment]
Fair enough.  Thanks for the consideration.
