### ISSUE TITLE
Feature request: Parameterized plans

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#1306]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

This is somewhat similar to #904, but in a few ways distinct.

I often use drake in a way that some parts of the plan need to be repeated.  One rational approach would be to convert what I'm doing into a function, but farther down, I usually need to use the intermediate steps in different ways (for example, I need two different types of summaries of the same simulation results).

My specific use case today is that I am running clinical trial simulations with many scenarios, and some of the scenarios are dramatically different.  And, as the team is brainstorming new scenarios, some of them look very different, but they will want them all compared to each other in the end.

I hope that this could look somewhat similar to normal plans, but with inputs defined as part of the plan, and that the plan could be expanded at runtime.  And, the plan would be expanded like a function call within the plan that is sent to `make()`.

An interface that I think could make sense is below:

```r
my_param_plan <-
  drake_plan_parameterized(
    p1=drake_parameter()
    v1=p1 + 1,
    v2=p1 + 2
  )

my_plan <-
  drake_plan(
    a1=my_param_plan(p1=1),
    a2=my_param_plan(p1=2)
  )
```

(In my real example, `v1` takes about an hour to compute, and it has downstream dependencies within the main plan.)

The hardest part of the API that I see is, how do I access the results within a1 and a2?  I could imagine accessing them as a list (`a1$v1`), but I know from prior discussions that is not likely to work well.  I could also imagine a simple prepending of the outer target name to the inner target (`a1_v1`).

My hope is that with dynamic branching, something like this could be made feasible without a lot more drake code.  I also realize that I could make my own targets manually, but it would require a lot of inspection of code to alter target names, so that seems like a bigger ask for a user than it may be within drake.

**Comment by billdenney** [comment]
As I thought about this more, it isn't dynamic at all.  It is preprocessing on a plan because everything about the targets is known up front.

**Comment by wlandau** [comment]
I think [static branching](https://books.ropensci.org/drake/static.html) and tidy evaluation can meet use cases like these. If I am missing something, would you please post a plan that elaborates on the problem you are facing?

``` r
library(drake)
scenario_functions <- rlang::syms(c("s1", "s2", "s3"))
plan <- drake_plan(
  sim = target(
    scenario(),
    transform = map(scenario = !!scenario_functions)
  ),
  oc = target(
    operating_characteristics(sim),
    transform = map(sim)
  ),
  summary = target(
    bind_rows(oc),
    transform = combine(oc)
  )
)

drake_plan_source(plan)
#> drake_plan(
#>   oc_sim_s1 = operating_characteristics(sim_s1),
#>   oc_sim_s2 = operating_characteristics(sim_s2),
#>   oc_sim_s3 = operating_characteristics(sim_s3),
#>   sim_s1 = s1(),
#>   sim_s2 = s2(),
#>   sim_s3 = s3(),
#>   summary = bind_rows(oc_sim_s1, oc_sim_s2, oc_sim_s3)
#> )

plot(plan)
```

![](https://i.imgur.com/Ay8KQiv.png)

<sup>Created on 2020-08-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

For what it's worth, [metaprogramming in `targets`](https://wlandau.github.io/targets-manual/branching.html#metaprogramming) is easier than static branching in `drake`, and you may even be able to come up with your own [target archetypes](https://wlandau.github.io/tarchetypes/) for clinical trial simulation.

**Comment by wlandau** [comment]
Tidy evaluation without static branching can also parameterize plans.

``` r
library(drake)
scenario <- rlang::sym("s2")
drake_plan(
  sim = (!!scenario)(),
  oc = operating_characteristics(sim)
)
#> # A tibble: 2 x 2
#>   target command                       
#>   <chr>  <expr_lst>                    
#> 1 sim    s2()                          
#> 2 oc     operating_characteristics(sim)
```

<sup>Created on 2020-08-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
More broadly, for these types of discussions, I prefer to dive deeply into the motivating problems before even thinking about new features. If we pursue workarounds before any new feature ideas are on the table, more people will understand the underlying issues, and `drake` will have a better chance of staying maintainable and internally consistent.

**Comment by billdenney** [comment]
Both are interesting methods to make it work.  (I don't think I would have thought of tidy evaluation without branching as a solution.  Thanks for that!)

For diving into the motivating problem to work toward potential new features, is this the correct forum or is there another that is preferred?  (I had thought this was it, but I'm also happy to use another-- I really appreciate `drake`, as you can likely tell, and I would like to make my questions and requests as simple/preferred as possible for you.)

**Comment by wlandau** [comment]
This is still a good place to discuss, and as always, thanks for your input. I was just trying to say that you understand your own sticking points better than I, so that's where I would prefer you to go into detail. That way, I can leverage my familiarity with `drake`'s design and goals as we explore workarounds and feature ideas together.

**Comment by billdenney** [comment]
Great, thanks for confirming.
