### ISSUE TITLE
warning from integer_hash -> type.convert 

### ISSUE THREAD

**Issue by bbolker** [ropensci/drake#1309]
As of [this commit](https://github.com/wch/r-source/commit/6ed0a69735c17c44443f8520aaa32113fc8b4373), `type.convert` warns when `as.is` is not specified.  `integer_hash` calls `type.convert` without specifying `as.is` [here](https://github.com/ropensci/drake/blob/7bb9b5163c0fd624183c4e7b1115057c235e82ff/R/drake_meta_.R#L349) ...

I can submit a PR if desired.

**Comment by wlandau-lilly** [comment]
Thanks, @bbolker. Should be fixed in b5ec59138966c785d8efdca0cc5bcb85ac942f83.
