### ISSUE TITLE
Broken link to "Cautionary notes and edge cases" in README

### ISSUE THREAD

**Issue by danliIDEA** [ropensci/drake#1315]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

The [link](https://books.ropensci.org/drake/caution.html) to Cautionary notes and edge cases returns a 404 error.

**Comment by wlandau** [comment]
Thanks for letting me know. That page of the manual no longer exists, so I removed the link.
