### ISSUE TITLE
Documentation Request: How to diagnose errors with dynamic targets

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#1317]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [x] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

## Description

This is hopefully a very simple addition to the documentation.

I just had an issue with a dynamic target failing.  I didn't know how to track down which (of the ~20) dynamic targets was the problem.  When I looked at the output of `diagnose()` I didn't notice the `subtarget_index` which pointed me right to the issue.  It would help if in the section on dynamic targets in the manual, a section were added called something like "How to diagnose errors with dynamic targets", and give an example like the one in the reprex below indicating that calling the function with `stop_at_3(readd(vals)[[3]])` will find the same error, and `3` comes from the `subtarget_index` provided by `diagnose()`.

I don't know if it would get more complex for `cross()` and `group()` dynamic targets, but it would help if those were also included.

## Reproducible example

``` r
library(drake)

stop_at_3 <- function(x) {
  if (x == 3) stop("It's 3")
  x
}

make(drake_plan(
  vals=1:5,
  results=
    target(
      stop_at_3(vals),
      dynamic=map(vals)
    )
))
#> > target vals
#> > dynamic results
#> > subtarget results_0b3474bd
#> > subtarget results_b2a5c9b8
#> > subtarget results_71f311ad
#> x fail results_71f311ad
#> Error: target results_71f311ad failed.
#> diagnose(results_71f311ad)$error$message:
#>   It's 3
#> diagnose(results_71f311ad)$error$calls:
#>   global::stop_at_3(vals)
#>   base::stop("It's 3")
diagnose(results_71f311ad)
#> $error
#> <simpleError in "stop_at_3(vals)": It's 3>
#> 
#> $seed
#> [1] 125908859
#> 
#> $subtarget
#> [1] "results_71f311ad"
#> 
#> $subtarget_index
#> [1] 3
```

<sup>Created on 2020-09-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
Sure, this is something people have asked for. In the interest of preserving the coherent flow of the dynamic branching chapter, I added https://github.com/ropensci-books/drake/commit/5f1dd469ef43bab6f9b1c50767825b61624d93a7 using the existing example.

**Comment by billdenney** [comment]
Thanks!

**Comment by wlandau-lilly** [comment]
By the way, because of its simplified infrastructure, debugging is [`targets`](https://github.com/wlandau/targets) is already much easier: <https://wlandau.github.io/targets-manual/practice.html#debugging>.

**Comment by wlandau** [comment]
By the way, because of its simplified infrastructure, debugging is [`targets`](https://github.com/wlandau/targets) is already much easier: <https://wlandau.github.io/targets-manual/practice.html#debugging>.

**Comment by billdenney** [comment]
Ah, I didn't know about ‘targets‘.  Thanks for letting me know of it.
