### ISSUE TITLE
Unusual call within function causes "not a symbol" error

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#1318]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [x] I am reasonably sure this is a genuine bug in `drake` and most likely not a user error. (If you run into an error and do not know the cause, please submit a "Trouble" issue instead.)
- [x] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

## Description

When using an unusual function (to work with the `nlmixr` library which has some other interaction issues with `drake`), I need to make a function that defines a set of differential equations.  The function definition is not a normal function; it is interpreted very specifically by `nlmixr`.  With that, it has unusual function syntax as shown below.

A second and perhaps more serious issue is that the `drake` cache appears to hold the error state in it even when the function in error is not called (see the second example below where `my_model` is not referenced).

## Reproducible example

``` r
library(drake)

my_model <- function() {
  A(0) = 1
}

dummy_fun <- function(x) 1

make(
  drake_plan(
    x=dummy_fun(my_model)
  )
)
#> Error: not a symbol: 'A(0) = 1'
make(
  drake_plan(
    y=1
  )
)
#> Error: not a symbol: 'A(0) = 1'
```

<sup>Created on 2020-09-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/New_York            
#>  date     2020-09-08                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
#>  backports     1.1.9   2020-08-24 [1] CRAN (R 4.0.2)
#>  base64url     1.4     2018-05-14 [1] CRAN (R 4.0.0)
#>  callr         3.4.3   2020-03-28 [1] CRAN (R 4.0.0)
#>  cli           2.0.2   2020-02-28 [1] CRAN (R 4.0.0)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.0)
#>  devtools      2.3.1   2020-07-21 [1] CRAN (R 4.0.2)
#>  digest        0.6.25  2020-02-23 [1] CRAN (R 4.0.0)
#>  drake       * 7.12.5  2020-08-26 [1] CRAN (R 4.0.2)
#>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.0)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.0)
#>  fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
#>  filelock      1.0.2   2018-10-05 [1] CRAN (R 4.0.0)
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
#>  highr         0.8     2019-03-20 [1] CRAN (R 4.0.0)
#>  hms           0.5.3   2020-01-08 [1] CRAN (R 4.0.0)
#>  htmltools     0.5.0   2020-06-16 [1] CRAN (R 4.0.2)
#>  igraph        1.2.5   2020-03-19 [1] CRAN (R 4.0.0)
#>  knitr         1.29    2020-06-23 [1] CRAN (R 4.0.2)
#>  lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.0)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.0)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
#>  pillar        1.4.6   2020-07-10 [1] CRAN (R 4.0.2)
#>  pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 4.0.2)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
#>  pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.0)
#>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
#>  processx      3.4.4   2020-09-03 [1] CRAN (R 4.0.2)
#>  progress      1.2.2   2019-05-16 [1] CRAN (R 4.0.0)
#>  ps            1.3.4   2020-08-11 [1] CRAN (R 4.0.2)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.0)
#>  R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.0)
#>  remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.2)
#>  rlang         0.4.7   2020-07-09 [1] CRAN (R 4.0.2)
#>  rmarkdown     2.3     2020-06-18 [1] CRAN (R 4.0.2)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
#>  storr         1.2.1   2018-10-18 [1] CRAN (R 4.0.0)
#>  stringi       1.4.6   2020-02-17 [1] CRAN (R 4.0.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
#>  testthat      2.3.2   2020-03-02 [1] CRAN (R 4.0.0)
#>  tibble        3.0.3   2020-07-10 [1] CRAN (R 4.0.2)
#>  tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.0)
#>  txtq          0.2.3   2020-06-23 [1] CRAN (R 4.0.2)
#>  usethis       1.6.1   2020-04-29 [1] CRAN (R 4.0.0)
#>  vctrs         0.3.4   2020-08-29 [1] CRAN (R 4.0.2)
#>  withr         2.2.0   2020-04-20 [1] CRAN (R 4.0.0)
#>  xfun          0.16    2020-07-24 [1] CRAN (R 4.0.2)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
#> 
#> [1] C:/Users/Bill Denney/Documents/R/win-library/4.0
#> [2] C:/Program Files/R/R-4.0.2/library
```

</details>

## Expected result

For the first call to `make()`, the value of `x` in the plan is 1.

For the second call to `make()`, no error occurs, since the code generating the error is not referenced while making the value of `y`.

## Session info

See reprex output.

**Comment by wlandau** [comment]
The first error happens during `drake`'s static code analysis. The line `A(0) = 1` is not valid R code because it implies that `A<-` is a [replacement function](https://cran.r-project.org/doc/manuals/R-lang.html#Subset-assignment) that tries to modify an illegal variable called `0`. So I would wrap all that in `ignore()`, e.g.

```{r}
my_model <- function() {
  ignore({
    A(0) = 1
  })
}
```

or 

```{r}
plan <- drake_plan(x = dummy_fun(ignore(my_model)))
```

**Comment by wlandau** [comment]
The second error happens because `my_model` is still in the calling environment, so `drake` tries to statically analyze it. You can remove that error by removing `my_model` from the environment.

``` r
library(drake)

my_model <- function() {
  A(0) = 1
}

dummy_fun <- function(x) 1

plan <- drake_plan(x = dummy_fun(my_model))

make(plan)
#> Error: not a symbol: 'A(0) = 1'

library(drake)

plan <- drake_plan(y = 1)

rm(my_model)

make(plan)
#> ▶ target y
```

<sup>Created on 2020-09-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
I think both problems are very `nlmixr`-specific. `drake` automatically treats the bodies of functions as valid R code, and I think this is still a valid assumption. So I recommend `ignore()` to enclose non-R DSLs.

**Comment by billdenney** [comment]
Thanks for the explanation.  I'll see if I can get a variation into the DSL so that either `A[0]` or `A(initial)` or similar that will look like valid R could be used instead of `A(0)`.

**Comment by billdenney** [comment]
Sorry, this was a duplicate of #910.
