### ISSUE TITLE
Drake runtime environment variables

### ISSUE THREAD

**Issue by yonicd** [ropensci/drake#1328]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/ropensci/drake/blob/master/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/drake/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] For any problems you identify, a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

What would you like to know?

Is there a runtime environment variable that can be checked for when drake runs to skip certain chunks in an Rmd document. In the same spirit of ` {r my chunk, eval = knitr::opts_knit$get("child")}`?

## Reproducible example

* [ ] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

**Comment by wlandau** [comment]
`drake` does not set an environment variable to indicate `make()` or `r_make()` is running. Is that what you were asking? I'm not sure I understand the use case.

**Comment by yonicd** [comment]
i have this type of rmd

````
---
title: "Analysis"
author: "Jonathan Sidi"
date: "`r Sys.Date()`"
output: 
  bookdown::html_document2: default
  bookdown::word_document2:
    fig_width: 6
    fig_height: 6
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE, 
  fig.path = '../../deliv/figures/',
  fig.topcaption=TRUE
  )
```

```{r sinew libraries}
library(officedown)
library(magrittr)
library(ggplot2)
library(patchwork)
library(drake)
```

```{r}
source(here::here('script/utils.R'))
```

...

````

the _drake.R file has it in it too

```r
library(magrittr)
library(drake)

source(here::here('script/utils.R'))

source(here::here('script/plan.R'))

drake_config(plan, verbose = 2)
```

I want to be able to run this file both standalone and through drake.

If I run this rmd standalone it runs ok and outputs the html in the directory where the file is saved. But if I try to run it in a drake plan it breaks because of the file is sourced twice.

if i comment eval=FALSE then the Rmd isn't standalone anymore.

If I there was a way to know if drake is in runtime then I could add a flag in the rmd chunk.

Does this description make sense?

**Comment by wlandau** [comment]
Seems like the sort of thing that should work. Which file is sourced twice? What kinds of things are in the rest of the Rmd? Does the Rmd call r_make()? Because then that would definitely cause problems. A report can wrap around drake or run within drake, but not both.

**Comment by yonicd** [comment]
the `script/utils.R` which is a file with helper functions that are placed in the runtime envir. I wanted to source it in `_drake.R` because I use the functions in multiple targets

when `lock_envir=TRUE` I get this error

```r
Quitting from lines 34-35 (periods.Rmd) 
Error : target period_report failed.
diagnose(period_report)$error$message:
  cannot change value of locked binding for 'map_sas_drive'. 
Please read the "Self-invalidation" section of the make() help file.
diagnose(period_report)$error$calls:
  base::source(here::here("script/utils.R"))
  base::withVisible(eval(ei, envir))
  base::eval(ei, envir)
  base::eval(ei, envir)
Error: callr subprocess failed: target period_report failed.
diagnose(period_report)$error$message:
  cannot change value of locked binding for 'map_sas_drive'. 
Please read the "Self-invalidation" section of the make() help file.
diagnose(period_report)$error$calls:
  base::source(here::here("script/utils.R"))
  base::withVisible(eval(ei, envir))
  base::eval(ei, envir)
  base::eval(ei, envir)
Type .Last.error.trace to see where the error occured
```

**Comment by wlandau** [comment]
Ah, I see what you mean now. I recommend two alternatives. Either:

1. Just disable environment locking, or
2. Move that part of the computation out of the report and into new targets in the plan. drake’s opinion (and my own) is that R Markdown should do as little work as possible: just load targets and annotate them with descriptive prose.
