### ISSUE TITLE
How the use the name of a dynamic subtarget?

### ISSUE THREAD

**Issue by Plebejer** [ropensci/drake#1336]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/ropensci/drake/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/ropensci/drake/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/drake/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] For any problems you identify, a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

I use dynamic targets in my plan. One of those targets writes files to disk. So I get one file per subtarget. Now I need to make sure that these files have distinguishible names. It would be nice if I could somehow get the cryptic name of the subtarget, since this would make it easy to bring the subtargets and the files written to disk together.

I played around with timestampts but this is not safe as it sometimes happens that two subtargets try to create a file at the same moment.

I suppose, this information is "somewhere". Is it also accessible within a dynamic target?

## Reproducible example

Does not apply here.

**Comment by wlandau** [comment]
[`id_chr()`](https://docs.ropensci.org/drake/reference/id_chr.html) allows you to get the name of the sub-target while `make()` or `r_make()` is running. That should allow you to name files in a way that matches your targets. Another alternative is to generate a universally unique identifier (UUID) with the `uuid` package or `tempfile()`.
