### ISSUE TITLE
Citation recommendations in readmes and/or webpages

### ISSUE THREAD

**Issue by trashbirdecology** [ropensci/drake#1343]
__Recommendation__
Add the recommended __citation__ to README and/or the package webpage. Also as an FYI, drake readme also doesn't include the instructions for retrieving citation using `citation()`.

__Background__
A colleague (who doesn't really use R) recently approached me asking about how they can easily find the citation for a few R packages, including `drake`. They said the only instructions  they found were "run `citation()`". 

@cboettig et al., I recommend that all rOpenSci packages have recommended citations on their readme/webpages, for our colleagues who do not use or are not familiar enough with R to run `citation()`. A nice example of doing so is over at [`osmdata`](https://github.com/ropensci/osmdata)

**Comment by wlandau** [comment]
A citation is now near the bottom of the README and should appear soon at https://docs.ropensci.org/drake. Thanks.
