### ISSUE TITLE
pkgdown site not updating

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#1344]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/ropensci/drake/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/ropensci/drake/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/drake/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

https://docs.ropensci.org/drake/ appears to have not updated since `drake` version 7.12.6. Development `drake` is on version 7.12.7.9000.

![Screen Shot 2020-11-11 at 7 51 35 AM](https://user-images.githubusercontent.com/1580860/98813829-d5be2c00-23f2-11eb-8fd4-267d0416a23c.png)

cc @jeroen

**Comment by jeroen** [comment]
Thanks, should be fixed now. The problem was that our jenkins job was still tracking your `master` branch to build the docs, but that branch no longer exists. Changed it to `main` now.

**Comment by jeroen** [comment]
Deploying now --> https://dev.ropensci.org/job/drake/83/console

**Comment by wlandau** [comment]
Awesome, thanks @jeroen! Looks up to date now.
