### ISSUE TITLE
Performance of format = "file" vs. file_in()

### ISSUE THREAD

**Issue by matthiasgomolka** [ropensci/drake#1349]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/ropensci/drake/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/ropensci/drake/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/drake/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] For any problems you identify, a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question
I'm monitoring several hundreds of GB of files in a drake plan using dynamic branching. Thus, these files are monitored via `target(..., format = "file")`. When I `make()` the plan, it takes ~ 25 minutes until it actually starts because it takes so long to `skip` (that's what it says in the log file) the targets with `format = "file"`. 

This is somewhat surprising, because in another drake plan where even bigger files are monitored - using `file_in()` and `file_out()` instead of `format = "file"` - importing these takes only ~ 1 minute. 

1. Is `file_in()` / `file_out()` generally faster than `format = "file"`?
1. Does the number of files have a large impact on the time it takes? Because in the first (slow) example, there are several thousands files to be monitored, whereas in the second example, there are only a few hundred (larger) files.
1. I would like to stick with `format = "file"` since it's more flexible in my opinion. Is there anything I can do to speed things up?

**Comment by wlandau** [comment]
> Is file_in() / file_out() generally faster than format = "file"?

On my system, `format = "file"` is actually faster, and neither is prohibitively slow. So I suspect other factors are at play here. If your data files sit on a remotely mounted network drive, that will slow things down a lot. Temporary storage, by comparison, is super fast (though not ideal for `drake` workflows).

```r
> library(drake)
> tmp <- tempfile()
> saveRDS(rnorm(2e8), tmp, compress = FALSE)
> system(paste("du -h", tmp))
1.5G	/var/folders/k3/q1f45fsn4_13jbn0742d4zj40000gn/T//RtmptJ1JDE/file17a977cda4ac2
> plan1 <- drake_plan(x = target(tmp, format = "file"))
> plan2 <- drake_plan(x = target(file_in(!!tmp), format = "file"))
> digest::digest(tmp, file = TRUE)
[1] "d68f2ffce92e27f6a12b6660ae92b30a"
> system.time(make(plan1, verbose = 0))
   user  system elapsed 
  0.364   0.365   0.743 
> system.time(make(plan2, verbose = 0))
   user  system elapsed 
  0.925   0.997   1.933 
```

> Does the number of files have a large impact on the time it takes? Because in the first (slow) example, there are several thousands files to be monitored, whereas in the second example, there are only a few hundred (larger) files.

If dealing with files is really the bottleneck, then runtime should scale linearly with the number of files. 100 large files is already a lot.

> I would like to stick with format = "file" since it's more flexible in my opinion. Is there anything I can do to speed things up?

I recommend using [`proffer`](https://github.com/r-prof/proffer) or similar profiling package to identify the bottleneck. Otherwise, it is difficult to speculate about what might be slow.

**Comment by matthiasgomolka** [comment]
Thanks for the explanation. I could verify that `format = "file"` is indeed a little faster than `file_in()`. I'm profiling right now and will come back with the results.

Just one more question regarding your `plan2`: Why do you specify `format = "file"` there as well? Until now, my understanding was that I don't need that for `file_in()` to work. Does that change anything or is it just to make the goal of the target more explicit?

**Comment by wlandau** [comment]
> Thanks for the explanation. I could verify that format = "file" is indeed a little faster than file_in(). I'm profiling right now and will come back with the results.

Nice. I am curious about the bottleneck. Do your data files live on a network drive?

> Just one more question regarding your plan2: Why do you specify format = "file" there as well? Until now, my understanding was that I don't need that for file_in() to work. Does that change anything or is it just to make the goal of the target more explicit?

My mistake, I originally meant to write `format = "file"` only in `plan1` and not `plan2`.  Just updated the example in https://github.com/ropensci/drake/issues/1349#issuecomment-739067635.

**Comment by matthiasgomolka** [comment]
> Do your data files live on a network drive?

Yes. And it seems as if there is no other bottleneck. Below are some screenshorts from {profvis} (I don't have the system requirements for {proffer} at work). 

Do I understand correctly from the last screenshot that it takes quite a while to uncompress the RDS file(s) (containing what exactly?) in the cache? But there is no way to store these using `qs`, since I already use `format = "file"`, right?

So I think, I basically have to live with it. Do I understand correctly that more `jobs_preprocess` in `drake_config()` should have a positive impact? (I already use `jobs_preprocess = 8L`)

**I know this is suboptimal**, but the full `.Rprofvis` file is > 100MB and I have no clue what information it includes so I'm reluctant to upload it here.

**If this is too tedious for you, feel free to close the issue without any further ado.**

---

![image](https://user-images.githubusercontent.com/6517388/101363164-5876c180-38a1-11eb-93b3-a7768670cb79.png)

---

![image](https://user-images.githubusercontent.com/6517388/101363340-9673e580-38a1-11eb-88d6-7ef8c35a3020.png)

---

![image](https://user-images.githubusercontent.com/6517388/101363419-ac81a600-38a1-11eb-8e51-e845bd07309a.png)

---

![image](https://user-images.githubusercontent.com/6517388/101363510-c7ecb100-38a1-11eb-8762-14aea3166c4c.png)

---

![image](https://user-images.githubusercontent.com/6517388/101363782-139f5a80-38a2-11eb-8f24-b615e76592cb.png)

**Comment by wlandau** [comment]
This makes sense to me. `drake` is just trying to check the existence and modification times of a large number of files on a remote network drive. Nothing `drake` itself can do to speed this up unfortunately.

If you have Linux, you can install `proffer` system requirements locally in your home folder with `proffer:: install_go()`. Mac and Windows might also have ways to install Go (and thus `pprof`) locally, I am not sure.
