### ISSUE TITLE
How to mix cross() and map()?

### ISSUE THREAD

**Issue by potash** [ropensci/drake#1351]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/ropensci/drake/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/ropensci/drake/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/drake/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] For any problems you identify, write a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

How to branch in a way that combines cross() and map()? I have three arguments but two of them are paired. For example arg1 can be "a" or "b", arg2 can be 1 or 2 and arg3 can be "red" or "blue" and I want to branch the following combinations:

a, 1, red
a, 2, blue
b, 1, red
b, 2, blue

## Reproducible example

```{r}
test_plan = drake_plan(
  test = target(
    print(c(arg1, arg2, arg3)),
    transform = cross(arg1=c("a", "b"),
                      map(arg2=c(1,2),
                          arg3=c("red","blue")))
    )
)
```

```
> test_plan
# A tibble: 2 x 2
  target command           
  <chr>  <expr_lst>        
1 test_a c("a", arg2, arg3)
2 test_b c("b", arg2, arg3)
```

This one works:

```{r}
test_plan = drake_plan(
  test = target(
    print(c(arg1, args23[1], args23[2])),
    transform = cross(arg1=c("a", "b"),
                      args23=c(c(1,"red"), c(2,"blue")))
    )
)
```

But the target names are ugly:

```{r}
> test_plan
# A tibble: 4 x 2
  target            command                                       
  <chr>             <expr_lst>                                    
1 test_a_c.1..red_  print(c("a", c(1, "red")[1], c(1, "red")[2]))…
2 test_b_c.1..red_  print(c("b", c(1, "red")[1], c(1, "red")[2]))…
3 test_a_c.2..blue_ print(c("a", c(2, "blue")[1], c(2, "blue")[2]…
4 test_b_c.2..blue_ print(c("b", c(2, "blue")[1], c(2, "blue")[2]…
```

What's the best way to do this?

**Comment by wlandau** [comment]
For static branching (`transform = ...`) you can use the `.data` argument of `map()`.

``` r
library(drake)
grid <- tibble::tribble(
  ~arg1, ~arg2, ~arg3,
  "a", 1, "red",
  "a", 2, "blue",
  "b", 1, "red",
  "b", 2, "blue"
)
drake_plan(
  x = target(
    f(arg1, arg2, arg3),
    transform = map(.data = !!grid)
  )
)
#> # A tibble: 4 x 2
#>   target     command          
#>   <chr>      <expr_lst>       
#> 1 x_a_1_red  f("a", 1, "red") 
#> 2 x_a_2_blue f("a", 2, "blue")
#> 3 x_b_1_red  f("b", 1, "red") 
#> 4 x_b_2_blue f("b", 2, "blue")
```

<sup>Created on 2020-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The newer [`targets`](https://github.com/wlandau/targets) ecosystem makes this friendlier and more obvious. [`tarchetypes::tar_map()`](https://wlandau.github.io/tarchetypes/reference/tar_map.html) always takes an argument grid like this, and [`targets`](https://github.com/wlandau/targets) itself supports [composable patterns in dynamic branching](https://wlandau.github.io/targets-manual/dynamic.html#pattern-construction).

**Comment by potash** [comment]
Ah, thanks that does it. Also thanks for referring me to `targets`, I just started using drake so maybe I'll switch over
