### ISSUE TITLE
Change default value of path to getOption(drake.path_cache)

### ISSUE THREAD

**Issue by matthiasgomolka** [ropensci/drake#1358]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/main/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

In our team we use drake with a non-default cache directory. This works fine, but it would be a little more convenient if we could easily pass the non-default path to all drake functions which use the arguments `cache` and `path` (such as `readd()` or `loadd()`). This could be done easily if the default value for `path` would be changed to `getOption(drake.path_cache)`. 

Then, one could set this option and all drake functions which use the cache would work without specifying `path = "/path/to/cache"` or `cache = non_default_cache`.

### Current behaviour
```r
loadd(my_target, path = "/path/to/cache")
# or
loadd(my_target, cache = my_cache)
```

### Proposed behaviour
```r
options(drake.path_cache = "/path/to/cache)

loadd(my_target)
```

This would work because the default value for `cache` is `drake::drake_cache(path = path)`. So the changes are minimal and the default behaviour would not change since `getOption(drake.path_cache)` defaults to `NULL` (the current default for `path`) if the option `drake.path_chache` is not set.

Of course, the name of the option is just a suggestion.

What do you think?

BTW: Due to drake, many of my colleages now make the switch to using R. So, again, thanks for your efforts!

**Comment by wlandau** [comment]
I regret cache flexibility in `drake` because it causes room for too much room for ambiguity and dangerous careless errors that cause loss of hard-earned data. For a tool that tries to promote reproducibility, this is especially egregious. I try to elaborate on this at https://github.com/ropensci/targets/discussions/297. `targets` is similar here because `drake:r_make()` works just like `targets::tar_make()` and is recommended over regular `make()`.

**Comment by matthiasgomolka** [comment]
Thanks for the explanation. I understand your reasoning, but I don't see how I can apply this strict view to my situation at work. 

Would it be OK to open a "Help"-Issue in the targets GitHub repo?

**Comment by wlandau** [comment]
Sure, feel free to post a discussion thread to `targets`.
