### ISSUE TITLE
Debugging difficulty with incorrect code

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#1371]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/ropensci/drake/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/ropensci/drake/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/drake/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] For any problem you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

I have a large (for me) plan with about 100 targets.  While working on it, I had some subtly invalid code.  The code parsed with the R parser, but it was definitely an error on my part.  When I tried to run the plan, I got the error below.  It took me a bit of time to find the problem because the error didn't give any real hints of where the problem started.

The request is to catch coding errors like this and give a more informative error than "subscript out of bounds".

## Reproducible example

``` r
library(drake)

foo <- function() {
  # Whoops, that plus sign at the end of the line was not intended
  scale_y_log10() +
    mod <- list()
}

make(drake_plan(bar=foo()))
#> Error in e[[2]]: subscript out of bounds
```

<sup>Created on 2021-07-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by wlandau** [comment]
This error happens during `drake`'s static code analysis to detect dependencies. Error messages are now improved:

``` r
foo <- function() scale_y_log10() + mod <- list()
drake::make(drake::drake_plan(bar = foo()))
#> Error: subscript out of bounds
#> Malformed code:
#> scale_y_log10() + mod <- list()
#> 
#> Malformed code:
#> function ()  scale_y_log10() + mod <- list()
```

<sup>Created on 2021-07-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by billdenney** [comment]
Thanks!
