### ISSUE TITLE
Consider integer argument to verbose?

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#165]
``import ...`` clogs up the screen but I'd still like to see ``check ...``. An integer argument to verbose could achieve this. 0 = FALSE, 1=TRUE, 2=No imports.

A better solution IMO would stop printing individual imports altogether and just do one chunk with a ... per stage. Now, we already see ``check`` for the imports anyway, so I don't see a big cost in switching the import printing off by default.

**Comment by wlandau-lilly** [comment]
I am supportive of attenuated verbosity, both as an option and the default. The code is ready, but I need an internet connection to push, which will need to wait until tonight or tomorrow.

**Comment by wlandau-lilly** [comment]
Also, I have a preference for silenced imports on 1 and complete verbosity on 2. That way, verbosity increases as ‘verbose’ increases.

**Comment by wlandau-lilly** [comment]
Fixed. This should also make the rendered vignettes much more readable.

**Comment by kendonB** [comment]
This is a great improvement! Any chance of removing the ``missing``s by default as well?

**Comment by wlandau-lilly** [comment]
Expanded:
0: nothing
1: checks and targets (default)
2: +missing
3: +imports

**Comment by wlandau** [comment]
From @krlmlr's workshop, I actually think more visually appealing default might be this:

0: nothing
1: just targets (default)
2: +checks
3: +missing
4: +imports

Thoughts? What about you, @dapperjapper?

**Comment by krlmlr** [comment]
Fully agree. Your suggestion means that users with non-default verbosity will get less info than before. I wonder if it's worthwhile to use a default verbosity of `0.5` or even `0` (with nothing -> `-1`) for the sake of backward compatibility, but perhaps verbosity levels are not part of the API definition ;-)

I also wonder if this would be a legitimate use case for an array of options:

- `drake.verbosity`
- `drake.verbosity.make`
- `drake.verbosity.read`
- `drake.verbosity.diagnose`
- ...

**Comment by wlandau** [comment]
Glad you're on board, Kirill. I am not so concerned about back-compatibility in this case. We can think about an array of verbosity options. My preference at the moment is to avoid extra detail.

**Comment by wlandau** [comment]
Thanks, Kirill! That would be a big help. There are verbosity cutoffs scattered throughout the code base, and I think it could just be a matter of incrementing them.
