### ISSUE TITLE
Consider passing target arguments as promises?

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#167]
Currently, drake seems to load targets that are arguments before calling the function they go into.

If these were promises then the user can potentially write more memory efficient code. With many targets, one could loop through and trim off what they don't need inside the function before loading further targets.

You would want to make sure that this still works efficiently in the case where one target is an input to many functions. As in, it shouldn't duplicate the loading.

**Comment by kendonB** [comment]
Another use case for this feature is making functions with errors fail quickly.

**Comment by wlandau-lilly** [comment]
With the current graph traversal algorithm, I am not sure this is wise because I do not see how to avoid duplicated loading. Not only is duplicated loading inefficient, it would also cause race conditions for local forms of parallelism such as `"mclapply"` and `"future_lapply"` with `future::plan(multicore)`.

But maybe I misunderstand how promises would work here. Would you walk through how out how you picture things playing out in an example?

If we change the graph traversal algorithm (see #168), promises may become the right thing to do. Maybe through [future](https://github.com/HenrikBengtsson/future)?

**Comment by kendonB** [comment]
I didn't know how this would work when asking this question :). But some research suggested ``delayedAssign`` can do it:

``` r
saveRDS(iris, "iris.rds")           
delayedAssign(x = "object_name", {  
Sys.sleep(5)                        
readRDS("iris.rds")                 
})                                  
                                    
function_1 <- function(x){          
print(tibble::as_tibble(x))         
}                                   
                                    
function_2 <- function(x){          
print(tibble::as_tibble(x))         
}                                   
system.time(function_1(object_name))
#> # A tibble: 150 x 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl>  <fctr>
#>  1          5.1         3.5          1.4         0.2  setosa
#>  2          4.9         3.0          1.4         0.2  setosa
#>  3          4.7         3.2          1.3         0.2  setosa
#>  4          4.6         3.1          1.5         0.2  setosa
#>  5          5.0         3.6          1.4         0.2  setosa
#>  6          5.4         3.9          1.7         0.4  setosa
#>  7          4.6         3.4          1.4         0.3  setosa
#>  8          5.0         3.4          1.5         0.2  setosa
#>  9          4.4         2.9          1.4         0.2  setosa
#> 10          4.9         3.1          1.5         0.1  setosa
#> # ... with 140 more rows
#>    user  system elapsed 
#>    0.34    0.00    5.64
                                    
system.time(function_2(object_name))
#> # A tibble: 150 x 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl>  <fctr>
#>  1          5.1         3.5          1.4         0.2  setosa
#>  2          4.9         3.0          1.4         0.2  setosa
#>  3          4.7         3.2          1.3         0.2  setosa
#>  4          4.6         3.1          1.5         0.2  setosa
#>  5          5.0         3.6          1.4         0.2  setosa
#>  6          5.4         3.9          1.7         0.4  setosa
#>  7          4.6         3.4          1.4         0.3  setosa
#>  8          5.0         3.4          1.5         0.2  setosa
#>  9          4.4         2.9          1.4         0.2  setosa
#> 10          4.9         3.1          1.5         0.1  setosa
#> # ... with 140 more rows
#>    user  system elapsed 
#>     0.3     0.0     0.3
```

**Comment by kendonB** [comment]
Looking at this again.

You're right; there is duplicated loading with mclapply.

With ``future_lapply``, does drake have a way of knowing what kind of parallelism is going to be used and whether duplicated loading is appropriate? For SLURM jobs, everything is loaded from disk (?), so duplicated loading is fine.

I'm also imagining the case of a small memory-constrained local machine which could benefit a lot from this behavior with sequential work as it could trim off unwanted data while loading targets in sequence.

I still don't know what the best choice is.

- For sequential work; delayedAssign is unambiguously good, AFAICT.
- For local parallelism ultimately using mclapply, delayedAssign might still be preferred but it would be case specific. In most cases it would be worse, I believe.
- For distributed parallelism where things are sent to single-core workers via disks, delayedAssign is unambiguously good.
- For distributed parallelism where things are sent to multi-core workers via disks, delayedAssign might still be preferred but it would be case specific. In most cases it would be worse, I believe. It gets quite tricky sorting out whether a worker has multiple cores 

A few decisions: which behavior should be the default? Should the default change for mclapply or other parallelisms that can send memory? 

Should this be a command-specific user choice? This one depends on your target market for drake as it further complicates an already complicated interface. I think this one would best be a wrapper around an argument in ``workplan`` like ``target2 = command(please_delay_loading_of_this_target_if_it's_not_yet_loaded(target1))``

**Comment by wlandau-lilly** [comment]
@kendonB I picture an argument in `make()` that controls the eagerness/laziness of assignment. I picture a flag in both `loadd()` and the functions in `envir.R`, which would ultimately [toggle between assign and delatedAssign() here](https://github.com/wlandau-lilly/drake/blob/365384aeb7921bd4cccc8c92941e9ba322313daa/R/read.R#L182). Do you think it is this easy?

**Comment by wlandau-lilly** [comment]
With `delayedAssign()`, we are no longer trying to minimize the number of calls to `loadd()`, so we could turn off [assign_to_envir()](https://github.com/wlandau-lilly/drake/blob/365384aeb7921bd4cccc8c92941e9ba322313daa/R/envir.R#L1) in those cases.

**Comment by kendonB** [comment]
_@kendonB I picture an argument in make() that controls the eagerness/laziness of assignment. I picture a flag in both loadd() and the functions in envir.R, which would ultimately toggle between assign and delatedAssign() here. Do you think it is this easy?_

This is actually a really good compromise that doesn't complicate the interface much at all.

**Comment by wlandau-lilly** [comment]
I think 3fd17c2adb5288661397ca4cd5e2a94f713f519d implements a solution. See the new `lazy_load` argument to `make()` and `drake_config()`, along with the `lazy` argument to `loadd()`. I [tested it](https://github.com/wlandau-lilly/drake/blob/3fd17c2adb5288661397ca4cd5e2a94f713f519d/tests/testthat/test-lazy-load.R), and it [seems to work for all parallel backends except one](https://github.com/wlandau-lilly/drake/blob/3fd17c2adb5288661397ca4cd5e2a94f713f519d/tests/scenarios/lazy_load.R).

I included some [cautionary documentation](https://github.com/wlandau-lilly/drake/blob/3fd17c2adb5288661397ca4cd5e2a94f713f519d/vignettes/caution.Rmd#the-lazy_load-flag-does-not-work-with-parlapply-parallelism) because `make()` with `lazy_load = TRUE` does not work with `"parLapply"` parallelism and `jobs` > 1. This does bother me, but it is probably not worth fixing. There is not much to like about the `"parLapply"` backend, and multisession `"future_lapply"` parallelism is almost the same anyway.

**Comment by wlandau** [comment]
Looking back, I am beginning to question this feature. Reasons:

1. `drake` now has several explicit memory strategies: https://books.ropensci.org/drake/memory.html#memory-strategies, which can be assigned globally and/or for targets one-by-one. The "unload" and "none" memory strategies are the most hands-off, and users can load dependencies with `readd()` as they see fit. With regard to trimming down targets we don't want to load (https://github.com/ropensci/drake/issues/167#issue-276283416) I think `memory_strategy = "none"` is far more usable than `delayedAssign()`. In the latter case, it is really easy to accidentally reference an object and thus load it into memory.
2. In many dynamic branching use cases, particularly for #1108, `drake` needs to override lazy loading anyway. We would need to document promises as a static-branching-only feature.

**Comment by wlandau** [comment]
But lazy loading is still a good idea for `loadd()`, I think, especially for active bindings.

**Comment by wlandau** [comment]
Then again, it seems extreme to go out of our way to deprecate the `lazy_load` argument and remove the underlying functionality. I just added some documentation.

**Comment by kendonB** [comment]
I recall the motivation for the `lazy_load` argument was to ensure that workers (particularly remote workers) would load dependencies rather than having master load them and send them (slowly) to the workers. Does this happen routinely now?

**Comment by wlandau** [comment]
We now have `make(caching = "worker")`, which is a more robust solution to this problem.

Why do you think it is that `make(caching = "worker")` is faster for you? In all other cases I have heard of, including my own experience, `make(caching = "master")` is much faster because it avoids laggy NFS operations.

**Comment by kendonB** [comment]
That option also makes the worker load dependencies and well as caching
output targets?

**Comment by wlandau** [comment]
Yes. It applies to loading dependencies, caching them, and validating storage with checksums as it comes across the network.
