### ISSUE TITLE
Consider styler to replace formatR

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#201]
For projects running `drake` > 5.0.0, it may be time to switch from `formatR::tidy_source()` to `styler::style_text()`:

```r
transformer <- tidyverse_style(
  scope = "tokens",
  strict = TRUE,
  indent_by = 2,
  start_comments_with_one_space = FALSE,
  reindention = tidyverse_reindention(),
  math_token_spacing = tidyverse_math_token_spacing()
)
style_text(text = command, transformers = transformer)
```

To do:

1. Strip comments from text.
2. Build in back compatibility of projects originally build with drake <= 5.0.0.

**Comment by wlandau** [comment]
See yihui/formatR#76. If `formatR` will continue to be supported, the large effort and risk of transitioning to `styler` may not be worth it.

**Comment by wlandau** [comment]
Given yihui/formatR#76, I am not likely to actually make this change until much later in the future.

**Comment by lorenzwalthert** [comment]
Hi. I just saw this and I wanted to point out to one problem with formatR that styler can dhandle better: tidyeval Syntax. Because formatR converts !!! x to !(!(!x)) or similar, so in the case you actually want to execute code, that may be detrimental. If you just use it for caching, I guess it's ok.

**Comment by wlandau** [comment]
Thanks, !! was actually the reason I started looking into styler. But I did manage to work around that shortcoming in #200: the styled/standardized version of the command is no longer the version that also needs to run. That takes the pressure off of formatR/settler. I am still sometimes having problems with '!(!...))', but not in a way that either tool was designed to help.

**Comment by lorenzwalthert** [comment]
Ok fine 😊. So probably it's a good decision to stick with formaR, at least as long as styler is a young and maturing project (e.g. there are more than 20 issues labeled with "Status: Postponed" that should he fixed at some point).

**Comment by wlandau** [comment]
I will definitely revisit the question. I believe `styler` has a bright future and that making the switch will eventually be the right decision.

**Comment by wlandau** [comment]
Replacing with #562 instead. I would prefer base R if possible because this is such a sensitive piec of the internals.
