### ISSUE TITLE
Use tidyselect in loadd() and elsewhere

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#209]
I wonder if we should use [tidyselect](https://cran.r-project.org/web/packages/tidyselect/index.html) for `loadd()` and other functions that accept multiple targets. This would give us access to adjectives like `starts_with()` and `everything()`, but I'm not sure how well this plays with file targets or very large lists of known targets.

**Comment by wlandau** [comment]
I would certainly enjoy an easier way to select the right targets, especially in large projects. I would have suggested using a `tidyselect` pipe chain that ends with `loadd()`, but then I remembered that `list` is not the first argument, which may make that hard.

**Comment by wlandau** [comment]
For what you have in mind, what would a typical `tidyselect`-powered call to `loadd()` look like?

**Comment by krlmlr** [comment]
I would look for `loadd(everything())` for starters, but maybe there are other ways to achieve this?

**Comment by wlandau** [comment]
Fortunately, `loadd()` already just loads everything if `...` and `list` are empty. For other cases, are you thinking we could write something like `loadd(ends_with("_summ"))` to get all our summaries, for example?

**Comment by krlmlr** [comment]
Thinking more about that, this might be a double-edged sword. It makes it particularly easy to pull in dependencies you don't need, just out of convenience. Given that `loadd()` already loads everything, we may want to postpone this for now.

**Comment by wlandau** [comment]
Sure, I tagged the issue as one we may revisit. Feel free to close if you wish. Personally, I find it easy to `grep("summ_*", cached(), value = TRUE)` to get target names, but other users might not know how to do that.

**Comment by wlandau** [comment]
I'm working on a tiny project right now where it would be super convenient to have `loadd(starts_with("selected_data"))`. If we also allowed `cached(starts_with("selected_data"))`, it would be easy to avoid unintended consequences. I am eager for and supportive of this feature.

**Comment by wlandau** [comment]
Maybe we could emulate [`dplyr:::pull.data.frame()`](https://github.com/tidyverse/dplyr/blob/18e0d91b2469cf88b428aa05990ffabe846c5aff/R/pull.R#L26)

**Comment by wlandau** [comment]
Not sure, just looking for a good example of where tidyselect is implemented. Tidyselect itself does not have any vignettes, so I suppose I should have just asked for guidance.

**Comment by krlmlr** [comment]
*dbplyr* and *dplyr* are major users of *tidyselect*, the [CRAN page](https://cran.r-project.org/web/packages/tidyselect/index.html) shows quite a few more revdeps.

**Comment by dapperjapper** [comment]
FWIW it would also be nice to have tidyselect in `build_times()`!

**Comment by wlandau** [comment]
I figured out how to make it work! See the `tidyselect` branch. The `drake_select()` function in `utils.R` is a start. Tests are failing right now, and I don't want to jump ahead until we've sorted out some issues.

It was straightforward to implement `tidyselect for `clean()` and `loadd()`. But other functions have problems.

1. Functions `built()`, `imported()`, `build_times()`, and `diagnose()` are excellent places for `tidyselect`. However, all their argument lists would need to start with `...`, which would require an API change. I don't think this is too jarring for most workflow, but depending on how technical we want to be, it may require yet another major version bump. Thoughts? 
2. On `master`, functions `cached()` and `progress()` work even if you supply nonsensical arguments. `progress(blablabla)` returns `"not built or imported"`, and `cached(blablabla)` returns `FALSE`. With tidyselect, I get `"object not found"` errors for both.

**Comment by wlandau** [comment]
Nope, `.strict` actually just filters out objects it doesn't find. Never mind.

**Comment by wlandau** [comment]
Just implemented `tidyselect` for `loadd()` and `clean()` in #263 (branch `tidyselect2`). Do you guys think I implemented and used the internal `drake_select()` function correctly?

My current thinking is that we can discuss and implement `tidyselect` in other functions on request. @dapperjapper, you mentioned `build_times()`. Is it worth the API change (inserting `...` as the first argument)?

**Comment by dapperjapper** [comment]
I think it's worth it! I don't use any other arguments to `build_times()` anyway.

**Comment by wlandau** [comment]
Starting to think `tidyselect` is overkill for `built()`, `imported()`, and `diagnose()`. But I will put something together for `build_times()`.
