### ISSUE TITLE
Add lazy = "binding" option to loadd()

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#210]
Should use `makeActiveBinding()` or perhaps the [bindr](https://cran.r-project.org/web/packages/bindr/index.html) package to provide access to built targets. From remake experience, accessing a target should only load results but never trigger a build.

The advantage over current `lazy = TRUE` is that updates to this target made in a different session are available immediately in the current session. This allows having a build script that is run e.g. with Ctrl + Shift + B from RStudio.

**Comment by wlandau** [comment]
Absolutely! I think this is the right place for active bindings. I should really learn more about `makeActiveBinding()` and `bindr`.

Just thinking out loud here, but there might also be a use for something like `make(..., lazy_load = "binding")` . Seems like it could make separate interactive non-`make()` sessions react without having to call `loadd()` explicitly. `make()` already [loads and unloads targets throughout the workflow](https://github.com/ropensci/drake/blob/master/R/envir.R) to try to be memory efficient, and lazy loading is currently an option.

**Comment by wlandau** [comment]
Looking into the `bindr` vignette, this looks really easy. It will likely be the next feature I add. Probably within the next couple days.

**Comment by wlandau** [comment]
Fixed via #224.
