### ISSUE TITLE
Catch warnings and messages

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#212]
Suggested by @krlmlr, also by @fmichonneau in richfitz/remake#177. For `drake`, I think a good solution will:

1. Print out warnings and messages to the console when the targets are actually building instead of waiting until the very end.
2. Store the warnings and messages alongside errors in a [new "logs" subspace](https://github.com/ropensci/drake/blob/5b49d407e5f9a3680d96847fed54c4f481d52874/R/subspace.R). (Subspaces are condensed versions of `storr` namespaces that help prevent #154.) Errors are processed and cached [here](https://github.com/ropensci/drake/blob/master/R/run.R#L9). I suspect ordinary exception handling around the [call to one_try()](https://github.com/ropensci/drake/blob/master/R/run.R#L10) would catch warnings.
3. Register the warnings properly so that they show up if the user calls `warnings()` after `make()`.
4. Add a new `type` argument to `diagnose()` that could be `"error"`, `"warning"`, or `"message"`, depending on the kind of build log the user wants. I am open to suggestions for better names. `type` could be more specific, and `diagnose()` could be generalized to a `drake_build_log()` at that point.

## Edit: to do:

- [x] Make `diagnose()` report errors, warnings, messages, etc.
- [x] Update vignettes and other documentation that references `diagnose()`.
- [x] Test that warnings and messages are printed out at the right times.
- [x] Test that target values, errors, and entire build logs are stored properly.
- [x] Run full battery of long package checks.

**Comment by wlandau** [comment]
We could also do some restructuring here to help the manual scheduler avoid requiring its workers to access the cache. Most of it will be in run.R and build.R. As @krlmlr mentioned, this could help with Digital Ocean-based caches.

**Comment by wlandau** [comment]
If we do not want remote processes to write to the cache (#236), then we may have to wait for `future` to make it possible: HenrikBengtsson/future#25.

**Comment by wlandau** [comment]
Echoing @krlmlr's comment in richfitz/remake#177, a complete solution would have `drake_build()` return an [rmonad object](https://cran.r-project.org/web/packages/rmonad/vignettes/introduction.html). #236 needs something like this, so #227 and #237 rely on it too. Learning about [rmonad](https://cran.r-project.org/web/packages/rmonad/vignettes/introduction.html) is very high on my priority list.

**Comment by wlandau** [comment]
FYI: [exception handling in `rmonad](https://github.com/arendsee/rmonad/blob/14bf2ef95c81be5307e295e8458ef8fb2b074dee/R/to-monad.R#L68).

**Comment by wlandau** [comment]
Update: I tried to pass warnings and messages along with the target's value in a list, but this return value is not type-safe when the value is a matrix and there are no warnings or messages. So I implemented a special R6 class to contain the results of a build. I think I like R6 classes for managing the numerous small internal components of `drake`, but I don't think I would want to use them for anything too large or overarching.

Anyway, I still have the above checklist to do. After that, I plan to embrace the `tibble`, then finally move on to #237.

**Comment by wlandau** [comment]
More thoughts: warnings and errors would naturally constitute part of the running `meta` list (metadata on targets). It will be simpler to load it with `drake_meta()` like all the other metadata.

**Comment by wlandau** [comment]
Update: I am optimistic about being able to push a fix today or tomorrow. Rather than jumping to fancy data structures, the expedient thing turned out to be just to add more stuff to the existing metadata. The main change that users will notice is the `diagnose()` function. Rather than just the error log, `diagnose()` will print a list that also contains any warnings, messages, and other context of the build.

**Comment by wlandau** [comment]
Fixed via #248. Tougher than I expected, but it really helps get the internals ready for the next issues.

**Comment by krlmlr** [comment]
Thanks for looking into it! I'm really eager to try this out, but might take a while.
