### ISSUE TITLE
Make Workflow is circular error less stringent?

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#216]
It looks like I'm getting this error because I have a recursive function in my plan.

I can see how this is problematic for drake, but I wonder if there is a simple solution? 

I would recommend not putting too much effort into solving this particular problem, since recursive functions are very rare in R code.

**Comment by wlandau** [comment]
Wow, I totally missed that! The solution seems straightforward: for the functions in [dependencies.R](https://github.com/ropensci/drake/blob/51da28f748d12e4caf133f1d72571183ba2e05bb/R/dependencies.R), force a target or function to not depend on itself.

**Comment by wlandau** [comment]
Well, maybe not necessarily in `dependencies.R`. That would require some restructuring that would not necessarily play nicely with the way `lightly_parallelize()` is set up. I think it would be much easier to catch this in [build_drake_graph()](https://github.com/ropensci/drake/blob/51da28f748d12e4caf133f1d72571183ba2e05bb/R/graph.R#L37) just before `is_dag()`. [`igraph`'s simplification features](http://igraph.org/r/doc/simplify.html) look super useful: check `is.simple()` for loops and use `simplify()` to remove them.

**Comment by wlandau** [comment]
Recursive functions should totally be allowed, so I have decided to just use `simplify()` at the end of `build_drake_graph()` without any warning. A patch is forthcoming.
