### ISSUE TITLE
Support ncol_legend = 0 in vis_drake_graph()

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#217]
Wanted to do a minimalistic example without the legend.

**Comment by wlandau** [comment]
Later, we might revisit a more obvious way to turn off the legend, but this should be quick and just as effective.

**Comment by krlmlr** [comment]
More importantly, perhaps we should show only the legend for node types we're actually using in a graph?

**Comment by wlandau** [comment]
That would certainly reduce clutter. However, I do wonder about new users who may not know about the graph's capabilities. To me, the full legend is an easy way to tell people about a way to monitor up-to-date, outdated, failed, and currently building targets.

**Comment by krlmlr** [comment]
Can we have a `full_legend = TRUE` argument then?

**Comment by wlandau** [comment]
Sure, I think that's the right thing to do.
