### ISSUE TITLE
Is option(width) respected?

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#219]
It doesn't appear so: https://krlmlr.github.io/drake-pitch/#6

(width = 60, output width = 84)

**Comment by wlandau** [comment]
Are we talking about the width and height arguments that vis_drake_graph() passes along to visNetwork()?

**Comment by krlmlr** [comment]
The width of text in the terminal.

**Comment by wlandau** [comment]
I see. Then the width option is not respected. There is some work to do in console.R.
