### ISSUE TITLE
Name conflict with Factual's Drake

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#220]
The company [Factual](https://github.com/factual) already has [its own Make-inspired workflow tool called Drake](https://github.com/factual/drake). It is a command line tool implemented in Clojure, and  the name stands for "Make for Data". It is file-focused, and it seems ostensibly language-agnostic. Admittedly, there seems to be [a way to use R in its workflows](https://github.com/Factual/drake/wiki/Example-R-protocol-use-with-RHadoop), but the focus is not R.

## Reasons to change the name

Factual's Drake came first, a full four years before the R package of the same name. In the year that the `drake` R package has been public, three people have suggested to me that I change its name to avoid a conflict. As @jennybc rightly put it, the issues are potential confusion and lack of discoverability. In a Google search for "drake workflow manager", Factual's Drake has the top three spots, and the `drake` R package has the ninth. Although I am not yet convinced that action is required, I am still concerned, and I would like to discuss the problem out in the open.

## Reasons to keep it

We may have discoverability problems right now, but the long-term situation looks better to me.

#### Drake is a really good name!

It's short and catchy, and it is evocative of a Make-based tool. The full name, "Data frames in R for Make", fits both the acronym and the functionality.

- Your workflow plan is a data frame.
- You do all your work in R.
- One of the parallel backends actually uses real `Makefile`s. If you use `make(..., parallelism = "Makefile")`, you really do have data frames in R intended for Make.

I find it difficult to think of other names that allude to both Make and R. [English words ending in "ake"](http://www.thefreedictionary.com/words-that-end-in-ake), for example, do not seem natural. If you are in favor of a name change, I would appreciate suggestions, preferably ones [cleared by the "`available`" package](https://github.com/ropenscilabs/available).

#### The future development of Factual's Drake seems uncertain.

After reading [this blog post from 2015](https://www.factual.com/blog/drake-after-two-years-barely-famous/), I am a bit doubtful of the continued development and support of Factual's Drake. In fact, [the most recent commit](https://github.com/Factual/drake/commit/3659c116790f1796261d6d23373de8bba1b663be) was from May of 2016, one of only 12 commits from that year. For what it's worth, it also requires Java to install.

#### The R package is still discoverable.

Factual's Drake has been in the open source world since 2013, and yet the paradigm of Make-inspired workflow management did not seem to gain traction in the R community during its more active years. This makes me less concerned that Factual's Drake will conflict with the potential user base of the R package. As I see it, most R users search for R packages to solve their problems.

I am optimistic about the R package `drake`'s chances to hit critical mass. In fact, thanks to rOpenSci, @krlmlr, and @jennybc, the `drake` R package has enjoyed a huge boost in presence and popularity in recent weeks. 

## Your input

I would like to know what you think.

- Does the name need to change?
- If so, what should the new name be?

**Comment by AlexAxthelm** [comment]
* `rproducible`
* `rtifact`
* `managr`
* `governr`
* `rebuildr`

Of these, my vote would be `rebuildr`, since I think it best gets across the message of what `drake` does, but there is a (minor?) name conflict with a chrome extension that was lat updated 2 years ago.

All of these passed `available::available()` checks when I looked.

**Comment by wlandau** [comment]
Nice suggestions, you guys. I am closing this issue because it is old and I am still resistant to changing the name, but let's keep talking on the thread.
