### ISSUE TITLE
Update graph vignette

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#225]
to account for new arguments.

We could use a web-page rendering service to review how the graph vignette looks in major browsers, and then detect major changes to that web page. I know these services must exist, but can't currently name any.

**Comment by wlandau** [comment]
I'm not sure I remember what we talked about here. Did you notice a place where the arguments of `vis_drake_graph()` disagree with the [graph.Rmd vignette](https://ropensci.github.io/drake/articles/graph.html)?

Maybe `phantom.js` could help us out somehow, or a service that uses it. I don't know any services like this either.

**Comment by wlandau** [comment]
Related: I am currently [including graph widgets in iframes](https://github.com/ropensci/drake/blob/master/vignettes/graph.Rmd#dependency-reactivity) using [RawGit](http://rawgit.com/). I wonder if there is a better way.

**Comment by krlmlr** [comment]
We now have the option to only show labels for nodes that are actually used, and to turn off the legend. I haven't found an example in the graph vignette, but maybe it's not designed to describe all available options=?

**Comment by wlandau** [comment]
Oh yes, legend control. We have that now, so we can definitely add it. Anything else?

**Comment by krlmlr** [comment]
Nothing I'm aware of, happy to review later.

**Comment by wlandau** [comment]
Sounds great. The vignette now has a small section on legend control near the end. Feel free to read it and make changes.

**Comment by krlmlr** [comment]
Looks good. Might need rebuilding because we added back legend elements for the shapes used. Did we plan to implement automatic building of the pkgdown site?

**Comment by wlandau** [comment]
I would love a way to automatically build the `pkgdown` site. Whenever the workflow graph images change, this is my workflow:

- Run [images.R](https://github.com/ropensci/drake/blob/master/images/images.R) to generate new images.
- Commit the new images to `master`.
- Look up the new production links to the images at [rawgit.com](https://rawgit.com/).
- Commit the new links to `master`.
- Run [docs.R](https://github.com/ropensci/drake/blob/master/docs.R) to update the `pkgdown` site files.
- Commit to `gh-pages`.

It gets the job done, but it is tedious.

**Comment by wlandau** [comment]
[Just updated the `pkgdown` site](https://ropensci.github.io/drake/articles/graph.html#control-the-legend-).

**Comment by krlmlr** [comment]
I forgot why it doesn't work if we just add `vis_drake_graph()` to a chunk?

**Comment by wlandau** [comment]
Because on CRAN, we would get the [same warnings and notes as visNetwork](https://cran.r-project.org/web/checks/check_results_visNetwork.html). I suppose we could avoid the `pandoc` warnings with `vis_drake_graph(..., file = "graph.html", selfcontained = FALSE)`, but then the size of the package would exceed 5 MB and the generated graph files may not even remain available to the [rendered vignettes on CRAN](https://cran.r-project.org/web/packages/drake/vignettes/). Last time I tried to externalize `visNetwork` files and include them in the package, I got a 404 error where each graph should have been in the rendered CRAN vignettes.

**Comment by krlmlr** [comment]
I see. From looking at https://cdn.rawgit.com/ropensci/drake/0b76e536/images/outdated.html, the script embedded into an `.html` file generated by *visNetwork* with `selfcontained = TRUE` consumes about 1.3 MB, the graph itself is only about 10 kB. Is there a way to avoid embedding the scripts? This would make us less dependent on size restrictions.

**Comment by wlandau** [comment]
If the rest of those 1.3 MB are the same for all graphs, then there should theoretically be a way to reference remote copies. Setting `selfcontained = FALSE` generates a large required `graph_files` folder to accompany a `graph.html` output. I wonder if the `visNetwork` developers would consider `selfcontained = "remote"`...

**Comment by krlmlr** [comment]
It's worth asking, but it feels we need to allow a base URL for the `selfcontained` argument. Same as `selfcontained = FALSE`, but this URL will be used as a prefix for the scripts.
