### ISSUE TITLE
Implement remake -> drake converter

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#230]
80-20 rule, do what's cheap to do and talk about the rest.

**Comment by wlandau** [comment]
Kirill, were you going to implement this one as well?

**Comment by krlmlr** [comment]
One difference between *remake* and *drake* is that the former "knows how to run itself": The `.yml` file explains which files to source, which packages to load, and contains the plan. In a typical *drake* workflow, a script creates the plan which (also) depends on functions in the global environment.

For the converter, a `remake.yml` file would (at least) correspond to:

- a `remake-main.R` file that contains `library()` and `source()` calls
- a `remake-plan.R` file that sources `remake-main.R` and creates (and runs?) the plan

The converter should cover `include` directives for other `.yml` files, which then correspond to other `*-main.R` and `*-plan.R` files (and additional `source()` calls).

This is doable, but I'm not terribly in love with that approach. Maybe I'm still too tied to my *remake* workflows and just need to adapt.

**Comment by wlandau** [comment]
> One difference between remake and drake is that the former "knows how to run itself": The .yml file explains which files to source, which packages to load, and contains the plan. In a typical drake workflow, a script creates the plan which (also) depends on functions in the global environment.

When you put it like that, it seems like a much harder problem to convert from `drake` to `remake`. I am glad we are not trying to go the other way.

> For the converter, a remake.yml file would (at least) correspond to

[`Drake`'s pedagogical examples](https://github.com/ropensci/drake/tree/master/inst/examples#learn-how-to-use-drake) and most of my old work projects have R scripts that turned out to resemble `remake`'s YAML fields.

`drake` R script | `remake.yml`
---|---
`packages.R` | `packages:`
`functions.R` | `sources:`
`plan.R` | `targets:`

For larger projects, `functions.R` obviously splits into a bunch of files. Lastly, I usually write a `make.R` that just `source()`s the files in the correct order and `make()`s the plan.

```r
source("packages.R")
source("functions.R")
source("plan.R")
make(plan)
```
> The converter should cover include directives for other .yml files, which then correspond to other *-main.R and *-plan.R files (and additional source() calls).

Alternatively, can we combine all the YAML files together? Maybe something resembling [`parallelRemake::collate_yaml()`](https://github.com/wlandau/parallelRemake/blob/c71c410602610c329b9dc0b681bbc6777e595e43/R/collate_yaml.R#L12)?

**Comment by krlmlr** [comment]
I'd rather map different `.yml` files to different scripts.

Put bluntly, I don't like the user to call `source()` at all, and I'm uneasy with the idea of processing objects taken from the global environment. Everything should still be R scripts, but I'd like to be able to say "here's a directory full of R scripts, look at them and do what needs to be done". If this is *drake*'s main mode of operation, it will become possible to cache the workflow graph and reconstruct only those parts that can possibly have changed, detected from changes to source files.

I'll try to come up with a design in the context of [*redrake*](https://github.com/krlmlr/redrake), which will also host the converter. We can later see if we want to port anything to *drake*. My experience with *rprojroot* and *here* suggests that a greatly simplified wrapper package lowers the entry barrier for new users.

**Comment by wlandau** [comment]
Have you looked at the `envir` argument of `make()`?

```r
e <- new.env(parent = globalenv())
with(e, source("workflow.R", local = TRUE))
make(e$plan, envir = e)
```

So is [`redrake`](https://github.com/krlmlr/redrake) going to be file-focused where `drake` is R-session-focused? Are you envisioning a point where `make()` with no arguments gets all the instruction it needs from files automatically? If I understand this correctly, we could impose some standards (for example, with a workflow plan always called `plan`) and change the default arguments to `make()` to accommodate.

**Comment by wlandau** [comment]
Closing because the converter will be offloaded to [`redrake`](https://github.com/krlmlr/redrake) (+1), but the conversation can continue here.

**Comment by krlmlr** [comment]
Yes, one of my remake slides just has

```r
make()
```

in large letters ;-)

I think most can be accomplished with existing *drake* functionality, no need to change the interface yet. The `envir` argument will play a role, but it feels cumbersome to explicitly create/use that environment. I have a few specific ideas, but they requires some thinking/tinkering.

**Comment by wlandau** [comment]
I guess there's a reason why so many Make-like tools have configuration files: `Makefile`, `Snakefile`, `remake.yml`, ...

Could [`redrake`](https://github.com/krlmlr/redrake) be a backend for `drake` just like `tidyselect` is for `dplyr`? In the last active days of `remake`, I confused a lot of people when I tried to explain the combination of `remake` + `parallelRemake` + `remakeGenerator`, and it would have been simpler for typical users to go through `remake` as an encompassing frontend.

**Comment by krlmlr** [comment]
I'm not sure what responsibilities a *drake* backend would have. I was thinking more about a simplified facade, but I'm open to suggestions.
