### ISSUE TITLE
Offload wildcard templating to the wildcard package

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#240]
https://github.com/wlandau/wildcard. We could replicate  `generate.R` using `wildcard`'s existing functions, copy over `test-generate.R`, and re-export the functions in `drake`. This would really help avoid duplicated effort as I try to maintain both packages simultaneously.

**Comment by krlmlr** [comment]
I had hoped we wouldn't need wildcard templating once we have the DSL (#233).

**Comment by wlandau** [comment]
Then maybe we should close this one.

**Comment by wlandau** [comment]
Maybe the DSL and wildcards try to solve the same problem, but I see no inherent friction between them. From #233 and #304, it sounds like the API part of the DSL will happen entirely inside `drake_plan()`. By contrast, wildcard evaluation happens totally outside `drake_plan()`. Can we develop both and see how things play out?

**Comment by krlmlr** [comment]
I'd rather focus on one of these problems only, and I'm not a fan of explicitly expanded plans ;-)

**Comment by wlandau** [comment]
That makes sense. I intended to not work too hard on the wildcard/expansion interface. #326 was an exception since it was so easy to implement.

**Comment by wlandau** [comment]
But I think #233 is ambitious and things take awhile to deprecate anyway, so we will have some time.

**Comment by krlmlr** [comment]
Fair enough. Even after #304 we still have to manually construct plans, and that problem looks ambitious already.

**Comment by krlmlr** [comment]
Given that we'll still need wildcard templating for some time, do we need to reopen this issue?

**Comment by wlandau** [comment]
Looking back at this, we would only borrow `evaluate_plan()` from the `wildcard` package, which would save at most 100 lines of code and add a package dependency. This does not seem worth it to me.

**Comment by wlandau** [comment]
We have a DSL now, and I plan to phase out the wildcard stuff eventually. So I think it makes sense to offload the wildcard functionality to a separate package. It should lighten the code base a little.

**Comment by wlandau** [comment]
On second thought, this would involve duplicating too many internal utility functions to be worth the effort. If we leave wildcards alone, they will pass away slowly and peacefully.
