### ISSUE TITLE
Use S3 classes internally to shorten the code base.

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#244]
From @krlmlr in #224. Here's an example for `loadd()` and `load_target()`. We could do the same for `store_target()`. `Drake`'s most central internals are logically organized, but they could be a lot more concise.

```r
loadd <- function(...){

}

load_target <- function(target, cache, namespace, envir, verbose, lazy){
  lazy <- parse_lazy_arg(lazy)
  switch(
    lazy,
    eager = eager_load_target(
      target = target,
      cache = cache,
      namespace = namespace,
      envir = envir,
      verbose = verbose
    ),
    promise = promise_load_target(
      target = target,
      cache = cache,
      namespace = namespace,
      envir = envir,
      verbose = verbose
    ),
    binding = binding_load_target(
      target = target,
      cache = cache,
      namespace = namespace,
      envir = envir,
      verbose = verbose
    )
  )
}
```

### S3 `loadd()` and `load_target()`

```r
loadd <- function(...){
  # ...
  lazy <- parse_lazy_arg(lazy)
  lapply(targets, function(x){
    class(x) <- lazy
    x
  })
  lightly_parallelize(targets, load_target, ...)
}

load_target.eager <- function(...){
# ...
}

load_target.promise <- function(...){
# ...
}

load_target.binding <- function(...){

}
```

**Comment by wlandau** [comment]
[`run_parallel_backend()`](https://github.com/ropensci/drake/blob/2049952e181618ed011693953dd07998ff13513c/R/parallel.R#L1) essentially does this already, but with a naive technique that does not use S3.

**Comment by wlandau** [comment]
I think we might keep this in mind for future development, but there is already so much going on with `drake` that I do not think this is worth the time right now.

**Comment by krlmlr** [comment]
Agreed. Added the "may revisit" label.

**Comment by wlandau** [comment]
`drake` is using S3 very heavily now, including the places mentioned in https://github.com/ropensci/drake/issues/244#issue-294992445.
