### ISSUE TITLE
Automatically generate a workflow plan data frame from arbitrary R code.

### ISSUE THREAD

**Issue by wlandau-lilly** [ropensci/drake#25]
Just something to dream about.

**Comment by wlandau-lilly** [comment]
This just might be possible after all with `CodeDepends` (`readScript()` and `getInputs()`). See duncantl/CodeDepends#14.

**Comment by wlandau-lilly** [comment]
This just might be possible after all with `CodeDepends` (`readScript()` and `getInputs()`). See @clarkfitzg's example at duncantl/CodeDepends#14.

**Comment by wlandau-lilly** [comment]
In fact, I will most likely solve this with `CodeDepends` ([CRAN](https://CRAN.R-project.org/package=CodeDepends), [GitHub](https://github.com/duncantl/CodeDepends)). This feature now seems within reach.

**Comment by wlandau-lilly** [comment]
I have been thinking about this one intermittently for a long time. Even with `CodeDepends`, I am not sure this feature is likely to work very well with most scripts. The scripts where it will work will end up looking a lot like `plan()`, but without the generative templating powered by `expand()` and `evaluate()`. I do not see much added value. Closing for now, will reopen if anyone sees a need and a clean implementation.

#9, however, is much easier and much more useful. I do plan to stick with that one.

**Comment by wlandau** [comment]
@lawremi, thanks for bringing this up this issue yesterday. I almost about it. cc @gmbecker,  your expertise is ideal here. A naive approach would be to just let the default functionality of `CodeDepends` handle the construction of a `drake` plan from a script, but I am not well versed in the edge cases that are likely to crop up when users take it and run too far.

Related idea: construct a `drake` plan from a `knitr`/R Markdown document with an extra `knit(tangle = TRUE)` preprocessing step.

**Comment by gmbecker** [comment]
@wlandau So my read on this is that CodeDepends could very easily generate a plan in the simple case. You have outputs (which can be targets) and the expressions and the inputs.

If you want people to be able to have targets that have more than one expression (I don't know how easy this is currently in drake) that can be complicated, but in the basic one epxression per target case CodeDepends can be used pretty much as is, I think.

I don't know of any situations in which CodeDepends wouldn't get the right _output_ for target identification.

**Comment by clarkfitzg** [comment]
I use CodeDepends for something similar in makeParallel. Relevant code: https://github.com/clarkfitzg/makeParallel/blob/master/R/inferGraph.R

**Comment by wlandau** [comment]
Some updated thoughts: as I understand it, the added value of this feature relative to `drake_plan()` is a little more convenience and familiarity for new users, so I would rather only implement the simple case:

1. Detect single-expression target/command bindings in R scripts and `knitr` reports, and 
2. Explain to users when this breaks.

> If you want people to be able to have targets that have more than one expression (I don't know how easy this is currently in drake) that can be complicated, but in the basic one expression per target case CodeDepends can be used pretty much as is, I think.

To be fair to `CodeDepends`, `drake_plan()` cannot handle multi-expression commands either. I have been recommending curly braces to contain multiple statements, which seems to work out fine.

```r
drake_plan(
  my_target = {
    while (is.na(result <- scrape_data("https://some-website.com")){
      Sys.sleep(retry_interval)
    }
    result
  }
)
```

For guidance, it may be enough to emphasize permanent name binding and one expression per target. I am picturing a help file that explains the difference between 

```r
my_target <- 1 # okay for drake on its own
for (i in 1:10){
  my_target <- my_target + rnorm(1, mean = i) # not okay for drake
}
```

and

```r
my_target <- {
  tmp <- 1
  for (i in 1:10){
    tmp <- tmp + rnorm(1, mean = i)
  }
  tmp
}
```

and refers to a new `drake_example()` in the [drake-examples repo](https://github.com/wlandau/drake-examples). Please let me know if you think I am missing something. This is a very general problem with that I have not spent much time thinking about, so I will not be surprised to learn that I am missing lots of use cases.

**Comment by wlandau** [comment]
Re https://github.com/ropensci/drake/issues/25#issuecomment-413977138: @clarkfitzg, your code is similar (but much nicer looking) to the code in [`R/Makefile.R`](https://github.com/ropensci/drake/blob/master/R/Makefile.R) that powers `drake::make(parallelism = "Makefile")`. The major difference is that `drake` creates dummy timestamp files as `Makefile` targets ([`R/timestamp.R`](https://github.com/ropensci/drake/blob/master/R/timestamp.R)) so we can sometimes stop downstream pipelines early based on `drake`'s hashes of targets. (@krlmlr's idea from https://github.com/wlandau/parallelRemake/issues/4).

A side note about `Makefile`s in `drake` is that we always create a new R session for each target, which adds up to a lot of overhead in cases like the [gsp example](https://ropenscilabs.github.io/drake-manual/gsp.html) where we have a large number of fast targets. In the early days, I thought about generating a `Makefile` to orchestrate the actions of an ensemble of persistent R sessions, but I found there were easier ways to create low-overhead parallel backends.
