### ISSUE TITLE
cached() is not type safe

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#264]
I have not revisited the internals of `cached()` in about a year, and I just came back to it for #209. The return value is not stable.

```r
load_basic_example()
make(my_plan)
cached()
## [1] "coef_regression1_large" "coef_regression1_small" "coef_regression2_large" ...
cached(small, blablabla)
##     small blablabla 
##      TRUE     FALSE 
```

In other words, `cached()` really becomes `is_cached()` when you supply target names. We should really export `is_cached()` and make `cached()` return a character vector of available targets. This separation also opens up `tidyselect` for `cached()`.

**Comment by wlandau** [comment]
I originally posted this issue because I was thinking about implementing `tidyselect` for `cached()`, but on second thought, `tidyselect` seems like overkill here. Closing, but willing to discuss.

**Comment by krlmlr** [comment]
I think type stability is important, but it may be easier to achieve with a new function name.
