### ISSUE TITLE
Use file_in() etc. instead of literal quotes in utility functions

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#266]
Examples:
- `deps(file_in("report.Rmd"))`
- `dependency_profile(file_in("report.md"))`
- `vis_drake_graph(config, subset = c("regression2_small", file_in("report.md")))`

**Comment by krlmlr** [comment]
For the last example it will be difficult to maintain the attributes if we use `c()`, it's easier with `list()`.

**Comment by wlandau** [comment]
That's the sort of thing I am worried about. Maybe we need a different kind of class.

**Comment by wlandau** [comment]
Relevant to possible `dir_out()` and `dir_in()` helpers contemplated in #12.

**Comment by krlmlr** [comment]
`loadd()` ?

**Comment by wlandau** [comment]
Possibly, but `loadd(file_in("file.csv"))` would load the hash, not the contents of the file itself. It is not something I would expect typical users to do.

**Comment by wlandau** [comment]
The distinction between inputs and outputs disappears when we get to utilities like `loadd()` and `deps()` (one command's output is another command's input). And I think a lot of this functionality is already covered by `as_drake_filename()`, which just puts double-quotes around strings.

```r
library(drake)
load_basic_example(verbose = FALSE)
config <- make(my_plan, verbose = FALSE)
deps(as_drake_filename("report.Rmd"))
#> [1] "coef_regression2_small" "large"                 
#> [3] "small"
names(dependency_profile(as_drake_filename("report.md"), config = config))
#> [1] "cached_command"                 "current_command"               
#> [3] "cached_file_modification_time"  "current_file_modification_time"
#> [5] "cached_file_hash"               "current_file_hash"             
#> [7] "cached_dependency_hash"         "current_dependency_hash"       
#> [9] "hashes_of_dependencies"
loadd(as_drake_filename("report.md"))
#> cache /tmp/RtmpKI7kfB/.drake
get(as_drake_filename("report.md"))
#> [1] "1b51fab1485c4b32df45a40b116927848c0e26b410ff1370d28ecaffd20409a7"
readd(as_drake_filename("report.md"), character_only = TRUE)
#> cache /tmp/RtmpKI7kfB/.drake
#> [1] "1b51fab1485c4b32df45a40b116927848c0e26b410ff1370d28ecaffd20409a7"
```

I had `as_file()` before, which did the same thing, but I deprecated it because I thought `as_file()` was likely to conflict with function names in other packages. Do you think we should un-deprecate it? Maybe use another name entirely?

I am resistant to introducing a `"class"` attribute because this feature seems unimportant relative to the large amount of error-prone refactoring required. For example, the attribute of `storr` keys goes away immediately. We would need to cache them in the `meta` namespace and restore them when targets are loaded.

```r
key <- structure("report.md", class = "file")
key
#> [1] "report.md"
#> attr(,"class")
#> [1] "file"
cache <- storr::storr_environment()
cache$set(key = key, value = "the file hash of report.md")
cache$list() # The class is gone.
#> [1] "report.md"
```

**Comment by krlmlr** [comment]
I'm fine with that, the broken symmetry between `file_out()` and `as_drake_filename()` is a bit odd but not too important. Does this mean we only need to update documentation?

**Comment by wlandau** [comment]
We should probably (1) update the documentation and (2) maybe think of a better name for `as_drake_filename()`. In this case, I don't think deprecating it again is such a big deal, and now is a good time to think of a better name. Maybe `file_name()`? That would repair the symmetry.

**Comment by wlandau** [comment]
How about `file_store()`?
