### ISSUE TITLE
Failed targets incorrectly register as up to date

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#267]
I don't think the third `make()` should succeed here. Do we have a way to invalidate targets without destroying the cached value?

``` r
library(drake)

fail <- FALSE

plan <- drake_plan(
  a = if (fail) stop() else 3,
  b = 5,
  c = list(a, b)
)
make(plan)
#> cache /tmp/RtmpN5pez5/.drake
#> connect 2 imports: fail, plan
#> connect 3 targets: a, b, c
#> check 3 items: fail, list, stop
#> check 2 items: a, b
#> target a
#> check 1 item: c

fail <- TRUE
make(plan)
#> cache /tmp/RtmpN5pez5/.drake
#> Unloading targets from environment:
#>   a
#> connect 2 imports: fail, plan
#> connect 3 targets: a, b, c
#> check 3 items: fail, list, stop
#> check 2 items: a, b
#> target a
#> fail a
#> Error: Target 'a' failed. Use diagnose(a) for details.
make(plan)
#> cache /tmp/RtmpN5pez5/.drake
#> connect 2 imports: fail, plan
#> connect 3 targets: a, b, c
#> check 3 items: fail, list, stop
#> check 2 items: a, b
#> check 1 item: c
#> All targets are already up to date.
readd(c)
#> cache /tmp/RtmpN5pez5/.drake
#> [[1]]
#> [1] 3
#> 
#> [[2]]
#> [1] 5
```

> Created on 2018-02-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by wlandau** [comment]
A quick hack would be to corrupt the metadata, but that would only work for some triggers. Maybe there should be a `failed_last_time()` trigger and supporting metadata?

**Comment by wlandau** [comment]
Wait: the solution is easy: we just don't cache the new metadata for a target that fails:

1.  Reverse `store_target()` and `handle_build_exceptions()` in [`conclude_build()`](https://github.com/ropensci/drake/blob/7158210b617dd104297788468540a1d8db05b7a8/R/build.R#L115).
2. Pull `finish_meta()` outside of `store_target()` and call it just after `handle_build_exceptions()` and just before `store_target()` in  [`conclude_build()`](https://github.com/ropensci/drake/blob/7158210b617dd104297788468540a1d8db05b7a8/R/build.R#L115).

**Comment by wlandau** [comment]
Correction: I think the following sequence may be more promising:

1. Store the metadata.
1. Quit if there is an error.
1. Store the target itself.

**Comment by krlmlr** [comment]
Let's not rush this. Maybe we can store metadata under a different path and then flip a switch or something only if the target has been built? (I'm not familiar with *drake* internals yet, just guessing.)

**Comment by wlandau** [comment]
I agree that we should be careful. However, I still suspect that there is straightforward solution. My guess is that the tests are failing because the changes alter the time course of the `progress` metadata (which is not so important to the core functionality or build logic).

**Comment by krlmlr** [comment]
I need to review the "Debugging" vignette before I can be of any help here.

**Comment by wlandau** [comment]
This issue is caused by a flaw in the build logic. Once the logic is corrected, the issue solves quite cleanly. See #269.
