### ISSUE TITLE
Simplify diagnosis of errors

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#272]
The default `print` method for `condition` objects is not very appealing, it's invoked when calling `diagnose()` for failing targets. I'm missing:

- a better default output, perhaps using *tracer* with https://github.com/r-lib/tracer/issues/2
- the ability to start the debugger at the point of failure, I remember *callr* had something that uses `dump.frames()`

**Comment by wlandau** [comment]
Do the existing `condition` objects supply the right input to `tracer`, or would the saved format have to be different? Right now, I do not know a good alternative to [`evaluate::try_capture_stack()`](https://github.com/ropensci/drake/blob/5ed42cf4517bf2548b77815c8e2f8893c3547d61/R/run.R#L27).

**Comment by krlmlr** [comment]
For *tracer*, I don't expect that a call stack is much more than just a list of calls, but I'm not sure. We need to do more for `dump.frames()`, maybe roll our own version of `try_capture_stack()`?

**Comment by wlandau** [comment]
Is that something we could request for trader itself? I often worry about how large the code base of drake is getting.

**Comment by krlmlr** [comment]
Maybe we can contribute to *evaluate*. It's a minor detail -- closing for now, let's revisit once we've sorted out responsibilities.
