### ISSUE TITLE
"Keep going" option

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#273]
like `make -k`. For overnight builds I want to go as far as possible before giving up. Currently I'm doing it with repeated invocation of `make()`, but maybe we can support a cleaner way?

**Comment by wlandau** [comment]
Seems really easy, actually. We just need to pass a `keep_going` argument to `make()`, then `drake_config()`, then onto `handle_build_exceptions()` to suppress [this call to `stop()`](https://github.com/ropensci/drake/blob/5ed42cf4517bf2548b77815c8e2f8893c3547d61/R/handlers.R#L25).

```r
handle_build_exceptions <- function(target, meta, config){
...

if (!config$keep_going){
    stop(
      "Target '", target, "' failed. Use diagnose(", target,
      ") for details.",
      call. = FALSE
  )
}
...
}
```

Should it be called `keep_going`, `continue_on_error`, `ignore_error`, or some other name?

**Comment by krlmlr** [comment]
`keep_going` sounds just right because `make` is using this.

**Comment by wlandau** [comment]
I had to take special precautions at the beginning of `store_target()` to make sure failed targets stay invalidated when `keep_going` is `TRUE`, but otherwise the fix was straightforward.

**Comment by krlmlr** [comment]
Thanks for the very quick fix! `keep_going = TRUE` works much better for my use case, but `make()` still terminates sometimes. I'll try to come up with a reprex tomorrow.

**Comment by wlandau** [comment]
Glad you like it. I wonder what could still cause `make()` to terminate. Could it be related to richfitz/storr#55?
