### ISSUE TITLE
Static ggraph visualization

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#279]
Per https://github.com/ropensci/drake/issues/229#issuecomment-368140927.

Also very useful for reprexes!

**Comment by wlandau** [comment]
Wrapping static graphs into #282. Visualization in general is a Pandora's box of possibilities in the best possible way, and it needs room to grow.

**Comment by wlandau** [comment]
Update: #481 should extend static graphs to the other visuals too.
