### ISSUE TITLE
Master aborts with staged parallelism and failing dependencies even if keep_going is TRUE

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#280]
This isn't mentioned in the "Caution" vignette, looks like a bug to me. Workflow plan (from an earlier version with a different random seed) and reprex below:

![rplot](https://user-images.githubusercontent.com/1741643/36619370-e3359218-18ee-11e8-97b0-d192436318a3.png)

``` r
library(drake)
library(tidyverse)

N <- 4
R <- 2 / N

set.seed(5)

make_job <- function(i, dep = NULL) {
  if (is.null(dep)) {
    deps_sym <- list()
  } else {
    deps_sym <- syms(paste0(dep, i))
  }
  
  if (runif(1) < R) {
    expr(fail(!!! deps_sym))
  } else {
    expr(succeed(!!! deps_sym))
  }
}

fail <- function(...) {
  stop("oops")
}

succeed <- function(...) {}

plan_a <-
  seq_len(N) %>%
  as_tibble() %>%
  transmute(
    target = paste0("a", value),
    call = map(value, make_job)
  ) %>%
  deframe() %>% 
  drake_plan(list = .)

plan_b <-
  seq_len(N) %>%
  as_tibble() %>%
  transmute(
    target = paste0("b", value),
    call = map(value, make_job, dep = "a")
  ) %>%
  deframe() %>% 
  drake_plan(list = .)

plan <- 
  bind_rows(plan_a, plan_b)

clean()
#> cache /tmp/RtmpfQ4PI9/.drake
make(plan, jobs = 2)
#> cache /tmp/RtmpfQ4PI9/.drake
#> connect 8 imports: plan_a, plan_b, make_job, succeed, fail, N, plan, R
#> connect 8 targets: a1, a2, a3, a4, b1, b2, b3, b4
#> check 2 items: stop, succeed
#> check 1 item: fail
#> check 4 items: a1, a2, a3, a4
#> Warning in mclapply(X = targets, FUN = drake_build_worker, meta_list =
#> meta_list, : all scheduled cores encountered errors in user code
#> check 4 items: b1, b2, b3, b4
#> load 4 items: a1, a2, a3, a4
#> Error: key 'a1' ('objects') not found

clean()
#> cache /tmp/RtmpfQ4PI9/.drake
make(plan, keep_going = TRUE, jobs = 2)
#> cache /tmp/RtmpfQ4PI9/.drake
#> connect 8 imports: plan_a, plan_b, make_job, succeed, fail, N, plan, R
#> connect 8 targets: a1, a2, a3, a4, b1, b2, b3, b4
#> check 2 items: stop, succeed
#> check 1 item: fail
#> check 4 items: a1, a2, a3, a4
#> check 4 items: b1, b2, b3, b4
#> load 4 items: a1, a2, a3, a4
#> Error: key 'a1' ('objects') not found
make(plan, keep_going = TRUE, jobs = 2)
#> cache /tmp/RtmpfQ4PI9/.drake
#> connect 8 imports: plan_a, plan_b, make_job, succeed, fail, N, plan, R
#> connect 8 targets: a1, a2, a3, a4, b1, b2, b3, b4
#> check 2 items: stop, succeed
#> check 1 item: fail
#> check 4 items: a1, a2, a3, a4
#> check 2 items: b2, b3
#> load 2 items: a2, a3
#> check 2 items: b1, b4
#> unload 2 items: a2, a3
#> load 2 items: a1, a4
#> Error: key 'a1' ('objects') not found
make(plan, keep_going = TRUE, jobs = 2)
#> cache /tmp/RtmpfQ4PI9/.drake
#> connect 8 imports: plan_a, plan_b, make_job, succeed, fail, N, plan, R
#> connect 8 targets: a1, a2, a3, a4, b1, b2, b3, b4
#> check 2 items: stop, succeed
#> check 1 item: fail
#> check 4 items: a1, a2, a3, a4
#> check 2 items: b2, b3
#> check 2 items: b1, b4
#> load 2 items: a1, a4
#> Error: key 'a1' ('objects') not found
make(plan, keep_going = TRUE)
#> cache /tmp/RtmpfQ4PI9/.drake
#> connect 8 imports: plan_a, plan_b, make_job, succeed, fail, N, plan, R
#> connect 8 targets: a1, a2, a3, a4, b1, b2, b3, b4
#> check 2 items: stop, succeed
#> check 1 item: fail
#> check 4 items: a1, a2, a3, a4
#> check 2 items: b2, b3
#> target a1
#> fail a1
#> target a4
#> fail a4
#> check 2 items: b1, b4
#> target b1
#> fail b1
#> target b4
```

> Created on 2018-02-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by wlandau** [comment]
In staged parallelism, `drake` calls [`prune_environment()`](https://github.com/ropensci/drake/blob/16472dcbb97b156bac9484278c46799d5b22c63d/R/envir.R#L26) in bulk before any of the targets are built in the next stage. If the objects its trying to load are not found, it will throw an error. Since `prune_environment()` is outside all the workers (even in manual scheduling), the error is not handled. Maybe we need to turn these loading errors into warnings.

For now, what if you set `lazy_load = TRUE`? That way, [`prune_environment()`](https://github.com/ropensci/drake/blob/16472dcbb97b156bac9484278c46799d5b22c63d/R/envir.R#L26) just creates promises, and the loading actually happens in the workers themselves.

**Comment by wlandau** [comment]
I think I was right: I reproduced your example, then turned `loadd()` errors into warnings in `prune_environment()`, which seems to fix the problem. I also used your example to refactor the `keep_going` test in `test-edge-cases.R`. Please let me know if the master process still halts prematurely even after https://github.com/ropensci/drake/commit/a23e5ff9ef351dc449df40351bd78e50f4549958.

**Comment by krlmlr** [comment]
Thanks. I'm not in love with muting errors to catch a known problem. Can we instead remove failed/not ready targets from `targets` when calling `downstream_nodes()` in https://github.com/ropensci/drake/commit/a23e5ff9ef351dc449df40351bd78e50f4549958#diff-c7cc5d903a9f8d61efdd3196d0c4ea27R28 ?

**Comment by wlandau** [comment]
How about throwing a warning if `keep_going` is `TRUE` and an error if `FALSE`? (See d529aff93acf472b34af3a28c98981df13534d6c.)

I am not sure changing `downstream_nodes()` would solve the problem. The dependencies to load are all upstream, and it still seems like we should try to load them all.

**Comment by krlmlr** [comment]
Not change `downstream_nodes()`, just the `targets` argument passed to it. What happens if `loadd()` succeeds because there is a cached but outdated value?

**Comment by wlandau** [comment]
Sorry, I still do not see the problem with the current usage of `downstream_nodes()`. The purpose of `downstream_nodes()` is to find targets we want to keep in memory for later. It does not tell us what to load, only what to protect from unloading if it already exists in memory. I am definitely missing a few steps.

**Comment by krlmlr** [comment]
I misread the code. It seems that `load_these` is generated from `target_deps` which is computed by `nonfile_target_dependencies()`. I think we just need to remove the non-ready targets from `load_these` and talk about it.

**Comment by wlandau** [comment]
I can see some reasons to remove failed targets from `load_these`.

#### Avoid wasting time.

If `X` failed and `Y` depends on `X`, then why waste time to build an invalid `Y`? Better to fail `Y` as soon as possible. But some commands may not call on `X` immediately.

```
drake_plan(
  X = stop(),
  Y = {
    results <- do_lots_of_work()
    c(results, X)
  }
)
```

So I think it is better to stop `Y` early in some other way than hiding its dependency `X`.

#### Avoid giving the false impression that `Y` is up to date.

Now that #267 is solved, `Y` should still be out of date if it is built on top of a failed `X`.

So I am not entirely convinced we need to change `load_these`.

**Comment by krlmlr** [comment]
I don't understand this sentence, it doesn't look consistent with the rest of the post:

> I can see some reasons to remove failed targets from load_these.

I fully agree we want to fail early, I'm just not sure a `tryCatch()` is the right way to achieve this, and that `Y` should be outdated if `X` has failed.

All I'm suggesting is to detect which targets won't be able to load (because they failed) rather than trying to load them and failing. It looks safe to alter the semantics and value of `load_these`.

What happens if `loadd()` fails to load target 2 of 3? Will both target 1 and 3 be loaded into the environment?

**Comment by wlandau** [comment]
> I don't understand this sentence, it doesn't look consistent with the rest of the post:

I was just thinking out loud. 

> What happens if loadd() fails to load target 2 of 3? Will both target 1 and 3 be loaded into the environment?

I think I finally understand: `tryCatch()` around `loadd()` is suboptimal when `loadd()` loads many targets. When looking for targets to exclude from loading, should we check for existence in the cache instead of failure?

**Comment by wlandau** [comment]
I think 39ee49a591758d6f97a5c76a1ee73ea2824351e9 is an improvement.
