### ISSUE TITLE
Show object, file, and function legend for full_legend = FALSE

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#281]
See visualization generated with `full_legend = FALSE` below. I'm missing the gray dot and the gray triangle.

![rplot](https://user-images.githubusercontent.com/1741643/36619370-e3359218-18ee-11e8-97b0-d192436318a3.png)

**Comment by wlandau** [comment]
With https://github.com/ropensci/drake/commit/02d0cdb403e9ee057a7fbc25a1fefc34fd59ec82 I get this:

```r
vis_drake_graph(drake_config(plan), full_legend = FALSE)
```

![screenshot_20180223_230345](https://user-images.githubusercontent.com/1580860/36625493-8d089cb4-18ee-11e8-8f29-7ee845f500e8.png)
