### ISSUE TITLE
Offload all visualization to separate tools

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#282]
A new `drakevis` package should support

- `dataframes_graph()`
- `vis_drake_graph()`
- `render_drake_graph()`

as well as the `ggraph` stuff that is coming up (#279 and #229).

**Comment by wlandau** [comment]
As @krlmlr said, this may belong with the scheduling package (#285). We should probably postpone this issue until we know what the scheduler will look like.

**Comment by wlandau** [comment]
Reopening because I think there are some things we could talk about regarding how visualization is offloaded. I think the scheduler and `drake` each has its own visualization needs. Given how hard it is to test visualization, I am starting to think each might have its own separate visualization package with its own suite of complex interactive [`shiny` apps](https://shiny.rstudio.com/). That would allow us to seriously expand the visualization functionality without encumbering the underlying tools.

**Comment by krlmlr** [comment]
Have you tried [*networkD3*](https://cran.r-project.org/web/packages/networkD3/index.html), by the way?

**Comment by wlandau** [comment]
Looks really neat! I did not know about it before.

**Comment by wlandau** [comment]
FYI: I think we should wrap #229 and #279 into this issue. And I really like the discussion at https://github.com/ropensci/unconf18/issues/12. If we are lucky, we can make progress from unconf18.

**Comment by wlandau** [comment]
[`ggdag`](https://github.com/malcolmbarrett/ggdag) looks like it has nice aesthetics for static graphs.

**Comment by wlandau** [comment]
I thought it would take a lot more code and testing to implement #279 and #229, but they actually turned out to be really simple once we had #229. So I am not in a rush to offload anything. I think any major extensions or truly ambitious new visualizations such as D3 graphs and Shiny apps should go in separate packages, and maybe one of them will replace `drake`'s existing visuals. But that has to play out externally first. In any case, offloading the visuals we already have into a special package seems like a lot more trouble than it is worth right now.

**Comment by wlandau** [comment]
Update: just tried `networkD3`. Using it for Sankey diagrams in #467. Looks promising.

**Comment by wlandau** [comment]
Re https://github.com/christophergandrud/networkD3/issues/241, `networkD3` will only be useful for `drake` to make Sankey diagrams until we can make all the edges point the same way.

**Comment by wlandau** [comment]
Let's also keep an eye on [`sankeyD3`](https://github.com/fbreitwieser/sankeyD3). Apparently, it has the ability to hide child nodes with a double-click.
