### ISSUE TITLE
Use pkgconfig to change default value for strings_in_dots argument

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#290]
We don't want to change the current default for backward compatibility, but we may want to provide a robust way to change the default for new code. With the *pkgconfig* package we can do:

```
drake_plan <- function(
  ...,
   strings_in_dots = pkgconfig::get_config("drake::strings_in_dots")) ...
```

This is safer than a global option, because *pkgconfig* allows different values depending on who's the caller. This makes a difference if we're called from different packages.

**Comment by wlandau** [comment]
I am unfamiliar with `pkgconfig`, but it seems like this would allow users to `set_config()` and avoid having to set `strings_in_dots = "literals"` for every call to `drake_plan()`. Is that the idea?

**Comment by krlmlr** [comment]
Thanks for the very quick fix!
