### ISSUE TITLE
Lonely single quotes confuse check_plan()

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#291]
I haven't succeeded in replicating the error with using only `c()` instead of `buy()`.

``` r
library(drake)
library(cooking)
plan <- drake_plan(
  meat = buy("meat", from = "the butcher's")
)
#> Warning: Converting double-quotes to single-quotes because the
#> `strings_in_dots` argument is missing. Use the file_in(), file_out(),
#> and knitr_in() functions to work with files in your commands, and pass
#> `strings_in_dots = "literals"` to remove this warning.
check_plan(plan)
#> cache /tmp/RtmpplXAkP/.drake
#> connect 1 import: plan
#> connect 1 target: meat
#> Error in parse(text = command): <text>:1:33: unexpected symbol
#> 1: buy('meat', from = 'the butcher's
#>                                     ^
plan <- drake_plan(
  meat = buy("meat", from = "the butcher's"),
  strings_in_dots = "literals"
)
check_plan(plan)
#> cache /tmp/RtmpplXAkP/.drake
#> connect 1 import: plan
#> connect 1 target: meat
#> Warning: Files in a command declared with single-quotes:
#>   s")
#> The way to declare files in drake is deprecated. Use file_in(), file_out(), and knitr_in() in your commands. See `?drake_plan` for examples.
#> Warning: missing input files:
#>   s")
```

> Created on 2018-03-03 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by wlandau** [comment]
I see what you are saying. On the other hand, I am not sure if there is anything to do here. Because of #232, we will inevitably drop automatic single-quoting, and then we will not longer have to worry about illegal strings such as `'the butcher's'`. I can think of a couple workarounds, but they all involve sanitizing commands in ways that may surprise the user.

**Comment by wlandau** [comment]
I think `pkgconfig::set_config("drake::strings_in_dots" = "literals") `  should prevent this until automatic single quotes are dropped.

**Comment by krlmlr** [comment]
I'm using `strings_in_dots = "literals"` explicitly in the second part of my reprex, and I'd expect it to just use the strings and not worry about single quotes.

**Comment by wlandau** [comment]
Yeah, it's glitchy because we cannot properly walk the AST to detect single-quoted strings. When it's time to remove the whole business of single-quotes, we can get rid of [`extract_filenames()`](https://github.com/ropensci/drake/blob/e87f05ad70a9c605df885c07df1bc5fa484db352/R/commands.R#L11), and the problem will go away.

**Comment by krlmlr** [comment]
Why do we need to walk the AST at all with `strings_in_dots = "literals"`?

**Comment by krlmlr** [comment]
More precisely, why are we looking at strings when walking the AST with `strings_in_dots = "literals"` ?

**Comment by wlandau** [comment]
Because users can still pass single-quoted filenames with the `list` argument to `drake_plan()`, and `drake` uses the same code analysis regardless of `strings_in_dots`.

**Comment by krlmlr** [comment]
Can we extend the effect of `strings_in_dots` to the `list` argument? Alternatively, I'd be happy if we had a different treatment internally for arguments that come from the dots and arguments that are passed via `list()`.

**Comment by wlandau** [comment]
I am not sure. While we still have awkward single-quoting, the strength of the `list` argument is that quotes stay put instead of getting mangled by R's parser. And any changes we work on now will become moot when we are ready to remove single-quoting altogether.

**Comment by krlmlr** [comment]
It's not even about `drake_plan()`:

``` r
drake::check_plan(tibble::tibble(target = "test", command = "\"'\""))
#> Warning: Files in a command declared with single-quotes:
#>   
#> The way to declare files in drake is deprecated. Use file_in(), file_out(), and knitr_in() in your commands. See `?drake_plan` for examples.
#> Warning: missing input files:
#> 
drake::check_plan(tibble::tibble(target = "test", command = "\"a'b\""))
#> Warning: Files in a command declared with single-quotes:
#>   b
#> The way to declare files in drake is deprecated. Use file_in(), file_out(), and knitr_in() in your commands. See `?drake_plan` for examples.
#> Warning: missing input files:
#>   b
```

> Created on 2018-03-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I think `drake_unquote()` can be improved. We don't seem to really need the `deep` argument, and simple unquoting is better done with

```r
gsub("^(?:'(.*)'|\"(.*)\")$", "\\1\\2", x)
```

. The same regex can be used in `is_file()`. Happy to dig a bit deeper here.

**Comment by wlandau** [comment]
Right. During `check_plan()` a `config` object is created because that opens up a lot of additional checks, including a dependency graph and code analysis.

Also, thanks for the regex tip. I pushed it in 5ba684a51cc733d2bd783d8ad83714745fa41839.

**Comment by krlmlr** [comment]
I wonder if we could avoid the `extract_filenames()` call if the `drake::strings_in_dots = "literals"` *pkgconfig* option is set.

**Comment by wlandau** [comment]
Most of the people who choose the `pkgconfig` route are conscious adopters of the new file API, so I am supportive of this.
