### ISSUE TITLE
Warn user if <- is used in drake_plan()

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#293]
I've seen this mistake multiple times today. Should be easy enough to detect.

**Comment by wlandau** [comment]
Alternatively, we could add some special parsing to accept `<-` and `->` in commands passed through `...`. It requires some specialized code analysis, but it should be robust enough.

**Comment by rkrug** [comment]
I don’t think this should be changed. The function drake_an() is taking named arguments and this is a standard behavior, that = is not equal to -> in function calls. Making this equivalent for this function would encourage sloppy (and wrong in all other cases) programming. It is simple wring to Use -> in a Funktion call  here and it wouldbe in inconsistent with R to change it here.

**Comment by wlandau** [comment]
Fair enough. I will soon push a commit that warns on `->` and `<-`.
