### ISSUE TITLE
Add support for iterative targets

### ISSUE THREAD

**Issue by rkrug** [ropensci/drake#298]
This is liked to issue #233, but I post it separately here to avoid mixing it with the more general discussion there.

Assuming the following situation and workflow of an iterative simulation:

1) initialize initial state
2) simulate ```Ni```
3) go back to ```i``` if ```i < I``` 
4) calculate stats from ```NI``` 

I would now use drake for this workflow, as it would allow me to continue at timestep ```i``` if there is an error in timestep ```i+1```. One might consider this as a misuse of drake, but it would make this kind of work much easier (automatically created checkpoints).

So I would suggest to add a verb ```repeat``` to the plan definition to allow exactly this kind of workflow.

```
drake_plan(
  init = initialize(),
  Ni_0 = generateN0(),
  Ni = plan_repeat(FUN = sim, from = 1, to = 100, Ni)
  stats = stats(Ni_100)
)
```

would result in a plan in the traditional way:

```
drake_plan(
  init = initialize(),
  Ni_0 = sim(N0),
  Ni_1 = sim(Ni_0),
  Ni_2 = sim(Ni_1),
  Ni_3 = sim(Ni_2),
  ...,
  Ni_100 = sim(Ni_99),
  stats = stats(Ni_100)
)
```

Not sure abut the best syntax for ```plan_repeat``` yet, specifically about sbecifying the reference to the previous target.

**Comment by wlandau** [comment]
It's a good suggestion, and I consider it part of #233. For now, you could use the [`wildcard` package](https://github.com/wlandau/wildcard).

```r
library(drake)
library(magrittr)
library(wildcard)
drake_plan(
  init = initialize(),
  ni_NEXT = sim(ni_PREVIOUS),
  stats = get_stats(ni_4)
) %>% 
  wildcard(wildcard = "NEXT", values = 1:4, expand = TRUE) %>%
  wildcard(wildcard = "PREVIOUS", values = 0:3, expand = FALSE)
#>   target          command
#> 1   init     initialize()
#> 2   ni_1        sim(ni_0)
#> 3   ni_2        sim(ni_1)
#> 4   ni_3        sim(ni_2)
#> 5   ni_4        sim(ni_3)
#> 6  stats get_stats(ni_4)
```
