### ISSUE TITLE
outdated() is impure

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#306]
by default. I'd have expected this to be free of side effects, but these can occur (under some circumstances) because of `make_imports = TRUE`.

**Comment by wlandau-lilly** [comment]
I'm willing to live with that if it means `outdated()` has the most current information about the imports.

**Comment by wlandau** [comment]
Given the need to check the imports, I have a preference to leave `outdated()` impure. But I could be convinced otherwise if I am overlooking something.

**Comment by krlmlr** [comment]
I was using `outdated()` in a function, and this was problematic. Let me see if I can come up with a reprex.

Eventually we should make sure that each function is either pure or has side effects, but we can postpone this. I'm not convinced `outdated()` really needs to make imports if the users are aware that they need to make targets for accurate results. Would a pure version of `outdated()` be able to show outdated imports?

**Comment by wlandau** [comment]
I think it would take some extra work to show outdated imports, though it might be worthwhile long-term. `Drake` is not currently prepared to show this information to users.
