### ISSUE TITLE
planning the 5.1.0 CRAN release

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#308]
Thanks to you guys, `drake` has come a long way since version 5.0.0, the latest CRAN release. I think we are steadily approaching the right time for a CRAN update, and I added some remaining issues to the [CRAN release 5.1.0 milestone](https://github.com/ropensci/drake/milestone/9). With the exception of #232, the updates are numerous, but minor. I think it will be a good checkpoint before we get started implementing more difficult issues such as #282, #283, #285, and #233.

What do you all think? Are there issues we should add/remove from the plan for 5.1.0?

**Comment by AlexAxthelm** [comment]
I think #232 on its own is a big enough change to warrant a release. All the other discussions that I've been part of are pretty major, and I think a checkpoint now is a good idea.

**Comment by wlandau** [comment]
I agree.

Another thing: I hear R 3.4.4 is going to come out this Thursday. Do you think this is likely to cause problems? Should we postpone the release until a week or so after that? Apparently, CRAN now automatically rejects packages that generate check warnings.

**Comment by AlexAxthelm** [comment]
I don't think there is huge rush to release, So long as the RC is clearly identified.

**Comment by wlandau** [comment]
Sure. All the issues for 5.1.0 are solved, so I think we're in a great position here. The extra time will give us more of a chance to double-check for bugs. Checks for HPCs and a couple old test projects appear fine on my end. Win-builder is throwing some NOTEs ("potentially bad URLs" and "non-standard" Authors@R roles, neither of which I think I can fix). In the meantime, I plan to **finally** work on the [design spec of the `workers` package](https://github.com/wlandau/workers/tree/specification).

**Comment by wlandau** [comment]
Just a reminder: I plan to submit `drake` 5.1.0 to CRAN tomorrow afternoon. Any last requests?

**Comment by AlexAxthelm** [comment]
Do the non-standard author tags resolve under 3.4.4?

**Comment by wlandau** [comment]
Unfortunately not, but they seem to go away in R-devel.

**Comment by wlandau-lilly** [comment]
5.1.0 is on CRAN! The source is up, and builds are presumably in progress. A big thanks to everyone who contributed ideas and patches.
