### ISSUE TITLE
Serve GitHub Pages from docs directory

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#312]
I've been struggling to accept this as a better solution myself for a long time, because a separate documentation branch seemed neat. I see the following advantages from [serving from `/docs`](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch):

- we don't need rawgit anymore, and we don't need to update hashes because we can link directly to the artifact on the GitHub Pages  (this alone feels worth it)
- we can preview pkgdown changes in pull requests if necessary
- docs and source are better synchronized

The project is bigger when cloning or installing from GitHub, but we already have `/images`, and I don't think `/docs` adds that much more.

**Comment by wlandau** [comment]
I like the idea. RawGit is a hassle. Can we .Rbuildignore the images so we can stay under 5MB? Will this approach work for the rendered CRAN vignettes?

**Comment by krlmlr** [comment]
Thanks. Yes. Yes. Yes. ;-)

**Comment by krlmlr** [comment]
But we need to store the images in `docs/images` instead of `images`.

**Comment by wlandau** [comment]
Ah, I think I am finally connecting the dots on this one. We just need to

- Move `images` to `docs/images`
- Change all the RawGit links to reference the images in the new location on the [`pkgdown` site](https://ropensci.github.io/drake/).

Tedious, but straightforward and definitely worth it.

**Comment by krlmlr** [comment]
I can do it, but you'll need to change the repo settings.

**Comment by wlandau** [comment]
Thanks, Kirill! Which settings do I need to change?
