### ISSUE TITLE
problematic precidence in if-elses?

### ISSUE THREAD

**Issue by gmbecker** [ropensci/drake#319]
https://github.com/ropensci/drake/blob/ca9cbbe5cf486f850cc499db78651e99ad4f4c66/R/dependencies.R#L293-L299

AFAIK is.primitive will never return TRUE in a case where is.function did not, so I believe the last condition on line 299 will never do anything. 

Caveat: this is based only on a reading of the code, not on any problem that arose by actually running it.

**Comment by wlandau** [comment]
Thanks, Gabe! I originally included `is.primtive()` for a reason, but I think that was before I added `is.function()`.
