### ISSUE TITLE
Documentation in bookdown format?

### ISSUE THREAD

**Issue by rkrug** [ropensci/drake#332]
This is now just an idea, but the documentation seems to grow and grow (which is brilliant). What about migrating the documentation to bookdown format https://bookdown.org/yihui/bookdown/ with the longterm goal of publishing it on bookdown.org?

 But it looks as if it would be quite mission to do that?

**Comment by wlandau** [comment]
I expect [`docs.R`](https://github.com/ropensci/drake/blob/master/docs.R) and all its output will become part of the `bookdown` site too.

**Comment by rkrug** [comment]
How is the documentation compiled at the moment? I only see the resulting html files in doc?

**Comment by wlandau** [comment]
The [`docs.R` script](https://github.com/ropensci/drake/blob/a09880ec3976685c7481143f21d5049523730b9b/docs.R#L47) runs [`pkgdown`](https://github.com/r-lib/pkgdown) to generate the HTML files in the [`docs` folder](https://github.com/ropensci/drake/tree/master/docs). For example, the [package vignettes](https://github.com/ropensci/drake/tree/master/vignettes) become the ["articles"](https://github.com/ropensci/drake/tree/master/docs/articles). Then, GitHub hosts the files in [`docs`](https://github.com/ropensci/drake/tree/master/docs) at [https://ropensci.github.io/drake/](https://ropensci.github.io/drake/). I generally like this system, but I want to remove the burden of long-form documentation from the [vignettes](https://github.com/ropensci/drake/tree/master/vignettes) and host only at [https://ropensci.github.io/drake/](https://ropensci.github.io/drake/) or an equivalent site.

**Comment by wlandau** [comment]
The `drake` user manual is here and in `bookdown` format: https://wlandau.github.io/drake-manual. Things left to do:

- [ ] Replace all `drake`'s vignettes with a pointer to the manual and `pkgdown` site. This will seriously lighten the load for CRAN.
- [ ] Copy over `images/`.
- [ ] Move over the code from `docs.R` that generates the HTML widgets and FAQ. 
- [ ] Automate the full compilation, from the HTML widgets to `faq.Rmd` and compiled `bookdown` site.
- [ ] Make sure all the image hashes match up.
- [ ] Mention the `bookdown` manual in the `drake` README.

**Comment by wlandau** [comment]
The user manual has a long way to go, but I think we're fully migrated to http://ropenscilabs.github.io/drake-manual + https://ropensci.github.io/drake/ for documentation. This is so much better! I am spending far less time re-building vignettes, the package is smaller, and there is no more funny business about having to individually HTML widgets that should just be automatically inline.
