### ISSUE TITLE
Add hooks to `make()` function

### ISSUE THREAD

**Issue by rkrug** [ropensci/drake#334]
# Suggestion

Add hooks to the make function. Possible hooks would be

- `before_make_hook()' which is executed before the whole make process
- `before_target_make_hook()` which is called before the compilation of each target is executed
- `after_target_make_hook()` which is executed after a target has been compiled and is stored in the cache
- `after_make_hook()' which is executed after the whole make process

# Motivation

These hooks would make it possible to e.g. publish results of an analysis target to a website, post them on e.g. Dropbox for collaborators, post-process them for publishing.

The advantage, in contrast to a new target, would be that there is no overhang in regards to space and cache management required. 

Additional usage of these hooks: setup environments as might be required by #333

**Comment by wlandau** [comment]
`make()` already has a `hook`, which wraps around a target's command. To cover `before_target_make_hook()` and `after_target_make_hook()`, you might try something like this.

```r
make(hook = function(command){
  run_before_target()
  value <- force(command)
  run_after_target()
  value
}
```

There is also `prework`, which is kind of like `before_make_hook()`. (The prework is also executed before each target for distributed parallelism: `"Makefile"`, "`future_lapply"`, and `"future"`.)

As for `after_make_hook()`, I would rather not include it as part of `drake`. I think it would be straightforward for users to call `make()` and then do any custom post-processing afterwards in an R script. `make()` does a lot, but it is not perfectly end-to-end, and that is okay.
