### ISSUE TITLE
Rmarkdown template

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#337]
How about providing a template that looks like the "normal" *rmarkdown* template but uses *drake* behind the scenes? This might lower the entry barrier for users who already use *rmarkdown* for reproducible research but end up with documents that render too slowly.

Suggested by @christophsax.

![pastedgraphic-2](https://user-images.githubusercontent.com/1741643/37773526-1d9ac2b2-2dde-11e8-9a9e-3b7d8c888f61.png)

**Comment by wlandau** [comment]
Absolutely. It would be really nice if users could select a `drake`-powered R Markdown file from the RStudio GUI.

**Comment by krlmlr** [comment]
Example package with lots of templates: https://github.com/rstudio/rticles

**Comment by christophsax** [comment]
I hacked together a few templates for various purposes, and could offer support. However, I probably should update my drake skills first.

**Comment by wlandau** [comment]
I am always glad to have help. I think we can modify one of the [existing `drake` examples](https://github.com/ropensci/drake/tree/master/inst/examples) for this purpose. One of the [pedagogical examples](https://github.com/ropensci/drake/tree/master/inst/examples#learn-how-to-use-drake) should be fine.

**Comment by wlandau** [comment]
I looked at the examples in [rstudio/rticles](https://github.com/rstudio/rticles), and I can picture a few different ways to approach this.

1. Just include a standalone vignette, maybe [example-gsp.Rmd](https://github.com/ropensci/drake/blob/master/vignettes/example-gsp.Rmd).
2. Include the [gsp example](https://github.com/ropensci/drake/tree/master/inst/examples/gsp), but with [`interactive-tutorial.R`](https://github.com/ropensci/drake/blob/master/inst/examples/gsp/interactive-tutorial.R) converted to `skeleton.Rmd` and the rest of the files in the `skeleton` folder.
3. Same as (2), but with `make.R` converted to `skeleton.Rmd`.
4. Same as (2) and (3), but with `skeleton.Rmd` as a vignette that just tells users to run `make.R`.

Which option do you think is most appropriate? How do you think we can avoid duplicate information? Would it require moving `inst/examples` to `inst/rmarkdown`?

**Comment by AlexAxthelm** [comment]
I may be missing something here, but is `drake` intended to be called from *within* Rmarkdown documents? I know that `knitr_in()` will find all of the `readd` and `loadd` calls, but how would this template work for calling `make()`?

**Comment by wlandau** [comment]
Calling `drake` inside R Markdown is possible, but it misses the point. On the other hand, the `inst/rmarkdown` templates assume the R Markdown document is the workflow manager. That is exactly why I feel mixed up here.

**Comment by christophsax** [comment]
Sorry for offering support without delivering. I haven't had time yet to get familiar with drake, and won't have for another two weeks. So feel free to move on. Will be interested in how it turns out (and probably will love it).

**Comment by wlandau** [comment]
It's okay, Christoph. In this case, advice is essentially just as good as a deliverable (re: https://github.com/ropensci/drake/issues/337#issuecomment-378949897). Given that `drake` bucks convention and operates outside R Markdown reports, what do you suggest we do? Once we're clear on the approach, the implementation will be super easy.

**Comment by krlmlr** [comment]
IMO, knitting the `.Rmd` file without running `drake::make()` should give an informative error, including detailed instructions.

**Comment by wlandau** [comment]
So maybe (2) with those detailed instructions in `skeleton.Rmd`? I could get behind that. At this point, I just wonder if there is a slick way to use the [pedagogical examples](https://github.com/ropensci/drake/tree/master/inst/examples#learn-how-to-use-drake) without duplicating information. It would be cumbersome to maintain the same code in both `inst/rmarkdown` and `inst/examples`. I suppose we could move `inst/examples` to `inst/rmarkdown` with some modifications to `drake_example()`, but it does seem a little awkward.
