### ISSUE TITLE
NA hash seems to be passed to storr

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#340]
When checking downstream dependencies for RSQLite, I've run into a situation where *drake* stops during analysis of the plan. I suspect the error stems from passing an `NA` hash to *storr*, but I wouldn't know why.

I'm seeing:

```r
Error in if (use_cache && exists0(hash, envir)) { :
  missing value where TRUE/FALSE needed
Calls: make ... lapply -> FUN -> diagnose -> <Anonymous> -> <Anonymous>
In addition: Warning messages:
1: In mclapply(X = keys, FUN = FUN, mc.cores = jobs, ...) :
  scheduled cores 10, 8, 5, 3, 2, 11, 13 encountered errors in user code, all values of the jobs will be affected
```

This is after patching the code that computes `do_build` to coerce to `logical` and convert `NA` to `FALSE`:

https://github.com/ropensci/drake/blob/d17d3a6c0a31b6ff14a8d47b3402ae341092d5db/R/staged_parallelism.R#L202-L209

The values of `do_build` are sometimes strings containing `"Error in if (use_cache && exists0(hash, envir)) { : \n  missing value where TRUE/FALSE needed\n"`. This code is used by `storr$get()`, if I'm not mistaken.

To reproduce:

1. Clone RSQLite from GitHub (https://github.com/r-dbi/RSQLite/commit/a5fc2989a5d7ea2f0c2a2d0f91e23f490f4f199f)
1. Extract the [drake cache](https://www.dropbox.com/s/7858tqb9tz46n2b/dot-drake.tar.gz?dl=0) to the project directory
1. Run `R -q -f revdep/drake.R`

I'm sorry I don't have a smaller example. Will try other parallel options.

**Comment by krlmlr** [comment]
Here's the mini-patch:

```patch
diff --git a/R/staged_parallelism.R b/R/staged_parallelism.R
index f15f1d1..884e556 100644
--- a/R/staged_parallelism.R
+++ b/R/staged_parallelism.R
@@ -206,8 +206,13 @@ parallel_stage <- function(worker, config) {
       meta_list = meta_list,
       config = config
     ) %>%
-      unlist
+      unlist()
+    print(do_build)
+    do_build <- as.logical(do_build)
+    print(do_build)
+    do_build[is.na(do_build)] <- FALSE
     build_these <- c(build_these, new_leaves[do_build])
+    print(build_these)
     if (!all(do_build)){
       trim_these <- new_leaves[!do_build]
       config$execution_graph <- delete_vertices(
```

**Comment by krlmlr** [comment]
The example I gave isn't sufficient to replicate locally. More files are needed, but I don't have them anymore. Trying now to replicate again.

**Comment by wlandau** [comment]
> The values of do_build are sometimes strings containing "Error in if (use_cache && exists0(hash, envir)) { : \n missing value where TRUE/FALSE needed\n". This code is used by storr$get(), if I'm not mistaken.

I have a guess as to why, and I think 9885ba36a52bd3e1dbf8389db114134191815dbc just might fix it. (Triggers like `file_trigger()` should always return logical, but I had calls to `stopifnot()`.) Does it help?

**Comment by krlmlr** [comment]
Thanks. I'll update *drake* and watch out for further occurrences of that error.
