### ISSUE TITLE
Give a character string to define a file dependency

### ISSUE THREAD

**Issue by norival** [ropensci/drake#347]
Hi!

I use the function `file_in()` inside `drake_plan()` to define a dependency to a file, but it only works if I give the path to the file directly. If I give it with the `file.path()` function or with a variable storing that file path, it doesn't work. I think this can be related to #12.

# Examples:

```
# preparation
library(drake)

path.data <- "data"
dir.create(path.data)
write.csv(iris, file.path(path.data, "iris.csv"))
```
    

## Working plan:

```
# working plan
working_plan <-
    drake_plan(iris_data = read.csv(file_in("data/iris.csv")),
                       strings_in_dots = "literals")
working_config <- make(working_plan)
vis_drake_graph(working_config)
```

This plan works fine, and the file `data/iris.csv` is considered as a dependency

[Working plan][2]

## Not working plan:

```
# not working
notworking_plan <-
    drake_plan(iris_data = read.csv(file_in(file.path(path.data, "iris.csv"))),
                       strings_in_dots = "literals")
notworking_config <- make(notworking_plan)
vis_drake_graph(notworking_config)
```

Here it is trying to read the file `iris.csv` instead of `data/iris.csv`.

## Working but problem with dependency:

```
# working but "data/iris.csv" is not considered as a dependency
file.name <- file.path(path.data, "iris.csv")
notworking_plan <-
   drake_plan(iris_data = read.csv(file_in(file.name)),
                      strings_in_dots = "literals")
notworking_config <- make(notworking_plan)
vis_drake_graph(notworking_config)
```

This last one works fine but the file is not considered a dependency, so drake doesn't re-run the plan if this file is changed.

[Not working drake plan][3]

So, is there a way to tell drake file dependencies from variables? I'm just learning drake, so I may have missed something.

Thank you!

  [1]: https://github.com/ropensci/drake
  [2]: https://i.stack.imgur.com/eERgH.png
  [3]: https://i.stack.imgur.com/XaplS.png

**Comment by wlandau** [comment]
Sorry Xavier, this behavior is unlikely to change in `drake` any time soon. We may work it into #233 and #304 if/when dependencies can be re-resolved at runtime, but that is long-term. For now, `drake` finds dependencies without running any of the code in your commands. In other words, it does not know what you mean when you give a `file.path()` to `file_in()`.

**Comment by norival** [comment]
Ok, no problem. Thanks for the answer =)
