### ISSUE TITLE
Working with HPC time limits

### ISSUE THREAD

**Issue by nulloa** [ropensci/drake#349]
I setup up my drake script originally before the major update so there are some functions I need to update, but my main problem is this: each target I have takes a while to run (25-35hrs each) and the cluster has a 70 hr per job limit, so one run won't finish all the targets. Is there any way to have drake just pick up where it left off; so like it can check to see which targets it's finished and run the remaining ones?

I've tried simply resubmitting the original R script, but nothing happens I think because nothing has been changed from the last time. I looked through the examples but I didn't see anything that matched my needs.

Hopefully that make sense?

Any pointers on this would be great. Also this is referencing code from my [functform](https://github.com/nulloa/functform) package.

```
library(drake)
library(functform)
require(dplyr)

prepare_data <- function(season=NULL, forecast_week=0){
  source('../../CreateCDCDF.R', echo=TRUE)
 
  # Set up the data
  df <- get_cdc_data(year=season)
 
  df <- rbind(subset(df, Year!=paste(tail(season, 1))),
              subset(df, Year==paste(tail(season, 1)) & WEEK <= forecast_week))
 
  dat = list(x = df$WEEK, k = 6, num = df$TotPat, y = df$TotILI, group = as.numeric(substr(df$REGION, 8,9)),
             og_group = df$REGION, nG = length(unique(df$REGION)), n = nrow(df), seas = as.numeric(df$Season),
             og_seas = df$Season, nS = length(unique(df$Season))
             )
 
  priors = list(mu0 = c(0,0,2,15,2,2), # c(b1, b2, nu, mu, ls1, ls2)
                C0 = diag(c(1, 1, .75, 2, .5, .5)) # Prior sd for MVN on mu0
                )
 
  opts <- asg_mle(dat$y, dat$x, dat$num, dat$group, dat$seas)
  initf <- function() {list(ctheta = opts)}

 
  d <- list(dat=dat, priors=priors, inits=initf)
  return(d)
}



datasets <- plan(OG   = prepare_data(season=c(2006:2007, 2010:2016), forecast_week=0),
                 FC3  = prepare_data(season=c(2006:2007, 2010:2016), forecast_week=3),
                 FC10 = prepare_data(season=c(2006:2007, 2010:2016), forecast_week=10),
                 FC20 = prepare_data(season=c(2006:2007, 2010:2016), forecast_week=20))

make(datasets)

methods <- plan(ASG_Common    = drake_mcmc(..dataset.., iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_common"),
                ASG_Indep     = drake_mcmc(..dataset.., iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_indep"),
                ASG_Simple_CS = drake_mcmc(..dataset.., iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_simple_cs"),
                ASG_Simple_SC = drake_mcmc(..dataset.., iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_simple_sc"),
                ASG_Group_CS  = drake_mcmc(..dataset.., iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_group_cs"),
                ASG_Group_SC  = drake_mcmc(..dataset.., iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_group_sc"),
                ASG_Mix       = drake_mcmc(..dataset.., iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_mix"),
                ASG_Mix2      = drake_mcmc(..dataset.., iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_mix2")
)

analyses <- analyses(methods,datasets)
print(analyses)
make(analyses, jobs=16)

```

**Comment by wlandau** [comment]
> my main problem is this: each target I have takes a while to run (25-35hrs each) and the cluster has a 70 hr per job limit, so one run won't finish all the targets.

We can definitely work with that. I recommend `drake`'s `"future"` backend, which can build each target in its own separate job on the cluster of your choice. Essentially, `drake`, talks to [`future`](https://github.com/HenrikBengtsson/future), which talks to [`batchtools`](https://github.com/mllg/batchtools). [`batchtools`](https://github.com/mllg/batchtools) uses *.tmpl files to talk to SLURM. The code below sets up a `batchtools.slurm.tmpl` file for a [SLURM](https://slurm.schedmd.com/) cluster and then deploys the targets. You may need to manually edit `batchtools.slurm.tmpl` to maximize the wall time, adjust the memory, request a specific type of node, etc.

```r
library(future.batchtools)
drake_batchtools_tmpl_file("slurm")
future::plan(batchtools_slurm, template = "batchtools.slurm.tmpl")
make(whole_plan, parallelism = "future", jobs = c(imports = 4, targets = 16))
```

where `whole_plan` is just `rbind(datasets, analyses)`. When you run your script containing `make()`, it should be in a background process on the login node rather than a 70-hour job on one of the compute nodes.

> Is there any way to have drake just pick up where it left off; so like it can check to see which targets it's finished and run the remaining ones?

This is exactly what `drake` is designed to do: skip work that you do not need to repeat.

> I've tried simply resubmitting the original R script, but nothing happens I think because nothing has been changed from the last time. 

If you want to restart from scratch, you can run `clean()` or `clean(destroy = TRUE)` to invalidate all the targets.

Does all this answer your questions?

**Comment by wlandau** [comment]
For completeness, here are my comments on the code you posted.

```r
library(drake)
library(functform)
library(dplyr)

# To embrace the glorious new file API
# (with file_in(), file_out(), and knitr_in())
# always set the `strings_in_dots` argument of drake_plan() to "literals".
default::default(drake_plan) <- list(strings_in_dots = "literals")

prepare_data <- function(season=NULL, forecast_week=0){
  # Is CreateCDCDF.R inside your project?
  # I am not sure how well this bodes for reproducibility.
  source('../../CreateCDCDF.R', echo=TRUE)

  # Set up the data
  # I assume get_cdc_data() is defined in CreateCDCDF.R.
  df <- get_cdc_data(year=season)

  df <- rbind(subset(df, Year!=paste(tail(season, 1))),
              subset(df, Year==paste(tail(season, 1)) & WEEK <= forecast_week))

  dat = list(x = df$WEEK, k = 6, num = df$TotPat, y = df$TotILI, group = as.numeric(substr(df$REGION, 8,9)),
             og_group = df$REGION, nG = length(unique(df$REGION)), n = nrow(df), seas = as.numeric(df$Season),
             og_seas = df$Season, nS = length(unique(df$Season))
  )

  priors = list(mu0 = c(0,0,2,15,2,2), # c(b1, b2, nu, mu, ls1, ls2)
                C0 = diag(c(1, 1, .75, 2, .5, .5)) # Prior sd for MVN on mu0
  )

  opts <- asg_mle(dat$y, dat$x, dat$num, dat$group, dat$seas)
  initf <- function() {list(ctheta = opts)}

  d <- list(dat=dat, priors=priors, inits=initf)
  return(d)
}

# plan() is deprecated in favor of drake_plan()
datasets <- drake_plan(
  OG   = prepare_data(season=c(2006:2007, 2010:2016), forecast_week=0),
  FC3  = prepare_data(season=c(2006:2007, 2010:2016), forecast_week=3),
  FC10 = prepare_data(season=c(2006:2007, 2010:2016), forecast_week=10),
  FC20 = prepare_data(season=c(2006:2007, 2010:2016), forecast_week=20)
)

# ..dataset.. is deprectaed in favor of dataset__
methods <- drake_plan(
  ASG_Common    = drake_mcmc(dataset__, iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_common"),
  ASG_Indep     = drake_mcmc(dataset__, iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_indep"),
  ASG_Simple_CS = drake_mcmc(dataset__, iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_simple_cs"),
  ASG_Simple_SC = drake_mcmc(dataset__, iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_simple_sc"),
  ASG_Group_CS  = drake_mcmc(dataset__, iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_group_cs"),
  ASG_Group_SC  = drake_mcmc(dataset__, iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_group_sc"),
  ASG_Mix       = drake_mcmc(dataset__, iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_mix"),
  ASG_Mix2      = drake_mcmc(dataset__, iter=5000, warmup=3000, thin=1, chains = 1, whichmodel="asg_mix2")
)

# analyses() is deprecated in favor of plan_analyses().
analyses <- plan_analyses(methods, datasets)

# Better to combine the datasets and analyses in a larger plan.
whole_plan <- rbind(datasets, analyses)

# Your dependency graph looks good.
config <- drake_config(whole_plan)
vis_drake_graph(config)

# I think it may be safer to use `whole_plan` and the `targets`
# argument to make just the datasets
make(whole_plan, targets = datasets$target)

# Then, you can deploy the time-consuming analyses to the SLURM cluster.
# Similar to drake_example("slurm"): https://github.com/ropensci/drake/tree/master/inst/examples/slurm
# but with the new "future" backend (better scheduling algorithm than "future_lapply")
library(future.batchtools)
drake_batchtools_tmpl_file("slurm") # You will need to adjust the settings for Iowa State's configuration.
future::plan(batchtools_slurm, template = "batchtools.slurm.tmpl")
make(whole_plan, parallelism = "future", jobs = c(imports = 4, targets = 16))

```

**Comment by wlandau** [comment]
It could have something to do with getting set up with the cluster. I am not sure, but I can think of a few things to try. First of all, what about `future`s without `drake`?

```r
library(future.batchtools)
drake_batchtools_tmpl_file("slurm")
future::plan(batchtools_slurm, template = "batchtools.slurm.tmpl")
f <- future(1 + 2) # Should run as a SLURM job
value(f)
## 3
```

Also, how about the smaller example from `drake_example("slurm")` (also [here](https://github.com/ropensci/drake/tree/master/inst/examples/slurm)). I would try both `make(parallelism = "future_lapply")` and `make(parallelism = "future")`. `"future_lapply"` is a less efficient backend, but it has been around longer.

**Comment by nulloa** [comment]
Hi Will,

I used the above code to get it up and running on the server and it runs well! Thanks so much. 

I am running into an issue though which is the job running in the background only runs so long (about ~8hrs) so it gets terminated.  This is the output:

```
fail ASG_Simple_CS_FC3
Error: Target `ASG_Simple_CS_FC3`` failed. Call `diagnose(ASG_Simple_CS_FC3)` for details. Error message:
  Worker terminated unexpectedly before the target could complete. Is something wrong with your system or job scheduler?
Execution halted
Warning message:
In delete.BatchtoolsFuture(future, onRunning = "skip", onMissing = "ignore",  :
  Will not remove batchtools registry, because the status of the batchtools was ‘defined’, ‘error’, ‘running’, ‘started’, ‘submitted’, ‘system’ and option 'future.delete' is FALSE or running in an interactive session: ‘/home/nulloa1/ServerScripts/R/MultiScriptsStanForecasting/Drake/.future/20180406_213045-TBu1Co/batchtools_1589679195’
```

So, I tried to setup another script which simply loads in the drake files, makes the plan, and runs it but I'm having issues.

```
library(drake)
library(functform)
library(dplyr)

# Load in previous results
loadd()

# Remake plan to check what needs to be run
make(whole_plan, targets = datasets$target)

# Redo setup for parallel
library(future.batchtools)
# drake_batchtools_tmpl_file("slurm") # WL: you will need to adjust the settings for Iowa State's configuration.
future::plan(batchtools_slurm, template = "batchtools.slurm.tmpl")
make(whole_plan, parallelism = "future", jobs = c(imports = 4, targets = 12))
```


It seems that I didn't tell drake to save ```my_plan``` so I'm at a loss for what to do now? Do I simply rerun the original script above until all targets are finished?

```
> ls()
 [1] "ASG_Common_OG"     "ASG_Indep_OG"      "ASG_Mix2_OG"      
 [4] "ASG_Mix_OG"        "ASG_Simple_CS_OG"  "ASG_Simple_SC_FC3"
 [7] "FC10"              "FC20"              "FC3"              
[10] "get_cdc_data"      "OG"                "prepare_data" 
```

**Comment by wlandau** [comment]
The IA State clusters previously had problems with `make(parallelism = "Makefile", prepend = "SHELL=srun")`, so I am glad `parallelism = "future"` is better.

I recommend regenerating `whole_plan` before running `make()` in your code. Each of the [pedagogical examples](https://github.com/ropensci/drake/tree/master/inst/examples#learn-how-to-use-drake) follows this approach.

As for the long background job on the login node, I am not sure exactly what to do. You could talk to the sys admin and see if you can extend the limit for jobs with a sufficient niceness (`nohup nice -19 ...`). Alternatively, maybe SLURM can submit jobs from compute nodes, or you could configure your `*.tmpl` in a way that lets you run `make()` on your local machine and submit jobs via `ssh`. If each target built faster than 8 hours, the easiest solution would be to resubmit `nohup nice -19 R CMD BATCH make.R &` on the login node every 8 hours using [cron/crontab](https://kvz.io/blog/2007/07/29/schedule-tasks-on-linux-using-crontab/), but I think your targets take to long for that. Sorry I could not be of more help. Please let me know what works.

**Comment by wlandau** [comment]
Sure, and thanks for the update. In examples like [this basic one](https://github.com/ropensci/drake/tree/master/inst/examples/basic), there is a separate [`plan.R` script](https://github.com/ropensci/drake/blob/master/inst/examples/basic/R/plan.R) that makes the workflow plan. In this case, the master script is [`make.R`](https://github.com/ropensci/drake/blob/master/inst/examples/basic/make.R), which runs [`plan.R` script](https://github.com/ropensci/drake/blob/master/inst/examples/basic/R/plan.R) to set up the plan before calling `make()`. In your own code, you might do something like this.

```r
library(drake)
library(functform)
library(dplyr)

# You don't actually need to load the previous results.
# For each target, drake detects what it needs to load with prune_envir():
# https://github.com/ropensci/drake/blob/a09880ec3976685c7481143f21d5049523730b9b/R/envir.R#L26
# loadd()

# Construct the plan.
datasets <- drake_plan(
  OG   = prepare_data(season=c(2006:2007, 2010:2016), forecast_week=0),
  FC3  = prepare_data(season=c(2006:2007, 2010:2016), forecast_week=3),
  FC10 = prepare_data(season=c(2006:2007, 2010:2016), forecast_week=10),
  FC20 = prepare_data(season=c(2006:2007, 2010:2016), forecast_week=20)
)
...
whole_plan <- rbind(datasets, analyses)

# Run the workflow.
make(whole_plan, targets = datasets$target)
library(future.batchtools)
# drake_batchtools_tmpl_file("slurm")
future::plan(batchtools_slurm, template = "batchtools.slurm.tmpl")
make(whole_plan, parallelism = "future", jobs = c(imports = 4, targets = 12))
```

Does that help?

Also, what about that long-running master process? Did you find a way to get it to run for more than 8 hours?

**Comment by nulloa** [comment]
OK this makes sense. This is basically what I was doing. Thanks!

I didn't find a way to get it running for over 12 hours. What I was doing was simply reruning the 
`nohup ...` command every so often after checking that previous jobs were finished. 

I've been busy with other things as the semester is winding down, but I'm hoping to talk with the administrator about submitting jobs from the SLURM queue. That'll be a summer tackle hopefully.

Thanks for all the help Will! Also looking forward to checking out the new basic example.

**Comment by wlandau** [comment]
Glad to hear `drake` plans make more sense. I am curious to hear the verdict on the master process. I think you have a solid case for jobs submitted with `nice -19`.
