### ISSUE TITLE
make from a partially exported cache

### ISSUE THREAD

**Issue by ruaridhw** [ropensci/drake#355]
Firstly, love this package! It has undoubtably filled a gap in the rmarkdown toolchain 🎉  

I had a couple of questions/feature-requests regarding a use-case...

Say I have a plan which builds a number of models (say a hundred targets) and then one post-processing target `model_res` which reconciles the relevant results from these models and solely feeds into the `report.Rmd` target.

My idea is to submit the model building stage to the HPC cluster, share the results to collaborators and each work on the report using `model_res` only.

1. To export/share the results is the best way going to require committing `./.drake` to git? Either by committing all the cache files or a singular zip file.
2. Is there a way for `drake` to only need `model_res` present when building `report.Rmd`? ie. None of the (supposedly large file size) upstream model targets are present but it is still possible to `rmarkdown::render` the report. I could redefine the plan locally to only `make report.Rmd` but wouldn't this invalidate the cache?

Thanks again!

**Comment by wlandau** [comment]
Thanks for the encouragement, Ruaridh! I think `drake` can do what you need. Let's take an oversimplified workflow to answer your second question first.

```r
library(drake)

model <- function(args){
  # Fit a model
}

post_process <- function(...){
  # do some post-processing
}

model_plan <- drake_plan(
  model1 = model(1),
  model2 = model(2),
  model_res = post_process(model1, model2),
  knit(knitr_in("report.Rmd"), file_out("report.md"))
)
model_plan
#> # A tibble: 4 x 2
#>   target          command                                                 
#>   <chr>           <chr>                                                   
#> 1 model1          model(1)                                                
#> 2 model2          model(2)                                                
#> 3 model_res       post_process(model1, model2)                            
#> 4 "\"report.md\"" "knit(knitr_in(\"report.Rmd\"), file_out(\"report.md\")…

config <- drake_config(model_plan)
vis_drake_graph(config)
```

![graph](https://user-images.githubusercontent.com/1580860/38322820-7d339854-3809-11e8-98e6-08af092e4e69.PNG)

From the graph, `report.md` only has `"report.Rmd"` and `model_res` as adjacent dependencies, not `model1` or `model2`. When you write `knitr_in("report.Rmd")` in the command, you tell `drake` to treat `"report.Rmd"` as a dependency and any objects you load with `loadd()` or `readd()` in the active code chunks. Here is what `report.Rmd` looks like. `model_res` is loaded in a code chunk, but not `model1` or `model2`. 

<pre><code>
---
title: "Results report"
author: You
output: html_document
---

# Results

```{r model_res}
library(drake)
readd(model_res)
```
</code></pre>

That way, reports can be run either with `drake::make()` or with `knitr`/`rmarkdown` after a `make()`. In the latter case, you only need `model_res` to be in the cache.

Also, if you want to only make certain targets, you can run `make(plan, targets = file_store("report.Rmd"))` or `make(plan, targets = c("model1", "model_res"))`. This approach builds everything upstream too. If you want to just build a target without worrying about upstream dependencies, see `drake_build()`.

Regarding your first question, this is the first time I have heard someone suggest a partially exported cache. Unfortunately, there are still unresolved issues about sharing `storr` caches like the one `drake` uses (https://github.com/richfitz/storr/issues/55, https://github.com/ropensci/drake/issues/198, https://github.com/ropensci/drake/issues/322). Committing the cache to `git` may require you to modify `.drake/.gitigore`, and your repository would be cluttered with a lot of tiny cache files, but I think it would help prevent your cache from getting corrupted in an archiving process. If you want to lighten the cache, you could clean some elements out first (`drake::clean(model1, model2)`).

**Comment by ruaridhw** [comment]
Yes, it certainly does.

If there are known issues with `storr`'s compatibility with compression then it sounds like an ugly git diff is the way to go. I guess this won't be quite as bad if I duplicate the cache, clean everything except `model_res` and then commit.

Ah, I was looking for `drake_build()`! (I would want to *avoid* building anything upstream of `model_res`). I also hadn't thought that `rmarkdown::render()` by itself would work but that makes obvious sense.

**Comment by wlandau** [comment]
Glad to hear it! Hopefully we can make `storr`s more portable going forward.
