### ISSUE TITLE
CRAN check errors in drake 5.1.0

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#356]
A bunch of [CRAN check errors](https://cran.r-project.org/web/checks/check_results_drake.html) just started showing up. This is a couple weeks after the release of both `drake` 5.1.0 and R 3.5.0. The Solaris error happened because a parallel socket cluster crashed (`make(parallelism = "parLapply", jobs = 2)`), which is rare and not `drake`'s fault. But the Linux R-devel errors are from the failure of [this little unit test](https://github.com/ropensci/drake/blob/7c67f802601dadeb39c4e1a1938d60a5867ef3ff/tests/testthat/test-tidy-eval.R#L18) of #200. I am trying to reproduce and fix the tidy eval error. It may be time for an quick CRAN patch.

**Comment by wlandau** [comment]
I see `dplyr` is getting [similar CRAN errors](https://cran.r-project.org/web/checks/check_results_dplyr.html) that also have to do with the use of tidy eval's `!!` operator. @krlmlr, if you have the chance, it would be great to know how this is solved in `dplyr`'s case.

I am checking the package with win-builder, and the unit tests run fine for 3.3.3 and 3.4.4. It is worth mentioning that 3.4.4 could not build the pdf manual, an error that did not show up anywhere else. I hope this is all because CRAN is having trouble updating to 3.5.0 and that this will all blow over.

**Comment by wlandau** [comment]
From @lionel-, these errors are happening for the best possible reason:

> Deparsing of !! is now fixed in R 3.5.0, i.e. !!x is now deparsed to "!!x" instead of "!(!x)". Using deparse makes unit tests dependent on the way R formats deparsed expressions and so may be brittle.

It should not be hard to fix the test.

**Comment by wlandau** [comment]
I reproduced the error, and I repaired the test in 96cfc07fda2381215c04d67b426d76fc64d32a27. I plan to submit a CRAN patch this week with the fix.

**Comment by wlandau** [comment]
Update: the test is fixed in 5c11b8554ceb1543d6eb41319fdbe7f795d03d8a. Will upload to CRAN when I finish testing/checking.

**Comment by wlandau** [comment]
Update: my usual long test suite passed (unit tests for all forms of parallelism on Linux and Windows, unit tests with global and local environments, real projects, win-builder, linting, spelling, coverage, `goodpractice`, etc.). I just submitted 5.1.2 to CRAN. I will close this issue if/when accepted. (CRAN package reviews have recently become more strict than in the past.)

**Comment by wlandau** [comment]
I see `drake` 5.1.2 on CRAN. closing.

**Comment by lionel-** [comment]
That was quick :-)
