### ISSUE TITLE
Detect duplicates in bind_plans()

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#361]
``` r
library(drake)
bind_plans(
  drake_plan(d = f(c, b)),
  drake_plan(c = f(a), a = 5),
  drake_plan(b = f(a), a = 5)
)
#> # A tibble: 5 x 2
#>   target command
#>   <chr>  <chr>  
#> 1 d      f(c, b)
#> 2 c      f(a)   
#> 3 a      5      
#> 4 b      f(a)   
#> 5 a      5
bind_plans(
  drake_plan(a = 3), drake_plan(a = 5)
)
#> # A tibble: 2 x 2
#>   target command
#>   <chr>  <chr>  
#> 1 a      3      
#> 2 a      5
```

> Created on 2018-04-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

The first case is useful if several plans inherit a common base plan and are then combined. Duplicate rows should just be removed. The second case should trigger an error.

**Comment by wlandau** [comment]
Good point. I am about to push a fix that also adds the analogous behavior to `drake_plan()`.

**Comment by krlmlr** [comment]
Thanks for the very quick fix!
