### ISSUE TITLE
Package dependencies

### ISSUE THREAD

**Issue by ldecicco-USGS** [ropensci/drake#362]
Sorry if this is answered somewhere else, I searched but maybe missed it. Can `drake` track R package versions? IE...could I pass my drake workflow to a collaborator and somehow easily have them run a function that would check for the existence of all the required packages? (and install? update or revert to an older version?)

Maybe another way to ask...does `drake` managed and save "project metadata" like the package versions and where they came from (ie..github/CRAN/etc). This would go a long way in reproduciblity.

**Comment by wlandau** [comment]
For metadata, `drake` does save the `sessionInfo()` of the last `make()`, and you can retrieve it from the cache using `drake_session()`. Package management in general is unfortunately beyond the scope of `drake`. There was a discussion in #6 (deeply buried, I know), but diving into package dependencies seemed to just make pipelines more brittle (prone to triggering updates), and `drake` already tries to do a lot as it is. I ended up deciding to promote `packrat` and containerization (Docker or Singularity) instead.
