### ISSUE TITLE
Export dependencies()?

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#363]
That seems to be the easiest way for a user to understand what a target depends on, another one (much less comfortable) being `dependency_profile(...)$hashes_of_dependencies`. What am I missing?

**Comment by wlandau** [comment]
Does [deps()](https://ropensci.github.io/drake/reference/deps.html) cover what you are thinking? If not, we can think about exporting more functionality.

**Comment by krlmlr** [comment]
`deps()` operates on expressions, `drake:::dependencies()` expects a target name and also returns a vector of target names.

**Comment by wlandau** [comment]
In that case, I think we should try to make this part of the API clean and consistent. It may be confusing to have one user-side function called `deps()` and another called `dependencies()`. Maybe we could add `target` and `graph` arguments to `deps()` and have `deps()` call `dependencies()` on those objects. Or we could rename both functions to make it clear that one expects expressions and the other expects target names.

**Comment by krlmlr** [comment]
How about something like `unbound_symbols()` instead of `deps()`? Do we use the term "prerequisites" at all?

**Comment by wlandau** [comment]
Hmm... I like prerequisites more than `unbound_symbols()`. Now that you have reminded me of this issue, what about `deps_code()` and `deps_target()`? The latter could be a thin wrapper around the existing `dependencies()`.

**Comment by wlandau** [comment]
As of da97e6e74d8e841a16c17a261c971e80fa01a94c, `drake` has `deps_targets()`, which does what I think you need.

**Comment by krlmlr** [comment]
Looks good, thanks!
