### ISSUE TITLE
AppVeyor CI disconnected

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#365]
At some point, AppVeyor stopped receiving new commits.

![hooks](https://user-images.githubusercontent.com/1580860/39127750-efaf0a3e-46d3-11e8-8df4-9abd11ead7ab.png)

I would like to diagnose, but I cannot view the [AppVeyor settings](https://ci.appveyor.com/project/ropensci/drake/settings).

![settings](https://user-images.githubusercontent.com/1580860/39127763-fa271aa6-46d3-11e8-81bf-2c0707e3694a.PNG)

@maelle, as the onboarding editor, do you have the ability to grant me access?

**Comment by maelle** [comment]
looking right now, weird, thx for the report

**Comment by maelle** [comment]
this is the webhook URL I see in Appveyor as well so I'm at a loss.

@sckott have similar things happened in the past?

**Comment by maelle** [comment]
![image](https://user-images.githubusercontent.com/8360597/39128293-b85e3846-4707-11e8-8867-a108ecff0e43.png)

@wlandau do you see any pattern in the ones that got a 500 vs a 204 response?

**Comment by maelle** [comment]
now wondering whether this repo is too active for Appveyor :joy:

**Comment by maelle** [comment]
I am also unable to trigger a new build by clicking on new build, it says "There was an error while trying to complete the current operation. Please contact AppVeyor support." 🤔

**Comment by wlandau** [comment]
The deliveries with 204 responses seem to be for pull requests, and the 500 ones seem to be for individual commits.

> now wondering whether this repo is too active for Appveyor

That's encouraging! I am doing my best to keep it active, though lately it has been hard to find enough uninterrupted time to work on the really big issues.

Anyway, thanks for trying. I thought there might be some setting that only you had access to. I suppose this really is a job for AppVeyor support.

**Comment by maelle** [comment]
Yep I think you should ask them. If you open an issue/send an email please @/cc me :-)

and good job on making this repo so active, even if you have less time!

**Comment by sckott** [comment]
looks like there's a new one with one triggered event so far

<img width="759" alt="screen shot 2018-04-23 at 9 13 44 am" src="https://user-images.githubusercontent.com/577668/39139395-aaba846e-46d6-11e8-9b18-d7c8fabbd411.png">

is it sorted out?  we can just delete the old one if the new one is working

**Comment by wlandau** [comment]
Looks like we do have a new webhook and AppVeyor builds are running normally again. I just deleted the old one. Thank you both.
