### ISSUE TITLE
p

### ISSUE THREAD

**Issue by Radibor** [ropensci/drake#389]
# Code of Conduct

You must obey this repository's [code of conduct](https://github.com/ropensci/drake/blob/master/CONDUCT.md), as must everyone who responds to you on the issue tracker.

# Before posting

Please search the [known issues](https://github.com/ropensci/drake/issues), both open and closed, including the [frequently-asked questions](https://github.com/ropensci/drake/issues?q=is%3Aissue+is%3Aopen+label%3A%22Frequently+Asked+Question%22). The articles on [cautionary notes and edge cases](https://ropensci.github.io/drake/articles/caution.html) and [debugging and testing drake projects](https://ropensci.github.io/drake/articles/debug.html) may also answer your questions.

When you post, please include a minimal reproducible example of the problem and/or desired behavior, if applicable. The [`reprex` package](https://github.com/tidyverse/reprex) package is particularly nice for this.

Also, good style really helps others read the code you share. The [tidyverse style guide](http://style.tidyverse.org/) has suggestions, the [`styler` package](http://styler.r-lib.org/) is a great way to clean up your code automatically, and the [`lintr` package](https://github.com/jimhester/lintr) checks for style issues.

**Comment by wlandau** [comment]
Blank issue. Closing.
