### ISSUE TITLE
Faster remote/distributed persistent workers

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#417]
Currently, `drake` can deploy remote persistent workers with a `future.batchtools` backend and `make(parallelism = "future_lapply")`. But from #416, `drake`'s current reliance on the file system may slow the code that schedules the targets.

1. A non-file-based message queue. `rzmq` is a good place to start, and I am already starting to climb the learning curve. Low-level TCP/IP sockets may also be worth pursuing if we can get different nodes to talk to each other. Thanks @clarkfitzg for your help on this so far.
2. A way to guarantee that all the files in the cache are synced before new targets begin building. We may be able to take advantage of the file polling mechanism in `batchtools` for this, or even just rely on the job dependency functionality already built into HPC systems. Possibly helpful: https://github.com/mllg/batchtools/issues/187, https://github.com/mllg/batchtools/issues/190.

Alternatively, `future_lapply` parallelism may not be the answer. As a colleague said to me today, this general problem is already solved. We may be able to use an existing generalized task scheduler or message broker, and the right direction may be to add more parallel backends.

In any case, I need to learn more and develop my skills before I can contribute to a solution. I expect this to be a long-term effort, and I do not want it to get in the way of the usual development and release schedule. `drake` is less than two years old, and it is an incredibly ambitious project. It has a long way to go.

**Comment by clarkfitzg** [comment]
]Python's dask](https://dask.pydata.org/en/latest/) might provide some inspiration.

**Comment by wlandau** [comment]
For (1), there are a ton of great possibilities, including ZeroMQ. For (2),`make(parallelism = "future_lapply")` should be safer once I merge #419 because I make each worker send a checksum to tell what data the master should expect. Then, I make the master wait until the worker's checksum agrees with the cached data (or time out). Overall, there may be totally different approaches from to avoid the limitations of NFS-based clusters. Maybe we can work `dask` into a new parallel backend for `drake`.

**Comment by wlandau** [comment]
I just talked with a colleague who test drove ZeroMQ last year. For a large number of workers passing small messages on an SGE cluster, ZeroMQ apparently did not add much speed relative to file-based message passing. He thinks the file I/O latency SGE itself may be the bottleneck. This makes me think a higher-level third-party toolbox like `dask` may be of more immediate use to us than low-level sockets.

**Comment by wlandau** [comment]
Or maybe the solution is to go even lower-level and bypass schedulers altogether. I'm thinking ZeroMQ + complete IP/port/host information for all the workers = fast, responsive remote processes.

**Comment by clarkfitzg** [comment]
Then will drake manage scheduling and synchronization? You might be also able to build on an existing R worker daemon. The ones I've looked at in SNOW, Rmpi, and SparkR are pretty similar.

**Comment by wlandau** [comment]
If we continue to operate at a low level, yes. And as always, thanks for the references.

**Comment by wlandau** [comment]
I am starting to think #425 is worth a shot first. [`clustermq`](https://github.com/mschubert/clustermq) spins up cluster jobs super fast. It does not help with persistent workers, but maybe [`clustermq`](https://github.com/mschubert/clustermq)-based transient workers are the next thing worth trying.

**Comment by wlandau** [comment]
Just implemented #452, which gives us [staged scheduling](https://ropensci.org/technotes/2018/05/18/drake-hpc/#staged-scheduling) based on [`clustermq`](https://github.com/mschubert/clustermq). Overhead for remote workers is lower than I have ever seen, and I am convinced [`clustermq`](https://github.com/mschubert/clustermq) is the answer. Closing in favor of #425 and https://github.com/mschubert/clustermq/issues/86.

**Comment by wlandau** [comment]
Update: we should investigate RPC systems in general. Thanks @dpastoor for all the advice during [R/Pharma 2018](http://rinpharma.com/).

**Comment by dpastoor** [comment]
I think in general, from reviewing the previous discussion, the choice needs to be determined whether or not you want to play nicely with HPC systems that use schedulers. Namely, as your colleague noted, zeromq will not help when the bottleneck is not getting data to a worker process, but rather fighting with the overhead of a separate scheduler. An alternative is to provide a better mechanism to _chunk_ execution on workers. Eg rather than sumitting 100 individual tasks, submit 10 jobs that each run 10 tasks. This would reduce the overhead of assigning so many lightweight tasks, which the grid schedulers are not really designed to do efficiently.

On the flip side, if the objective is to provide a low latency system where you can _ignore_ the underlying scheduler, that is where you will get the performance benefits from either systems like clustermq or rpc style systems.

For example, schedule starting N server processes which will lock down those resources on the cluster, then execute your work across those.

**Comment by wlandau** [comment]
Absolutely. This is why I am interested in improving `drake`'s [persistent workers](https://ropenscilabs.github.io/drake-manual/hpc.html#persistent-scheduling), particularly via https://github.com/mschubert/clustermq/issues/86. It may be slow to submit workers to a scheduler initially, but if we only need to do that once, the rest of the work will not repeatedly incur this overhead. Of course, I am assuming those workers have long enough wall times, which may not be the case for restrictive clusters in an academic setting. That is where I think the chunk execution mechanism you mentioned could play a role.

As for bypassing the scheduler, this is something I have not investigated yet, and I am not sure how sysadmins would feel about it. But at my company, one of our internal job submission tools might actually do this. I will ask.
