### ISSUE TITLE
Fewer checks during busy waiting

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#422]
The current setting of `mc_wait` is too low to cause an effect on my system. A value of `1e-2` actually puts the workers and the master to sleep somewhat. (Also, `1e-9` is hard-coded in a few places.) This is a tradeoff between latency and idle check cycles, perhaps even make it an option?

``` r
microbenchmark::microbenchmark(
  Sys.sleep(1e-9),
  Sys.sleep(1e-3),
  Sys.sleep(1e-2),
  Sys.sleep(3e-2)
)
#> Unit: nanoseconds
#>              expr      min       lq        mean   median       uq      max
#>  Sys.sleep(1e-09)      825     4904    13193.93    13969    21431    25447
#>  Sys.sleep(0.001)  1057086  1121589  1163744.97  1143276  1199982  1377577
#>   Sys.sleep(0.01) 10055734 10117596 10208263.26 10151432 10316300 10420913
#>   Sys.sleep(0.03) 30061106 30136093 30234835.89 30226672 30357808 30404595
...
```

> Created on 2018-06-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

It might be easier if _fs_ exposed the wrappers around inotify and friends that libuv seems to provide.

**Comment by wlandau** [comment]
I changed `mc_wait` to `0.01` (and fixed the hard-coded references to `1e-9`) and I did not notice a loss in performance. I think `mc_wait` could definitely be a user-side option in later releases.
