### ISSUE TITLE
Consider being more selective in `save()` in `prepare_distributed` in `run_future_lapply`

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#436]
`prepare_distributed` contains the following call to `save` which is quite a bottleneck:

```r
save(
    list = ls(globalenv(), all.names = TRUE),
    envir = globalenv(),
    file = globalenv_file(config$cache_path)
  )
```
Is it possible to refine this so that it only saves the items that are needed to build the targets to be made? This also seems unnecessary for many types of futures and seems to be replicating a function of the `future` package itself, which is really good at sending objects around different processes.

**Comment by wlandau** [comment]
We mostly need `save()` for `Makefile` parallelism. I think we can get away with just saving the imports. We can probably also suppress it altogether for `"future"` parallelism.

**Comment by wlandau** [comment]
I would prefer to handle this one after #440, specifically https://github.com/ropensci/drake/issues/440#issuecomment-401511564.

**Comment by wlandau** [comment]
f247d27bf31eb18fce0bccdb00a637fcd360c757 excludes targets in the plan from being saved. That is the best I can do safely.
