### ISSUE TITLE
why rbuildignore news.md?

### ISSUE THREAD

**Issue by sckott** [ropensci/drake#447]
howdy. curious why news.md is here https://github.com/ropensci/drake/blob/master/.Rbuildignore#L21

because then it doesn't show up on cran landing page https://cran.r-project.org/web/packages/drake/

**Comment by wlandau** [comment]
Thanks, Scott. I had added `NEWS.md` to `.Rbuildignore` back when I did not know a top-level `NEWS.md` file was acceptable for a package on CRAN.
