### ISSUE TITLE
Consider removing or optionalizing the gc() in this while loop

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#454]
It looks like the vast majority of the overhead time causing the problem in #449 is spent in this while loop:

https://github.com/ropensci/drake/blob/master/R/mclapply.R#L75-L78

If I remove the `gc()` I see substantial speed improvements, though the master process certainly still can't keep up with the workers for the up-to-date targets which obviously process fast. A better solution would be to do a round of preprocessing targets using the same strategy as `outdated` so that the first round of targets sent in `fl_master` are out-of-date.

**Comment by wlandau** [comment]
cc @krlmlr. Ref: [comment](https://github.com/ropensci/drake/pull/429/files/8d0d2ac8d9e247db993152b53b9993c1e032fecd#r197463432), #428, #429. Looks like we should use `gc()` more sparingly.

**Comment by wlandau** [comment]
And since persistent workers check if targets can be skipped, this may be yet another issue solved with #440.

**Comment by wlandau** [comment]
In de5835f3135e700c65bdf61862303a5236ec7adc, `drake` calls `gc()` after each target build and on exit. Please see how it works for you. We can always elect to call `gc()` less often, but I think de5835f3135e700c65bdf61862303a5236ec7adc may strike a nice compromise.

**Comment by kendonB** [comment]
https://github.com/ropensci/drake/commit/de5835f3135e700c65bdf61862303a5236ec7adc is going to be even worse as it will call gc() for every up-to-date target.

**Comment by wlandau** [comment]
Then 20026537bcd0dbf1d4718f44637b6d693e5f41bb should be an improvement.

**Comment by kendonB** [comment]
Big improvements with [2002653](https://github.com/ropensci/drake/commit/20026537bcd0dbf1d4718f44637b6d693e5f41bb) using future_lapply. Still took 13 mins to start building targets as opposed to the minute or so it takes to start using staged parallelism so there's still plenty to gain from a preprocessing stage using lighter parallelism. Much faster than the literal hours is was taking a couple of nights ago.
