### ISSUE TITLE
reinstate future_lapply_staged?

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#456]
This worked quite well before for the large project I was doing in December that nicely fit into stages. The projects are data-large but not conceptually large. The December project was 7 stages broken into ~30000 targets and the one I'm working on now is 3 stages broken into ~30000 targets. Many "big-data" projects follow a similar pattern.

I've gone through each of `future`, (new) `future_lapply`, and `clustermq_staged` and they all seem to struggle with these large staged projects.

**Comment by wlandau** [comment]
See #450.

**Comment by kendonB** [comment]
Sorry I missed that!
