### ISSUE TITLE
possible new bug in make_targets

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#460]
Do you have ideas for an MWE for this possible bug in `make_targets`?
```
debug: config$schedule <- targets_graph(config = config) %>% igraph::delete_vertices(v = up_to_date)
# running this line:
Error in as.igraph.vs(graph, v) : Invalid vertex names
```

**Comment by kendonB** [comment]
Tests all pass so I wonder if it's due to the size of the plan (~130000)

**Comment by wlandau** [comment]
Did you set `igraph_opt("return.vs.es")` to `FALSE` re https://github.com/ropensci/drake/issues/435#issuecomment-402555943? Also, did you supply a `graph` argument manually?

**Comment by wlandau** [comment]
Also, do you use the `targets` argument of `make()`. That may be why, in which case it is a bug.

**Comment by wlandau** [comment]
Yup, it's a bug when you supply `targets`. When you do that, not all the targets are in the graph.

```r
library(drake)
plan <- drake_plan(a = 1, b = a, c = b)
config <- drake_config(plan, targets = "b")
make_targets(config)
#> Error in as.igraph.vs(graph, v): Invalid vertex names
```

Will fix soon.
