### ISSUE TITLE
knitr_in() gives warning message for Rmd files without code chunks

### ISSUE THREAD

**Issue by lorenzwalthert** [ropensci/drake#470]
I created a Rmd file without code chunks (see below) and used `knit_in()` with `rmarkdown::render()` which gives me this warning, which looks more like a parsing error.
```r
library(drake)
library(magrittr)
drake_plan(
  report =rmarkdown::render(
    input = knitr_in("test-rmd.Rmd"),
    output_format = "all",
    quiet = TRUE, clean = FALSE, 
  ),
    strings_in_dots = "literals"
) %>%
  make()
Warning messages:
1: In value[[3L]](cond) :
  Could not parse file 'test-rmd.Rmd'. Drake dependencies could not be extracted from code chunks: <text>:10:6: unexpected symbol
9: 
10: text jhafsd
         ^
2: In value[[3L]](cond) :
  Could not parse file 'test-rmd.Rmd'. Drake dependencies could not be extracted from code chunks: <text>:10:6: unexpected symbol
9: 
10: text jhafsd
```

The reason I'd like to use `knit_in()` for files that don't have drake dependencies is that I created targets with `evaluate_plan()` for *all* my Rmd reports which live in a certain folder and I don't want to manually specify which need `knit_in()` and which don't. Can we drop the warning if there are no code chunks or no code chunks contain `loadd` or `readd` statements or at least make it more informative. I was just a bit irritated by the parsing error as it seemed as drake wanted to parse plain text.

The Rmd looked like this:

```
---
title: "EDA Results"
output:
  github_document: default
  html_document:
    toc: true
    toc_float: true
---

text jhafsd fjha lej hadlkjf
```

**Comment by wlandau** [comment]
Thanks for letting me know. Definitely a reasonable use case. I never intended dependency detection to fail for codeless `knitr` reports. Will push a fix soon.

`drake` uses `knit(tangle = TRUE)` to extract R code from `knitr` reports. To tangle without writing files, I originally copied `CodeDepends`:

https://github.com/duncantl/CodeDepends/blob/224dc60d7b47ecebba5b4159ebb0cdc52a8bdf04/R/sweave.R#L15-L30

But for codeless reports, `knitr::knit(in.con, output = out.con, tangle = TRUE)` just returns all the text in the report. I don't know why, but `knitr::knit("test-rmd.Rmd", output = out.con, tangle = TRUE)` seems to fix the problem, returning empty as expected.
