### ISSUE TITLE
Best practices for including a drake workflow in a package

### ISSUE THREAD

**Issue by tiernanmartin** [ropensci/drake#471]
I'm at the beginning stages of a new project and I'm considering whether to try using the package convention to organize it. I'd also like to use `drake` to manage a few data development workflows within the package, so now I'm wondering about the compatibility between `drake` and r packages.

Have you given this any thought? Any gotcha's that I should know about before I start down this path?

Thanks!

**Comment by wlandau** [comment]
Great question. I think the main gotchas are covered at https://ropenscilabs.github.io/drake-manual/best-practices.html#workflows-as-r-packages. Related: #243. Please let me know if you find others.

**Comment by tiernanmartin** [comment]
Great -- thanks for pointing me to the right part of the documentation!

**Comment by tiernanmartin** [comment]
Have you given any thought to the best practices for documenting a `drake` plan that is included in as a function within a package? 

Should we be wrapping `plan`s into functions at all? Or should they just exist as `.R` files that are made accessible through helper functions provided in the package?

**Comment by wlandau** [comment]
I like the idea of having a package function that generates the plan, documented and demonstrated with `roxygen2` according to the usual community standards. In my opinion, the further removed from `*.R` files, the better.

By the way, the manual is changing fast, and the original link has moved to https://ropenscilabs.github.io/drake-manual/organize.html#workflows-as-r-packages.

**Comment by tiernanmartin** [comment]
Thanks for the updated link.

I'm going to experiment with this. I am inspired by other project-as-package examples like Jason Fisher's [groundwater model ](http://jfisher-usgs.github.io/r/2016/08/04/wrv-case-study) and `drake` seems like an excellent way to implement a reproducible workflow within a package.

If I put together a example package built around a minimal `drake` workflow would you consider giving feedback on the package structure and documentation?

**Comment by wlandau** [comment]
Absolutely, I will eagerly review your package. It is exciting to learn that you are pursuing this. If/when you are ready to release it, could we showcase it in `drake`'s documentation?

**Comment by tiernanmartin** [comment]
Definitely.

My plan is to start with the workflow in the `main` example and modify it as necessary to illustrate the advantages and challenges of including it in a package. At this point I'm not sure what these modifications will entail, although I can already see that I should avoid using datasets like `iris` that exist in other packages.

I'll see what I come up with and share it once it's ready for feedback. 

Would you like me to continue using this issue for packaged-workflow -related questions or should I open individual issues?

**Comment by wlandau** [comment]
Sounds great! For the sake of easy lookup later on, I think I would prefer a bunch of individual issues.

**Comment by wlandau** [comment]
Of course, feel free to reference this one. In fact, I may comment with an index later on because this issue is in the FAQ.

**Comment by tiernanmartin** [comment]
@wlandau 

Alright I have taken a first pass at creating a packaged drake workflow: https://github.com/tiernanmartin/drakepkg

Full disclosure: I am not a package developer and have no clue what I'm doing.

As I said before, my main goal with this exercise was to see what stumbling blocks I ran into and spark a conversation about whether this is a good idea. If you decide it is useful enough to include in `drake`'s documentation that would be a great bonus.

I look forward to your feedback!
