### ISSUE TITLE
drake-manual, error returned in "main example"

### ISSUE THREAD

**Issue by drag05** [ropensci/drake#488]
drake-manual, the main example: `make(plan)` returns error. 

`diagnose(report)$error` 
<simpleError in plot_rmspe(rmspe = results): could not find function "plot_rmspe">`

Thank you!

**Comment by wlandau** [comment]
Thanks for the report, @drag05. Would you elaborate more on the specifics? It would really help to have some code that reproduces the error from a clean workspace and file system (related: [`reprex`](https://github.com/tidyverse/reprex)).

The `plot_rmspe()` function actually belongs to the [gross state product example](https://ropenscilabs.github.io/drake-manual/gsp.html). Did you run that one before trying the [main example](https://ropenscilabs.github.io/drake-manual/main.html)? `drake` uses a file system cache and looks for functions loaded into your workspace, so it helps to use a fresh session and working directory.

### Attempts to reproduce the error

I recompiled the manual, and both the [chapter on the main example in the manual](https://ropenscilabs.github.io/drake-manual/main.html) and the [chapter on the gross state product example](https://ropenscilabs.github.io/drake-manual/gsp.html) seem to have run fine.

The code for those examples is [available here](https://github.com/ropensci/drake/tree/master/inst/examples), and you can generate the files with `drake_example()`. Fresh copies of those examples seem to work.

``` r
drake::drake_example("main")
withr::with_dir("main", source("make.R"))
#> target raw_data
#> target data
#> target fit
#> target hist
#> target report
drake::drake_example("gsp")
withr::with_dir("gsp", source("make.R"))
#> target state_year_pcap
#> target state_year_hwy
#> ...
#> target rmspe_pc_emp_unemp
#> target rmspe
#> target plot
#> Saving 7 x 5 in image
#> Target plot messages:
#>   Saving 7 x 5 in image
#> target report
```

**Comment by wlandau** [comment]
Also, feel free to post issues to the [manual development page](https://github.com/ropenscilabs/drake-manual).

**Comment by wlandau** [comment]
Another thing to check: are you running the [main example](https://github.com/ropensci/drake/tree/master/inst/examples/main) using with the [`report.Rmd` file from the gsp example](https://github.com/ropensci/drake/blob/master/inst/examples/gsp/report.Rmd#results)? The [main example](https://github.com/ropensci/drake/tree/master/inst/examples/main) has its own [`report.Rmd` file](https://github.com/ropensci/drake/blob/master/inst/examples/main/report.Rmd).

**Comment by drag05** [comment]
Hello, 
While trying to answer your request, I've stumbled upon another problem:

`require(drake)`
Loading required package: drake

Attaching package: ‘drake’

The following object is masked from package:Matrix :

    expand

`drake_example('main')`
`file.exists('raw_data.xlsx')`
[1] FALSE
`file.exists('report.Rmd')`
[1] FALSE`

If I shut down R and restart, I obtain the following:

`require(drake)`
Loading required package: drake
`drake_example('main')`
`file.exists('raw_data.xlsx')`
[1] TRUE
`file.exists('report.Rmd')`
[1] TRUE

**Comment by drag05** [comment]
In neither case my working directory is 'main'. Yet, second time it shows file.exist = TRUE

**Comment by drag05** [comment]
Regarding the main issue (please see the last element in list):

> `diagnose(report)`
$`name`
[1] "report"

$target
[1] "report"

$imported
[1] FALSE

$foreign
[1] TRUE

$missing
[1] TRUE

$seed
[1] 1096375117

$output_files
       file_out 
"\"report.md\"" 

$input_files
         file_in         knitr_in 
"\"report.Rmd\"" "\"report.Rmd\"" 

$command
[1] "{\n knit(knitr_in(\"report.Rmd\"), file_out(\"report.md\"), quiet = TRUE) \n}"

$dependency_hash
[1] "1325bbd962df40881cc6e91b5106ef238ac5f2d44a5a7bb2f30793a70b9cbf1a"

$input_file_hash
[1] "19df5927a3f6388f36c955b1d6c9b787faa067a295edb012cae7dd24f483fae4"

$output_file_hash
[1] "13fb66f782330f47d61a715cbce9168df0566a2f4e87bed9a732d8d897e4cde0"

$start
   user  system elapsed 
  13.91    9.01 3996.48 

$time_command
    item   type elapsed user system
1 report target     0.4 0.31   0.08

$mtime
[1] "2018-07-28 23:42:49 EDT"

$time_build
    item   type elapsed user system
1 report target    0.46 0.33   0.13

$messages
[1] "Quitting from lines 53-59 (report.Rmd) "

$error
**<simpleError in plot_rmspe(rmspe = results): could not find function "plot_rmspe">**

**Comment by wlandau** [comment]
What version of drake are you using? There may have been an issue in a previous version, I do not remember. But it looks like you are using 5.3.0, which should be fine.

Re https://github.com/ropensci/drake/issues/488#issuecomment-409672827: you seem to be using the [gsp `report.Rmd` file](https://github.com/ropensci/drake/blob/master/inst/examples/gsp/report.Rmd), which calls `plot_rmspe()` on line 58. The [`report.Rmd` file generated by drake_example("main")](https://github.com/ropensci/drake/blob/master/inst/examples/main/report.Rmd) only has 20 lines. In other words, for the [correct report file](https://github.com/ropensci/drake/blob/master/inst/examples/main/report.Rmd), the message "Quitting from lines 53-59 (report.Rmd)" does not make sense.

I think the problem is that you have leftover files from previous attempts at the examples. These problems should go away if you clear them out and generate a new copy with `drake_example("main")`. Either that or try the following in a new session.

```r
library(drake)
dir.create("scratch") # drake tries not to overwrite an existing "main" folder
setwd("scratch")
drake_example("main")
setwd("main")
source("make.R")
```

**Comment by drag05** [comment]
Hello,
Sorry for the late replay! 

Running

`trace(drake:::drake_example, edit = TRUE)`

I found that `drake_example()` calls
 
`drake_examples()` which lists all installed examples

 and then, directs them 

`to = getwd()`. 

Hence, specifying "an example" should open a copy of this example into my `wd` through
 `file.copy(from, to)`
which is the next-to-last line in function call

Actually, running

`drake::drake_example('main')`  results in

`file.exists('report.Rmd')`
TRUE

and 

`file.exists('raw_data.xlsx')`
TRUE

**Comment by wlandau** [comment]
What version of R are you using? `file.copy()` may behave differently on yours.

`drake_example()` sets the `recursive` argument of `file.copy()` to `TRUE`. So if your working directory looks like this beforehand,

```
|-old_folder1/
|---file1
|---file2
|-old_folder2/
|---file3
```

Then it will look like this after `file.copy(from = "folder", to = getwd(), recursive = TRUE)`.

```
|-folder/
|---file4
|---file5
|-old_folder1/
|---file1
|---file2
|-old_folder2/
|---file3
```

Reproducible example:

```r
# Create a temporary directory.
dir <- tempfile()
dir
#> [1] "/tmp/Rtmp9glyQ7/file235217d0037e"
dir.create(dir)
# Add a file to this temp directory.
list.files(dir) # No files yet.
#> character(0)
file.create(file.path(dir, "file")) # Create a file.
#> [1] TRUE
list.files(dir) # Our file exists.
#> [1] "file"
# Copy the new directory to our working directory.
list.files() # Things in our working directory right now.
#>  [1] "old_stuff"
file.copy(from = dir, to = getwd(), recursive = TRUE) # Copy over our new dir.
#> [1] TRUE
list.files() # We see our new directory.
#>  [1] "file235217d0037e" "old_stuff"
list.files("file235217d0037e")
#>  [1] "file"
```

**Comment by drag05** [comment]
I am using v 3.5.1

**Comment by wlandau** [comment]
That helps. And what version of `drake` are you using? What is the output of the following?

```r
library(drake)
sessionInfo()
```

Another thing to try: destroy the cache with `drake::clean(destroy = TRUE)` before trying again.

The following reproducible example works for me on R 3.5.1, for Ubuntu 16.04, Windows 7, and Mac OS High Sierra, and for both the current development version of `drake` (https://github.com/ropensci/drake/commit/ceb86ceb1bfa68cc6fc81071948776fac95b3289) and the current CRAN release (version 3.5.0).

``` r
library(drake)
list.files()
#> [1] "reprex_reprex.R"        "reprex_reprex.spin.R"  
#> [3] "reprex_reprex.spin.Rmd"
drake_example("main")
list.files()
#> [1] "main"                   "reprex_reprex.R"       
#> [3] "reprex_reprex.spin.R"   "reprex_reprex.spin.Rmd"
setwd("main")
list.files()
#> [1] "clean.R"       "COPYRIGHT.md"  "LICENSE.md"    "make.R"       
#> [5] "raw_data.xlsx" "README.md"     "report.Rmd"
source("make.R")
#> target raw_data
#> target data
#> target fit
#> target hist
#> target report
sessionInfo()
#> R version 3.5.1 (2018-07-02)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: KDE neon User Edition 5.12
#> 
#> Matrix products: default
#> BLAS: /usr/lib/libblas/libblas.so.3.6.0
#> LAPACK: /usr/lib/lapack/liblapack.so.3.6.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] bindrcpp_0.2.2   forcats_0.3.0    stringr_1.3.1    dplyr_0.7.6     
#>  [5] purrr_0.2.5      readr_1.1.1      tidyr_0.8.1      tibble_1.4.2    
#>  [9] ggplot2_3.0.0    tidyverse_1.2.1  drake_5.3.1.9001
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_0.12.18        lubridate_1.7.4     txtq_0.0.4         
#>  [4] lattice_0.20-35     listenv_0.7.0       assertthat_0.2.0   
#>  [7] rprojroot_1.3-2     digest_0.6.15       mime_0.5           
#> [10] R6_2.2.2            cellranger_1.1.0    plyr_1.8.4         
#> [13] backports_1.1.2     evaluate_0.11       httr_1.3.1         
#> [16] pillar_1.3.0        rlang_0.2.1         curl_3.2           
#> [19] lazyeval_0.2.1      readxl_1.1.0        R.utils_2.6.0      
#> [22] R.oo_1.22.0         rmarkdown_1.10      labeling_0.3       
#> [25] downloader_0.4      igraph_1.2.2        munsell_0.5.0      
#> [28] broom_0.5.0         compiler_3.5.1      modelr_0.1.2       
#> [31] pkgconfig_2.0.1     globals_0.12.1      htmltools_0.3.6    
#> [34] tidyselect_0.2.4    codetools_0.2-15    future_1.9.0       
#> [37] crayon_1.3.4        withr_2.1.2         R.methodsS3_1.7.1  
#> [40] grid_3.5.1          nlme_3.1-137        jsonlite_1.5       
#> [43] gtable_0.2.0        magrittr_1.5        formatR_1.5        
#> [46] storr_1.2.1         scales_0.5.0        cli_1.0.0          
#> [49] stringi_1.2.4       fs_1.2.5            testthat_2.0.0.9000
#> [52] xml2_1.2.0          filelock_1.0.1      tools_3.5.1        
#> [55] glue_1.3.0          hms_0.4.2           parallel_3.5.1     
#> [58] yaml_2.2.0          colorspace_1.3-2    base64url_1.4      
#> [61] rvest_0.3.2         knitr_1.20          bindr_0.1.1        
#> [64] haven_1.1.2
```

Created on 2018-08-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000).

Would you execute the following code and paste the output into this thread? Without knowing exactly what you are doing step by step, starting with a clean session and clean working directory, I do not know what else I can do to help.

```r
install.packages("reprex")
library(reprex)
reprex({
  library(drake)
  list.files()
  drake_example("main")
  list.files()
  setwd("main")
  list.files()
  source("make.R")
  sessionInfo()
})
```

**Comment by drag05** [comment]
Here is the
`drake` version:

``` {r}
packageVersion('drake')
[1] ‘5.3.0’
```

and here is the `reprex()` value

``` {r} library(drake)
list.files()
#> [1] "file28e81ce03bac"                "file28e8648690c_reprex.R"       
#> [3] "file28e8648690c_reprex.spin.R"   "file28e8648690c_reprex.spin.Rmd"
#> [5] "file28e873b73bfb"                "file28e87a8435c6"               
#> [7] "file28e8de55847"
drake_example("main")
list.files()
#> [1] "file28e81ce03bac"                "file28e8648690c_reprex.R"       
#> [3] "file28e8648690c_reprex.spin.R"   "file28e8648690c_reprex.spin.Rmd"
#> [5] "file28e873b73bfb"                "file28e87a8435c6"               
#> [7] "file28e8de55847"                 "main"
setwd("main")
list.files()
#> [1] "clean.R"       "make.R"        "raw_data.xlsx" "report.Rmd"
source("make.R")
#> target raw_data
#> target data
#> target fit
#> target hist
#> target report
sessionInfo()
#> R version 3.5.1 (2018-07-02)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 7 x64 (build 7601) Service Pack 1
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] bindrcpp_0.2.2  forcats_0.3.0   stringr_1.3.1   dplyr_0.7.6    
#>  [5] purrr_0.2.5     readr_1.1.1     tidyr_0.8.1     tibble_1.4.2   
#>  [9] ggplot2_3.0.0   tidyverse_1.2.1 drake_5.3.0    
#> 
#> loaded via a namespace (and not attached):
#>  [1] storr_1.2.0       tidyselect_0.2.4  listenv_0.7.0    
#>  [4] haven_1.1.2       lattice_0.20-35   colorspace_1.3-2 
#>  [7] testthat_2.0.0    htmltools_0.3.6   yaml_2.2.0       
#> [10] rlang_0.2.1       R.oo_1.22.0       pillar_1.3.0     
#> [13] glue_1.3.0        withr_2.1.2       R.utils_2.6.0    
#> [16] modelr_0.1.2      readxl_1.1.0      bindr_0.1.1      
#> [19] plyr_1.8.4        cellranger_1.1.0  munsell_0.5.0    
#> [22] gtable_0.2.0      rvest_0.3.2       R.methodsS3_1.7.1
#> [25] future_1.9.0      codetools_0.2-15  evaluate_0.11    
#> [28] labeling_0.3      knitr_1.20        curl_3.2         
#> [31] parallel_3.5.1    broom_0.5.0       Rcpp_0.12.18     
#> [34] backports_1.1.2   scales_0.5.0      formatR_1.5      
#> [37] jsonlite_1.5      mime_0.5          fs_1.2.5         
#> [40] hms_0.4.2         digest_0.6.15     stringi_1.2.4    
#> [43] rprojroot_1.3-2   grid_3.5.1        cli_1.0.0        
#> [46] tools_3.5.1       magrittr_1.5      lazyeval_0.2.1   
#> [49] crayon_1.3.4      pkgconfig_2.0.1   xml2_1.2.0       
#> [52] lubridate_1.7.4   assertthat_0.2.0  rmarkdown_1.10   
#> [55] httr_1.3.1        globals_0.12.1    R6_2.2.2         
#> [58] igraph_1.2.2      nlme_3.1-137      compiler_3.5.1

Created on 2018-08-03 by the reprex package (v0.2.0).
```

**Comment by drag05** [comment]
Where are we with the initial issue?

`could not find function "plot_rmspe"`

Thank you!

**Comment by wlandau** [comment]
Thanks, @drag05. Looks like the error went away and your report builds just fine now. [`reprex`](https://github.com/tidyverse/reprex) guarantees that your code runs in a clean R session with a clean set of files, so I think it's just a matter of resetting your local files and environment.

**Comment by drag05** [comment]
Hi Will,

On one of my computers the environment variable path was pointing toward
R-3.5.0. Changed it to R-3.5.1 and re-installed drake. Now I cannot run the
"main" example at all. Both file.exists() give FALSE. This time on Windows 10,
64Bit.

The other laptop (Win 7) had the path correctly set. Regardless, both give
file.exists() FALSE

I just thought you needed to know. We'll talk next week. Have a nice week end!

Dragos
