### ISSUE TITLE
pretty printing of plans

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#489]
It is difficult to visually inspect long commands in workflow plan data frames. Example: https://github.com/ropensci/drake/issues/257#issuecomment-405335622.

```r
library(drake)
pkgconfig::set_config("drake::strings_in_dots" = "literals")
drake_plan(
  u_auckland = make_place(
    Name = "University of Auckland",
    Latitude = -36.8521369,
    Longitude = 174.7688785
  ),
  shapefile = {
    file_out("u-auckland.prj", "u-auckland.shx", "u-auckland.dbf")
    st_write(
      obj = u_auckland,
      dsn = file_out("u-auckland.shp"),
      driver = "ESRI Shapefile",
      delete_dsn = TRUE
    )
  }
)
#> # A tibble: 2 x 2
#>   target     command                                                      
#> * <chr>      <chr>                                                        
#> 1 u_auckland "make_place(Name = \"University of Auckland\", Latitude = -3…
#> 2 shapefile  "{\n    file_out(\"u-auckland.prj\", \"u-auckland.shx\", \"u…
```

Desired output:

```r
# A tibble: 2 x 2
  target     command                                             
* <chr>      <drake_cmd>
1 u_auckland make_place(
               Name = "University of Auckland",
               Latitude = -36.8521369,
               Longitude = 174.7688785
             )
2 shapefile  {
               file_out(
                 "u-auckland.prj",
                 "u-auckland.shx",
                 "u-auckland.dbf"
               )
               st_write(
                 obj = u_auckland,
                 dsn = file_out("u-auckland.shp"),
                 driver = "ESRI Shapefile",
                 delete_dsn = TRUE
               )
             }
```

I am not sure if this is possible, but I think it may be worth trying some combination of [`pillar::pillar_shaft()`](https://github.com/r-lib/pillar), [`styler`](https://github.com/r-lib/styler), [`highlight`](https://github.com/romainfrancois/highlight), and [`crayon`](https://github.com/r-lib/crayon).

**Comment by connoralbright** [comment]
This would be a very, very nice feature.

**Comment by wlandau** [comment]
Brilliant! Much easier and just as good.

**Comment by wlandau** [comment]
We will just have to make it really clear that the plan is just a data frame and that people do not always need to use `drake_plan()`. Ref: https://github.com/ropensci/drake/issues/451#issuecomment-408884875. Maybe a comment would be enough.

```r
> print(plan)
data frame generated by drake_plan(
  u_auckland = make_place(
                 Name = "University of Auckland",
                 Latitude = -36.8521369,
                 Longitude = 174.7688785
               )
  shapefile = {
                file_out(
                  "u-auckland.prj",
                  "u-auckland.shx",
                  "u-auckland.dbf"
                )
                st_write(
                  obj = u_auckland,
                  dsn = file_out("u-auckland.shp"),
                  driver = "ESRI Shapefile",
                  delete_dsn = TRUE
                )
              }
)
```

**Comment by wlandau** [comment]
We should define a special S3 class and print method for printing, and I am having some initial trouble. The guide on [extending `tibble`](https://cran.r-project.org/web/packages/tibble/vignettes/extending.html) helped me get started, but I still do not know how to make sure an S3 `"drake_plan"` class gets preserved during `dplyr` operations.

```r
drake::load_mtcars_example()
class(my_plan) <- c("drake_plan", "tbl_df", "tbl", "data.frame")
`[.drake_plan` <- function(...){
  as_drake_plan(NextMethod())
}
filtered <- dplyr::filter(my_plan, target %in% c("small", "report"))
class(filtered)
## [1] "tbl_df"     "tbl"        "data.frame"
```

**Comment by wlandau** [comment]
Just started to construct the call in the [`drake_plan_call` branch](https://github.com/ropensci/drake/tree/drake_plan_call). Code: 

```r
drake_plan_call <- function(plan){
  target_calls <- purrr::pmap(plan, drake_target_call)
  as.call(c(quote(drake_plan), target_calls))
}

drake_target_call <- function(...){
  args <- list(...)[drake_plan_columns()] %>%
    select_valid()
  target <- parse(text = args$target)[[1]]
  args$target <- NULL
  if (!is.null(args$command) && is.character(args$command)){
    args$command <- parse(text = args$command)[[1]]
  }
  if (!is.null(args$trigger) && is.character(args$trigger)){
    args$trigger <- parse(text = args$trigger)[[1]]
  }
  if (!identical(names(args), "command")){
    args$command <- as.call(c(quote(target), args))
  }
  call("=", target, args$command)
}
```

It's almost correct, but there are annoying extra parentheses around each target.

```r
> load_mtcars_example()
> drake_plan_call(my_plan)
drake_plan((report = knit(knitr_in("report.Rmd"), file_out("report.md"), 
    quiet = TRUE)), (small = simulate(48)), (large = simulate(64)), 
    (regression1_small = target(command = reg1(small), trigger = trigger(condition = is_tuesday(), 
        trigger = NULL))), (regression1_large = reg1(large)), 
    (regression2_small = reg2(small)), (regression2_large = reg2(large)), 
    (summ_regression1_small = suppressWarnings(summary(regression1_small$residuals))), 
    (summ_regression1_large = suppressWarnings(summary(regression1_large$residuals))), 
    (summ_regression2_small = suppressWarnings(summary(regression2_small$residuals))), 
    (summ_regression2_large = suppressWarnings(summary(regression2_large$residuals))), 
    (coef_regression1_small = suppressWarnings(summary(regression1_small))$coefficients), 
    (coef_regression1_large = suppressWarnings(summary(regression1_large))$coefficients), 
    (coef_regression2_small = suppressWarnings(summary(regression2_small))$coefficients), 
    (coef_regression2_large = suppressWarnings(summary(regression2_large))$coefficients))
```

**Comment by wlandau** [comment]
We now have an internal `drake_plan_call()` function to generate calls to `drake_plan()` from actual plans. Ref: #493.

**Comment by wlandau** [comment]
Next steps:

- [ ] Implement a new S3 `"drake_plan"` class for plans.
    - [ ] **Force the class stick to the plan during `dplyr` operations, etc. I would appreciate advice on this point.**
    - [ ] All functions that return a plan should ensure this class.
- [ ] Style `drake_plan()` call.
    - [ ] Use clever indentation to make it look like a table, with targets indexed like lines in a `tibble`.
    - [ ] Ensure the commands are formatted with a nice style. We may need a custom `styler` style guide.
    - [ ] Use `styler` control line width. Ref: https://github.com/r-lib/styler/issues/247, https://github.com/r-lib/styler/pull/390.
    - [ ] Gracefully cap the number of lines per target printed.
    - [ ] Gracefully cap the number of total lines printed.
- [ ] Use syntax highlighting. Investigate the possibilities:
    - [ ] [`prettycode`](https://github.com/r-lib/prettycode)
    - [ ] [`crayon`](https://github.com/r-lib/crayon)
    - [ ] [`highlight`](https://github.com/romainfrancois/highlight)
    - [ ] [`highr`](https://github.com/yihui/highr)
    - [ ] [`colorout`](https://github.com/jalvesaq/colorout)

**Comment by wlandau** [comment]
Update: from #494, we now have a special `"drake_plan"` S3 class for plans. [`dplyr` functions still seem to drop the class](https://stackoverflow.com/questions/51693365/extending-tibble-getting-the-new-s3-class-to-stick), but other than that, we have the ground work now. A new `print.drake_plan()` method will come eventually. I am not exactly sure on the best style, but I am convinced that it should be some cleverly indented and colored version of a call to `drake_plan()`.

**Comment by wlandau** [comment]
Continued work on this will be in the files [`R/drake_plan_class.R`](https://github.com/ropensci/drake/blob/master/R/drake_plan_class.R) and [`R/drake_plan_print.R`](https://github.com/ropensci/drake/blob/master/R/drake_plan_print.R).

**Comment by wlandau** [comment]
So apparently, dropping `tibble` subclasses is already a known `dplyr` issue: https://github.com/tidyverse/dplyr/issues/2532. Makes me think we should just roll with it and expose the `as_drake_plan()` method.

**Comment by wlandau** [comment]
@lorenzwalthert, I would like to include you in this conversation too. This feature is likely to require a custom `styler` style guide for calls to `drake_plan()`.

**Comment by lorenzwalthert** [comment]
Thanks. I think the fact that attributes and sub classes are generally not preserved in R are a pitty ne limit the usefulness of this mission slightly. Anyways, as_drake_plan() seems a way out and I am happy to provide huifeance repated styling. Just let me know what the requirements are.

**Comment by wlandau** [comment]
After letting this issue sit for a few days, I no longer think the `drake` plan itself should have special printing. It is so crucial to emphasize that the plan is just a data frame, and printing out a function call by default could make the plan too mysterious. But what if we expose `drake_plan_call()` and add a nice print method for the output?

Most of the remaining work for that is to create a custom style guide. Relevant: https://lorenzwalthert.netlify.com/posts/customizing-styler-the-quick-way/

**Comment by wlandau** [comment]
I think the syntax highlighting piece may be better suited to `styler` itself. Ref: https://github.com/r-lib/styler/issues/417.

**Comment by lorenzwalthert** [comment]
To be honest, I think you don't even need `styler` for the highlighting only. Can we just use `cat(prettycode::highlight(...), sep = "\n")`?

**Comment by wlandau** [comment]
Sure, seems to work fine in my own console.

**Comment by lorenzwalthert** [comment]
Ok, cool. I mean you can still use styler to prettify your code beforehand according to a (custom) style guide.

**Comment by wlandau** [comment]
I'm a little unclear about the role of `pd_flat$newlines` vs `pd_flat$lag_newlines`. Would you elaborate? Here is what I am seeing. Using `pd_flat$newlines`, no new line breaks are added.

```r
add_line_breaks <- function(pd_flat){
  pd_flat$newlines <- pd_flat$newlines + (pd_flat$token == "SYMBOL_SUB")
  pd_flat
}
guide <- function(){
  styler::create_style_guide(line_break = tibble::lst(add_line_breaks))
}
styled <- styler::style_text(text, style = guide)
cat(prettycode::highlight(styled), sep = "\n")
#> drake_plan(small_data = download_data("https://some_website.com") %>% select_my_columns() %>%
#> munge(), large_data_raw = target(command = download_data("https://lots_of_data.com") %>%
#> select_top_columns, trigger = trigger(change = time_last_modified("https://lots_of_data.com"),
#> command = FALSE, depend = FALSE), timeout = 1000))
```

And with `pd_flat$lag_newlines`:

```r
add_line_breaks <- function(pd_flat){
  pd_flat$lag_newlines <- pd_flat$lag_newlines | (pd_flat$token == "SYMBOL_SUB")
  pd_flat
}
guide <- function(){
  styler::create_style_guide(line_break = tibble::lst(add_line_breaks))
}
styled <- styler::style_text(text, style = guide)
cat(prettycode::highlight(styled), sep = "\n")
#> drake_plan(
#> small_data = download_data("https://some_website.com") %>% select_my_columns() %>%
#> munge(),
#> large_data_raw = target(
#> command = download_data("https://lots_of_data.com") %>%
#> select_top_columns,
#> trigger = trigger(
#> change = time_last_modified("https://lots_of_data.com"),
#> command = FALSE,
#> depend = FALSE),
#> timeout = 1000))
```

**Comment by wlandau** [comment]
I think it is appropriate to have:

- A new line and a 2-space indent for each target name.
- A new line and a 4-space indent for each argument to `target()` (only appears at the target name level).
- A new line and a 6-space indent for each argument to `trigger()` (only appears as the `trigger` argument to `target()`).
- Line breaks and appropriate indentation for other code long enough to wrap. (commands, custom triggers).

**Comment by wlandau** [comment]
I figured out a solution: at the top level, recurse the AST of a `drake_plan()` call to make sure we have the proper line breaks and indentation. Then, apply `styler::style_text()` to the leaf nodes. The result is quite nice, and we have syntax highlighting with `prettycode::highlight()` in the console.

``` r
library(drake)
plan <- drake_plan(
  small_data = download_data("https://some_website.com") %>%
    select_my_columns() %>%
    munge(),
  large_data_raw = target(
    command = download_data("https://lots_of_data.com") %>%
      select_top_columns,
    trigger = trigger(
      change = time_last_modified("https://lots_of_data.com"),
      command = FALSE,
      depend = FALSE
    ),
    timeout = 1e3
  ),
  strings_in_dots = "literals"
)
print(plan)
#> # A tibble: 2 x 4
#>   target    command                     trigger                    timeout
#> * <chr>     <chr>                       <chr>                        <dbl>
#> 1 small_da… "download_data(\"https://s… <NA>                            NA
#> 2 large_da… "download_data(\"https://l… "trigger(change = time_la…    1000
drake_plan_source(plan)
#> drake_plan(
#>   small_data = download_data("https://some_website.com") %>%
#>     select_my_columns() %>%
#>     munge(),
#>   large_data_raw =target(
#>     command = download_data("https://lots_of_data.com") %>% select_top_columns(),
#>     trigger =trigger(
#>       change = time_last_modified("https://lots_of_data.com"),
#>       command = FALSE,
#>       depend = FALSE
#>     ),
#>     timeout = 1000
#>   ),
#>   strings_in_dots = "literals"
#> )
```

**Comment by wlandau** [comment]
I do like the simplicity of deferring to `styler`'s defaults, but the [code for the recursion](https://github.com/ropensci/drake/blob/master/R/drake_plan_source.R#L79-L128) is longer and more complicated than I would like. A custom style guide would make it more concise.

**Comment by lorenzwalthert** [comment]
This indeed seems complicated. What are the requirements for the styling? E.g. line break after `drake_plan(` and after every target code?

**Comment by wlandau** [comment]
That's part of it. I would prefer each of the following to start on its own line:

- Every target (argument to `drake_plan()`)
- Every argument to `target()`
- Every argument to `trigger()`
- Every piece of code following `%>%`
- Every closing parenthesis.

This, plus the indentation above, are what I am after. I take it this is difficult to do in `styler`? Do you think a custom style guide would require more code than the [existing solution](https://github.com/ropensci/drake/blob/master/R/drake_plan_source.R#L79-L128)?

**Comment by krlmlr** [comment]
FYI: The `"vertical"` class in _pillar_ is being renamed to `"pillar_vertical"`. Seems safer to use the `"glue"` class for this purpose, or actually any other class that just prints the contents of the object via `cat()` .

**Comment by wlandau** [comment]
Good point. I forgot I already defined a `"drake_plan_source"` class and a special print method, so we actually do not need to borrow an S3 class from another package.

**Comment by wlandau** [comment]
Update: the current behavior is to create a special `expr_list` class for the `command`, `trigger`, and `transform` columns of the plan. Using S3 magic, these columns get deparsed to characters when the plan gets printed, and an `<expr>` label appears at the top of the `tibble`.

``` r
library(drake)
drake_plan(
  data = get_data(),
  y = analyze_data(data)
)
#> # A tibble: 2 x 2
#>   target command           
#>   <chr>  <expr>            
#> 1 data   get_data()        
#> 2 y      analyze_data(data)
```

<sup>Created on 2019-05-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Drawbacks:

1. This is a lot of bookkeeping for the sake of pretty printing.
2. The *entire* column is deparsed when the `tibble` gets printed, which does not scale well. Printing should be instantaneous, we have a low tolerance for delays.

So I would rather rely on https://github.com/r-lib/pillar/issues/34 and https://github.com/r-lib/pillar/pull/153. But because `pillar`'s enhanced printing relies on `vctrs`, there is a snag: https://github.com/r-lib/pillar/issues/34#issuecomment-489490309.
