### ISSUE TITLE
More documentation of wildcards?

### ISSUE THREAD

**Issue by jzelner** [ropensci/drake#495]
It would be great if there was more thorough documentation of the wildcards that can be used in expand_plan, etc. I haven't noticed a lot of detail on this in the tutorials, particularly for parameters, etc. Apologies if I have missed this somewhere!

-Jon

**Comment by wlandau** [comment]
Hi Jon,


The best documentation on wildcards is new and thus easily missed. Does https://ropenscilabs.github.io/drake-manual/plans.html#generating-large-workflow-plans have what you need?

Will

**Comment by wlandau** [comment]
Thanks Jon, it is gratifying to hear `drake` is working so well for you. Please feel free to send more questions my way.
