### ISSUE TITLE
dependency_profile(): should the output be more specific?

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#496]
I would really like to know what the community thinks about this one because I am undecided.

### Background

`dependency_profile()` is designed to help users figure out why a target might be out of date. The output is already improved in `drake` 5.4.0.9000:

``` r
library(drake)
load_mtcars_example() # Get the code with drake_example("mtcars").
config <- make(my_plan, verbose = FALSE)
# regression2_small should be up to date.
dependency_profile(target = regression2_small, config = config)
#> # A tibble: 4 x 4
#>   hash    changed old_hash                     new_hash                   
#>   <chr>   <lgl>   <chr>                        <chr>                      
#> 1 command FALSE   f08c9f154406ce85ab9834ffb10… f08c9f154406ce85ab9834ffb1…
#> 2 depend  FALSE   ffe33a15d52e57557072fb9eb57… ffe33a15d52e57557072fb9eb5…
#> 3 file_in FALSE   01234566814cd2a2b3cd7c19c90… 01234566814cd2a2b3cd7c19c9…
#> 4 file_o… FALSE   01234566814cd2a2b3cd7c19c90… 01234566814cd2a2b3cd7c19c9…
## Change an in-memory dependency and update the cache.
reg2 <- function(d) {
  d$x3 <- d$x ^ 3
  lm(y ~ x3, data = d)
}
make(skip_targets = TRUE)
# The change is detected.
dependency_profile(target = regression2_small, config = config)
#> # A tibble: 4 x 4
#>   hash    changed old_hash                     new_hash                   
#>   <chr>   <lgl>   <chr>                        <chr>                      
#> 1 command FALSE   f08c9f154406ce85ab9834ffb10… f08c9f154406ce85ab9834ffb1…
#> 2 depend  TRUE    ffe33a15d52e57557072fb9eb57… 0675307b21b618a78b59a38659…
#> 3 file_in FALSE   01234566814cd2a2b3cd7c19c90… 01234566814cd2a2b3cd7c19c9…
#> 4 file_o… FALSE   01234566814cd2a2b3cd7c19c90… 01234566814cd2a2b3cd7c19c9…
```

### Question

Should the output be more specific? Should it report the changes to each and every dependency instead of just the hashes that activate the triggers?

### Pros

Finer detail would really help users narrow down which targets or imports are causing a target to be out of date.

### Cons

1. Performance: we would need to carry around all the hashes of all the dependencies in the metadata, which would consume more memory, storage, and runtime, especially for workflows with lots of connections among lots of targets.
2. Back compatibility: all targets built with `drake` <= 5.4.0 would suddenly fall out of date because the finer detail in `dependency_profile()` requires modifying the output of functions `dependency_hash()`, `file_input_hash()`, and `file_output_hash()`.

**Comment by kendonB** [comment]
More detail is better here. You could even add columns for each of the triggers? Users can always subset the larger df themselves using `filter` and `select`.

**Comment by wlandau** [comment]
Thanks, Kendon! I am actually more worried about the additional internal bookkeeping prior to `dependency_profile()` that it would take to support the enhanced detail. It would require [`drake_meta()`](https://github.com/ropensci/drake/blob/80b82d2e4d4dcda5d61cf7c3b939bc6612185356/R/meta.R#L48) objects to always store everything about the current dependency profile. Targets with ~1e5 dependencies would be lugging around several megabytes of metadata, which could slow things down for huge spatial data projects like yours.

**Comment by kendonB** [comment]
That would add up fast if you had many such targets, yes.

**Comment by wlandau** [comment]
Reopening. I just returned to an old project and saw that all my targets were mysteriously out of date.

**Comment by wlandau** [comment]
See https://github.com/ropenscilabs/drake-manual/issues/31#issuecomment-417401519. We should use cache log files instead.
