### ISSUE TITLE
Add ability to highlight certain stages of your plan

### ISSUE THREAD

**Issue by nathaneastwood** [ropensci/drake#524]
Apologies for opening another issue, but I feel this is separate to the last one I opened.

Following on from my questions in #523, another Rmarkdown/wider `drake` question I have is around breaking changes. Let's say you do some EDA, fit a couple of models and then write your report. But then you take another look at the data and notice something fundamentally wrong which makes your results - and therefore the conclusions in your prose - wrong. Currently, `drake` will take note of changes in the EDA / data manipulation stage, rerun them and the report and voila, your report is updated, but then conclusions in it are wrong and unless you've made a mental note, you may "forget" to make those changes to your prose. It would be useful to be able to put a blocker or marker on the visual dependency graph (maybe make a node red?) such that certain stages won't be rerun or will provide a warning.

I'm kind of approaching this from a point of view of being at the end of the day or handing over some analysis piece to a colleague after a review.

**Comment by wlandau** [comment]
It's an interesting question. Seems like an old problem in literate programming, with the difference here being that `drake` actually promises that your report is up to date after you run `make()`.

If you are worried about your prose being out of date and it is too late in the day for a serious rewrite, you could always insert a [custom trigger](https://ropenscilabs.github.io/drake-manual/triggers.html) before you step out of the office. With `drake_plan(report = target(..., trigger = trigger(condition = TRUE))`, your report will always show up as out of date in the dependency graph no matter how many times you run `make()`.

I think other solutions are probably out of scope for `drake`. `drake` has no way of knowing if the informational content of your prose matches the content of the results even if you do make an effort to update the writing. @gmbecker explains it best in his talks: reproducibility is about trust, and trust at every level of the scientific process goes way beyond computational pipeline toolkits.
