### ISSUE TITLE
Documentation Request: Details of Random Seed Behavior?

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#526]
I just had a question about how `drake` manages the random seed, and I came across #218 which in combination with the help to `make()` got me partway there.

I found that `drake` does what I'd like it to do, I think, but I'm not sure if this is fully documented.  I'm happy to help with crafting the documentation (i.e. a pull request) if you can help confirm what I think is happening:

1. A root seed is set for a project when `make()` or `drake_config()` is called.
2. A target-specific seed is set for each target by using the root seed and the target name.
3. Whenever the target is run, the seed is set to that target-specific seed (ensuring that starting random values are identical within a target).

If this is accurate, then I think that point 1 above is covered by existing documentation and points 2 and 3 are not clear beyond the general statement that reproducibility is preserved.

(To be clear, I think you've done a wonderful job of RNG management, but it wasn't clear from the documentation that you'd put all that functionality into it.)

**Comment by wlandau** [comment]
Thanks, @billdenney! (1), (2), and (3) are exactly right. (1) was @krlmlr's idea.

Looking back at the help files for `make()` and `drake_config()`, I now see that I missed (2) and (3). I think https://github.com/ropensci/drake/commit/347f9b9b8ea1b748b1772a0b4af465842455e80f covers it. If you see anything else or you want to add to the [manual](https://github.com/ropenscilabs/drake-manual), I would greatly appreciate pull requests.

**Comment by billdenney** [comment]
Thank you, that looks great!  I now see that it's discussed in the FAQ.  Sorry that I missed that before.

**Comment by wlandau** [comment]
Nothing to apologize for. You clearly did your due diligence.
