### ISSUE TITLE
Wildcards in trigger condition are not expanded

### ISSUE THREAD

**Issue by idavydov** [ropensci/drake#528]
As far as I understand, one of the motivations for the new trigger interface (#473) was the ability to write a code like this:
```r
drake_plan(
  target1 = ...,
  target2 = target(
    ...,
    trigger=trigger(
      condition = is_small_enough(target1)
    )
  )
)
```

This seems to work fine, however `evaluate_plan` seems to ignore trigger while expanding wildcards:
```r
library(drake)
library(magrittr)
pkgconfig::set_config("drake::strings_in_dots" = "literals")


plan <- drake_plan(
  a = n__ + 1,
  b = target(
    a_n__ + 2,
    trigger=trigger(condition=a_n__ > 0)
  )
) %>% evaluate_plan(list(n__=1:2))

plan
```

That's the output:

```
# A tibble: 4 x 3
  target command trigger                       
* <chr>  <chr>   <chr>                         
1 a_1    1 + 1   NA                            
2 a_2    2 + 1   NA                            
3 b_1    a_1 + 2 trigger(condition = a_n__ > 0)
4 b_2    a_2 + 2 trigger(condition = a_n__ > 0)
```

I expected to have this:
```
3 b_1    a_1 + 2 trigger(condition = a_1 > 0)
4 b_2    a_2 + 2 trigger(condition = a_2 > 0)
```

# A more general question
Please let me know if I should open a separate issue or ask on stackoverflow.

I would like to "kill" certain  branches based on their input. E.g., if for some input data I haven't received enough results, I do not want to continue.

It seems that `trigger(condition=...)` won't help because dependency reasoning has a higher priority over `condition` and `trigger(depend=FALSE, condition=...)` will disable dependency monitoring for the target completely.

The easiest workaround I see now is to return a special value (e.g. `NULL`). And in this case all downstream commands would have to check for a special value.

```r
plan <- drake_plan(
  a = rnorm(1),
  b = if (a>0) sqrt(a) else NULL,
  c = if (is.null(b)) NULL else b+1,
  d = if (is.null(c)) NULL else c+1,
)
```

Any suggestions?

**Comment by wlandau** [comment]
### Wildcards in triggers

`evaluate_plan()` has a `columns` argument. Here, you can list all the columns in the plan where you want `drake` to look for wildcards.

``` r
library(drake)
library(magrittr)
pkgconfig::set_config("drake::strings_in_dots" = "literals")
drake_plan(
  a = n__ + 1,
  b = target(
    a_n__ + 2,
    trigger=trigger(condition=a_n__ > 0)
  )
) %>%
  evaluate_plan(
    rules = list(n__ = 1:2),
    columns = c("command", "trigger")
  )
#> # A tibble: 4 x 3
#>   target command trigger                     
#> * <chr>  <chr>   <chr>                       
#> 1 a_1    1 + 1   <NA>                        
#> 2 a_2    2 + 1   <NA>                        
#> 3 b_1    a_1 + 2 trigger(condition = a_1 > 0)
#> 4 b_2    a_2 + 2 trigger(condition = a_2 > 0)
```

### The more general question

I like your workaround. When I designed triggers, I did not anticipate the need to explicitly suppress a target. Maybe there should be a `suppress` trigger analogous to the `condition` trigger. I do not know, and I will think about it.

**Comment by idavydov** [comment]
Thanks! Totally missed `columns`. My bad.

**Comment by wlandau** [comment]
No worries. `drake` is complicated.

**Comment by wlandau** [comment]
Also, I tend to focus a lot more on the issue tracker than StackOverflow. I try to check the questions tagged with `drake-r-package`, but even so, I end up missing more than I would like.
