### ISSUE TITLE
Get the worker to do the loading in `future` parallelism?

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#539]
Giving `future` parallelism another try. With a lot of targets, all the loading is quite rough on the main process. Is it feasible to structure the dispatch so that the the worker loads dependencies?

**Comment by wlandau** [comment]
I also plan to implement this for `make(parallelism = "clustermq", caching = "worker"). Slightly related: https://github.com/ropensci/drake/issues/449#issuecomment-402955145.

**Comment by wlandau** [comment]
Also, I just noticed that `"future"` parallelism needs checksums to make sure the data writes back correctly. I will roll in a patch.

**Comment by wlandau** [comment]
Fixed via #544.
