### ISSUE TITLE
Show caching message when verbose = 4?

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#541]
I have a job that might be I/O heavy due to caching and I can't quite tell as when I look at the txtq or batchtools logs the most I can see is `target ...`, loading, and unloading. 

The `storring` stage naturally fits with `verbose = 4`, I think.

something like : `storring <target_name>` printed like the other messages would do it. Could also consider chucking all the messages into the worker txtq's as well.

**Comment by wlandau** [comment]
Sounds reasonable and easy to implement. I am hoping to get to this and #539 later this week.
