### ISSUE TITLE
Change interpretation of the jobs argument?

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#553]
From https://github.com/ropensci/drake/issues/435#issuecomment-430985651, I am starting to think `make(jobs = 16)` should be equivalent to `make(jobs = c(imports = 1, targets = 16))` rather than the current `make(jobs = c(imports = 16, targets = 16))`. What do you think? cc @kendonB, @idavydov.

**Comment by wlandau** [comment]
Should be a simple matter of changing [this line in `parse_jobs()`](https://github.com/ropensci/drake/blob/b2969173dd7bb1ec214bffc505f074e1880bc869/R/config.R#L658).

**Comment by idavydov** [comment]
In my opinion that would be a good pragmatical decision.

1. In case of small plans, this should not affect the performance significantly.
2. For the large plans with a large number of jobs this should provide significant benefit (see https://github.com/ropensci/drake/issues/435#issuecomment-430982475).
3. The only case when this could make things worse is a huge plan with the moderate number of workers (e.g. 1k targets, 5 jobs).

But I think cases when imports are the bottleneck should not be common.

**Comment by wlandau** [comment]
Yeah, I agree. And the decision is much easier now that version >= 6.0.0 has far fewer imports (ref: #519). Fixed in https://github.com/ropensci/drake/commit/100c71fca0096a2b7fe26670f3d64207abe9fa92.

**Comment by wlandau** [comment]
Edit: please see b786fe3d3aabaf47ea6e02776bd3267ea427240a.https://github.com/ropensci/drake/commit/100c71fca0096a2b7fe26670f3d64207abe9fa92 has a bug.
