### ISSUE TITLE
Inconsistency between gather_plan and gather_by

### ISSUE THREAD

**Issue by idavydov** [ropensci/drake#554]
There is an inconsistency in the behavior of `gather_plan()` and `gather_by()`.

While `gather_by()` only outputs the result of the gathering, `gather_by()` includes the original plan:

```r
gather_by <- function (plan, ..., prefix = "target", gather = "list") 
{
    <...>
    if (ncol(cols)) {
        bind_plans(plan, gathered[keep, ])
    }
    else {
        bind_plans(plan, gathered)
    }
}
```

In my opinion that is a bit counter-intuitive. I think the common use-case would be to perform `gather_by()` on a subset of a large plan and bind the result to the master plan. E.g., 

```r
my.plan <- ...
my.plan <- my.plan %>%
    filter(str_detect(target, '^my.stat.df_')) %>%
    gather_by(simulation__, prefix='gather', gather='dplyr::bind_rows') %>%
    bind_plans(my.plan)
```

However this will create duplicate entries in the plan, so the proper code would look like:

```r
my.plan <- ...
my.plan <- my.plan %>%
    filter(str_detect(target, '^my.stat.df_')) %>%
    gather_by(simulation__, prefix='gather', gather='dplyr::bind_rows') %>%
    filter(str_detect(target, '^gather_')) %>%
    bind_plans(my.plan)
```

As it probably does not make sense to break backwards compatibility, my suggestion would be to add an option to include the original plan.

```r
gather_by <- function (plan, ..., prefix = "target", gather = "list", include.original = TRUE) 
{
    <...>
    if (ncol(cols))
        gathered <- gathered[keep, ]
    if (include.original) {
        bind_plans(plan, gathered)
    }
    else {
        gathered
    }
}
```

P.S. I'm probably leaving too many issues :) Please feel free to let me know if that's too much.

**Comment by idavydov** [comment]
Comparison of behavior of `gather_plan()` and `gather_by()`

``` r
library(drake)
suppressMessages(library(dplyr))

pkgconfig::set_config("drake::strings_in_dots" = "literals")
plan <- drake_plan(
  small = data.frame(type = "small", x = rnorm(25), y = rnorm(25)),
  large = data.frame(type = "large", x = rnorm(1000), y = rnorm(1000))
)
gather_plan(plan, target = "combined")
#> # A tibble: 1 x 2
#>   target   command                           
#>   <chr>    <chr>                             
#> 1 combined list(small = small, large = large)

plan <- drake_plan(
  df = data.frame(type = "df_size__", x = distribution__(size__), y = distribution__(size__))
) %>% evaluate_plan(
  list(
    size__ = c(25, 1000),
    distribution__ = c('rnorm', 'rexp')
    ),
  trace=TRUE
)
gather_by(plan, distribution__)
#> # A tibble: 6 x 6
#>   target  command       size__ size___from distribution__ distribution___…
#>   <chr>   <chr>         <chr>  <chr>       <chr>          <chr>           
#> 1 df_25_… "data.frame(… 25     df          rnorm          df_25           
#> 2 df_25_… "data.frame(… 25     df          rexp           df_25           
#> 3 df_100… "data.frame(… 1000   df          rnorm          df_1000         
#> 4 df_100… "data.frame(… 1000   df          rexp           df_1000         
#> 5 target… list(df_25_r… <NA>   <NA>        rexp           <NA>            
#> 6 target… list(df_25_r… <NA>   <NA>        rnorm          <NA>
```

Created on 2018-10-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by wlandau** [comment]
## Proposal

Good points. To choose between the two options in https://github.com/ropensci/drake/issues/554#issuecomment-431283854, I will implement new  `append` argument. The affected functions are `gather_plan()`, `gather_by()`, `reduce_plan()`, and `reduce_by()`.

The default values of `append` would not agree at first, but we can fix that later. For now, I think we set two of the defaults to `NULL` and warn about the eventual change if the user does not supply a non-`NULL` value.

## Question for you

@idavydov, it sounds like you have a preference for a default of `append = FALSE`. But from #376, others may disagree. @tmastney, what do you think?

**Comment by tmastny** [comment]
In principle, I agree that you shouldn't gather all the targets. However, I disagree with your conclusion that it shouldn't bind to the original plan.

My ideal world is described here: https://github.com/ropensci/drake/issues/376#issuecomment-419753810 Basically, the idea is to only gather and bind certain row-groups within the `gather_by` column. I believe this would solve both our concerns.

**Comment by wlandau** [comment]
I think I would actually handle https://github.com/ropensci/drake/issues/376#issuecomment-419753810 with a separate argument. `append` concerns itself with targets available before gathering (e.g. `informal_look_3_1` and `informal_look_3_1` in https://github.com/ropensci/drake/issues/376#issuecomment-419756682) and you seem to be asking to about the targets created in the gathering process.

**Comment by wlandau** [comment]
For this thread in particular, we are talking about defaults. Would it be too much of an inconvenience to set `append` to `TRUE` in `gather_by()`?

**Comment by wlandau** [comment]
See https://github.com/ropensci/drake/issues/376#issuecomment-432210898 as well.

**Comment by tmastny** [comment]
I'm also still in favor of `append = TRUE` being the default. From my perspective, I don't see it as an inconsistency because `gather_by` and `gather_plan` are fundamentally different operations, but I can see how it could be confusing to someone reading it the first time.

For me, I think `append = TRUE` is the most common operation. For a usability standpoint, I think using the most popular default makes sense, even if it is different from `gather_plan`.

**Comment by wlandau** [comment]
Fair enough, thanks for the input. `gather_plan()` and `gather_by()` do sound almost the same, but `gather_by()` actually calls `gather_plan()` internally, and in a way, these functions accommodate different situations. We can always deprecate and change the defaults  later if we need to, and it's good to have a bias against change for this sort of thing. Closing this issue and #555.
