### ISSUE TITLE
Follow through with hooks?

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#558]
I never really followed through with `make(hook = some_custom_function)`, and I want to come back to it because it could really help get the most out of [hasty mode](https://ropenscilabs.github.io/drake-manual/hpc.html#hasty-mode). `make(parallelism = "hasty")` throws away reproducibility and runs really fast because it's a blank slate. With better support for hooks, anyone could try out their own caching/hashing/memoization techniques, and we could all experiment with better ways to make `drake` both fast and reproducible.

Here's an example. First, we define a custom build hook that controls when to build each target.

```r
time_stamp_hook <- function(target, config, command, ...){
  # Get the *time stamps* of the dependencies.
  # Time stamps are faster to generate than hashes.
  current_time_stamps <- drake:::dependencies(target, config) %>%
    get_current_time_stamps()
  old_time_stamps <- drake:::dependencies(target, config) %>%
    get_old_time_stamps()

  # Skip the target if the time stamps of the dependences
  # did not change since last time.
  if (!identical(current_time_stamps, old_time_stamps)){
    return()
  }

  # Build the target
  value <- force(command)

  # Save that return value. Remember, hasty mode does not cache targets.
  saveRDS(value, file = fs::path_ext_set(target, "rds"))

  # Return the target so drake can put it into memory for subsequent targets.
  value
}
```

Then, we see how fast and reproducible `make()` is.

```r
make(some_large_plan, parallelism = "hasty", hook = time_stamp_hook)
make(some_large_plan, parallelism = "hasty", hook = time_stamp_hook)
...
```

**Comment by idavydov** [comment]
Cool idea. It could also solve #529.

```r
early_stop <- function() {
    es <- list()
    class(es) <- 'early_stop'
    es
}

is.early_stop <- function(x) class(x) == 'early_stop'

early_stop_hook <- function(target, config, command, ...){
    is.es <- drake:::dependencies(target, config) %>%
        sapply(is.early_stop(readd(x))) %>%
        any
    if (is.es) {
        value <- early_stop()
    } else {
        value <- default_hook(target, config, command, ...)
    }

    value
}
```

**Comment by idavydov** [comment]
In order to have flexibility it would be nice to have `drake::check()`, `drake::build()` & `drake::store()`. In such case `drake::check_build_store()` could look like this:

```r
check_build_store <- function(target = target, config = config, command = command, ...) {
    if (check(target=target, config=config, command=command, ...))
        value <- build(target=target, config=config, command=command, ...)
    store(value, arget=target, config=config, command=command, ...)
}
```

Not sure though how `store()` would work with `make(..., caching="worker")`.

**Comment by idavydov** [comment]
Everything below is my personal opinion, and I'm not sure I understand how it should work internally.

But I think it would be great to be able to change all the aspects of execution. I think there are two approaches to achieve this:

1. Multiple hooks (e.g., `save_hook`, `check_hook`, `build_hook`).
2. One hook & multiple helper functions (`check`, `store`, `build`, ...).

If there's one large hook and no helper functions, this would require reimplementation of drake's logic for some trivial cases.

I understand that my idea could be slightly out of scope for this feature.

**Comment by wlandau** [comment]
I think we could have both: `save_hook()`, `check_hook()`, and `build_hook()` could be examples, and then the user could have custom hooks that invoke some combination of `check()`, `build()`, and `store()`. I really like where this is going!

A couple more thoughts.

1. I think we should only support hooks for "hasty" mode (`make(parallelism = "hasty")`). Hooks never really succeeded as a feature in the other parallel backends. There are complicated special cases for each individual backend, and users should really not be hacking into the standard backends anyway.
2. The works "check", "build", and "store" are likely to conflict with exported functions from other packages. Maybe these thin-layer helper functions:

- `target_deps()`: We already have `deps_target()`. We could just deprecate and rename it (also: `deps_code()` => `code_deps()`).
- `target_meta()`: Target metadata for the build decision. Deprecate `drake_meta()` and rename it.
- `target_check()`: Rename and export `should_build_target()`.
- `target_build()`: Rename `build_target()` and export it.
- `target_store()`: Rename and export `store_outputs()`. Also recompute the `meta` argument from `target_meta()` if the user does not supply it.

That should allow the user to reconstruct `drake`'s existing procedure for processing each target, or mix and match pieces. All caching is done on the workers, but that's not such a bad limitation.

**Comment by idavydov** [comment]
I think preventing hooks in all modes other than `hasty` could be really limiting.

Maybe a certain subset of hooks could be available everywhere? I can imagine a scenario when one would want to have a hook around `store` specifically in one of the cluster modes. The same with `check`.

If that's not possible, it would be great to have a simple way to re-implement parallel modes in hasty mode. But this sounds more difficult.

Here are a couple of potential uses for hooks:

1. Create network logging to track progress of large plans on a cluster. This should be a hook around `build` (e.g. job xxx submitted to a host, job xxx completed; 1Mb saved to storage).
2. Backup storage backend (e.g. in case storing in one of the databases fails, store results in a file). This would require a hook for `store`.
3. Early stop (#529), a hook for `check`.
4. Your example with timestamps, a hook for `check`.
5. Notify some kind of software when a node was computed. This would potentially allow online visualization dependency. A hook for `build` & `store`.

**Comment by wlandau** [comment]
I think I have a clearer idea of what you are envisioning. Individual `check`, `build`, and `store` hooks would support the use cases you mention. Each hook (respectively) could wrap around the inside of `target_check()`, `target_build()`, and `target_store()`. Hasty mode can have its own special hook.

Here's my thinking: a hook is a function of the form:

```r
function(expr, target, value, meta, config){
  ...
  force(expr)
  ...
}
```

where 

- `...` are things you might do before or after a build: extra checking, logging, etc.
- `expr` is code that runs whatever step you are in: `check`, `build`, or `store`.
- `target` is the name of the target.
- `value` is the return value of the target after running its command. Only applies to the `store` hook.
- `meta` is target metadata produced by the current `drake_meta()`.
- `config` is the list of internal runtime parameters from `drake_config()`.

The full design of this feature will require more thought, time, and iteration. So here is my plan.

1. Deprecate the current `hook` argument and allude to the possibility of specialized hooks in a future release.
2. Implement the hook for hasty mode to allow more people to experiment with better caching/hashing/storage mechanisms.
3. Release `drake` version 6.1.0 to CRAN, which contains an important patch (#548).
4. Work on the other hooks at the beginning of the next development cycle.

**Comment by wlandau** [comment]
Each hook will make use of slightly different arguments. Here are some shared components:

- `...` are things you might do before or after a build: extra checking, logging, etc.
- `target` is the name of the target.
- `value` is the return value of the target after running its command. Only applies to the `store` hook.
- `meta` is target metadata produced by the current `drake_meta()`.
- `config` is the list of internal runtime parameters from `drake_config()`.

It will be up to the user to write each hook. Here is what I am thinking for the general form of each.

```r
hook_check <- function(target, meta, config){
  # more code ...
  phase_check(target, meta, config) # currently should_build_target()
  # more code ...
}

hook_build <- function(target, meta, config){
  # more code ...
  phase_build(target, meta, config) # currently just_build()
  # more code ...
}

hook_store <- function(target, value, meta, config){
  # more code ...
  phase_store(target, value, meta, config) # currently store_outputs()
  # more code ...
}

hook_hasty <- function(target, config){
  # more code ...
  phase_hasty(target, config) # currently a call to eval()
  # more code ...
}
```

**Comment by wlandau** [comment]
A few more remarks:

- As in the previous comment, I think the proposed `target_*()` functions should actually be named `phase_*()` because they apply to imports as well.
- Internally, I am thinking about accompanying `outer_phase_*()` functions that call the hooks.
- `phase_*()` will be exported, but `outer_phase_*()` will not.
- I no longer think there is a need to rename `deps_target()`, `deps_code()`, or `drake_meta()`. I plan to rename and export the following:
    - `should_build_target()` => `phase_check()`
    - `just_build()` => `phase_build()`
    - `store_outputs()` => `phase_store()`

**Comment by wlandau** [comment]
This feature could even replace the `keep_going` argument. cc @krlmlr.

**Comment by idavydov** [comment]
The approach you are describing sounds really nice & flexible.

**Comment by wlandau-lilly** [comment]
Thanks. Could be relevant to https://github.com/ropenscilabs/drake-manual/issues/46 as well.

**Comment by wlandau-lilly** [comment]
We should also allow a list column of hooks for each hook type. This is similar to triggers, though I do not plan on scanning hooks for dependencies.

**Comment by wlandau** [comment]
Playing devil's advocate here: should we really be exposing so much of the internals in an API? Seems a bit complicated and dangerous on reflection. "Hasty mode" is the real sandbox here. What if we made `drake`'s ordinary build behavior more accessible in hasty mode? Maybe explicit guidance with a hook like this:

```
my_hook = function(target, config){
  meta <- drake_meta(target, config)
  check <- check_phase(target, meta, config)
  if (!check){
    return()
  }
  value <- build_phase(target, meta, config)
  store_phase(target, value, meta, config)
}
```

`drake` already has tons of features. I feel like I should be more resistant to adding more.

**Comment by idavydov** [comment]
In my opinion hasty mode is good when you want to completely override behavior of drake. Most often you would like to change one aspect of drake's behavior, e.g. use timestamps instead of hashes.

From the user perspective it would be much easier to expose well-defined phases of evaluation.

Additionally, as far as I understand it would be extremely difficult to re-implement clustermq or other parallel backend in the hasty mode. And this way hasty mode is stuck with multi-core systems.

I think that the fact that drake's does not guarantee 100% reproducibility is not such a big problem. It is easy to accidentally break reproducibility using other features such as triggers or #527.

That said, of course it is your decision in the end. These are just suggestions.

**Comment by idavydov** [comment]
Also, I think if there is API for checking targets, perhaps trigger API could be eventually deprecated or re-implemented via hooks. This potentially could lead to some simplification of the code?

**Comment by wlandau** [comment]
> In my opinion hasty mode is good when you want to completely override behavior of drake. Most often you would like to change one aspect of drake's behavior, e.g. use timestamps instead of hashes.
>
> From the user perspective it would be much easier to expose well-defined phases of evaluation.

Thinking more about this on the implementation side, I actually believe it will be difficult to change just one aspect of `drake`'s behavior using a hook. Those 3 phases are interconnected. See my comments on the timestamp example near the bottom.

> Additionally, as far as I understand it would be extremely difficult to re-implement clustermq or other parallel backend in the hasty mode. And this way hasty mode is stuck with multi-core systems.

Hasty mode uses `clustermq` for `jobs > 1`. The `clustermq.scheduler` and `clustermq.template` global options allow you to choose between local multicore computing, deployment to a scheduler, or deployment over an `ssh` connection. Implementation was actually pretty easy. I just borrowed the code that currently supports `make(parallelism = "clustermq")`.

This, of course, does not cover cases where you want a single worker on the cluster. But in that case, you could just submit a single job to your cluster that calls `make()`, rather than `make()` itself submitting the jobs.

> I think that the fact that drake's does not guarantee 100% reproducibility is not such a big problem. It is easy to accidentally break reproducibility using other features such as triggers or #527.

Reproducibility is actually really important to `drake`. It was originally designed with comptuational reproducibility as the main goal, and the README makes strong claims about it. It's never going to be perfect, and there are edge cases that break it. But I still think it is worth minimizing cases where reproducibility fails and providing a more-or-less controlled environment.

Back to the use cases you mentioned:


> 1. Create network logging to track progress of large plans on a cluster.

`drake` already logs build progress. You can failed targets and currently running targets with `progress()`, `in_progress()`, `failed()`, and `vis_drake_graph()`.

> 2. Backup storage backend (e.g. in case storing in one of the databases fails, store results in a file). This would require a hook for store.

Or wrap the relevant commands inside a function like `db()` in https://github.com/ropenscilabs/drake-manual/issues/46#issuecomment-432044266.

> 3. Early stop (#529), a hook for check.

I thought choosing a different mode (blacklist vs whitelist) for the `condition` trigger covered that one.

> 4.  Your example with timestamps, a hook for check.

To totally rely on timestamps, a "check" hook would unfortunately not be sufficient. The "store" phase needs modification too: if we really want to see gains in speed, we should skip serialization and hashing and store the target some other way.

5. Notify some kind of software when a node was computed. This would potentially allow online visualization dependency. A hook for build & store.

See [this example](https://stackoverflow.com/questions/52121537/trigger-notification-from-report-generation-in-r-drake-package). Triggers can do this too.

**Comment by wlandau** [comment]
> Also, I think if there is API for checking targets, perhaps trigger API could be eventually deprecated or re-implemented via hooks.

It is a good thought. I will still think about hooks going forward, maybe there is something both elegant and safe we can do.

**Comment by idavydov** [comment]
Thanks for the detailed response, from the practical point of view this looks convincing. And of course implementation has a priority. 

I also thought that the wrapper approach to #529 and https://github.com/ropenscilabs/drake-manual/issues/46#issuecomment-432044266 is slightly hack-ish. It limits expressions you can use for targets (e.g., `a[1:10,]` becomes impossible), and also is very repetitive.

Perhaps it's possible to solve this even without involving hooks using something like this:

```r
my.wrapper <- function(expression, target, command, deps, columns) {
  con <- connect_to_db()
  dbDisconnect(con)
  expression
  execute(con)
}
my.plan <- ... %>%
  wrap_command(my.wrapper, filter='^db_operation_')
```

**Comment by wlandau** [comment]
Yeah, good points. It seems possible to add something like a build hook just by making it easier wrap up commands. Currently, commands do not have access to the target name or the `config` object, so things might be tricky. Please feel free to add to https://github.com/ropenscilabs/drake-manual/issues/46.

Anyway, I just added a `hasty_build` argument to `make()` and `drake_config()`. So in hasty mode, you have full control over how targets are built. This will also be extremely useful for benchmarking and experimentation to make `drake` itself faster.

I will keep thinking about hooks. In retrospect, retries and timeouts would have been much easier with hooks (ref: #76). But for the meantime, I do not plan to develop this feature for non-hasty modes of execution.
