### ISSUE TITLE
Alternative to wildcard__

### ISSUE THREAD

**Issue by idavydov** [ropensci/drake#559]
What I find frustrating is that traditional approach to wildcards often leads to triple underscores in the code. It's very hard to distinguish double and triple underscores in many fonts.

```r
my.plan <- drake_plan(
  data = rnorm(size__, mean__),
  mean = mean(data_size___mean__)
) %>% evaluate_plan(
  list(
    size__ = c(100, 1000),
    mean__ = c(0, 1, 2)
    )
)
```

I couldn't come up with a satisfactory solution. Here are some ideas.

If there exists a really good work-around, it could be probably introduced into the documentation?

# .dots.

```r
my.plan <- drake_plan(
  data = rnorm(.size., .mean.),
  mean = mean(data_.size._.mean.)
) %>% evaluate_plan(
  list(
    .size. = c(100, 1000),
    .mean. = c(0, 1, 2)
    )
)
```

To me this solution looks visually better. It does not require any changes to the drake code. It might slightly clash with ggplot and other libraries, where `.names.` are used.

One objection is that drake uses `.` to escape certain characters (e.g., `-`), however in practice this does not work well anyway (note variable name `data_-1`).

```r
drake_plan(
  data = rnorm(100, mean__),
  mean = mean(data_mean__)
) %>% evaluate_plan(
  list(
    mean__ = c(-1, 0)
    )
)
#> # A tibble: 4 x 2
#>   target  command       
#>   <chr>   <chr>         
#> 1 data_.1 rnorm(100, -1)
#> 2 data_0  rnorm(100, 0) 
#> 3 mean_.1 mean(data_-1) 
#> 4 mean_0  mean(data_0)
```

# {curly.brackets}
```r
drake_plan(
  data = rnorm(`{size}`, `{mean}`),
  mean = mean(`data_{size}_{mean}`)
) %>% evaluate_plan(
  list(
    `{size}` = c(100, 1000),
    `{mean}` = c(0, 1, 2)
    )
)
```

I like the look of `{wildcards}`, it feels more like variables. But yes, it requires backticks. So I wouldn't promote it to documentation. 

Unfortunately this does not work as expected.

```
Error in grep(wildcards[i], all_values, value = TRUE) : 
  invalid regular expression '{size}', reason 'Invalid contents of {}'
```

Should wildcard names be really treated as regular expressions?

# Any other ideas?

Drake relies on parsing R code within `drake_plan()`. It might be impossible to include non-standard characters into identifiers. If that's the case we are stuck with only two "special" characters: dot (`.`) and underscore (`_`). In this case the only alternative is using backticks.

**Comment by wlandau** [comment]
Great points. I just added some text to the wildcard section of the manual (on its way to the web)

> Wildcards for `evaluate_plan()` do not need to have the double-underscore suffix. Any > valid symbol will do.
>
> ```{r evaluateplan5}
> plan <- drake_plan(
>   t  = rt(1000, df = .df.),
>   normal = runif(1000, mean = MEAN, sd = ..sd)
> )
> evaluate_plan(
>   plan,
>   rules = list(
>     MEAN = c(0, 1),
>     ..sd = c(3, 4),
>     .df. = 5:7
>   )
> )
> ```

I also added to the examples in the help file of `evaluate_plan()`. I think this makes it clear enough that you do not need `__`. Please feel free to submit pull requests to update other areas of the documentation you think need to include mentions.

**Comment by wlandau** [comment]
> It's very hard to distinguish double and triple underscores in many fonts.

Very true. Maybe a single underscore would have been slightly better. In any case, the [tidyverse style guide](http://style.tidyverse.org/) and the best, cleanest code in the community relies on underscores. Dots may be easier to look at, but generally speaking, reliance on dots can generate some unexpected edge cases when it comes to S3 methods. I think that is why the recommended style has moved to underscores.

> One objection is that drake uses . to escape certain characters (e.g., -), however in practice this does not work well anyway (note variable name data_-1).

That's because `drake` uses the base `make.names()` function. The dots are unfortunate, but I trust the results more than anything I would write myself.

> I like the look of {wildcards}...

So do I, and that's what the `glue` package uses. I even thought about using `glue` instead of `grep` instead of a backend for `drake_plan()`. Unfortunately, `drake_plan()` requires that the commands can already be parsed as code, and that is unlikely to change.

**Comment by idavydov** [comment]
Thanks, great response!

Just a small comment. The code from curly brackets section is a valid R-code.

Do you think [in `check_wildcard_rules`](https://github.com/ropensci/drake/blob/12e09dd6c3b1fa38015c9a9ec5a322a960728b36/R/wildcards.R#L269) there's a need for `fixed=TRUE`?

**Comment by wlandau** [comment]
> Do you think in check_wildcard_rules there's a need for grep(..., fixed=TRUE)?

Absolutely, thanks for catching that. I thought I put `fixed = TRUE` everywhere, but I guess I forgot.

**Comment by wlandau** [comment]
https://github.com/ropensci/drake/commit/9a94c76516c1cb18f8624de02fa40e44574117ac seems to allow curly braces. However, in the `rules` argument, I found I needed to use enclosing quotes in addition to back ticks.

``` r
library(drake)
plan <- drake_plan(
  t  = rt(1000, df = .df.),
  normal = runif(1000, mean = `{MEAN}`, sd = ..sd)
)
evaluate_plan(
  plan,
  rules = list(
    "`{MEAN}`" = c(0, 1),
    ..sd = c(3, 4),
    .df. = 5:7
  )
)
#> # A tibble: 7 x 2
#>   target     command                      
#>   <chr>      <chr>                        
#> 1 t_5        rt(1000, df = 5)             
#> 2 t_6        rt(1000, df = 6)             
#> 3 t_7        rt(1000, df = 7)             
#> 4 normal_0_3 runif(1000, mean = 0, sd = 3)
#> 5 normal_0_4 runif(1000, mean = 0, sd = 4)
#> 6 normal_1_3 runif(1000, mean = 1, sd = 3)
#> 7 normal_1_4 runif(1000, mean = 1, sd = 4)
```

Created on 2018-10-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by idavydov** [comment]
Now thanks to your fix it's possible to do interesting stuff.
What do you think about the following approach:

# Slightly dangerous
```r
plan <- drake_plan(
  data = rnorm((size), (mean)),
  mean = mean(`data_(size)_(mean)`)
) %>% evaluate_plan(
  list(
    "(size)" = c(100, 1000),
    "(mean)" = c(0, 1, 2)
    )
)
```

This could create problems if you call something like:

```r
my.mean <- my.wrapper(mean)
```

# A safer version
```r
plan <- drake_plan(
  data = rnorm(W(size), W(mean)),
  mean = mean(`data_W(size)_W(mean)`)
) %>% evaluate_plan(
  list(
    "W(size)" = c(100, 1000),
    "W(mean)" = c(0, 1, 2)
    )
)
```

It's also trivial to write a simple wrapper around `evaluate_plan()` which will automatically surround wildcard names by `W(.)` and rename columns in case `trace=TRUE`.

**Comment by wlandau** [comment]
I think it's mostly a matter of personal style, unless I am missing something and there are plans that are easy to create using `(wildcard)` and difficult using `wildcard__`. To be honest, my opinions about wildcard format are not very strong.

**Comment by wlandau** [comment]
It just occurred to me: `(wildcard)` might also work well with [`glue`](https://github.com/tidyverse/glue) if you select `.open = "("` and `.close = ")"`.

**Comment by idavydov** [comment]
Is it possible to use `evaluate_plan` with glue somehow?

**Comment by wlandau** [comment]
You could alternate between calls to `glue` and `evaluate_plan()` if that is what you mean. I considered using `glue` as a backend for `evaluate_plan()` at one point, but decided against it.
