### ISSUE TITLE
A base R replacement for formatR::tidy_source()

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#562]
# Background

I am trying to trim down [`drake`'s package dependencies](https://github.com/ropensci/drake/blob/master/DESCRIPTION#L62-L76). I removed 7 just yesterday, bringing the count down from 22 to 15. I am not too concerned about base packages like `utils`, packages in [`r-lib`](https://github.com/r-lib) like [`withr`](github.com/r-lib/withr), or [tidyverse](https://github.com/tidyverse) packages like [`dplyr`](https://github.com/tidyverse/dplyr). And it seems infeasible to remove [`storr`](https://github.com/richfitz/storr), [`igraph`](github.com/igraph/rigraph), or `codetools`. So as I continue on, I hope to find a base R replacement for `formatR::tidy_source()`.

`formatR::tidy_source()` provides a means of [standardizing a target's commands](https://github.com/ropensci/drake/blob/4a85199412d5cea7620f74b43d9356ec3e4f5f6c/R/commands.R#L66-L82). This standardization removes comments, strange indentation, etc. before `drake` decides if a command changed since last `make()`. Clearly, if all we do is add spaces or comments, we don't want `drake` to rebuild the target.

# Requirements

A base R replacement should

1. Style the text's indentation and spacing in a consistent manner.
2. Remove comments.
3. Turn assigment `=`s and `<-`'s into `->`.

# Challenges

R's default parser will take care of (1) and (2), but (3) is tricky.

``` r
library(magrittr)
  parse(text = "z = {f('#') # comment
      
x <- 5
    }",
    keep.source = FALSE
  )[[1]] %>%
    deparse() %>%
    cat(sep = "\n")
#> z = {
#>     f("#")
#>     x <- 5
#> }
```

<sup>Created on 2018-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
<sup>Created on 2018-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

# Rollout

This change will invalidate all targets in all workflows, so I am postponing the release until `drake` 7.0.0 (first half of 2019). We should also add a warning in [`assert_compatible_cache()`](https://github.com/ropensci/drake/blob/4067a755b26fdc055d1ededa13953a2e5e196041/R/cache.R#L513-L542).

**Comment by wlandau** [comment]
To elaborate: this is `drake`'s current behavior.

``` r
drake:::standardize_command
#> function (x) 
#> {
#>     x <- ignore_ignore(x) %>% language_to_text
#>     formatR::tidy_source(source = NULL, comment = FALSE, blank = FALSE, 
#>         arrow = TRUE, brace.newline = FALSE, indent = 4, output = FALSE, 
#>         text = as.character(x), width.cutoff = 119)$text.tidy %>% 
#>         paste(collapse = "\n") %>% braces
#> }
#> <bytecode: 0x4631438>
#> <environment: namespace:drake>
```

<sup>Created on 2018-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wlandau** [comment]
Also cc @lorenzwalthert. Do you have advice on turning assignment `=` into `<-` using base R?

**Comment by wlandau** [comment]
Relevant: https://stackoverflow.com/questions/53035126/turn-into-using-only-base-r?noredirect=1#comment92971001_53035126

**Comment by s-fleck** [comment]
have you looked at base R`s parse()? that's one step further then just restyling the code

**Comment by hrbrmstr** [comment]
```
library(magrittr)

raw_src <- "z = {f('#') # comment

x <- 5
y = 'test'
    }"

first <- parse(text = raw_src, keep.source = TRUE)

src_info <- getParseData(first, TRUE)

elements_with_equals_assignment <- subset(src_info, token == "EQ_ASSIGN")

raw_src_lines <- strsplit(raw_src, "\n")[[1]]

for (idx in 1:nrow(elements_with_equals_assignment)) {
  stringi::stri_sub(
    raw_src_lines[elements_with_equals_assignment[idx, "line1"]],
    elements_with_equals_assignment[idx, "col1"],
    elements_with_equals_assignment[idx, "col2"]
  ) <- "<-"
}

parse(
  text = paste0(raw_src_lines, collapse="\n"),
  keep.source = FALSE
)[[1]] %>%
  deparse() %>%
  cat(sep = "\n")
## z <- {
##     f("#")
##     x <- 5
##     y <- "test"
## }
```

**Comment by wlandau** [comment]
Thank you so much, @hrbrmstr! Your demo of `utils::getParseData()` (which I did not know about before) was exactly what I needed to see!

I actually prefer not to depend on `stringi` because it takes a long time to compile, among other reasons. And as for tidyverse packages, I do not mean the package called `tidyverse`, just a select few like `dplyr` and `rlang` that are already in the `DESCRIPTION` file.

Anyway, if we go through each line backwards, we can handle equals signs using only `base` and `utils`.

``` r
standardize_code <- function(x){
  x <- as.character(x)
  parsed <- parse(text = x, keep.source = TRUE)
  info <- utils::getParseData(parsed, includeText = TRUE)
  equals <- info[info$token == "EQ_ASSIGN", ]
  lines <- strsplit(x, "\n")[[1]]
  for (line in unique(equals$line1)){
    line_info <- equals[equals$line1 == line, ]
    for (col in sort(line_info$col1, decreasing = TRUE)){
      lines[line] <- paste0(
        substr(x = lines[line], start = 0, stop = col - 1),
        "<-",
        substr(x = lines[line], start = col + 1, stop = nchar(lines[line]))
      )
    }
  }
  deparse(
    parse(
      text = paste0(lines, collapse="\n"),
      keep.source = FALSE
    )[[1]]
  )
}

x <- "z = {f('#'); w = 123; char = \"str\"  # comment

x <- 5
  y = 'test'  
z <- function(a = 1){
  sqrt(x = a)
}
}"

y <- standardize_code(x)
y
#>  [1] "z <- {"                     "    f(\"#\")"              
#>  [3] "    w <- 123"               "    char <- \"str\""       
#>  [5] "    x <- 5"                 "    y <- \"test\""         
#>  [7] "    z <- function(a = 1) {" "        sqrt(x = a)"       
#>  [9] "    }"                      "}"

cat(y, sep = "\n")
#> z <- {
#>     f("#")
#>     w <- 123
#>     char <- "str"
#>     x <- 5
#>     y <- "test"
#>     z <- function(a = 1) {
#>         sqrt(x = a)
#>     }
#> }
```

<sup>Created on 2018-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

So `standardize_command()` will look like this:

```r
standardize_command <- function(x) {
  x <- ignore_ignore(x) %>%
    language_to_text()
  formatR::tidy_source(
    source = NULL,
    comment = FALSE,
    blank = FALSE,
    arrow = TRUE,
    brace.newline = FALSE,
    indent = 4,
    output = FALSE,
    text = as.character(x),
    width.cutoff = 119
  )$text.tidy %>%
    paste(collapse = "\n") %>%
    braces
}
```

**Comment by wlandau** [comment]
So `standardize_command()` will look like this:

```r
standardize_command <- function(x) {
  x <- ignore_ignore(x) %>%
    language_to_text() %>%
    standardize_code()
}
```

**Comment by wlandau** [comment]
From [this comment](https://stackoverflow.com/questions/53035126/turn-into-using-only-base-r/53036016#comment92972773_53036016)

> +1 but i could break it with '='(zz,yy) and zz = yy = 3

Above, `x = y = z` becomes `x <- y <- z`. We retain an equals sign for <code>'='(zz, yy)</code> but that special case is unlikely to crop up in user-side `drake` commands.

Another thing: the following code

```r
function(b = mtcars){
  lm(mpg ~ wt, data = b)
} -> f
```

becomes


```r
function(b = mtcars) f <- {
  lm(mpg ~ wt, data = b)
}
```

I am okay with that. For the purposes of `drake:::standardize_command()`, the code does not actually need to execute properly. It just needs to be in a standardized format that only depends on what the return value is likely to be.

**Comment by s-fleck** [comment]
I wonder if there is any way to utilise the byte compiler for this? something like compile the function, calculate the md5 sum of the byte code, see if it matches the crc of the last known version. I tried playing around with this yesterday but I could find no way to retrieve the actual byte code (just its memory address)

**Comment by lorenzwalthert** [comment]
I am not sure I can follow, but thanks all involved people to work on this :-) 

First, formatR has zero dependencies, so the benefit of replacing functionality from a widely used package with an *internal* solution for a non-trivial task (problems mentioned throughout the thread) does not seem that beneficial to me.

Second, I am not sure if *styling* is the way to go if the problem can be understood as *caching*. I.e. why not hashing the parse data? 
``` r
library(magrittr)

assign_one <- "z = {f('#') # comment
x <- 5

y -> 'test'
}"

assign_two <- "z <- {f('#') # comment

x = 5
y = 'test'
}"

hash_code <- function(code) {
  # reverse '->' to '<-' AND keep code valid
  text <- deparse(parse(text = code)[[1]])
  parse_data <- parse(text = code, keep.source = TRUE) %>%
    getParseData(includeText = TRUE)
  parse_data$text[parse_data$EQ_ASSIGN | parse_data$LEFT_ASSIGN] <- "="
  hash <- parse_data[parse_data$token != "COMMENT" & parse_data$terminal, c("token", "text")] %>%
    digest::digest()
}



lapply(list(assign_one, assign_one), hash_code)
#> [[1]]
#> [1] "11a6e12298f1e850dcd2bd64115a6e0c"
#> 
#> [[2]]
#> [1] "11a6e12298f1e850dcd2bd64115a6e0c"
```

<sup>Created on 2018-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Note that this turns `->` into `<-` in a **valid** way and then converts both to `=`, so it meets all requirements outlined above under (3). Credit to https://github.com/r-lib/styler/issues/409#issuecomment-414359788.

Third, allowing any other assignment than `=` inside `drake::drake_plan()` is wrong and I believe it should not only throw a warning, but in fact return a plain error, as the resulting plan is not useful anyways.
``` r
drake::drake_plan(g <- x)
#> Warning: Use `=` instead of `<-` or `->` to assign targets to commands in `drake_plan()`. For example, write `drake_plan(a = 1)` instead of `drake_plan(a <- 1)`. Arrows were used to declare these commands:
#>   g <- x
#> # A tibble: 1 x 2
#>   target         command
#>   <chr>          <chr>  
#> 1 drake_target_1 g <- x
```

This is really an edge case and getting it right is probably quite hard. So I am not sure why we are trying to create a solution that can hash `x <- 1`  and `1 -> x` to the same value.

<sup>Created on 2018-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by lorenzwalthert** [comment]
I am not sure I can follow, but thanks all involved people to work on this :-) 

First, formatR has zero dependencies, so the benefit of replacing functionality from a widely used package with an *internal* solution for a non-trivial task (problems mentioned throughout the thread) does not seem that beneficial to me.

Second, I am not sure if *styling* is the way to go if the problem can be understood as *caching*. I.e. why not hashing the parse data? We already have `digest` as a first-level dependency, so here is my proposal:
``` r
library(magrittr)

assign_one <- "z = {f('#') # comment
x <- 5

y <- 'test'
z <- 4

x2 <- 'test2' 
}"

assign_two <- "z = {f('#') # comment X
x = 5

y <- 'test'
z = 4
'test2' -> x2
}"

hash_code <- function(code) {
  # reverse '->' to '<-' AND keep code valid
  code <- deparse(parse(text = code)[[1]])
  parse_data <- parse(text = code, keep.source = TRUE) %>%
    getParseData(includeText = TRUE)
  change_row <- parse_data$token == "LEFT_ASSIGN"
  parse_data$text[change_row] <- "="
  parse_data$token[change_row] <- "EQ_ASSIGN"
  hash <- parse_data[parse_data$token != "COMMENT" & parse_data$terminal, c("token", "text")] %>%
    c() %>%
    digest::digest()
}



lapply(list(assign_one, assign_two), hash_code)
#> [[1]]
#> [1] "96c34606528d64f2d258731a79837c1b"
#> 
#> [[2]]
#> [1] "96c34606528d64f2d258731a79837c1b"
```

<sup>Created on 2018-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>


Note that this turns `->` into `<-` in a **valid** way and then converts both to `=`, so it meets all requirements outlined above under (3). Credit for reversing `->` to https://github.com/r-lib/styler/issues/409#issuecomment-414359788.

Third, allowing any other assignment than `=` inside `drake::drake_plan()` is wrong and I believe it should not only throw a warning, but in fact return a plain error, as the resulting plan is not useful anyways.
``` r
drake::drake_plan(g <- x)
#> Warning: Use `=` instead of `<-` or `->` to assign targets to commands in `drake_plan()`. For example, write `drake_plan(a = 1)` instead of `drake_plan(a <- 1)`. Arrows were used to declare these commands:
#>   g <- x
#> # A tibble: 1 x 2
#>   target         command
#>   <chr>          <chr>  
#> 1 drake_target_1 g <- x
```
<sup>Created on 2018-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

This is really an edge case and getting it right is probably quite hard. So I am not sure why we are trying to create a solution that can hash `x <- 1`  and `1 -> x` to the same value.

**Comment by wlandau** [comment]
I really `hash_code()` because it is tidy and explicit. I will introduce it into #563 and give it more thought.

I think this is unrelated to the API function `drake_plan()`. There, the expected format is `drake_plan(target = command)`.

```r
drake::drake_plan(y = g <- x)
#> # A tibble: 1 x 2
#>   target command
#>   <chr>  <chr>  
#> 1 y      g <- x 
```

**Comment by wlandau** [comment]
Also, I think we can avoid serialization when we hash if we paste everything together first. Could save some time that we could reinvest in a long-ish hash algorithm.

```r
standardize_code <- function(x){
  x <- as.character(x)
  x <- deparse(parse(text = x)[[1]])
  info <- parse(text = x, keep.source = TRUE) %>%
    utils::getParseData(includeText = TRUE)
  change <- info$token == "LEFT_ASSIGN"
  info$text[change_row] <- "="
  info$token[change_row] <- "EQ_ASSIGN"
  info[info$token != "COMMENT" & info$terminal, c("token", "text")] %>%
    lapply(FUN = paste, collapse = " ") %>%
    paste(collapse = " >> ") %>%
    digest::digest(algo = "sha256", serialize = FALSE)
}
```

**Comment by wlandau** [comment]
But it still seems to have problems.

``` r
library(magrittr)
standardize_code <- function(x){
  x <- deparse(parse(text = as.character(x), keep.source = FALSE)) %>%
    paste(collapse = "\n")
  info <- parse(text = x, keep.source = TRUE) %>%
    utils::getParseData(includeText = TRUE)
  change <- info$token == "LEFT_ASSIGN"
  info$text[change] <- "="
  info$token[change] <- "EQ_ASSIGN"
  info[info$token != "COMMENT" & info$terminal, c("token", "text")] %>%
    lapply(FUN = paste, collapse = " ") %>%
    paste(collapse = " >> ") %>%
    digest::digest(algo = "sha256", serialize = FALSE)
}
standardize_code("y=sqrt(x=1)")
#> [1] "e133b7dbb0b12167bd18f31f82ecc79cdf9f6914c256eb5762d749502e5457a4"
standardize_code("y <- sqrt(x = 1)")
#> [1] "2043d80987b0787db97bc408d3bbad3b974e92e4106f3d2a258c8f2d46e5e014"
```

<sup>Created on 2018-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

It appears the `EQ_ASSIGN` gets labeled as `EQ_SUB`.

``` r
library(magrittr)
standardize_code <- function(x){
  x <- deparse(parse(text = as.character(x), keep.source = FALSE)) %>%
    paste(collapse = "\n")
  info <- parse(text = x, keep.source = TRUE) %>%
    utils::getParseData(includeText = TRUE)
  change <- info$token == "LEFT_ASSIGN"
  info$text[change] <- "="
  info$token[change] <- "EQ_ASSIGN"
  info[info$token != "COMMENT" & info$terminal, c("token", "text")]
}
standardize_code("y=sqrt(x=1)")
#>                   token       text
#> 1  SYMBOL_FUNCTION_CALL expression
#> 2                   '('          (
#> 4            SYMBOL_SUB          y
#> 5                EQ_SUB          =
#> 6  SYMBOL_FUNCTION_CALL       sqrt
#> 7                   '('          (
#> 9            SYMBOL_SUB          x
#> 10               EQ_SUB          =
#> 11            NUM_CONST          1
#> 13                  ')'          )
#> 17                  ')'          )
standardize_code("y <- sqrt(x = 1)")
#>                   token       text
#> 1  SYMBOL_FUNCTION_CALL expression
#> 2                   '('          (
#> 4                SYMBOL          y
#> 5             EQ_ASSIGN          =
#> 7  SYMBOL_FUNCTION_CALL       sqrt
#> 8                   '('          (
#> 10           SYMBOL_SUB          x
#> 11               EQ_SUB          =
#> 12            NUM_CONST          1
#> 14                  ')'          )
#> 18                  ')'          )
```

<sup>Created on 2018-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
```

**Comment by lorenzwalthert** [comment]
You forgot to get rid of the `expression` term using subsetting, i.e. you have
```r
  x <- deparse(parse(text = as.character(x), keep.source = FALSE)) %>%
```
but you need 
```r
  x <- deparse(parse(text = as.character(x), keep.source = FALSE)[[1]]) %>%
```
so
``` r
library(magrittr)
standardize_code <- function(x) {
  x <- deparse(parse(text = as.character(x), keep.source = FALSE)[[1]]) %>%
    paste(collapse = "\n")
  info <- parse(text = x, keep.source = TRUE) %>%
    utils::getParseData(includeText = TRUE)
  change <- info$token == "LEFT_ASSIGN"
  info$text[change] <- "="
  info$token[change] <- "EQ_ASSIGN"
  info[info$token != "COMMENT" & info$terminal, c("token", "text")] %>%
    lapply(FUN = paste, collapse = " ") %>%
    paste(collapse = " >> ") %>%
    digest::digest(algo = "sha256", serialize = FALSE)
}
standardize_code("y=sqrt(x=1)")
#> [1] "2f3905f7987e8b54c1cdad95475c8a754a591e5a124a43123df387337abb4866"
standardize_code("y <- sqrt(x = 1)")
#> [1] "2f3905f7987e8b54c1cdad95475c8a754a591e5a124a43123df387337abb4866"
```

<sup>Created on 2018-10-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000)</sup>

**Comment by wlandau** [comment]
Awesome, thanks! With that, we also need to handle empty strings.

```r
standardize_code <- function(x){
  if (!length(x)){
    return(as.character(NA))
  }
  x <- deparse(parse(text = as.character(x), keep.source = FALSE)[[1]]) %>%
    paste(collapse = "\n")
  info <- parse(text = x, keep.source = TRUE) %>%
    utils::getParseData(includeText = TRUE)
  change <- info$token == "LEFT_ASSIGN"
  info$text[change] <- "="
  info$token[change] <- "EQ_ASSIGN"
  info[info$token != "COMMENT" & info$terminal, c("token", "text")] %>%
    lapply(FUN = paste, collapse = " ") %>%
    paste(collapse = " >> ") %>%
    digest::digest(algo = "sha256", serialize = FALSE)
}
```

And now, it passes `drake`'s test suite. I have updated #563.

**Comment by wlandau** [comment]
A potential speed issue: https://github.com/ropensci/drake/pull/563#issuecomment-434284360
