### ISSUE TITLE
Support argument separator for evaluate_plan

### ISSUE THREAD

**Issue by lorenzwalthert** [ropensci/drake#565]
Sometimes, it would be convenient for `evaluate_plan()` to keep one target as is. This is currently not possible (if I am not mistaken). Let's look at the following example: 
``` r
library(drake)
methods <- drake_plan(
  regression1 = reg1(dataset__),
  regression2 = reg2(dataset__)
)
datasets <- drake_plan(
  small = simulate(5),
  large = simulate(50)
)
evaluate_plan(methods,
  wildcard = "dataset__",
  values = c("", "small", "large")
)
#> # A tibble: 6 x 2
#>   target            command    
#>   <chr>             <chr>      
#> 1 regression1_      reg1()     
#> 2 regression1_small reg1(small)
#> 3 regression1_large reg1(large)
#> 4 regression2_      reg2()     
#> 5 regression2_small reg2(small)
#> 6 regression2_large reg2(large)
```

<sup>Created on 2018-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

There is no way I can prevent the underscore being injected in the target name. I.e. keeping `regression1` as a target is not possible, even if I specify the empty string in the rules. Hence, I propose to introduce an argument `sep` or similar that defaults to `_` to separate the initial target name and the suffix.

**Comment by wlandau** [comment]
Functions that now support a new `sep` argument:

- `gather_by()`
- `evaluate_plan()`
- `expand_plan()`
- `plan_analyses()`
- `plan_summaries()`
- `reduce_by()`
- `reduce_plan()`
