### ISSUE TITLE
Faster code analysis

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#573]
Related: #41. The code analysis for automatic dependency detection is the biggest bottleneck in initialization. A couple goals:

1. Detect true globals in the existing recursion so we can avoid `codetools::findGlobals()`.
2. Consider a custom C++ backend for the code analysis.

I think we should do (1) before (2).

**Comment by wlandau** [comment]
So apparently, we can remove a lot of overhead just by removing calls to `parse()`. Here is a `profvis` for a really long command.

![bottleneck](https://user-images.githubusercontent.com/1580860/47974904-9e854980-e079-11e8-8f98-3bc8d8d704a7.png)

**Comment by wlandau** [comment]
After #574, the benchmarks look much better.

``` r
library(drake)
n <- 1000
x <- parse(
  text = paste0(
    "max(",
    paste0(paste0("target_", seq_len(n)), collapse = ", "),
    ")"
  )
)[[1]]
pkgconfig::set_config("drake::strings_in_dots" = "literals")
profvis::profvis(drake:::command_dependencies(x))
```

![](https://i.imgur.com/AEbC0RD.png)

<sup>Created on 2018-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wlandau** [comment]
Now, the bottleneck really is `codedepends`.

**Comment by wlandau** [comment]
Add-on item from https://github.com/ropensci/drake/issues/615#issuecomment-447585359: throw a warning whenever a scanned call is likely to modify the global environment. Users should write pure functions, but they do not always do so.

- `data()`
- `<<-`
- `->>`
- `library()`
- `require()`
- `attachNamespace()`
- `loadNamespace()`
- `requireNamespace()`
- `unloadNamespace()`

**Comment by wlandau** [comment]
To close this issue, it is enough to:

- [ ] Merge #625.
- [ ] Address the edge case described in #625.
- [ ] Do more profiling.

**Comment by wlandau** [comment]
In https://github.com/ropensci/drake/pull/625, the bottleneck seems to appending stuff `results$globals`. Maybe we should use a hash table.

![screenshot_20181218_074154](https://user-images.githubusercontent.com/1580860/50155570-69842d80-029a-11e9-8d43-bcbe27f0f242.png)

**Comment by wlandau** [comment]
The last thing I will try before closing this issue is to pre-compute `ignored_symbols_list`, a list that we can use for creating and populating [`locals`](https://github.com/ropensci/drake/blob/d39e0ac086a317024762fcb361c0427b35e0d55a/R/code_analysis.R#L11) faster (using `list2env(hash = TRUE)`) at the beginning of [`analyze_code()`](https://github.com/ropensci/drake/blob/d39e0ac086a317024762fcb361c0427b35e0d55a/R/code_analysis.R#L1). After that, we can work on improvements on a case-by-case basis.

**Comment by wlandau** [comment]
As of 4cce23812262d005228eeb36185f7b2760849173, I think I have exhausted the lowest-hanging fruit to speed up the code analysis. A lot more work needs to be done to speed up `drake` overall. Issues like [this one](https://stackoverflow.com/questions/53781148/is-there-a-way-of-chunking-drake-outputs-to-speed-up-plan-verification-and-dis) are coming up (though I do not know if OP was using version 6.2.1, which is faster than its predecessors).

I am closing this issue in favor of more targeted ones that will come up later.

**Comment by wlandau** [comment]
I will say that I could really use help with the profiling. Realistic test cases are usually too large for `profvis` to handle, and more targeted ones are not realistic enough to be useful. cc @bpbond.

**Comment by bpbond** [comment]
You mentioned this previously, and I'm happy to take a hard look if useful.

**Comment by wlandau** [comment]
@bpbond, an update: #633 sped up `drake` quite a lot, and I am currently out of hypotheses about the next potential bottlenecks.

**Comment by wlandau** [comment]
I think what we're after is [`Rprof()`](https://www.rdocumentation.org/packages/utils/versions/3.4.3/topics/Rprof) + [`profile`](https://github.com/r-prof/profile). The [overhead example](https://github.com/wlandau/drake-examples/tree/master/overhead) may be a good place to start.
