### ISSUE TITLE
Syntax highlighting of styler and drake potentially cause styler devel to fail on reverse dependency check

### ISSUE THREAD

**Issue by lorenzwalthert** [ropensci/drake#584]
I need to submit styler tomorrow to safely retain it on cran because of r-lib/styler#419. As I was running revdepcheck, I found the following example in the help file of `drake_plan_source()` in drake not working anymore with the styler devel version. I think it has to do with syntax highlighting that is potentially done twice. I will look into it this afternoon. Do you have any ideas why this could happen? 

```r
plan <- drake::drake_plan(
  small_data = download_data("https://some_website.com") %>%
    select_my_columns() %>%
    munge(),
  large_data_raw = target(
    command = download_data("https://lots_of_data.com") %>%
      select_top_columns,
    trigger = trigger(
      change = time_last_modified("https://lots_of_data.com"),
      command = FALSE,
      depend = FALSE
    ),
    timeout = 1e3
  ),
  strings_in_dots = "literals"
)
print(plan)
if (requireNamespace("styler", quietly = TRUE)){
  source <- drake_plan_source(plan)
  print(source) # Install the prettycode package for syntax highlighting.
}
## Not run: 
file <- tempfile() # Path to an R script to contain the drake_plan() call.
writeLines(source, file) # Save the code to an R script.

## End(Not run)
``

**Comment by lorenzwalthert** [comment]
Ok, I found the problem. The declaration of `drake:::print.drake_plan_source()` is:

```r

function(x, ...) {
  if (requireNamespace("prettycode", quietly = TRUE)) {
    x <- prettycode::highlight(x)
    NextMethod()
  }
  else {
    NextMethod()
  }
}
```

So indeed we highlight twice, once in styler and once in drake and it throws an error at the second time:

``` r
prettycode::highlight(prettycode::highlight("a <- 3"))
#> Error in parse(text = code, keep.source = TRUE) : 
#>   <text>:1:3: unexpected input
```


So I think ideally drake does not do the highlighting if the styler version is beyond 1.0.2 because styler already does it as of version 1.0.2.9000. Like this:
```r
print.drake_plan_source <- function (x, ...) {
  if (getNamespaceVersion("styler") > "1.0.2") {
    NextMethod()
  }
  else {
    x <- prettycode::highlight(x)
    NextMethod()
  }
}
```

**Comment by lorenzwalthert** [comment]
O

**Comment by wlandau** [comment]
In addition, all the tests involving `styler` are skipped on CRAN, so you should be able to submit the latest `styler` without breaking `drake`.

**Comment by lorenzwalthert** [comment]
Tests yes, but R CMD CHECK also checks examples, which is where the problem occurred.

**Comment by wlandau** [comment]
I had planned the next drake CRAN release for late December, and I am on vacation this week. Is there a workaround in styler itself that can make it CRAN-ready more quickly?

Ultimately, I think we need prettycode::highlight to be idempotent.

**Comment by lorenzwalthert** [comment]
I think we can submit with reference to this issue and that the devel version of drake is not failing and a new release is planned in December. I think this is in line with common practice. Alternatively, we can drop the highlighting feature, but I'd try submitting as is first.
