### ISSUE TITLE
is drake_debug safe?

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#587]
`drake_debug` calls `build_store` which eventually gets to `store_outputs`. It looks like the user can in principle introduce extra code in debug mode, hit `c`, and drake will store the output with the hash of the unaltered code. Is this actually what's going on? I think that `drake_debug` shouldn't store anything, including dependency hashes etc.

**Comment by wlandau** [comment]
Skipping storage is an easy fix, and I think it is the right call. I will take care of it when I return to the office on Tuesday.
