### ISSUE TITLE
deploying to a Docker container for reproducible workflow

### ISSUE THREAD

**Issue by januz** [ropensci/drake#589]
@wlandau Thank you so much for your work on the `drake` package! I only recently started using it and now can't imagine working without it anymore...

Over the last days, I I have been researching ways to package a `drake` workflow for a research project that I plan to publish as a research compendium and found @tiernanmartin's `drakepkg`. I have since worked on a fork of `drakepkg` (see [here](https://github.com/tiernanmartin/drakepkg/issues/6#issue-385417951)).

To encourage users to use a reproducible computational environment, I include a Dockerfile and a link to run the Docker container with the analysis package installed on Binderhub in the `README` of the Github repository. I would like to go one step further though and extend the `reproduce_analysis()` function by an option to deploy the processing to a Docker container by default. That way, users could use the same computational environment even when they install the package locally and one can ensure that they get a warning that re-running the analysis in their own environment without Docker doesn't ensure "complete" reproducibility.

Unfortunately, I don't understand how to deploy drake workflows to a Docker container. I have tried your example from [here](https://github.com/wlandau/drake-examples/blob/master/Docker-psock/run.R), but this results in a timeout error:

```
Error in socketConnection("localhost", port = port, server = TRUE, blocking = TRUE,  : 
  reached elapsed time limit
```

The docker container seems to be started (i.e., it's listed when I run `docker ps` in the terminal). Do you have an idea what might be going wrong?

Thank you for your help!

**Comment by wlandau** [comment]
@januz could we move this issue to https://github.com/wlandau/drake-examples/issues/7?
