### ISSUE TITLE
Remove dependency on dplyr

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#593]
Of all `drake`'s strict package dependencies, `dplyr` is the heaviest. Challenges:

- Replace `group_by() %>% do()` etc. with base R.
- Substitute `bind_rows(x, y)` with something that can handle different columns between `x` and `y`.

**Comment by bpbond** [comment]
Happy to help here if useful.

**Comment by wlandau** [comment]
Thank you for the offer, @bpbond! I would really appreciate help reducing package dependencies in both "Imports:" and "Suggests:". I knew extricating `dplyr` and `tidyselect` would be messy, so I took care of them myself in #594.

In "Imports:", `purrr` and `R6` are the easiest to tackle. Don't worry about `pkgconfig` or `formatR`, those two will go away on their own in the next major release (see #564 and #563). `codetools` is super difficult, and I am working on replacing it via #573. Other than that, I have good reasons for keeping `digest`, `igraph`, `rlang`, `storr`, `tibble`, and `utils` where they are.

The "Suggests:" list is massive. At this point, `abind`, `MASS`, `DBI`, and `RSQLite` are only used in tests. Likewise, `dplyr` and `ggplot` should only be needed in examples (especially https://github.com/wlandau/drake-examples). I may remove `ggraph` at some point because `drake` can now print static graphs automatically with `webshot` (see the documentation of the `file` argument of `vis_drake_graph()`). `future.apply` and `txtq` are likely to go away via #561 at some point.

**Comment by bpbond** [comment]
I'll take a look a de-`purrr`ing the code.

**Comment by wlandau** [comment]
Thanks, that would really help!

**Comment by wlandau** [comment]
I am so glad you are still interested in helping!

## Profiling

Now that the "Imports:" list is much smaller, I think the number 1 priority is speed. Computational overhead is still a major weakness, and with `magrittr` and `dplyr` gone from the stack, profiling with [`profvis`](https://rstudio.github.io/profvis/) is much easier than in the past. In other words, there has never been a better time to speed up `drake`. You could make a huge impact this way.

The [overhead example](https://github.com/wlandau/drake-examples) (ref: #498) is a toy workflow that isolates and exaggerates `drake`'s busywork, and the files contain a GNU Make counterpart for comparison.

## More cleanup and streamlining

As long as we are thinking about shortening the "Suggests:" list, maybe we could use a base R replacement for `rprojroot::find_root()`. It is only called once in `R/test.R`.

I think we can convert the test in `tests/testthat/test-dbi.cache.R` into a new example in https://github.com/wlandau/drake-examples. The main issue it was testing is that `drake` needs to support parallel computing even with caches that do not support parallel writes. `make(caching = "master")` makes sure only the master process saves stuff to the cache, and I think the following test will suffice in place of `tests/testthat/test-dbi.cache.R`. The, we can remove `DBI` and `RSQLite` from "Suggests:"

```r
test_with_dir("master caching, environment caches and parallelism", {
  skip_on_cran()
  skip_if_not_installed("future")
  load_mtcars_example()
  future::plan(future::multiprocess)
  config <- make(
    my_plan,
    cache = storr::storr_environment(), # not thread-safe
    caching = "master",
    parallelism = "future",
    jobs = 2
  )
  expect_true("report" %in% justbuilt(config))
})
```

Related: https://ropenscilabs.github.io/drake-manual/store.html#caches. In light of #561, I think that section of the manual should focus on `caching = "master"` and the "clustermq" and "future" backends.

Also related: `tests/testthat/test-dbi.cache.R` makes use of the `fetch_cache` argument of `make()` and `drake_config()`, a feature I never actually followed through with. In light of `caching = "master"`, I was planning to remove all use of `fetch_cache` internally and deprecate the `fetch_cache` argument in all exported functions.

The main pedagogical example ([source here](https://github.com/wlandau/drake-examples) + `load_main_example()`) is the reason why `dplyr` is still in "Suggests:". I think that example's use of packages makes sense, and I do not think we actually need a `load_main_example()` function. The right solution is probably to deprecate it and eventually remove it, but I do not want to rush into that too fast.
