### ISSUE TITLE
Preserve backticks in wildcard template plans (or allow chained plan templates)

### ISSUE THREAD

**Issue by ashiklom** [ropensci/drake#595]
I am trying to use wildcard templating to create a plan _with multiple steps_ for each wildcard. Ideally, I would love to do something like this:

```r
input <- paste0("obj-", 1:3)
plan_temp <- drake_plan(
  targeta = paste("input__", "a"),
  targetb = paste(targeta, "b"),
  strings_in_dots = "literals"
)
plan <- evaluate_plan(plan_temp, rules = list(input__ = input))
```

...where the `targeta` in the `targetb` command is expanded for every `input__`. However, as far as I can tell, this is not currently possible (any may be too difficult to implement anyway) and this plan evaluates to:

```
  target        command                  
  <chr>         <chr>                    
1 targeta_obj.1 "paste(\"obj-1\", \"a\")"
2 targeta_obj.2 "paste(\"obj-2\", \"a\")"
3 targeta_obj.3 "paste(\"obj-3\", \"a\")"
4 targetb       "paste(targeta, \"b\")"  
```

As an alternative, I've been trying to use the built-in (?) rules for target naming to automatically generate a bunch of `targetb`s:

```r
plan_temp <- drake_plan(
  targeta = paste("input__", "a"),
  targetb = paste(`targeta_input__`, "b"),
  strings_in_dots = "literals"
)
plan <- evaluate_plan(plan_temp, rules = list(input__ = input))
```

This works well _as long as the expansion only produces syntactically valid output_. In this example, the resulting plan looks like this:

```
# A tibble: 6 x 2
  target        command                      
  <chr>         <chr>                        
1 targeta_obj.1 "paste(\"obj-1\", \"a\")"    
2 targeta_obj.2 "paste(\"obj-2\", \"a\")"    
3 targeta_obj.3 "paste(\"obj-3\", \"a\")"    
4 targetb_obj.1 "paste(targeta_obj-1, \"b\")"
5 targetb_obj.2 "paste(targeta_obj-2, \"b\")"
6 targetb_obj.3 "paste(targeta_obj-3, \"b\")"
```

There are two issues here: 

(1) The "true" target (`targeta_obj-1`) is **silently converted to a syntactically valid name** (`targeta_obj.1`), which means it cannot be accessed by the same wildcard further down; and (2) the **backticks** around `targeta_input__` that would have allowed me to use syntactically invalid names are **dropped**. 

As a result, all the `targetb` targets fail to build because `targeta_obj-1` is interpreted as `targeta_obj - 1` and `targeta_obj` doesn't exist.

I understand why this happens the way it does, and that these problems may not be fixable (at least, not easily), but I think it would at least be worth adding a caveat to the documentation that this is an edge case where wildcard templating doesn't work as one might expect.

**Comment by ashiklom** [comment]
For documentation purposes, the workaround I'm currently using is to split these up into two plans and use `make.names` to reference the correct names for `targetb`.

```r
plana_temp <- drake_plan(targeta = paste("input__", "a"))
plana <- evaluate_plan(plana_temp, rules = list(input__ = input))
planb_temp <- drake_plan(targetb = paste(inputb__, "b"))
planb <- evaluate_plan(planb_temp, rules = list(inputb__ = make.names(input)))
plan <- bind_plans(plana, planb)
plan
```

**Comment by wlandau** [comment]
Sorry @ashiklom, I do not think I understand what you mean. Would you show an example of the data frame you want to produce?

Are you asking about which combinations of wildcard values you can have? Combinations of multiple wildcards can be awkward in some complicated use cases, and a nice workaround is to generate a grid of function arguments and feed it to `map_plan()`.

Or are you asking about the sanitation of target names specifically? `drake` always treats targets as ordinary variables in R, so all target names must be valid symbol names, and `drake` calls `make.names()` as part of the preprocessing. Sorry, but that is unlikely to change in the future.

**Comment by ashiklom** [comment]
> Are you asking about which combinations of wildcard values you can have?
> Or are you asking about the sanitation of target names specifically?

Both, because they both contributed to my use case. But they are different topics, so I probably should have created two separate issues.

This code generates the `data.frame` I want using the current version of `drake`:

``` r
library(drake)
pkgconfig::set_config("drake::strings_in_dots" = "literals")

clean(destroy = TRUE)

input <- paste0("obj-", 1:3)

plana_temp <- drake_plan(targeta = paste("input__", "a"))
plana <- evaluate_plan(plana_temp, rules = list(input__ = input))
planb_temp <- drake_plan(targetb = paste(targeta_inputb__, "b"))
planb <- evaluate_plan(planb_temp, rules = list(inputb__ = make.names(input)))
plan <- bind_plans(plana, planb)
plan
#> # A tibble: 6 x 2
#>   target        command                      
#>   <chr>         <chr>                        
#> 1 targeta_obj.1 "paste(\"obj-1\", \"a\")"    
#> 2 targeta_obj.2 "paste(\"obj-2\", \"a\")"    
#> 3 targeta_obj.3 "paste(\"obj-3\", \"a\")"    
#> 4 targetb_obj.1 "paste(targeta_obj.1, \"b\")"
#> 5 targetb_obj.2 "paste(targeta_obj.2, \"b\")"
#> 6 targetb_obj.3 "paste(targeta_obj.3, \"b\")"
```

My first point was that it would be nice if I could abbreviate this plan creation somehow, ideally with something like:

```r
template <- drake_plan(
  targeta = paste("input__", "a"),
  targetb = paste(targeta, "b")
)
```

...where `drake` is smart enough to figure out that it needs to automatically expand _both_ `targeta` and `targetb`. Perhaps you might consider syntax like:

```r
template <- drake_plan(
  targeta = paste("input__", "a"),
  targetb = paste(drake_expand(targeta), "b")
)
```

...where `drake_expand` would communicate to `evaluate_plan` that `targetb` should be expanded across all inputs to `targeta`. But I can see how this is challenging, and how `map_plan` may provide a sufficiently powerful alternative that this isn't worth implementing.

My **second** point was regarding sanitation of target names during wildcard expansion. As I said, I understand the rationale for using `make.names` and why this is unlikely to change, but I think it is worth adding a note to the documentation that indicates that target names, _including those derived from wildcards_ are coerced via `make.names()` to be syntactically valid. I may have missed it, but I didn't see this mentioned anywhere in the current manual. I think this is an important caveat which can really bite people in advanced drake plan creation. For example:

``` r
library(drake)
pkgconfig::set_config("drake::strings_in_dots" = "literals")
planc <- drake_plan(
  "invalid target a" = rnorm(10),
  "invalid target b" = `invalid target a` ^ 2
)
planc
#> # A tibble: 2 x 2
#>   target           command             
#>   <chr>            <chr>               
#> 1 invalid.target.a rnorm(10)           
#> 2 invalid.target.b `invalid target a`^2
make(planc)
#> target invalid.target.a
#> target invalid.target.b
#> fail invalid.target.b
#> Error: Target `invalid.target.b` failed. Call `diagnose(invalid.target.b)` for details. Error message:
#>   object 'invalid target a' not found
clean(destroy = TRUE)

pland <- tibble::tibble(
  target = c("invalid target a", "invalid target b"),
  command = c("rnorm(10)", "`invalid target a`^2")
)
pland
#> # A tibble: 2 x 2
#>   target           command             
#>   <chr>            <chr>               
#> 1 invalid target a rnorm(10)           
#> 2 invalid target b `invalid target a`^2
make(pland)
#> Unloading targets from environment:
#>   invalid.target.a
#> target invalid.target.a
#> target invalid.target.b
#> fail invalid.target.b
#> Error: Target `invalid.target.b` failed. Call `diagnose(invalid.target.b)` for details. Error message:
#>   object 'invalid target a' not found
clean(destroy = TRUE)
```

Again, I totally understand why this behavior is the way it is -- I just wish it was documented.

**Comment by wlandau** [comment]
Thanks for elaborating. Wildcards can already solve your first point about target expansion. You do need to anticipate the suffixes that `evaluate_plan()` adds to target names, but I think this is manageable.

``` r
library(drake)
pkgconfig::set_config("drake::strings_in_dots" = "literals")
template <- drake_plan(
  target_a = paste("obj-number", "a"),
  target_b = paste(target_a_number, "b")
)
template
#> # A tibble: 2 x 2
#>   target   command                        
#>   <chr>    <chr>                          
#> 1 target_a "paste(\"obj-number\", \"a\")" 
#> 2 target_b "paste(target_a_number, \"b\")"
plan <- evaluate_plan(template, wildcard = "number", values = 1:3)
plan
#> # A tibble: 6 x 2
#>   target     command                   
#>   <chr>      <chr>                     
#> 1 target_a_1 "paste(\"obj-1\", \"a\")" 
#> 2 target_a_2 "paste(\"obj-2\", \"a\")" 
#> 3 target_a_3 "paste(\"obj-3\", \"a\")" 
#> 4 target_b_1 "paste(target_a_1, \"b\")"
#> 5 target_b_2 "paste(target_a_2, \"b\")"
#> 6 target_b_3 "paste(target_a_3, \"b\")"
config <- drake_config(plan)
vis_drake_graph(config)
```

![](https://i.imgur.com/8Cfeo3F.png)

<sup>Created on 2018-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wlandau** [comment]
On your second point: we're really testing the limits of code flexibility here. It can be helpful to push boundaries in times like these.

Once users understand that targets are variables, I think this is enough of a nudge in the right direction for the vast majority of use cases. I would be happy to [consider pull requests](https://github.com/ropensci/drake/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) if you find places in the documentation of [`evaluate_plan()`](https://github.com/ropensci/drake/blob/master/R/wildcards.R#L166), the [chapter of the manual on plans](https://github.com/ropenscilabs/drake-manual/blob/master/plans.Rmd), or anywhere else. Currently, the majority of attention I can spare on open source projects is focused on other aspects of `drake`.

When it comes to wildcards within strings, it may help to use the wildcard as *part* of the string, not the whole thing. For example, instead of this:

``` r
library(drake)
library(magrittr)
pkgconfig::set_config("drake::strings_in_dots" = "literals")
drake_plan(target = string) %>%
  evaluate_plan(wildcard = "string", values = c("my string 1", "my string 2"))
#> # A tibble: 2 x 2
#>   target             command    
#>   <chr>              <chr>      
#> 1 target_my.string.1 my string 1
#> 2 target_my.string.2 my string 2
```

<sup>Created on 2018-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I recommend this:

``` r
library(drake)
library(magrittr)
pkgconfig::set_config("drake::strings_in_dots" = "literals")
drake_plan(target = "my string number") %>%
  evaluate_plan(wildcard = "number", values = 1:2)
#> # A tibble: 2 x 2
#>   target   command          
#>   <chr>    <chr>            
#> 1 target_1 "\"my string 1\""
#> 2 target_2 "\"my string 2\""
```

<sup>Created on 2018-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

The second way has fewer surprises.

**Comment by ashiklom** [comment]
Thanks for the quick and insightful replies!

The versatility of the wildcard templating based on your examples is impressive, and definitely sufficient to get me where I want to be. Once I get a chance, I will take a crack at a PR adding a few notes about target name sanitization to the manual. 

P.S. Also, _huge_ thanks for developing and actively maintaining `drake`. It really has been transformative for the way I work, and I want to make sure my minor, edge-case issues don't overshadow that.

**Comment by wlandau** [comment]
I am so glad to hear `drake` is making a difference in your work. Let's keep our discussions going.
