### ISSUE TITLE
Allow targets to pass even when errors occured

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#604]
This might be a tricky one.

I do not have a simple reprex (yet).

#### Problem

I am fitting models using `mlr`. They are tuned and everything is running in parallel.
Now when running a `benchmark()` call, at some point some function calls fail due to certain reasons (most often in the tuning stage). In `mlr` the user can set 

`configureMlr(on.learner.error = "warn", on.error.dump = TRUE)`

This settings causes the whole `benchmark()` call to continue even if there were errors in certain sub-calls/workers. It is similar to `make(keep.going = TRUE)`.
In this case, some failing calls in certain stages do not harm the end result and it is normal that this is going to happen in certain settings.

Right now, some targets of my workflow never pass because `drake` marks them as failed (which is correct) after it detected errors when building the target. 

#### Wish

**I would like to be able to force pass specific targets regardless if `drake` detected errors during the call or not.** 

I know that doing this does not prevent me from getting completely unwanted outcomes and will skip all errors probably (even majors ones) for that specific target. However, before I used `drake` I had to deal with this problem anyways and I needed to check manually for the correctness of the outcomes.

#### Possible solutions 

I am not sure what could be a possible solution for this. Are there some meta-information attached to targets? If not, maybe an additional column named "force_pass" or similar could be added to the plan.

Or 

Curious what your opinion on that is :)

**Comment by wlandau** [comment]
> Right now, some targets of my workflow never pass because drake marks them as failed (which is correct) after it detected errors when building the target.

Even when you tried `make(keep_going = TRUE)`? (Note the underscore in the argument name.)

> I would like to be able to force pass specific targets regardless if drake detected errors during the call or not.

Here are some things that might help:

I recommend trying `trigger(condition = ..., mode = "blacklist")`. Small example: https://github.com/ropensci/drake/issues/529#issuecomment-427798444. More information:

- [Triggers in the manual](https://ropenscilabs.github.io/drake-manual/triggers.html)
- Discussion: #528 and later #529.

**Comment by wlandau** [comment]
You could also consider the timeout and retried arguments of make() if you think these will help avoid spurious failures.

**Comment by wlandau** [comment]
> So I would like to manually override the "failed" status to "passed".

Ah, that helps me understand. I recommend wrapping your commands and/or functions in `try()` statements.

I do not plan to support a way to force failed targets to show up as up to date. It may make sense for your use case, but my sense is that these cases are rare. `drake` is all about making sure you can trust the results of a data analysis project. The feature we are thinking about would be tempting, and it could probably cause many users to incorrectly violate reproducibility.

When `drake` thinks a target fails, it does not bother to store the result (but it does store the error messages so you can call `diagnose()` later). So those targets and anything downstream will unavoidably be out of date (black or red in the graph). It is possible to hack the "progress" [`storr`](https://github.com/richfitz/storr) namespace to turn red nodes to black, but I do not recommend it.

``` r
library(drake)
plan <- drake_plan(
  x = stop(123),
  y = {
    x
    1 + 1
  }
)
make(plan, keep_going = TRUE)
#> target x
#> fail x
#> target y
cached() # x is missing
#> [1] "y"
config <- drake_config(plan)
vis_drake_graph(config)
```

![](https://i.imgur.com/q2KSfUQ.png)

``` r
progress()
#>          x          y 
#>   "failed" "finished"
config$log_progress <- TRUE
drake:::set_progress("x", "finished", config)
config$log_progress <- FALSE
progress()
#>          x          y 
#> "finished" "finished"
vis_drake_graph(config)
```

![](https://i.imgur.com/8ebrWHJ.png)

Created on 2018-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by pat-s** [comment]
> I do not plan to support a way to force failed targets to show up as up to date. It may make sense for your use case, but my sense is that these cases are rare.

> The feature we are thinking about would be tempting, and it could probably cause many users to incorrectly violate reproducibility.

I am definitely on your side in terms of reproducibility. However, performance/benchmarking calls are a common tasks in R and I think this might occur more often once more people from this field get to know drake (which I think btw drake is perfect for).

> When drake thinks a target fails, it does not bother to store the result (but it does store the error messages so you can call diagnose() later).

Yes I know. I did that, saw the error and also that the object is actually fine. So yeah, in this case a custom rebuild trigger could prevent that. This would be one option. Another one would be to change the status manually.

> So those targets and anything downstream will unavoidably be out of date (black or red in the graph).

This is my main problem, yes.

> It is possible to hack the "progress" storr namespace to turn red nodes to black, but I do not recommend it.

How exactly would this help me here? Both red and black nodes will trigger a rebuild, won't they? 



Thanks for your help :+1:

**Comment by wlandau** [comment]
> I am definitely on your side in terms of reproducibility. However, performance/benchmarking calls are a common tasks in R and I think this might occur more often once more people from this field get to know drake (which I think btw drake is perfect for).

Glad to hear it. Would `try()` work to exempt performance benchmarks from the occasional error? What am I missing?

``` r
library(drake)
run_benchmarks_1 <- function(){
  stop(123)
}
run_benchmarks_2 <- function(){
  456
}
plan <- drake_plan(
  x = try(run_benchmarks_1()),
  y = run_benchmarks_2()
)
make(plan)
#> target x
#> target y
config <- drake_config(plan)
vis_drake_graph(config)
```

![](https://i.imgur.com/QPpeSFI.png)

Created on 2018-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)


> How exactly would this help me here? Both red and black nodes will trigger a rebuild, won't they?

If all you want is to turn red nodes into black ones, that is the best way I can think of. Other than that, you are right, it will not help.

**Comment by wlandau** [comment]
FYI: the new `cancel()` and `cancel_if()` functions may be useful in similar situations: https://github.com/ropensci/drake/pull/1135.
