### ISSUE TITLE
Move tibble to "Suggests:"

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#609]
Excluding `igraph` and "`Suggests:`", `tibble` now stands out as `drake`'s heaviest strict dependency. I think we should make `tibble` optional.

Internally, we could replace `tibble()` and `as_tibble()` with functions that return `data.frame`s if `tibble` is not installed. We would need to do this in `R/*.R` and `tests/testthat/*.R`.

@bpbond, are you interested in taking on the implementation?

**Comment by bpbond** [comment]
Yes! Though can't start until after this week.

**Comment by wlandau** [comment]
Yeah, I was glad to see that thread. Thanks for your work on downsizing `tibble`.

To be clear, I do not mean to criticize `tibble`'s stack size. Coming from me, that would be ironic/hypocritical :sweat_smile:.

**Comment by wlandau** [comment]
Related: `drake` 6.2.1 is currently building on CRAN, and it is compatible with `tibble` 2.0.0.

**Comment by wlandau** [comment]
@bpbond, just a tip: there is a lot of text replacement in this one:

- `tibble::tibble(` :arrow_right: `weak_tibble(`
- `tibble::as_tibble(` :arrow_right: `weak_as_tibble(`

Just in case you did not know this already, here is some useful command line magic if you have access to a Linux or Mac system.

- `sed -i -e 's/tibble::tibble(/weak_tibble(/g' drake/R/*.R`
- `sed -i -e 's/tibble::tibble(/weak_tibble(/g' drake/tests/testthat/*.R`
- `sed -i -e 's/tibble::as_tibble(/weak_as_tibble(/g' drake/R/*.R`
- `sed -i -e 's/tibble::as_tibble(/weak_as_tibble(/g' drake/tests/testthat/*.R`

**Comment by bpbond** [comment]
Already use `sed` but thanks @wlandau . I'll look at this.
