### ISSUE TITLE
bind_plans(list()) is not valid anymore in > v6.2.0

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#611]
In my workflow I had `bind_plans(list(planA, planB))`. Not sure where I picked the `list()` wrapping up, I probably saw it in some example and used it?

However, this synatx does not work anymore in _drake_ > v6.2.0 as 

`plans <- Filter(f = nrow, x = plans)`

returns an empty object if a list is supplied.

Not using `list()` is easier anyways. Just wanted to let you know. Couldn't find it in the changelog :)

**Comment by wlandau** [comment]
Sorry about that. Previously, `bind_plans()` was based on `bind_rows()` from `dplyr`. I am trying to get rid of extra package dependencies, so I implemented a base R version of `bind_plans()` for `drake` 6.2.1 so I could remove `dplyr` from ["`Imports:`"](https://github.com/ropensci/drake/blob/48445910ce0f84ce224e84ae2b26c7ba57653714/DESCRIPTION#L69-L79). Now, `bind_plans()` works more like `rbind()`.

``` r
library(drake)
plan1 <- drake_plan(a = 1, b = 2)
plan2 <- drake_plan(c = 3, d = 4)
bind_plans(plan1, plan2)
#> # A tibble: 4 x 2
#>   target command
#>   <chr>  <chr>  
#> 1 a      1      
#> 2 b      2      
#> 3 c      3      
#> 4 d      4
do.call(bind_plans, list(plan1, plan2))
#> # A tibble: 4 x 2
#>   target command
#>   <chr>  <chr>  
#> 1 a      1      
#> 2 b      2      
#> 3 c      3      
#> 4 d      4
bind_plans(list(plan1, plan2))
#> NULL
```

<sup>Created on 2018-12-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I think it is worth fixing `bind_plans()` so `bind_plans(list(plan1, plan2))` does not return `NULL`.

**Comment by wlandau** [comment]
You're welcome. Glad you brought this up.
