### ISSUE TITLE
TWEEDS conference presentation

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#627]
I was invited to present `drake` at this conference but can't attend: https://tweeds.io/

The mission of the conference is to give and see presentations on data science tools that are relevant to economics. Non-economists are more than welcome!

@wlandau do you or someone else who knows drake well want to go present?

**Comment by wlandau** [comment]
I am delighted to learn they are interested!

I would love to go myself, but unless the December 31 submission deadline can be extended, I cannot attend either. At companies like mine, requesting permission to attend a conference and release presentation materials is a painfully slow process, and all the gatekeepers are on vacation for the rest of the year.

Would you be willing to create a thread at https://discuss.ropensci.org?

**Comment by wlandau** [comment]
Closing this as an issue because it is not directly related to development or a specific use case. However, we can continue to discuss here or on the rOpenSci forums.
