### ISSUE TITLE
Include timings with `store` message?

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#635]
I think the `store` message could be more useful with some timings. Would probably want multiple measurements of time as the user probably wants to know how much is taken up by overhead versus actual computation.

**Comment by wlandau** [comment]
Worth considering. This would be a low-risk feature in terms of its impact on `drake`'s internals, so on the implementation side, I prefer to leave it as low-hanging fruit for a PR (cc @bpbond). On the other hand, `drake` is going through a serious downsizing/simplification phase, so peripheral features like this one may run contrary to the goals of the current development cycle.

The console printing functions are in `R/console.R`. Here is how to get the storage time of a target.

```r
library(drake)
load_mtcars_example()
make(my_plan)
meta <- diagnose("report")
meta$time_build["elapsed"] - meta$time_command["elapsed"]
```

There is usually a `meta` list floating around the build functions for each target.

**Comment by wlandau** [comment]
Correction: `meta$time_build["elapsed"] - meta$time_command["elapsed"]` should include most of the overhead, not just the storage time.

**Comment by wlandau** [comment]
Preference: add times in a separate line and activate with a special level of `verbose`. See #646.
