### ISSUE TITLE
Changes in generic functions don't get picked up as dependency changes

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#636]
Hopefully this is able to be followed. Below, I install a minimal package, run `make`, then reinstall a different version that changes a generic function, then rerun `make`. The second `make` thinks it's up-to-date. Afterwards, I show that `make` notices the change when using the "subgeneric" (not sure of the correct term) directly.

This is likely an issue with the upstream package but it's worth adding to the Cautionary Notes section of the manual.
``` r
devtools::install_github("yihui/rmini")
library(drake)
library(rmini)
detach("package:rmini", unload = TRUE)
my_plan <- drake_plan(show_hello = rmini::hello(x = "Will"),
                      strings_in_dots = "literals")
make(my_plan)
#> target show_hello
#> Hi! I love characters!

devtools::install_github("kendonb/rmini")
library(rmini)
detach("package:rmini", unload = TRUE)

# The function output has changed:
rmini::hello(x = "Will")
#> Hi! I love characters! You didn't notice me change!

# make hasn't noticed the change
make(my_plan)
#> All targets are already up to date.

devtools::install_github("yihui/rmini")
library(drake)
library(rmini)

detach("package:rmini", unload = TRUE)
clean(show_hello)
my_plan <- drake_plan(show_hello = rmini:::hello.character(x = "Will"),
                      strings_in_dots = "literals")
make(my_plan)
#> target show_hello
#> Hi! I love characters!

devtools::install_github("kendonb/rmini")
library(rmini)
detach("package:rmini", unload = TRUE)
rmini:::hello.character(x = "Will")
#> Hi! I love characters! You didn't notice me change!

# Now, when using the "subgeneric", make notices the change 
make(my_plan)
#> target show_hello
#> Hi! I love characters! You didn't notice me change!
```

<sup>Created on 2018-12-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by wlandau** [comment]
Yes, there is no way for `drake` to track S3 methods because the pre-`make()` static code analysis only sees the names of generic functions. Would you post this one to the [manual's development site](https://github.com/ropenscilabs/drake-manual)?
