### ISSUE TITLE
Add saythanks?

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#638]
It's nice to be able to say thanks! https://saythanks.io/

**Comment by wlandau** [comment]
Hmm... while I personally find constructive criticism more useful, I really like the precedent this sets for open source projects in general. And the badge will fit right in.

**Comment by wlandau** [comment]
I will add my own personal SayThanks.io mailbox as a temporary placeholder, but many more people deserve thanks for `drake`. I wonder if @ropensci would be willing to open an account. cc'ing @maelle, `drake`'s @ropensci onboarding editor.

**Comment by karthik** [comment]
Happy to do this for you. Who should this email go to? I can set up `drake@ropensci.org` (I hope we don't hire Drake someday) to go to the authors/maintainers?

**Comment by wlandau** [comment]
Thanks, @karthik. Your comment nudged me to take a closer look, and until https://github.com/kennethreitz/saythanks.io/issues/44 is solved, I actually think I can handle this with a separate gmail account and a [specialized filter](https://webapps.stackexchange.com/questions/50372/auto-forwarding-emails-to-2-email-addresses). I do appreciate the offer, though.

**Comment by wlandau** [comment]
The README badge now links to https://saythanks.io/to/drake-r-package-feedback. To anyone connected with `drake`'s development and/or @ropensci, just ping me and I will set up gmail forwarding from `no-reply at saythanks dot io` to your email account through `drake.r.package.feedback at gmail dot com`. cc'ing some possible takers.

- @AlexAxthelm
- @benmarwick
- @bpbond  
- @dapperjapper 
- @gothub
- @jules32
- @HenrikBengtsson
- @kendonB 
- @krlmlr 
- @maelle
- @mschubert

**Comment by wlandau** [comment]
In fact, I will add anyone who requests it. I see no reason to limit this to `drake` developers.

**Comment by maelle** [comment]
maybe @stefaniebutland would like to see how such notes look like?

**Comment by stefaniebutland** [comment]
You should find some thanks in your inbox soon 🙏

**Comment by wlandau** [comment]
I saw, that's nice of you.
