### ISSUE TITLE
Trim down the API for 7.0.0

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#644]
`drake`'s API has too many functions. Many of them should be deprecated.

**Comment by wlandau** [comment]
Much of this will happen as we remove parallel backends. Some need to be deprecated, some should just be gracefully hidden from the user, and a few can be deleted outright. I will take care of those personally:

- `cmq_staged_build()`
- `default_hasty_build()`
- `default_Makefile_args()`
- `default_Makefile_command()`
- `default_recipe_command()`
- `default_parallelism()`
- `do_prework()`
- `fl_master()`
- `Makefile`-related arguments of `make()` and `drake_config()`
- `mc_process()`
- `mc_master()`
- `mk()`
- `prepare_distributed()`
- `r_recipe_wildcard()`
- `shell_file()`
- `time_stamps()`

@bpbond, could I enlist your help again with the rest? 

Some functions can just be deprecated outright:

- `built()`
- `find_project()` (`find_cache()` should be good enough)
- `imported()`
- `parallel_stages()`

Many are internal functions I never should have exposed. When we deprecate one of these functions (say, `fun()`) we also need to create a new unexported function `fun_()` to replace all original uses of `fun()` internally.

- `analysis_wildcard()`
- `dataset_wildcard()`
- `cache_path()`
- `cache_namespaces()`
- `check_plan()`
- `drake_palette()`
- `drake_tip()`
- `in_progress()`
- `make_imports()`
- `make_targets()`
- `make_with_config()`
- `prune_drake_graph()`
- `recover_cache()`
- `store_drake_config()`
- `target_namespaces()`

**Comment by bpbond** [comment]
Happy 2019 @wlandau . Yes, happy to help with this.

**Comment by wlandau** [comment]
Awesome, your help will be so valuable here! There is a lot of refactoring to do, and with two back-to-back conferences in January, I will be really strapped for time for a while.

**Comment by wlandau** [comment]
Sorry, I closed the wrong issue.
