### ISSUE TITLE
How to combine() while keeping track of the sources of targets

### ISSUE THREAD

**Issue by htlin** [ropensci/drake#693]
I have a plan which looks like the following:
```
plan <- drake_plan(
  s_load = target(
    load_csv(vx, vy, vz),
    transform = cross(
      vx = c("x1", "x2"),
      vy = c("y1", "y2"),
      vz = c("z1", "z2")
    )
  ),
  s_extract = target(
    extract_feature(s_load),
    transform = cross(s_load)
  ),
  s_merge = target(
    merge_feature(s_extract),
    transform = combine(vx, vy)
  ),
  s_collect = target(
    collect(quo(s_merge)),
    transform = combine()
  )
)
```

In the `collect` function I want to collect all values into a data frame (4x3) so that I can do other statistical analysis afterwards, but I need to keep track of the original source targets (x1/y2 combination for example) that produced each value.  So far I got it to work with `quo` together with `quo_get_expr` and `eval_tidy` as follows:
```
collect <- function(results) {
  keys <- as.list(quo_get_expr(results))[-1]
  values <- unlist(rlang::eval_tidy(results))
  ......
}
```

But I need to do lots of ugly string parsing and splitting after that.  Is there any better way of doing this?

**Comment by wlandau** [comment]
Such a great question and such a great time to ask it!

## First, some clarifications

Before I answer, I would just like to point out that the [use of `combine()` has just changed](https://ropenscilabs.github.io/drake-manual/plans.html#combine) (ref: #691, #692). Now, `combine(w, x, .by = c(y, z))` tells `drake` to aggregate the `w_*` and `x_*` targets for each combination of `y` and `z`. Does that make sense?

Is this the general workflow you are after?

``` r
library(drake)
plan <- drake_plan(
  s_load = target(
    load_csv(vx, vy, vz),
    transform = cross(
      vx = c("x1", "x2"),
      vy = c("y1", "y2"),
      vz = c("z1", "z2")
    )
  ),
  s_extract = target(
    extract_feature(s_load),
    transform = map(s_load)
  ),
  s_merge = target(
    merge_feature(s_extract),
    transform = combine(s_extract, .by = c(vx, vy))
  ),
  s_collect = target(
    collect(quo(s_merge)),
    transform = combine(s_merge)
  )
)

config <- drake_config(plan)
vis_drake_graph(config)
```

![](https://i.imgur.com/ahSQLe6.png)

<sup>Created on 2019-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

## Tracking targets in `combine()`

I originally wanted to make `combine()` generate named lists, but because of strange behavior in `deparse()` across different versions of R and different platforms, I cannot implement it in a consistent way.

But I think your clever use of `rlang::quo()` gets us really close. First, we construct our plan with `trace = TRUE` so we have special columns to tell us where the targets came from.

``` r
library(drake)
plan <- drake_plan(
  s_load = target(
    load_csv(vx, vy, vz),
    transform = cross(
      vx = c("x1", "x2"),
      vy = c("y1", "y2"),
      vz = c("z1", "z2")
    )
  ),
  s_extract = target(
    extract_feature(s_load),
    transform = map(s_load)
  ),
  s_merge = target(
    merge_feature(s_extract),
    transform = combine(s_extract, .by = c(vx, vy))
  ),
  s_collect = target(
    collect(quo(s_merge)),
    transform = combine(s_merge)
  ),
  trace = TRUE
)

plan
#> # A tibble: 21 x 9
#>    target   command   vx    vy    vz    s_load s_extract  s_merge s_collect
#>    <chr>    <chr>     <chr> <chr> <chr> <chr>  <chr>      <chr>   <chr>    
#>  1 s_load_… "load_cs… "\"x… "\"y… "\"z… s_loa… <NA>       <NA>    <NA>     
#>  2 s_load_… "load_cs… "\"x… "\"y… "\"z… s_loa… <NA>       <NA>    <NA>     
#>  3 s_load_… "load_cs… "\"x… "\"y… "\"z… s_loa… <NA>       <NA>    <NA>     
#>  4 s_load_… "load_cs… "\"x… "\"y… "\"z… s_loa… <NA>       <NA>    <NA>     
#>  5 s_load_… "load_cs… "\"x… "\"y… "\"z… s_loa… <NA>       <NA>    <NA>     
#>  6 s_load_… "load_cs… "\"x… "\"y… "\"z… s_loa… <NA>       <NA>    <NA>     
#>  7 s_load_… "load_cs… "\"x… "\"y… "\"z… s_loa… <NA>       <NA>    <NA>     
#>  8 s_load_… "load_cs… "\"x… "\"y… "\"z… s_loa… <NA>       <NA>    <NA>     
#>  9 s_extra… extract_… "\"x… "\"y… "\"z… s_loa… s_extract… <NA>    <NA>     
#> 10 s_extra… extract_… "\"x… "\"y… "\"z… s_loa… s_extract… <NA>    <NA>     
#> # … with 11 more rows
```

<sup>Created on 2019-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Next, we can pass the plan itself to `collect()` and combine the information with the names of the list.

```r
library(dplyr)
library(rlang)

collect <- function(quosure, plan) {
  # Actually get the list.
  list <- eval_tidy(quosure)
  
  # Get the names of the list elements.
  target_names <- all.vars(quo_squash(quosure))
  
  # Name the list elements according to target names.
  names(list) <- target_names
  
  # Get the trace of those targets
  metadata <- filter(plan, target %in% target_names)
  
  # postprocessing...
  wrangle(list, metadata)
}

collect(
  quo(list(
    s_merge_.x1._.y1.,
    s_merge_.x2._.y1.,
    s_merge_.x1._.y2., 
    s_merge_.x2._.y2.))
  ,
  plan
)
```

One downside is that this makes `s_collect` oversensitive to changes in the plan, so feel free to use `ignore()` so that the plan is not an actual dependency.

```r
plan <- drake_plan(
  ...
  s_collect = target(
    collect(quo(s_merge), ignore(plan)), # prevents `plan` from being an actual dependency
    transform = combine(s_merge)
  ),
  trace = TRUE
)
```

## Follow-up

Does that meet your use case? If so, may I write about this in [the manual](https://ropenscilabs.github.io/drake-manual/plans.html#combine)? Does your project have a public repo on GitHub?

**Comment by wlandau** [comment]
Maybe `combine()` needs to invoke a function that creates named lists from unnamed arguments.

``` r
named_list <- function(...) {
  list <- list(...)
  names(list) <- as.character(match.call(expand.dots = FALSE)$...)
  list
}

a <- b <- c <- 1

named_list(a, b, c)
#> $a
#> [1] 1
#> 
#> $b
#> [1] 1
#> 
#> $c
#> [1] 1
```

<sup>Created on 2019-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wlandau** [comment]
Edit: if we use `match.call()`, I do not actually think we need `quo()`. See the edit to `collect()` above.

**Comment by wlandau** [comment]
I think I addressed this issue above and with https://github.com/ropenscilabs/drake-manual/commit/75edaf8d3836ec42c75a8b9aa4bc26cf91b33e76. Please let me know if you have more questions.

**Comment by wlandau** [comment]
Great to know, @htlin. And if your project ever does become public, please let me know. I think most of us are in similar situations where we cannot share our projects publicly, so it has been difficult to find truly useful examples that motivate the problem `drake` is trying to solve.

**Comment by htlin** [comment]
I am trying to write a more general `collect` function, here I share it below:

```
collect <- function(input, plan) {
  col_names <- names(input[[1]])
  if (is.null(col_names)) {
    col_names <- paste("value", seq(1, length(input[[1]])), sep = "")
  }
  names(input) <- all.vars(match.call()$input)
  output <- filter(plan, target %in% names(input))
  
  output[, col_names] <- NA
  for (i in seq_along(input)) {
    output[output$target == names(input)[i], col_names] <- unlist(input[[i]])
  }
  output
}
```

Not sure if it can be made cleaner, but at least now I am able to support different kinds of values passed from the previous step: a single value, a list of values, and a named list.  If it is a named list then I will use the names as the column names in the final table.

**Comment by wlandau** [comment]
Glad you found something that works. But I wonder, is each `input[[i]]` a data frame? If each `s_load_*` target had manual indicator columns for `vx`, `vy`, and `vz`, I think you would have the same information.

**Comment by wlandau** [comment]
Edit: the link to the relevant section in the manual changed to https://ropenscilabs.github.io/drake-manual/plans.html#large-plans.
