### ISSUE TITLE
NSE applied within targets before transforms applied: file_in and file_out woes

### ISSUE THREAD

**Issue by brendanf** [ropensci/drake#696]
My (bioinformatics) workflow involves application of command line utilities over lots of files. In order to do this in `drake`, my idea is to encapsulate each command line call in an R function.  Using standard unix utilities:

```r
my_copy <- function(from, to) {
system2("cp", args = c(from, to))
}

in_files <- paste0("in", 1:10, ".txt")
file.create(in_files)
out_files <- paste0("out", 1:10, ".txt")

plan <- drake_plan(
  copies = target(my_copy(file_in(the_in), file_out(the_out)),
                        transform = map(the_in = !!in_files, the_out = !!out_files))
# do more steps here...
)

make(plan)
```

This works fine.

However, some command line utilities I want to use have more than one input or output, which are not all explicitly listed on the command line (typically, a base name is given, and the command generates the full names from these). Exactly how many and which outputs will be created may depend on other options set at the command line.  I'll use [`split`](http://manpages.ubuntu.com/manpages/precise/en/man1/split.1.html) as an easily accessible example. The reasonable thing to do, I thought, was to use NSE to have the R function calculate what the input and output files would be, and then call `file_in` and `file_out` appropriately.  The function starts to look like a mess, but it works as intended.

```r
my_split <- function(from, stem, n) {
  suffixes <- with(expand.grid(y = letters, x = letters),
                   paste0(x,y))[1:n]
  out.files <- paste0(stem, suffixes)
  quo({
    file_in(!!from)
    file_out(!!out.files)
    system2("split", c(paste0("-n r/", !!n),
                       !!from,
                       !!stem))
  })
}

split_in = "longfile.txt"
writeLines(as.character(1:1000), split_in)

plan2 <- drake_plan(
  splits = target(!!my_split(split_in, "shortfile", 10))
)

make(plan2)
```

That is, it works as intended until I want to use a transform...

```r
manysplits <- paste0("longfile", 1:10, ".txt")
map(manysplits, writeLines, text = as.character(1:1000))

plan3 <- drake_plan(
  splits = target(!!my_split(f, f, 10),
                  transform = map(f = !!manysplits))
)
## Error in paste0(stem, suffixes) : object 'f' not found
```
Apparently `drake_plan` is applying NSE to the target (thus finding f) before it applies the transform, which would give `f` its value.  I'm sure sometimes this would be the desired effect, but in my case it's a big stumbling block.

**Comment by brendanf** [comment]
It's worth mentioning that this issue can come up with R functions, not just command line utilities; there are plenty of bioinformatics packages with functions like `something(in.dir, out.dir)` which does something to every file in `in.dir`, and saves the results in `out.dir`.

**Comment by wlandau** [comment]
Yeah, tidy evaluation in commands should probably happen after transforms. Until I get to that, I think you can remove `!!` from `my_split` and call `eval_tidy()` afterwards.

```r
library(drake)
library(magrittr)
library(purrr)
library(rlang)

my_split <- function(from, stem, n) {
  suffixes <- with(expand.grid(y = letters, x = letters),
                   paste0(x,y))[1:n]
  out.files <- paste0(stem, suffixes)
  quo({
    file_in(!!from)
    file_out(!!out.files)
    system2("split", c(paste0("-n r/", !!n),
                       !!from,
                       !!stem))
  })
}

manysplits <- paste0("longfile", 1:2, ".txt")

plan3 <- drake_plan(
  splits = target(my_split(f, f, 3), transform = map(f = !!manysplits))
)

plan3$command <- map_chr(plan3$command, function(x) {
  parse_expr(x) %>%
    eval_tidy() %>%
    quo_squash() %>%
    expr_text()
})

drake_plan_source(plan3)
#> drake_plan(
#>   splits_.longfile1.txt. = {
#>     file_in("longfile1.txt")
#>     file_out(c("longfile1.txtaa", "longfile1.txtab", "longfile1.txtac"))
#>     system2("split", c(paste0("-n r/", 3), "longfile1.txt", "longfile1.txt"))
#>   },
#>   splits_.longfile2.txt. = {
#>     file_in("longfile2.txt")
#>     file_out(c("longfile2.txtaa", "longfile2.txtab", "longfile2.txtac"))
#>     system2("split", c(paste0("-n r/", 3), "longfile2.txt", "longfile2.txt"))
#>   }
#> 
)

config <- drake_config(plan3)
vis_drake_graph(config)
```

![capture](https://user-images.githubusercontent.com/1580860/52074224-68ac1000-2557-11e9-8fd7-79fa4a281fa1.PNG)

**Comment by brendanf** [comment]
Thanks, that works for now and I'll look forward to a change in the evaluation order.

I am aware that I can solve this problem the "old way", by constructing the drake plan manually. 
```r
metaplan4 <- tibble(from = manysplits,
                    stem = manysplits,
                    n = 10)
plan4 <- 
  tibble(command = pmap(metaplan4,
                                          compose(expr_text,
                                                          quo_squash,
                                                          my_split)),
         target = paste0("target", seq_along(command)))

make(plan4)
```
Unfortunately, both ways involve some metaprogramming that obscures what is actually going on for people who aren't fairly sophisticated R programmers.  One of my goals for reproducible research is that my colleagues shouldn't look at my scripts and say "what the hell does this do!?". 

What if you could also tell `drake` about input and output files by putting them in special columns?  Something like this seems more clear:

```r
my_split <- function(from, stem, n) {
  system(glue("split -n r/{n} {from} {stem}"))
}

split_outs <- function(stem, n) {
  suffixes <- with(expand.grid(y = letters, x = letters),
                   paste0(x,y))[1:n]
  paste0(stem, suffixes)
}

drake_plan(
  splits = target(my_split(file_in(f), f, n),
                  transform = map(f = !!manysplits,
                                  n = 1:10),
                  file_out = split_outs(f, n))
)
```

I've assumed that out_file would have the transform applied to it, then be evaluated and wrapped in a list; I don't know if that's the most intuitive behavior or not, but it would make my life easy.  :-)   My ideal behavior would be:

* If any of the transform variables are mentioned in the expressions given for file_in/out, then transform, evaluate, and capture the results in a `list`.
* Otherwise, evaluate the expression.  It should evaluate to either a `character` or a `list`; in either case, its length should be the same as that implied by the transform, and any other length should be an error.

**Comment by wlandau** [comment]
> Unfortunately, both ways involve some metaprogramming that obscures what is actually going on for people who aren't fairly sophisticated R programmers. One of my goals for reproducible research is that my colleagues shouldn't look at my scripts and say "what the hell does this do!?".

Totally agreed. You should not have to do cryptic metaprogramming, and the call to `drake_plan()` should tell a transparent story.

> As a feature request, what if you could also tell drake about input and output files by putting them in special columns?

Interesting idea. However, I think it will be hard to convince me on this. First, `drake` is already very complicated and I am trying to downsize and simplify it. Also, `drake` is opinionated: it tries to get users to move away from special custom files and to trust in the caching system that governs ordinary targets. This is part of what it means for `drake` to be R-focused. There are better pipeline tools than `drake` when it comes to tracking and manipulating files, but `drake` is domain-specific in the sense that you only need to think about R objects if your workflow is entirely within R.

**Comment by wlandau** [comment]
Without transformations, I think special `file_out` and `file_in` columns would make far less of a difference on the user side, and I think it would complicate `drake`'s internals. Let's keep thinking about more elegant solutions. Let's keep thinking about how to solve this more elegantly. I feel as though we should not need `!!my_split`.

Would you post some examples of the plans you would like to achieve? It really helps me to have expected input and expected output. I particularly like the format that [`reprex`](https://github.com/tidyverse/reprex) encourages.

Also, your `plan2` should now work because tidy evaluation now happens after transformation (https://github.com/ropensci/drake/pull/703/commits/f226c0120ab474099f2b9d253433389acf4c2afa).

**Comment by wlandau** [comment]
#1178 should come in handy here.
