### ISSUE TITLE
map() back to original variables after after combine()

### ISSUE THREAD

**Issue by brendanf** [ropensci/drake#710]
My plan has parts which are "embarrassingly parallel" and parts which are less so. Combining the results of parallel calculations works well; splitting the results back into parallel calculations does not.

In a toy example, imagine than `A:D` are four datasets, which may have some duplicate values in one column (but unique values in other columns, so that they are not actually redundant).  There are two types of dataset, with `A` and `B` in type 1, and `C` and `D` in type 2; the types do not share any duplicate data, so they can be treated completely separately.

`expensive_calc()` is an expensive calculation which needs to be performed on the data.  In order to reduce the calculation time, it is memoized, so it is much more efficient to send it all of the data from each type at one time.  Then, the results are mapped back to the original datasets using function `distribute_results()`.

Here is the plan:
``` r
library(drake)

inputs <- lapply(LETTERS[1:4], as.symbol)
types <- rep(c(1, 2), each = 2)

plan <- drake_plan(
  wide1 = target(
    ez_parallel(a),
    transform = map(a = !!inputs,
                    type = !!types)
  ),
  serial = target(
    expensive_calc(wide1),
    transform = combine(wide1, .by = type)
  ),
  dist = target(
    distribute_results(serial, wide1),
    transform = map(serial,
                    wide1)
  )
)
vis_drake_graph(drake_config(plan))
```
![image](https://user-images.githubusercontent.com/16835777/52284584-fbd4b380-2964-11e9-8bb3-56cbc78a7de1.png)

<sup>Created on 2019-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

`drake` does not keep track of which values of `wide1` correspond to which values of `serial`, so the results are not applied to the correct data.

If the number of datasets is not divisible by the number of types, then the plan fails completely.

``` r
library(drake)

inputs <- lapply(LETTERS[1:5], as.symbol)
types <- rep(c(1, 2), length.out = 5)

plan <- drake_plan(
  wide1 = target(
    ez_parallel(a),
    transform = map(a = !!inputs,
                    type = !!types)
  ),
  serial = target(
    expensive_calc(wide1),
    transform = combine(wide1, .by = type)
  ),
  dist = target(
    distribute_results(serial, wide1),
    transform = map(serial,
                    wide1)
  )
)
#> Error: Failed to make a grid of grouping variables for map().
#> Grouping variables in map() must have suitable lengths for coercion to a data frame.
#> Possibly uneven groupings detected in map(serial, wide1):
#>   c("serial_1", "serial_2")
#>   c("wide1_A_1", "wide1_B_2", "wide1_C_1", "wide1_D_2", "wide1_E_1")

vis_drake_graph(drake_config(plan))
#> Error in is.data.frame(x): object 'plan' not found
```

<sup>Created on 2019-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wlandau** [comment]
Great use case. My suggestion is to follow through with the custom grid of settings you started with. #697 is similar. See below.

``` r
library(drake)

inputs <- lapply(LETTERS[1:5], as.symbol)
types <- rep(c(1, 2), length.out = 5)

wide_vals <- rlang::syms(paste0("wide_", inputs))
serial_vals <- rlang::syms(paste0("serial_", types))

plan <- drake_plan(
  wide = target(
    ez_parallel(a),
    transform = map(a = !!inputs, type = !!types)
  ),
  serial = target(
    expensive_calc(wide),
    transform = combine(wide, .by = type)
  ),
  dist = target(
    distribute_results(serial_, wide_),
    transform = map(serial_ = !!serial_vals, wide_ = !!wide_vals)
  )
)

drake_plan_source(plan)
#> drake_plan(
#>   wide_A_1 = ez_parallel(A),
#>   wide_B_2 = ez_parallel(B),
#>   wide_C_1 = ez_parallel(C),
#>   wide_D_2 = ez_parallel(D),
#>   wide_E_1 = ez_parallel(E),
#>   serial_1 = expensive_calc(list(wide_A_1, wide_C_1, wide_E_1)),
#>   serial_2 = expensive_calc(list(wide_B_2, wide_D_2)),
#>   dist_serial_1_wide_A = distribute_results(serial_1, wide_A),
#>   dist_serial_2_wide_B = distribute_results(serial_2, wide_B),
#>   dist_serial_1_wide_C = distribute_results(serial_1, wide_C),
#>   dist_serial_2_wide_D = distribute_results(serial_2, wide_D),
#>   dist_serial_1_wide_E = distribute_results(serial_1, wide_E)
#> )

config <- drake_config(plan)
vis_drake_graph(config)
```

![](https://i.imgur.com/QRJTjO8.png)

<sup>Created on 2019-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

I realize this is a little inconvenient for you, but for `drake_plan()` to remember all the `wide_*`'s that go into the `serial_*`'s, the challenges are far greater. To see why, let's look at a similar plan with the trace turned on.

``` r
library(drake)

inputs <- lapply(LETTERS[1:5], as.symbol)
types <- rep(c(1, 2), length.out = 5)

drake_plan(
  wide = target(
    ez_parallel(a),
    transform = map(a = !!inputs, type = !!types)
  ),
  serial = target(
    expensive_calc(wide),
    transform = combine(wide, .by = type)
  ),
  trace = TRUE
)
#> # A tibble: 7 x 6
#>   target   command                              a     type  wide    serial 
#>   <chr>    <expr>                               <chr> <chr> <chr>   <chr>  
#> 1 wide_A_1 ez_parallel(A)                     … A     1     wide_A… <NA>   
#> 2 wide_B_2 ez_parallel(B)                     … B     2     wide_B… <NA>   
#> 3 wide_C_1 ez_parallel(C)                     … C     1     wide_C… <NA>   
#> 4 wide_D_2 ez_parallel(D)                     … D     2     wide_D… <NA>   
#> 5 wide_E_1 ez_parallel(E)                     … E     1     wide_E… <NA>   
#> 6 serial_1 expensive_calc(list(wide_A_1, wide_… <NA>  1     <NA>    serial…
#> 7 serial_2 expensive_calc(list(wide_B_2, wide_… <NA>  2     <NA>    serial…
```

<sup>Created on 2019-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

To generate the correct `dist_*` targets automatically, the last 2 elements of `wide1` need to be lists of symbols: `list(wide1_A_1, wide1_C_1, wide1_E_1)` and `list(wide1_B_2, wide1_D_2)`. Then, we need to unpack those symbols correctly and feed them to `distribute_results()`. As soon as we start to try, we have nested data structures and recursion, which puts large burdens on complexity and runtime. For now, I would prefer to stick with the current simplifying assumptions.

But let's keep thinking about a more elegant solution. In case you want to help out, the code for transformations is [here](https://github.com/ropensci/drake/blob/master/R/api-dsl.R), and it gets called [here](https://github.com/ropensci/drake/blob/6a453cc0a9501dcebaa4a531b70dfbbbbed478ea/R/api-plan.R#L174).

**Comment by wlandau** [comment]
With dynamic branching, you have more control over how `combine()` happens because you can create your own grouping vector for `.by`
