### ISSUE TITLE
combine() does not evaluate the combined variable in functions.

### ISSUE THREAD

**Issue by brendanf** [ropensci/drake#715]
When the `combine()` variable appears as the argument of a function, its values are not properly evaluated during `make()`.  This is a reversion.

``` r
library(drake)
x_ <- letters[1:2]
out <- drake_plan(
  A = target(x, transform = map(x = !!x_)),
  B = target(A, transform = combine(A)),
  C = target(c(A), transform = combine(A)),
  trace = TRUE
)
make(out)
#> target A_.a.
#> target A_.b.
#> target B
#> target C
readd(B)
#> [[1]]
#> [1] "a"
#> 
#> [[2]]
#> [1] "b"
readd(C)
#> [[1]]
#> A_.a.
#> 
#> [[2]]
#> A_.b.

## should be the same
```

<sup>Created on 2019-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wlandau** [comment]
That's odd. `B` is correct. I will have a look.

**Comment by wlandau** [comment]
I believe I fixed this in c68b46b7c0f3e0937f4f1547e4ce861ddd213f06.

That was a really insidious bug you found just now. Thank you for these issues. They are really helping prepare for the release of version 7.0.0.

**Comment by wlandau** [comment]
FYI: combine() changed slightly in #729.

**Comment by wlandau** [comment]
Update: please use the syntax in #730 instead of #729.
