### ISSUE TITLE
Question: Can I use file_in when I don't control the filename?

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#721]
Is there any way that I can use `file_in()` or something similar when I don't directly control or know the names of the files that are input?

I am building a drake plan where I want to load data using a package that does more complex data load (from many files, specifically the `xpose` package's `xpose_data` function; it's very specific to my field of work, so it is unlikely that many users will be familiar).

The function loads somewhere between 3 and >10 files to make an object for future analysis, and I don't directly control what those files are.  The result of the call depends on work done outside of R (that is not immediately easy to bring into R).

To make this a bit clearer, I may have a directory structure like the following (note that the real directory structure is more complex):

* results/
    * run1.result
    * run1.information
    * run1.csv
    * table1.tab
    * mytable3.tab
    * run2.result
    * run2.information
    * run2.errors

And the way that the function works, it will look at `run1.information` to determine what files to load.  If I execute `xpose_data(runno=1, dir="results/")`, it may load "run1.result", "run1.information", "run1.csv", "table1.tab", and "mytable3.tab".  But if I execute `xpose_data(runno=2, dir="results/")`, it may load "run2.result", "run2.information", and "run2.errors".

**Comment by wlandau** [comment]
Unfortunately, you do need to know and declare every `file_in()` file in advance. However,  metaprogramming and tidy evaluation can make this easier. To repeat this technique over multiple `runno` values, you might try the [new experimental DSL](https://ropenscilabs.github.io/drake-manual/plans.html#large-plans) (currently in development `drake` only).

Also, you can leave out files that are not scientifically meaningful and do not affect your results (maybe `run2.errors`).

```r
library(drake)
library(tidyverse)

# Maybe something like this:
# run1_files <- list.files("itp", full.names = TRUE) %>%
#   grep(pattern = "run1", value = TRUE)

files <- c("results/run1.result", "results/run1.csv")

plan <- drake_plan(xpose_obj = {
  file_in(!!files)
  xpose::xpose_data(runno = 1, dir = "results")
})

drake_plan_source(plan)
#> drake_plan(
#>   xpose_obj = {
#>     file_in(c("results/run1.result", "results/run1.csv"))
#>     xpose::xpose_data(runno = 1, dir = "results")
#>   }
#> )
```

**Comment by billdenney** [comment]
Thanks for the quick answer!

The solution to use `file_in()` on every file in the directory is reasonable for my current use case.  I'll put in a request in `xpose` to make a function that will return all the files that will be loaded so that I can make a more specific `file_in()` call (or PR if I can figure it out).
