### ISSUE TITLE
Feature Request: Assignment into Lists

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#722]
This is somewhat related to #694.

Can new syntax be added so that assignment into lists is possible?  Maybe the way that drake works, it would be easier to assign into an environment instead-- either would work for this request since (most?) environments can be coerced into lists.

If assigning into a list, then I could imagine syntax like:

```r
my_plan <-
  drake_plan(
    my_list=list(),
    `my_list$foo`=1
  )
make(my_plan)
```
(Currently, I get a `my_list.foo` as it appears to go through something like make.names.)

If an environment is simpler, I think that it could have an interface like the following with a new column in the plan data.frame for `environment` (with an interface via a new `drake_environment` argument to `drake_plan()`):

```r
my_plan <-
  drake_plan(
    foo=1,
    drake_environment="my_list"
  )
make(my_plan)
```

Or combining the ideas, add a new `drake_list` argument to `drake_plan()`:
```r
my_plan <-
  drake_plan(
    foo=1,
    drake_list="my_list"
  )
make(my_plan)
```

And this third option may be the simplest to implement as it could be implemented by just concatenating all the target names into a list and making that the last target:

```r
my_plan <-
  drake_plan(
    foo=1
  )
my_plan <-
 rbind(
    my_plan,
    data.frame(
      target="my_list",
      command=sprintf("list(%s)", paste(my_plan$target, my_plan$target, sep="=", collapse=", "))
    )
  )
make(my_plan)
```

(I could imagine this playing well with the DSL being generated as many of the expanded arguments may work well by being assigned into a cleaner space, like a list or environment.)

**Comment by wlandau** [comment]
This is a new one for me. My initial reaction is to turn

```r
drake_plan(
  my_list = list(),
  `my_list$foo` = 1
)
```

into

```r
drake_plan(
  my_list = list(),
  my_list_2 = {
    my_list$foo <- 1
    my_list
  }
)
```

The reason is `drake`'s design philosophy: targets are immutable. In other words, once you create a target, it is no longer modified downstream. This intentional limitation enhances reproducibility because it ensures that each target's starting materials are always available for checking. So to update your list, you will actually end up copying it into a new list first.

Immutability is successful in pure functional programming (e.g. Haskell) but possibly less so in big data applications where you want to avoid copying things. I am still looking for workarounds (e.g. https://github.com/ropenscilabs/drake-manual/issues/46#issuecomment-447617446) but not at the cost of immutability.

If you have specific use cases that you think about in terms of list modification, feel free to share and we try to figure out how `drake` would handle them.

**Comment by billdenney** [comment]
Given your answer, I agree that my request doesn't necessarily make sense, but I'm going to give a bit more of an explanation in case we're not fully talking about the same thing.  I'm not necessarily thinking of the list as a mutable object but as a concatenation of other results that are ready for summary together.

One example that I commonly use is to generate a list of models that I have fit.  I then apply various model-selection functions on that list of models to help choose the best model(s).  So, the list itself is immutable (after the last model is built).  Code similar to what I presented in the third example above is how I'm currently doing this within `drake` (though as a drake novice, I'm not sure that's the best way).

**Comment by wlandau** [comment]
How about [`combine()`](https://ropenscilabs.github.io/drake-manual/plans.html#combine)?

``` r
library(drake)
drake_plan(
  data = get_data(),
  model = target(fit_model(index), transform = map(index = c(1, 2))),
  model_list = target(model, transform = combine(model))
)
#> # A tibble: 4 x 2
#>   target     command               
#>   <chr>      <expr>                
#> 1 data       get_data()            
#> 2 model_1    fit_model(1)          
#> 3 model_2    fit_model(2)          
#> 4 model_list list(model_1, model_2)
```

Created on 2019-02-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by billdenney** [comment]
That looks like it would do it!

**Comment by wlandau** [comment]
Awesome. And when I solve #723, it will be easier to mix and match transformed and untransformed targets. For now, you may need to write some things literally.

``` r
library(drake)
drake_plan(
  data = get_data(),
  model = target(fit_model(index), transform = map(index = c(1, 2))),
  extra_model = fit_extra_model(),
  model_list = target(c(model, extra_model), transform = combine(model))
)
#> # A tibble: 5 x 2
#>   target      command                               
#>   <chr>       <expr>                                
#> 1 data        get_data()                            
#> 2 model_1     fit_model(1)                          
#> 3 model_2     fit_model(2)                          
#> 4 extra_model fit_extra_model()                     
#> 5 model_list  c(list(model_1, model_2), extra_model)
```

Created on 2019-02-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by wlandau** [comment]
I opened this #723 by mistake. `drake` is already correct. In the third row, we need `map(.tag_in = model)`, not `map(.tag_in = "model")` (symbols, not quotes).

``` r
  library(drake)
drake_plan(
  data = get_data(),
  model = target(fit_model(index), transform = map(index = c(1, 2))),
  extra_model = target(fit_extra_model(), transform = map(.tag_in = model)),
  model_list = target(model, transform = combine(model))
)
#> # A tibble: 5 x 2
#>   target      command                            
#>   <chr>       <expr>                             
#> 1 data        get_data()                         
#> 2 model_1     fit_model(1)                       
#> 3 model_2     fit_model(2)                       
#> 4 extra_model fit_extra_model()                  
#> 5 model_list  list(model_1, model_2, extra_model)
```

<sup>Created on 2019-02-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wlandau** [comment]
FYI: combine() changed slightly in #729.

**Comment by wlandau** [comment]
Update: please use the syntax in #730 instead of #729.

**Comment by billdenney** [comment]
Thanks!
