### ISSUE TITLE
Old targets in cache when upgarding to new 7.0.0 plan syntax breaks viz_drake_graph()

### ISSUE THREAD

**Issue by gadenbuie** [ropensci/drake#725]
I'm a new user of drake, as in started using it today! Thank you already!

About half way through converting some old scripts into a drake plan, I realized that I had to update to the dev version to use the new plan generating API (which is awesome!). At which time, I ran into an issue while updating a plan with targets in copy-paste style to the new plan syntax.

Before updating, I ran my plan and it completed. After upgrading both `drake` and the syntax of my plan, running `make(plan, force = TRUE)` worked great. But `vis_drake_graph(config)` would give me an error like:

```
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
```

It took me a while to track this down to `build_times()`, specifically the line

```r
out <- do.call(rbind, out)
```

which was failing because an outdated target from the previous plan that I had removed during refactoring was still in the `config`. So not all of the elements in `out` at that point have the same number of columns.

```r
[[15]]
# A tibble: 1 x 4
  target                                                 elapsed  user system
  <chr>                                                    <dbl> <dbl>  <dbl>
1 stat_plots_.figures.quantile_normalized_PDL.pdf._.PDL.    35.0  33.4  0.555

[[16]]
# A tibble: 1 x 5
  item           type   elapsed  user system
  <chr>          <chr>    <dbl> <dbl>  <dbl>
1 stat_plots_cd3 target    36.2  34.3  0.585
```

Running `drake::clean()` completely resolved the problem, but it took quite some time to realize this due to the cryptic error message (and maybe that I'm new to `drake`). You might consider mentioning this to users who are interesting in upgrading old plans, or adding a check in `build_times()` to catch this with a more informative error message.

**Comment by wlandau** [comment]
I am really glad you spoke up. The upcoming breaking changes in `drake` are all worth it, but I still worry about the transition from the users' side. 4e1f128ed01b9480ffc94fdd4488560d3e4f6a79 improves the cache compatibility message

> 
> This project was last run with drake version 6.2.1.
> Your cache is not compatible with the current version of drake (6.2.1.9003).
> To run your project with version 6.2.1.9003, either:
>     1. Run `clean(destroy = TRUE)` to clear the cache first (recommended) or
>     2. Run `make(force = TRUE)` to overwrite targets in the cache on the fly (which saves more of your work but may cause issues like  https://github.com/ropensci/drake/issues/725).
> Be warned: if you do either, all you targets will run from scratch.
> You may wish to downgrade drake to version 6.2.1 instead.

and should also allow `build_times()` to work with uneven columns of times.

**Comment by gadenbuie** [comment]
Thanks! This looks great and definitely would have worked for me in the moment. I know I'm new to drake but the new changes are awesome and completely worth it -- being able to specify a handful of targets in a single, readable line was :100:
