### ISSUE TITLE
FYI: upcoming rOpenSci announcement

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#744]
I plan to publish an rOpenSci tech note to accompany the release of `drake` version 7.0.0, and it would be great to list those of you who contributed ideas or code patches. Please contact me if you would rather not be mentioned. cc 

- @bart1
- @billdenney
- @bpbond
- @brendanf
- @dapperjapper
- @HenrikBengtsson
- @htlin
- @idavydov
- @kendonB
- @krlmlr
- @mschubert
- @pat-s
- @tmastny

**Comment by billdenney** [comment]
Thanks for the acknowledgment!

**Comment by wlandau** [comment]
Edit: I just added @ha0ye and @MilesMcBain to the list. Again, please let me know of you would prefer to *not* be mentioned.

**Comment by wlandau** [comment]
...and the draft tech note lives [here](https://github.com/ropensci/roweb2/pull/423). [Click here](https://deploy-preview-423--ropensci.netlify.com/technotes/2019/03/18/drake-700/) for a fully rendered preview.

**Comment by wlandau** [comment]
I almost forgot about https://github.com/ropensci/drake/commit/ec050a452d2081675a4ed834234581f92c6b03ed. `drake` 7.0.0 has reduced trigger verbosity thanks to @aedobbyn. Amanda, I added a mention in the [upcoming tech note](https://github.com/ropensci/roweb2/pull/423). If would rather not be included, please let me know before March 18 so I can revert https://github.com/ropensci/roweb2/pull/423/commits/f6603ca10cbe429300dba397af869df07df52ef2.

**Comment by aedobbyn** [comment]
Looks great @wlandau, thanks for the heads up!
