### ISSUE TITLE
Feature Request: Pipe Plan?

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#746]
I occasionally have long-running code (usually 10s of minutes) that is amenable to pipe processing.

It would be handy to have a pipe-like operator that would automate the simplicity of magrittr-style pipes and the computational efficiency of `drake`.

What I'm thinking of is something that may look like the following:

```r
long_running_result <-
  data %drake>%
  long_running_task_1() %drake>%
  long_running_task_2() %drake>%
  make()
```

Where it would do something like the following under the hood:

```r
automated_planning <-
  drake_plan(
    r1=data %>% long_running_task_1(),
    r2=r1 %>% long_running_task_2()
  )
make(automated_planning)
readd(r2)
```

P.S. No worries if the response is "I don't think that's a good fit for core drake functionality."

**Comment by wlandau** [comment]
Neat idea! Unfortunately, `drake` does not always mix well with pipes (#335, #527, https://github.com/tidyverse/magrittr/issues/163) so we should not encourage all the functionality in your sketch. But maybe within `drake_plan()`? I will think about it.

```r
drake_plan(
  result = data %dp%
    task_1() %dp%
    task_2()
)
#> # A tibble: 3 x 2
#>   target command       
#>   <chr>  <expr>        
#> 1 data_1 data          
#> 2 data_2 task_1(data_1)
#> 3 result task_2(data_2)
```

Scanning for `%dp%` is expensive, but not if we support an optional `pipe` argument to `target()`. That would even allow us to use the regular [`magrittr`](https://github.com/tidyverse/magrittr) pipe symbol.

```r
drake_plan(
  result = target(
    data %>%
      task_1() %>%
      task_2(),
    pipe = TRUE
  )
)
#> # A tibble: 3 x 2
#>   target command       
#>   <chr>  <expr>        
#> 1 data_1 data          
#> 2 data_2 task_1(data_1)
#> 3 result task_2(data_2)
```

It does take away some of the magical implicitness of the pipe, but speed is more important.

We would also need to stay faithful to what [`magrittr`](https://github.com/tidyverse/magrittr) does. Ideally, we should tell [`magrittr`](https://github.com/tidyverse/magrittr) to give us an expanded functional sequence before the metaprogramming that gives us targets and commands.

**Comment by wlandau** [comment]
See #748. Not yet sure if it is a good idea, but this is the way I would implement it. Still needs profiling.

**Comment by wlandau** [comment]
Major use case: reduce calls to `transform = map()`. Less code to create the same plan, and target names come out nicer.

``` r
library(drake)
  
# without the pipe.
drake_plan(
  pre_result = target(
    task1(data, analysis),
    transform = map(analysis = c("bayes", "freq"))
  ),
  mid_result = target(
    task2(pre_result),
    transform = map(pre_result)
  ),
  result = target(
    task3(mid_result),
    transform = map(mid_result)
  )
)
#> # A tibble: 6 x 2
#>   target                               command                             
#>   <chr>                                <expr>                              
#> 1 pre_result_.bayes.                   task1(data, "bayes")                
#> 2 pre_result_.freq.                    task1(data, "freq")                 
#> 3 mid_result_pre_result_.bayes.        task2(pre_result_.bayes.)           
#> 4 mid_result_pre_result_.freq.         task2(pre_result_.freq.)            
#> 5 result_mid_result_pre_result_.bayes. task3(mid_result_pre_result_.bayes.)
#> 6 result_mid_result_pre_result_.freq.  task3(mid_result_pre_result_.freq.)

# with the pipe
drake_plan(
  result = target(
    task1(data, analysis) %dp%
      task2() %dp%
      task3(),
    transform = map(analysis = c("bayes", "freq"))
  )
)
#> # A tibble: 6 x 2
#>   target           command                
#>   <chr>            <expr>                 
#> 1 result_.bayes..2 task1(data, "bayes")   
#> 2 result_.bayes..1 task2(result_.bayes..2)
#> 3 result_.bayes.   task3(result_.bayes..1)
#> 4 result_.freq..2  task1(data, "freq")    
#> 5 result_.freq..1  task2(result_.freq..2) 
#> 6 result_.freq.    task3(result_.freq..1)
```

<sup>Created on 2019-02-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by billdenney** [comment]
Wow!  Thank you for jumping on this!

**Comment by wlandau** [comment]
You are welcome, it is a fun idea to play around with. I am still not sure about merging #748, and I just solicited more advice [here](https://discuss.ropensci.org/t/should-drake-have-a-pipe/1592).

**Comment by wlandau** [comment]
I let this issue simmer for several weeks, and I have decided to not add it to `drake`.

The purpose of `%dp%` would be to reap the same benefits as the [`magrittr`](https://github.com/tidyverse/magrittr) pipe. The official purpose of the [`magrittr`](https://github.com/tidyverse/magrittr) pipe is to improve the *readability* of code, not compactness. I feel that `%dp%` only makes things more cryptic. Other drawbacks:

1. Performance: several comments in #748 show an unavoidable performance penalty. We could probably mitigate the some of it, but there is probably no easy fix (ref: https://github.com/ropensci/drake/pull/748#issuecomment-474375008) it could still show up as a bottleneck later.
2. Ambiguity: as soon as we start applying custom transforms and columns, we need to put our `%dp%` chain inside a call to `target()` ([example here](https://github.com/ropensci/drake/pull/748#issuecomment-474375008)). The word "target" is singular, yet we are generating multiple targets with the pipe. I find this misleading.
3. Complexity: `tidyverse` pipes are unfamiliar, but my colleagues seem to find `%dp%` counterintuitive. Plus, it stands out in an odd way from the rest of `drake`'s syntax.

**Comment by billdenney** [comment]
Thanks for considering it and putting so much work into it!
