### ISSUE TITLE
plot_ly wants to remove bindings from environment

### ISSUE THREAD

**Issue by htlin** [ropensci/drake#749]
Say I have a Rmd code chunk as follows:
```
library(plotly)
loadd(sData)
plot_ly(sData, x = ~carat, y = ~price, color = ~clarity)
```

And a plan script:
```
library(drake)

data("diamonds")
plan <- drake_plan(
  sData = target(
    diamonds
  ),
  sReportMain = rmarkdown::render(
    knitr_in("report_plotly.Rmd"),
    output_file = "report_plotly.html",
    quiet = TRUE
  )
)

make(plan)
```

Then I am getting the error:
> <simpleError in is.list(x): .onLoad failed in loadNamespace() for 'shiny', details:
>   call: rm(.Random.seed, envir = .GlobalEnv, inherits = FALSE)

It's quite annoying and unfortunate to have plot_ly doing this here - is there any workaround without setting the `make(lock_envir = FALSE)`, as I still very much like to have this check for the rest of my plans.

**Comment by wlandau** [comment]
Yeah, that does sound annoying. You could try using a non-global environment.

```r
envir <- new.env(parent = globalenv())
source("your_file_of_functions.R", local = envir)
make(plan, envir = envir)
```

**Comment by wlandau** [comment]
Another alternative: run `make(targets = non_plotly-targets, lock_envir = TRUE)` first and then `make(lock_envir = FALSE)` to build the rest. I may reopen this thread if I learn something from [here](https://stackoverflow.com/questions/54811667/lock-environment-but-not-random-seed). `lock_envir` + `.Random.seed` is proving to be a challenge.

**Comment by rsangole** [comment]
Faced this issue today. @wlandau - continue using your suggested solutions above, or is there an  alternate solution now?

**Comment by wlandau** [comment]
There is still not an alternate solution.
