### ISSUE TITLE
make() does not respect elapsed time limit when using clustermq backend

### ISSUE THREAD

**Issue by brendanf** [ropensci/drake#752]
I ran a plan using clustermq on SLURM.  I gave a timeout for both the workers (via their SLURM template) and the master, using `make(..., elapsed = 3600)` for a 1h timeout.  One of the workers died via segfault.  SLURM killed all the other workers after their time was up, but the master was still idling about 10 hours later.  In the absence of heartbeating for workers (mschubert/clustermq#33), it would be nice to at least be able to tell the master when to give up on waiting for results.

**Comment by wlandau** [comment]
Arguments `elapsed` and `cpu` apply to targets, not workers. Timeouts are [imposed on the R commands](https://github.com/ropensci/drake/blob/65153eb9c08f87685f648c09f3a53d610554c521/R/exec-run.R#L3-L13) in your `drake_plan()`. You do bring up an important point about the master process, but I think this is out of scope for `drake`.

If you want, you could impose a time limit outside of `make()`, either with `R.utils::withTimeout()` (which could conflict with individual target timeouts if you run stuff locally) or with `timeout` on Linux

```r
nohup timeout R CMD BATCH your_script_that_runs_drake.R &
```

**Comment by brendanf** [comment]
I was thinking that `elapsed` applied per task, I guess I was just confused about who enforced the timeout; I thought that if the master sent a task to a worker, and had not heard anything back after `elapsed` seconds, then it would decide that the task had failed.  But if I understand you correctly, the code enforcing the `elapsed` timeout is executed completely on the worker?

**Comment by wlandau** [comment]
> I was thinking that `elapsed` applied per task, I guess I was just confused about who enforced the timeout; I thought that if the master sent a task to a worker, and had not heard anything back after `elapsed` seconds, then it would decide that the task had failed.

These arguments work in a way that generalizes beyond the kind of parallelism you are using ([`future`](https://ropenscilabs.github.io/drake-manual/hpc.html#the-future-backend), [`clustermq`](https://ropenscilabs.github.io/drake-manual/hpc.html#the-clustermq-backend), or no parallelism at all).. I would be happy to take pull requests to spell this out up the documentation, either in the [argument definitions](https://github.com/ropensci/drake/blob/0ce2d0f962c98b3b6d13fef3fb37a7563863b998/R/preprocess-config.R#L131-L143) or the manual [here](https://github.com/ropenscilabs/drake-manual/blob/57c2ed2ac06c2cdcd8980c2328e56944a102ef3a/plans.Rmd#L134-L138) or [the hpc chapter](https://github.com/ropenscilabs/drake-manual/blob/master/hpc.Rmd).

> But if I understand you correctly, the code enforcing the `elapsed` timeout is executed completely on the worker?

Yes, separately for each target, no matter what kind of worker we have.
