### ISSUE TITLE
Cache in bad state after `clustermq` job with worker caching

### ISSUE THREAD

**Issue by brendanf** [ropensci/drake#754]
I ran a relatively large job (80 workers, 160 targets) on my cluster using the `clustermq` backend.  After the job, I got an error when trying to read two of the targets:
```r
> readd(target.44)
Error in readRDS(self$name_hash(hash)) : error reading from connection
```
Subsequent calls to `outdated()` or `make()` consider those two targets complete and do not try to build them, but any further targets depending on them fail with the same error.

I looked in the logs for the workers that had built those targets, and they did not have any problems; both even built an additional target (not dependent on the first) after the problematic one.

I thought I could remove the faulty cached values, and then rerun `make()` to rebuild only those two targets, but `clean()` also failed:
```r
> drake::clean("target.44")
Error in readRDS(self$name_hash(hash)) : error reading from connection
```

I am guessing this problem might have happened because of two workers trying to modify the cache simultaneously? Whatever the cause, how can I remove the faulty cache values without deleting the whole cache?

**Comment by wlandau** [comment]
You could try `rescue_cache(garbage_collection = TRUE)`. See also https://github.com/richfitz/storr/issues/55. If that does not work, is there a way you can reproduce the problem and/or share your cache. Not much else I can suggest on my end, unfortunately.

**Comment by wlandau** [comment]
Hmm... maybe there are a few things we could try if `rescue_cache()` does not work. Which, if any, of the following functions fail?

```r
cache <- storr::storr_rds(".drake") # https://github.com/richfitz/storr
key <- "target.44"
cache$list()
cache$exists(key)
cache$get(key)
hash <- cache$get_hash(key)
cache$driver$get_object(hash)
cache$del(key)
```

**Comment by wlandau** [comment]
Looking back, I think this issue is contained in #126, #155, and https://github.com/richfitz/storr/issues/55, so I am closing it. But let's keep talking if you continue to run into problems.
