### ISSUE TITLE
`map` does't work with dates

### ISSUE THREAD

**Issue by karldw** [ropensci/drake#759]
I have a function I want to run once for each date in a vector of dates. Here I've replaced it with the dummy function `add_1`. I was hoping to use the new `map` to build a bunch of targets, one for each date. This approach seems to work fine for bare numbers, but not for Dates.

``` r
library(drake)

dates <- seq(as.Date("2019-01-01"), as.Date("2019-01-05"), by=1)
numbers <- seq(1, 5, by=1)
add_1 <- function(x) {
  stopifnot(length(x) == 1)
  x + 1
}
plan <- drake::drake_plan(
  # works:
  numbers_added = target(add_1(x), transform=map(x=!!numbers)),
  # works, but returns the function add_1, not the result
  dates_added1   = target(add_1, transform=map(x=!!dates)),
  # fails:
  dates_added2   = target(add_1(x), transform=map(x=!!dates))
)
make(plan)
#> target numbers_added_1
#> target numbers_added_2
#> target numbers_added_3
#> target numbers_added_4
#> target numbers_added_5
#> target dates_added1_structure.17897..class....Date..
#> target dates_added1_structure.17898..class....Date..
#> target dates_added1_structure.17899..class....Date..
#> target dates_added1_structure.17900..class....Date..
#> target dates_added1_structure.17901..class....Date..
#> target dates_added2_structure.17897..class....Date..
#> fail dates_added2_structure.17897..class....Date..
#> Error: Target `dates_added2_structure.17897..class....Date..` failed. Call `diagnose(dates_added2_structure.17897..class....Date..)` for details. Error message:
#>   object 'structure(17897, class = "Date")' not found
```

This might be another issue, but the differences between `map` and `purrr::pmap` surprised me. 
- `target(add_1, transform=map(x=!!dates))` runs without error, but only returns the function `add_1`, not the values returned by `add_1`.
-  `target(add_1(x), transform=map(x=dates))` doesn't iterate through the dates, instead providing the entire vector of dates as the argument to `add_1`.

My goal here is to iterate through a set of dates, using drake to run code for the dates that haven't been processed yet. The simple way to do this would be `purrr::map(vector_of_dates, some_memoized_function)`, but that doesn't work as well for downstream steps. I'm new to drake, so please let me know if I'm going about this the wrong way.

**Comment by karldw** [comment]
I'm using drake 6.2.1.9005 (ropensci/drake@0f90705)

**Comment by wlandau** [comment]
Thanks for the report. I would not have though of this edge case. I believe the problem with dates is fixed in 75bfbefd26c65b9d90f607906159b9759b230671, and I will close this issue once I answer your question about `purrr::map()`.

**Comment by wlandau** [comment]
That is because `purrr::map()` evaluates code, whereas `drake_plan()` creates code without evaluating it. The two approaches meet different needs. Mapping in functional programming is a more general concept than either implementation expresses on its own. I compared the two in the manual just to establish a basis of familiarity. I did not mean to imply that they would be the same in all (or even most) respects.

> `target(add_1, transform=map(x=!!dates))` runs without error, but only returns the function `add_1`, not the values returned by `add_1`.

`map()` is supposed to create calls of the form `add_1(x)` where each date takes turns getting substituted in for `x`. Since the symbol `x` does 

> `target(add_1(x), transform=map(x=dates))` doesn't iterate through the dates, instead providing the entire vector of dates as the argument to `add_1`.

Yes, this is a consequence of metaprogramming. When you create a `drake_plan()` you are creating code, not output. So you need to tell `drake` to take the *values* stored in your `dates` variable, not the literal symbol `dates`. In tidy evaluation, this is what the `!!` operator is designed for.

**Comment by wlandau** [comment]
By the way, the implementation of the solution made the following call to `drake_plan()` 15% faster. So thanks again for posting.

```r
x_vals = as.numeric(seq_len(1000))
drake_plan(
  x2 = target(x1, transform = map(x1 = !!x_vals)),
  x3 = target(x2, transform = map(x2)),
  x4 = target(x3, transform = map(x3)),
  x5 = target(x4, transform = map(x4)),
  x6 = target(x5, transform = map(x5)),
  x7 = target(x6, transform = map(x6)),
  x8 = target(x7, transform = map(x7)),
  x9 = target(x8, transform = map(x8)),
  x10 = target(x9, transform = map(x9)),
  x11 = target(x10, transform = combine(x10))
)
```
