### ISSUE TITLE
Minor request: allow trailing commas?

### ISSUE THREAD

**Issue by karldw** [ropensci/drake#760]
It would be convenient if drake plans allowed for a trailing comma, as dplyr or python do. This is obviously super minor. Thanks for the great package!

``` r
library(drake)
plan <- drake_plan(
  numbers_added = identity(1), # this comma causes trouble
)
make(plan)
#> Error in safe_deparse(x): argument "x" is missing, with no default

# In contrast this works:
dplyr::select(mtcars, cyl, )
#>                     cyl
#> Mazda RX4             6
#> ...
```

**Comment by wlandau** [comment]
Now fixed.

``` r
library(drake)
drake_plan(
  , a = 1, , b = f(x),,,
)
#> # A tibble: 2 x 2
#>   target command
#>   <chr>  <expr> 
#> 1 a      1      
#> 2 b      f(x)
```

<sup>Created on 2019-03-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

This one was weird. It required dealing with missing/unusable symbols (refs [here](http://r.789695.n4.nabble.com/Assigning-empty-symbol-to-variable-td4678752.html) and [here](https://stackoverflow.com/questions/3892580/create-missing-objects-aka-empty-symbols-empty-objects-needed-for-f)).
