### ISSUE TITLE
Request: clearer errors when providing a plan instead of a config

### ISSUE THREAD

**Issue by karldw** [ropensci/drake#764]
As a new user, I was somewhat confused about which functions require drake config objects and which took plans. The docs provide clear examples, but it might still be useful to have an error message that provides more detail about what's required. Do you think this is worth the hassle?

``` r
plan <- drake::drake_plan(x1 = 1)

# This is incorrect, but I was confused about what was going wrong:
drake::vis_drake_graph(plan)
#> Warning: Unknown or uninitialised column: 'graph'.
#> Error in V(config$graph): Not a graph object

# Should have done this instead:
config <- drake::drake_config(plan)
drake::vis_drake_graph(config)
```

One way to approach it would be to add this error to functions that expect a config:
```r
if (inherits(config, "drake_plan")) {
  stop("You must first call drake_config to convert this plan to a config")
}
```

**Comment by wlandau** [comment]
Good point. Let's see if someone at next week's [Chicago R Unconference](https://chirunconf.github.io) wants to get involved.

Requirements:

- [ ] A new internal `assert_config()` function that applies the `if()` statement suggested above. Please write it in `R/utils-utils.R`
- [ ] Usage of `assert_config()` in the following functions:
    - [ ] `r_make()`
    - [ ] `r_drake_build()`
    - [ ] `r_outdated()`
    - [ ] `r_missed()`
    - [ ] `r_drake_graph_info()`
    - [ ] `r_vis_drake_graph()`
    - [ ] `r_sankey_drake_graph()`
    - [ ] `r_drake_ggraph()`
    - [ ] `r_predict_runtime()`
    - [ ] `r_predict_workers()`
- [ ] A test in `tests/testthat/test-edge-cases.R` to verify that `assert_config()` works as expected in at least some of these functions. Please use `skip_on_cran()`
- [ ] A short description of the change under "Enhancements" in `NEWS.md`.

**Comment by wlandau** [comment]
Oops, I closed the wrong issue just now.

**Comment by wlandau** [comment]
To make the assertion stronger, we should assign a formal class to `drake_config()` objects, and I am not sure I want to do that just yet. The proposed assertion is weak, but I think it covers the majority of mistakes, e.g. supplying plans instead of `drake_config()` lists.
