### ISSUE TITLE
Figure paths of .md reports

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#766]
When creating a report that outputs plots from code and knitting to `.md`, the figure paths are not set correctly by default.

```r
reports = drake_plan(
  report1 = knitr::knit(
    knitr_in("analysis/rmd/report.Rmd"),
    output = file_out("analysis/rmd/report.md"),
    quiet = TRUE),
  strings_in_dots = "literals"
)
```

So in the resulting `.md` file, the figure paths refer to the root of of the `.md` document which is `"ProjROOT/analysis/rmd/figure"`. However, the figures are actually stored in `ProjROOT/figure`. Hence, previewing the .md file fails.

To solve this, I added `knitr::opts_knit$set(base.dir = 'analysis/rmd/')` to the setup chunk of the reports document.
Is there any better way to do this? Wondering that no one before fell over this? :thinking: 	

(In the "mtcars" examples no plots are generated so the issue does not show up there.)

**Comment by wlandau** [comment]
Thanks for the note, @pat-s. I think we should wrap this into https://github.com/ropenscilabs/drake-manual/issues/55. `knitr::opts_knit$set(base.dir = 'analysis/rmd/')` in the report itself sounds like the right call.

**Comment by wlandau** [comment]
...maybe it's only the right call if you always `knit` those reports in `drake`. If you open the document in the RStudio IDE and press the "knit" button, `knitr` might look for `analysis/rmd/analysis/rmd/` instead. So maybe you could leave the `opts_knit$set()` out of the report and put it in the command.


```r
reports = drake_plan(
  report1 = knitr::knit(
    knitr::opts_knit$set(base.dir = "analysis/rmd/")
    knitr_in("analysis/rmd/report.Rmd"),
    output = file_out("analysis/rmd/report.md"),
    quiet = TRUE),
  strings_in_dots = "literals"
)
```

Either that or use your original plan and make sure the option is set for all targets

```r
make(plan, prework = quote(knitr::opts_knit$set(base.dir = "analysis/rmd/"))
```

**Comment by pat-s** [comment]
And again you come up with an even better solution. Thanks! :tada:
