### ISSUE TITLE
Specialized issue templates

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#770]
If you open a new issue, you will see text already in the comment box.

![screenshot_20190306_233633](https://user-images.githubusercontent.com/1580860/53932680-cbb62880-4068-11e9-9bcd-14fa606bf5b9.png)

The text comes from [`.github/PULL_REQUEST_TEMPLATE.md`](https://github.com/ropensci/drake/blob/master/.github/PULL_REQUEST_TEMPLATE.md). Glancing at [`workflowr`'s repo](https://github.com/jdblischak/workflowr), I learned that it is possible to define [multiple templates](https://github.com/jdblischak/workflowr/tree/master/.github/ISSUE_TEMPLATE) to give more specialized guidance to users who click the "New issue" button.

![asdf](https://user-images.githubusercontent.com/1580860/53932792-6a428980-4069-11e9-8730-0feebe89a1ff.png)

It would be great if we could follow the example of [`workflowr`](https://github.com/jdblischak/workflowr) and create specialized issue templates for `drake`.

**Comment by BListyg** [comment]
@wlandau Hey Will! I hope you have safe travels. I think I might tackle this sometime this week if that's ok?

**Comment by wlandau** [comment]
Absolutely, Ben! Thanks for keeping me posted.

Back home and catching up now. I hope your trip back was nice and smooth too.

**Comment by wlandau** [comment]
Hey Ben, are you still interested in writing these specialized issue templates?

**Comment by wlandau** [comment]
I thought more about the kinds of specific issues facing `drake` and decided to go ahead and add [some templates here](https://github.com/ropensci/drake/tree/master/.github/ISSUE_TEMPLATE). @BListyg, I will still accept pull requests if you have more ideas.
