### ISSUE TITLE
Cancel Slurm job when canceling r_make()

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#772]
When canceling an `r_make()` call, the respective scheduler jobs are not killed (in my case Slurm). This was different when using only `make()`. Probably because the call is running in a standalone R session via `callr`?

(I just fell over this while waiting and waiting for a new job to start but the canceled job from the `r_make()` call was still valid.)

Thinking in a different way: This would even enable the "feature" of closing a terminal window and the job keeps running in the background. But probably this is just a nice undesired side-effect here.

**Comment by wlandau** [comment]
That's really odd. I assuming you are using the `clustermq` backend? I reproduced the problem on an SGE cluster with the [main example](https://github.com/wlandau/drake-examples/tree/master/main) and `drake_config(plan, parallelism = "clustermq", jobs = 2)`.

Unfortunately, this issue falls outside the scope of `drake` itself. You can reproduce it with just `clustermq` and `callr`.

```r
callr::r(function() clustermq::Q(Sys.sleep, 60, n_jobs = 1))
# Now, cancel early with CTRL-C or ESC.
# The `callr` process terminates, but the cluster job keeps running.
```

**Comment by wlandau** [comment]
I will open an issue in `clustermq`.

**Comment by wlandau** [comment]
> Thinking in a different way: This would even enable the "feature" of closing a terminal window and the job keeps running in the background. But probably this is just a nice undesired side-effect here.

On an unrelated note, `r_make(r_fn = callr, r_args = list(supervise = FALSE))` should theoretically allow you to close the window and trust that the master process is still running. I have not tested this, though.

**Comment by wlandau** [comment]
Hmm... so from https://github.com/r-lib/callr/issues/99, the buck really does stop at `drake`. Unfortuantely, there seems to be no automatic way around this. Maybe you could define your own function with a cleanup callback.

```r
my_r_make <- function() {
  on.exit(system("scancel -u USERNAME"))
  r_make()
}
```

**Comment by wlandau** [comment]
The `callback` argument described in `?callr::r` seems to do something unrelated.

**Comment by wlandau** [comment]
Different approach: https://github.com/mschubert/clustermq/issues/131.
