### ISSUE TITLE
use_drake()

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#773]
Re https://github.com/ropensci/drake/issues/761#issuecomment-468848523 it would be nice to have a function that sets up the R script files for a typical `drake` project.

## Resources

- [Chapter in the manual on `drake` projects](https://ropenscilabs.github.io/drake-manual/projects.html).
- [The main example](https://github.com/wlandau/drake-examples/tree/master/main) (download with `drake_example("main")`).

## Functionality.

The `use_drake()` function should write the following files to the user's project root.

```
_drake.R
make.R
R/
├── packages.R
├── functions.R
└── plan.R
```

Each file should have

1. A description of its role, and
2. Commented-out code from `drake_example("main")`.

We can store these files in a new `skeleton` subfolder of [`inst/examples`](https://github.com/ropensci/drake/tree/master/inst/examples) and reference them with `system.file(package = "drake", mustWork = TRUE)`.

## Other implementation details

- [ ] Write a new test in `tests/testthat/test-examples.R` to ensure the files are copied correctly.
- [ ] Briefly describe the change in the most recent ["New features" section of `NEWS.md`](https://github.com/ropensci/drake/blob/master/NEWS.md).
- [ ] If you like, add yourself as a contributor in the [`DESCRIPTION` file](https://github.com/ropensci/drake/blob/4d2c69b61ad1c2b3be75734de865e2ea1ef93879/DESCRIPTION#L26-L61).

**Comment by wlandau** [comment]
## A couple more details

1. We should make sure these files are written to the user's correct project root, which could be an R package with a `DESCRIPTION` file or just a file system with an `*.Rproj` file. We can probably glean best practices from the `rprojroot` package and the internals of `usethis`.
2. We need to be careful to not overwrite existing files.

**Comment by tjmahr** [comment]
What do you think about using usethis to implement this? They provide a [`use_template()`](https://usethis.r-lib.org/reference/use_template.html) function that apply the usual usethis steps and checks. That way we can satisfy both the checks (for the project root and for preventing overwriting) for free. 

To avoid dependency, we can suggest the package and do a `require()` in the function. 

The only change to your proposal would be that usethis wants the templates to live `inst/templates`.

**Comment by wlandau** [comment]
Oh neat, I did not know about `use_template()`. Looks like the right tool for the job. We may have invoke it once per file, but that is not such a big deal. And `inst/templates` is fine.

Also, `drake` has an internal `assert_pkg()` function to ensure an optional package is installed. That + namespacing (e.g. `pkg::fun()`) + [Suggests](https://github.com/ropensci/drake/blob/ae093a068c1be05bcb217de07b79882c0643e156/DESCRIPTION#L84) should cover us.

Are you interested in taking on the implementation yourself?

**Comment by wlandau** [comment]
We can probably just write `make.R` and `_drake.R` and link to examples of the supporting scripts.
