### ISSUE TITLE
Docs suggestion: installing clustermq doesn't have to be so hard

### ISSUE THREAD

**Issue by karldw** [ropensci/drake#781]
Currently the [docs say](https://ropenscilabs.github.io/drake-manual/hpc.html#the-clustermq-backend):
 > You must first install [ZeroMQ](http://zeromq.org/) ([instructions here](http://zeromq.org/intro:get-the-software)) and then install the [`clustermq`](https://github.com/mschubert/clustermq) package.

Could I suggest amending this to:
> If you're not using Windows or macOS, you must first install [ZeroMQ](http://zeromq.org/) ([instructions here](https://github.com/mschubert/clustermq#installation)). Then, on any operating system, install the [`clustermq`](https://github.com/mschubert/clustermq) package.
Note that `clustermq` works on Windows, but its ability to run parallel code is limited.

The benefit of pointing to the _clustermq_ install docs instead of ZeroMQ are:
- Recent versions of Ubuntu know about `libzmq3-dev`; users don't need to add another software source
- Installation for Linuxbrew, Conda, Fedora, and Arch is clearer

In the current docs it's implied, but not explicitly stated, that _clustermq_ will work on Windows but not be able to parallelize.

Ref: https://github.com/mschubert/clustermq/issues/64 and https://github.com/mschubert/clustermq/issues/84 for issues with parallel execution on Windows.

**Comment by wlandau** [comment]
Thanks, @karlw. In https://github.com/ropenscilabs/drake-manual/commit/fcfbcc81b2732c45f7fb7ec16a6679f5ef8c62b5, I defer completely to [`clustermq`'s installation instructions](https://github.com/mschubert/clustermq/blob/master/README.md#installation). That should cover it.

[`drake`'s manual](http://ropenscilabs.github.io/drake-manual) actually lives in a [different GitHub repository](https://github.com/ropenscilabs/drake-manual). In the future, would you post issues about the manual there instead?

**Comment by karldw** [comment]
Yes, definitely. Sorry about that!
