### ISSUE TITLE
Broken link in pgkdown NEWS

### ISSUE THREAD

**Issue by lorenzwalthert** [ropensci/drake#782]
The link under version 7.0, breaking changes, to the details for the first bullet points to a local file. 

Link in the doc: https://ropensci.github.io/drake/news/index.html#breaking-changes
points to: file:///home/landau/projects/drake-manual/_book/plans.html#large-plans

**Comment by wlandau** [comment]
Thanks, @lorenzwalthert. I will update the v7.0.0 release notes too.
