### ISSUE TITLE
Interested in trying the rOpenSci pkgdown template?

### ISSUE THREAD

**Issue by maelle** [ropensci/drake#783]
https://github.com/ropenscilabs/rotemplate WIP, it needs early testers/adopters :wink: 

Here's how adding it looks like https://github.com/ropensci/ropenaq/commit/955c55d7189aab767e389ebd5c37921491005218 (I can make a PR!)

**Comment by wlandau** [comment]
@maelle, I would love to adopt the template. A PR may be convenient, but as a little learning exercise, I think I would like to try myself first.

**Comment by maelle** [comment]
Awesome! Any question/comment welcome (I'll answer tomorrow, am about to log off)

**Comment by wlandau** [comment]
The template is now live at https://ropensci.github.io/drake. The existing visuals clash a bit with the light blue in the banner, but it's not bad.

**Comment by wlandau** [comment]
Say, are there plans for an rOpenSci `bookdown` template too? I would add one to https://github.com/ropenscilabs/drake-manual if available.

**Comment by maelle** [comment]
Thanks for asking! :smile_cat: It's actually quite hard to style bookdown (at least for me), but you can use the CSS I have in https://github.com/ropensci/dev_guide <- any idea how I could make it easier to share? I created a file called style.css and it's mentioned in the _output.yml config file.

It mostly only helps getting rOpenSci colors in the book, because I haven't been able to add the favicon :woman_shrugging:

In the dev branch of dev_guide there's also a PDF export for the book, whose only customization is having links in rOpenSci blue, which IIRC happens via preamble.tex

**Comment by maelle** [comment]
Heeey I :eyes: that *you* know how to add a favicon to a bookdown book, PR welcome to the dev branch of dev_guide :smile:

**Comment by wlandau** [comment]
@maelle, thanks for your patience.

> you can use the CSS I have in https://github.com/ropensci/dev_guide... I created a file called style.css and it's mentioned in the _output.yml config file.

That's so convenient! Simply linking to https://ropensci.github.io/dev_guide/style.css in `_output.yml` worked for `drake`'s manual just fine (ref: https://github.com/ropenscilabs/drake-manual/commit/34475f5c60008bdf636037350990be83341ad90b, now live).

> Heeey I eyes that you know how to add a favicon to a bookdown book, PR welcome to the dev branch of dev_guide smile

Sounds like fun. Is there an SVG copy of https://github.com/ropensci/dev_guide/blob/master/images/icon_short_color.png available?

**Comment by maelle** [comment]
Yay, awesome that it's so easy, and thanks for adopting the CSS!

Thanks for adding the favicon to the dev guide :grin:
