### ISSUE TITLE
Error parsing text

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#784]
When building a plan where I just want a value to equal a string, I got an unexpected error.  The example below is trivial, but I'm wanting to use this regexp pattern many places separately.  It wasn't immediately obvious why this is an issue.

After finding the issue, I assumed that wrapping it in `ignore()` would help, but it did not.

My immediate work-around will be to wrap this in a function, but it seems like something that could trip others up, too.  (Including my future self.)

``` r
library(drake)

make(drake_plan(log_pattern="log\\((.*?)\\)"))
#> Warning: Converting double-quotes to single-quotes because the
#> `strings_in_dots` argument is missing. Use the file_in(), file_out(), and
#> knitr_in() functions to work with files in your commands. To remove this
#> warning, either call `drake_plan()` with `strings_in_dots = "literals"` or
#> use `pkgconfig::set_config("drake::strings_in_dots" = "literals")`.
#> Warning: Files in a command declared with single-quotes:
#>   log\\((.*?)\\)
#> The use of single-quotes to declare files is deprecated. Use file_in(), file_out(), and knitr_in() in your commands. See `?drake_plan` for examples.
#> Warning: missing input files:
#>   log\\((.*?)\\)
#> Error in base::parse(text = code, keep.source = FALSE): <text>:1:4: unexpected input
#> 1: log\
#>        ^
make(drake_plan(log_pattern=ignore("log\\((.*?)\\)")))
#> Warning: Converting double-quotes to single-quotes because the
#> `strings_in_dots` argument is missing. Use the file_in(), file_out(), and
#> knitr_in() functions to work with files in your commands. To remove this
#> warning, either call `drake_plan()` with `strings_in_dots = "literals"` or
#> use `pkgconfig::set_config("drake::strings_in_dots" = "literals")`.
#> Warning: Files in a command declared with single-quotes:
#>   log\\((.*?)\\)
#> The use of single-quotes to declare files is deprecated. Use file_in(), file_out(), and knitr_in() in your commands. See `?drake_plan` for examples.
#> Warning: missing input files:
#>   log\\((.*?)\\)
#> target log_pattern
```

Created on 2019-03-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by wlandau** [comment]
It looks like you are using `drake` <= 6.2.1. Version 7.0.0 was released to CRAN last week, and it does not have this error. ([Details here](https://ropensci.org/technotes/2019/03/18/drake-700/)).

``` r
library(drake)
packageVersion("drake")
#> [1] '7.0.0'
plan <- drake_plan(log_pattern = "log\\((.*?)\\)")
make(plan)
#> target log_pattern
```

<sup>Created on 2019-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

This error comes from the old file API, which assumed all strings in commands were file names (clue: `strings_in_dots`). All remnants of the old file API were finally removed in `drake` 7.0.0.

**Comment by billdenney** [comment]
Thanks for the quick response.  Yes, I'm still using the old version (with plans to update probably next week).
