### ISSUE TITLE
Out of band file storage location with drake objects?

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#789]
What is the right location to store a file associated with a `drake`-managed target that is not directly controlled by the user?

In metrumresearchgroup/mrgsolve#471, I found an issue where the `mrgsolve` package expects compiled shared objects to be loaded prior to a simulation step.  This works as expected during the first call to `make()`, but if the R session is closed, a new R session is opened, a simulation setting is changed, and `make()` is run again, there is an error.  A fix for this particular issue is being implemented over there to try to load the shared objects, but...

The compiled filesystem objects associated with a drake target may not be correctly removed from the filesystem when the drake target is invalidated.

As a specific example:
1. The function `mcode_cache()` writes a compiled shared object to the filesystem.  The user has no control of the filename, and in normal usage doesn't want to know about it (that shared object is managed by the `mrgsolve` library).
2. If the call to `mcode_cache()` is invalidated as a target (e.g. one of the arguments changes), it's not clear to me that the filesystem will be correctly cleaned.  (Or even if it is correctly cleaned by `mrgsolve` there are other use cases like HTTP caching where it probably wouldn't be correctly cleaned.)

So, what I think is a feature request:  Could `drake` have something like a monitored directory which would capture files written to the filesystem that are not typically planned for direct user interaction, but `drake` could know that they are associated with a target, and if that target is invalidated, those files are deleted.

I'm thinking that the monitored directory could possible be named something like ".drake/monitor" or ".drake/watch", and before the first target and after each target, the directory would be recursively checked for changes and any changes would be considered implicitly like `file_out()`.

I understand that this could be an expensive operation, so monitoring would default to off.  (Though if unused, it may be less expensive... though if cluster parallelism were used, it would be hard to get right... I will understand if it's not the right fit.)

**Comment by wlandau** [comment]
Odd that models from old sessions do not work. When the functionality is available in `mrgsolve`, one workaround is indeed to use `file_in()`/`file_out()` and focus on the shared object file directly. Unless you plan to transfer the workflow to a different platform with different build tools, the shared object file should theoretically remain valid.

But do you really need compiled models to be targets? When I ran your example from https://github.com/metrumresearchgroup/mrgsolve/issues/471#issue-423015863, the model compiled very quickly.  If other PK models compile this fast, then you might consider compiling and running the model in a single target. You can do all this in a temporary directory to avoid dealing with messy output files (see `with_temp_dir()` below).

```r
library(mrgsolve)
library(drake)

model_text <- "
$PARAM @annotated
CL   :  1 : Clearance (volume/time)
V    : 20 : Central volume (volume)
KA   :  1 : Absorption rate constant (1/time)

$CMT  @annotated
EV   : Extravascular compartment
CENT : Central compartment

$GLOBAL
#define CP (CENT/V)

$PKMODEL ncmt = 1, depot = TRUE

$CAPTURE @annotated
CP : Plasma concentration (mass/volume)
"

with_temp_dir <- function(code) {
  while(file.exists(dir <- tempfile())) {} # dir <- tempfile() should be fine. The chance of a conflict is small.
  dir.create(dir)
  on.exit(unlink(dir, recursive = TRUE)) # Optional. You usually do not need to worry about removing temp files yourself.
  withr::with_dir(dir, code)
}

my_plan <- drake_plan(
  my_idata = data.frame(ID = 2),
  sim_result = with_temp_dir({
    model <- mcode(model_text, model = "pk1")
    mrgsim(model, idata = my_idata)
  })
)

make(my_plan)
```

Grouping stuff into targets is an art. To get the most out of `drake`, the amount of computation you pack into a target should be

1. Small enough that you skip the target a lot, and
2. Time-consuming enough to make skipping it useful.

As for the feature request, I hesitate to monitor files in the way you describe. `drake`'s main focus is your R session and R code, and the added complexity of `.drake/watch` seems to only benefit edge cases like this one.

**Comment by billdenney** [comment]
Thanks for the quick response as always!

As with many reproducible examples, this is more of a toy example.  The models are always fast to compile (seconds) while prior steps for parameter estimation and subsequent simulations and summaries can take a long time (usually minutes or less, but long enough that they make iteration on reporting slow).  In the real examples, there are other parts that go with the model compilation which make the model a logical unit target to collect other information (like parameters from other long-running steps).  I'll see what can be done with `file_out()`, and I'm pretty sure that I'll get what I need though in a less-generalized way.
