### ISSUE TITLE
inconsistency in naming using `map` transform with .id = FALSE

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#790]
``` r
library(drake)
drake_plan(
  data = target(
    get_data(param),
    transform = map(param = c(1, 2))
  ),
  results = target(
    get_results(data),     
    transform = map(param) 
  )
)
# This looks good.
#> # A tibble: 4 x 2
#>   target    command            
#>   <chr>     <expr>             
#> 1 data_1    get_data(1)        
#> 2 data_2    get_data(2)        
#> 3 results_1 get_results(data_1)
#> 4 results_2 get_results(data_2)

drake_plan(
  data = target(
    get_data(param),
    transform = map(param = c(1, 2))
  ),
  results = target(
    get_results(data),     
    transform = map(param, .id = FALSE) 
  )
)
# the "1" in "results_1" disappears
#> # A tibble: 4 x 2
#>   target    command            
#>   <chr>     <expr>             
#> 1 data_1    get_data(1)        
#> 2 data_2    get_data(2)        
#> 3 results   get_results(data_1)
#> 4 results_2 get_results(data_2)
```

<sup>Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by wlandau** [comment]
Hmm... interesting point. However, I am not sure there is anything inherently special about `param = c(1, 2)`. It is also common to see `param = c("x", "y")`, etc. To me, it seems better to stay consistent with all length-one base cases, i.e.

``` r
library(drake)
drake_plan(
  data = get_data("abc"),
  results = get_results(data)
)
#> # A tibble: 2 x 2
#>   target  command          
#>   <chr>   <expr>           
#> 1 data    get_data("abc")  
#> 2 results get_results(data)
```

<sup>Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

versus

``` r
library(drake)
drake_plan(
  data = target(
    get_data(param),
    transform = map(param = "abc", .id = FALSE)
  ),
  results = target(
    get_results(data),     
    transform = map(data, .id = FALSE) 
  )
)
#> # A tibble: 2 x 2
#>   target  command          
#>   <chr>   <expr>           
#> 1 data    get_data("abc")  
#> 2 results get_results(data)
```

<sup>Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Other reasons to continue omitting the `*_1` suffix:

- It allows us to apply [make_unique()](https://github.com/ropensci/drake/blob/f9c97edd653543aa4958a7a456cce5e5e57abf8f/R/utils-utils.R#L465) internally without needing messy logic to check for duplicates beforehand. `make.unique()` has similar behavior, but its second index is `.1`, which contradicts R's one-based indexing.
- We may eventually return to a feature like the proposed pipe (#746 and #748) and the implementation is much cleaner if the last target in the chain is the original base name.
