### ISSUE TITLE
Feels a bit weird that these are the same

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#792]
I would have thought that the first one here wouldn't work. I'd worry here that people learning these might get confused over the behavior with the first one.
``` r
library(drake)

# Expected this to throw an error
drake_plan(
  x = target(y, transform = map(y = c(1, 2, 3))),
  z = target(x, transform = combine(x))
)
#> # A tibble: 4 x 2
#>   target command            
#>   <chr>  <expr>             
#> 1 x_1    1                  
#> 2 x_2    2                  
#> 3 x_3    3                  
#> 4 z      list(x_1, x_2, x_3)

drake_plan(
  x = target(y, transform = map(y = c(1, 2, 3))),
  z = target(list(x), transform = combine(x))
)
#> # A tibble: 4 x 2
#>   target command            
#>   <chr>  <expr>             
#> 1 x_1    1                  
#> 2 x_2    2                  
#> 3 x_3    3                  
#> 4 z      list(x_1, x_2, x_3)
```

<sup>Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by kendonB** [comment]
Weird too:

``` r
library(drake)
  drake_plan(
  x = target(y, transform = map(y = c(1, 2, 3))),
  z = target(x + 2 - 1, transform = combine(x))
)
#> # A tibble: 4 x 2
#>   target command                  
#>   <chr>  <expr>                   
#> 1 x_1    1                        
#> 2 x_2    2                        
#> 3 x_3    3                        
#> 4 z      `+`(x_1, x_2, x_3, 2) - 1
```

<sup>Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by wlandau** [comment]
https://github.com/ropensci/drake/issues/792#issue-424031821: 

Now that version 7.0.0 is released, I am more hesitant to disable features that work as intended (ref: #717).

Personally, I like the convenience. You can just say "combine x" and `drake` will know what you mean.

There is some redundancy, but not ambiguity. Once we realize `x_1, x_2, x_3` is not valid language by itself, we see that `list(x_1, x_2, x_3)` is the only possible safe interpretation of `target(x, transform = combine(x))`. 

https://github.com/ropensci/drake/issues/792#issuecomment-475482060:

Interesting. I will ask on StackOverflow if we can add back the syntactic sugar. But speaking from experience, it is difficult to fight R's parser.

**Comment by wlandau** [comment]
Let's see what we find at https://stackoverflow.com/questions/55301813/recover-the-syntactic-sugar-of-operators

**Comment by wlandau** [comment]
From [this comment](https://stackoverflow.com/questions/55301813/recover-the-syntactic-sugar-of-operators?noredirect=1#comment97335180_55301813), https://github.com/ropensci/drake/issues/792#issuecomment-475482060 looks unavoidable. `drake` would have to check for all binary operators in order to get this right, and this is difficult, especially in static code analysis. Workaround: 

```r
drake_plan(
  x = target(y, transform = map(y = c(1, 2, 3))),
  z = target(sum(x) + 2 - 1, transform = combine(x))
)
#> # A tibble: 4 x 2
#>   target command                   
#>   <chr>  <expr>                    
#> 1 x_1    1                         
#> 2 x_2    2                         
#> 3 x_3    3                         
#> 4 z      sum(x_1, x_2, x_3) + 2 - 1
```

**Comment by wlandau** [comment]
Dynamic branching has more consistent `combine()` return values. Everything aggregated with `combine()` is always a list. The extra consistency comes from the fact that dynamic branching works entirely without metaprogramming (which also helps `make()` get going 10x faster than in the static case).

``` r
library(drake)
library(tibble)
plan <- drake_plan(
  x = tibble(x = rnorm(2), y = rnorm(2)),
  y = target(x, dynamic = map(x)),
  z = target(y, dynamic = combine(y))
)
make(plan)
#> target x
#> subtarget y_97652030
#> subtarget y_7100b24c
#> subtarget z_12c67aca

str(readd(z)[[1]])
#> List of 2
#>  $ :Classes 'tbl_df', 'tbl' and 'data.frame':    1 obs. of  2 variables:
#>   ..$ x: num 0.851
#>   ..$ y: num 0.327
#>  $ :Classes 'tbl_df', 'tbl' and 'data.frame':    1 obs. of  2 variables:
#>   ..$ x: num 0.545
#>   ..$ y: num -0.48

plan <- drake_plan(
  x = tibble(x = rnorm(2), y = rnorm(2)),
  y = target(x, dynamic = map(x)),
  z = target(list(y), dynamic = combine(y))
)
make(plan)
#> subtarget z_12c67aca

str(readd(z)[[1]])
#> List of 1
#>  $ :List of 2
#>   ..$ :Classes 'tbl_df', 'tbl' and 'data.frame': 1 obs. of  2 variables:
#>   .. ..$ x: num 0.851
#>   .. ..$ y: num 0.327
#>   ..$ :Classes 'tbl_df', 'tbl' and 'data.frame': 1 obs. of  2 variables:
#>   .. ..$ x: num 0.545
#>   .. ..$ y: num -0.48
```

<sup>Created on 2019-11-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
