### ISSUE TITLE
Feature Request: directory_out()?

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#794]
This is related to both #721 and #789.

As I'm working on implementing some of the aspects of a pseudo-monitored directory from the discussion in #789, I find that I'm hitting a wall with unknown filenames.  Rather than the completely generalized monitored directory solution from #789, I wonder if a `directory_out()` command could be implemented?

I'm thinking that the method would assume that the directory was empty before the target were run, and that any files in the directory were created by that target.  Ideally, it would have a `recursive` option to check recursively from that directory.

The challenge that I'm hitting with the solutions I see available relates to lack of control of the filenames of target.  The only way that I can think of making the right selections is to run everything once, determine the `file_out()` options, hard code them, and then rerun from there.  But, since I don't control the filenames, were they to be randomly assigned (e.g. with `tempfile()`), that wouldn't really work.  Also, with a case similar to #721, if an external process works, one set of files will be generated, if the external process fails, a different set of files will be generated (and detecting success or failure prior to running the step is impossible).

P.S. For API parallelism, `directory_in()` would also be useful, especially in the #721 case.

**Comment by wlandau** [comment]
Yeah, let's revisit #12. A lot has changed in `drake` since I last looked at that thread.

**Comment by wlandau** [comment]
Thanks for the reminder about #12. I think #795 is powerful, clean, and consistent with `drake`'s attitude toward files.

**Comment by billdenney** [comment]
I feel like it's 100% my pleasure!  :)

**Comment by wlandau** [comment]
Related: #1178
