### ISSUE TITLE
Unnamed .RData file with functions sitting in workdir after calling make

### ISSUE THREAD

**Issue by LDalby** [ropensci/drake#801]
After I've run make on my plan I have an unnamed .RData file containing the functions I've sourced in my master file. If I then later run want to rerun, I get the following warning:

```
Warning message:
Auto-saved workspace file '.RData' detected. This is bad for reproducible code. You can remove it with unlink(".RData"). 
```
What I'm I doing wrong here? Is this .RData file supposed to be there or is it maybe some cleanup that fails?

**Comment by wlandau** [comment]
To avoid saving `.RData` files, you can start R with `R --no-save` in the terminal or disable the saving of workspace images in the RStudio IDE (under `Tools > Global Options...` or `Tools > Project Options...`). I will expand the warning message to give a better hint.

![Capture](https://user-images.githubusercontent.com/1580860/55160310-7043fb80-5139-11e9-978a-c894d5a0eca8.PNG)

**Comment by LDalby** [comment]
Thank's for your response!

I already have RStudio set up that way so that's not causing it. I followed the suggestion in section 4.1 in the manual and ran `R CMD BATCH make.R` to make my plan. 
Perhaps it would be good to update that command to read: `R CMD BATCH --no-save make.R`?

**Comment by wlandau** [comment]
> Perhaps it would be good to update that command to read: R CMD BATCH --no-save make.R?

Yes, exactly.

**Comment by wlandau** [comment]
I will update the guidance.
