### ISSUE TITLE
Reduce the memory footprint of the plan.

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#812]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [x] Advanced users: verify that the bottleneck still persists in the current development version (i.e. `remotes::install_github("ropensci/drake")`) and mention the [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity) of the [Git commit you install](https://github.com/ropensci/drake/commits/master).

## Description

In `drake` >= 7.0.0, commands in plans are language objects rather than character strings. The change seemed positive at the time: it decreased preprocessing time and increased the sophistication of the metaprogramming. However, the plan now takes up a lot more memory, and it is interfering with issues like #800. cc @kendonB.

## Reproducible example and benchmarks

``` r
library(drake)
plan <- drake_plan(
  x = target({
      your(really(long(command(i))))
      takes(up(a(lot(of(memory())))))
    },
    transform = map(i = !!seq_len(10000))
  )
)
print(object.size(plan), units = "KB")
#> 19297.9 Kb
print(object.size(plan$target), units = "KB")
#> 625.1 Kb
print(object.size(plan$command), units = "KB")
#> 18671.9 Kb
command_text <- purrr::map_chr(plan$command, drake:::safe_deparse)
print(object.size(command_text), units = "KB")
#> 1796.9 Kb
```

<sup>Created on 2019-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

## Some options

1. Do not store the plan in `config`. 
2. Go back to text.
3. Do nothing

(1) is probably best. We may be able to downsize other parts of `config` too.

**Comment by kendonB** [comment]
Is it also an option to not expand the plan using the DSL until the very last second (in my case, on the worker)? Or only when printing ( requiring a `drake_plan` S3 class with a print method)?

**Comment by wlandau** [comment]
That's certainly where we want to go for #685, but it is very long-term.

**Comment by wlandau** [comment]
Wait... @kendonB, I think this may actually be possible in the short term. Maybe `drake_plan(lazy = TRUE)` could return an [active binding](https://www.rdocumentation.org/packages/base/versions/3.5.3/topics/bindenv) that evaluates the transforms when the object is referenced. The callback would also need to perform tidy evaluation and cleanup because the DSL comes afterwards, re #696.

**Comment by wlandau** [comment]
The feature may need to come after April's maintenance release.

**Comment by wlandau** [comment]
Unfortunately, none of this affects `config$layout`, which is much more difficult to condense.

**Comment by wlandau** [comment]
I would still like to first try not storing the plan in `config` at all.

**Comment by wlandau** [comment]
On reflection, I think `drake` has outgrown the data frame as a data structure for plans. The original purpose was to give users control. R programmers and statisticians already know how to transform/munge data frames, and I was hoping to auto-magically carry over our users' already strong data/`dplyr` skills to post-processing wizardry. However, I do not think that happens in practice. Especially with the [DSL](https://ropenscilabs.github.io/drake-manual/plans.html#large-plans), it seems like most users just call `drake_plan()` once and then leave the plan alone.

So then what kind of data structure should replace the current one? Maybe an unexpanded data frame inside a reference class? Can we do it all in S3 with special print/expand methods as in https://github.com/ropensci/drake/issues/812#issuecomment-479212039? What if `drake_plan(expand = "lazy")` generated a data frame of class `c("drake_plan", "drake_unexpanded", "tbl_df", "tbl", "data.frame")`, which we could expand to a class of `c("drake_plan", "tbl_df", "tbl", "data.frame")` when we need to? Then again, that adds complexity, which adds up to a lot of clutter. Should we just rip the band-aid off and always delay expansion? Would that require a new major version bump? We just released version 7, and I think it is far too early for version 8.

**Comment by kendonB** [comment]
> The original purpose was to give users control. R programmers and statisticians already know how to transform/munge data frames, and I was hoping to auto-magically carry over our users' already strong data/dplyr skills to do post-processing wizardry. However, I do not think that happens in practice. Especially with the DSL, it seems like most users just call drake_plan() once and then leave the plan alone. The opportunity/control was not as easy or obvious as I had originally thought.

Agree.


> On reflection, I think drake has outgrown the data frame as a data structure for plans. 

Perhaps. We're still just talking about a few hundred MB for quite a large plan. This seems to add up when sending to hundreds of workers, but for the vast majority of users a few hundred MB in main memory is benign. It also shifts the expansion burden to `make` and potentially `print` which users may call many times after calling `drake_plan`. I often will also just check what a command looks like using `plan$command[i]` or `plan %>% filter(target %>% str_detect("x")) %>% pull(command)`. How would that work?

That being said, there is an opportunity here to lighten the load of the main script. If a lot of people start to use `drake` on HPCs, you could imagine the testing/launching nodes getting clogged up, though that seems like a distant prospect. 

I think overall I now disagree with https://github.com/ropensci/drake/issues/812#issuecomment-479212039 being the right way to go, as doing it well would require a huge number of subset and assignment cases being handled (see all the dplyr/base methods in https://github.com/r-spatial/sf/, for example). I think I was too optimistic to think that it would just be `print` that would be affected.

**Comment by wlandau** [comment]
> This seems to add up when sending to hundreds of workers...

That reminds me: what does #800 look like for you now? Since we last spoke about it, I redirected the closure of `config$sleep`, which could get jobs going even faster.

> It also shifts the expansion burden to make and potentially print which users may call many times after calling drake_plan.

Yeah, expansion takes a second or two for enormous plans, and `print()` methods need to be faster. I did profiling studies for version 7.0.0 to minimize the delay, but it's still not totally gone. Perhaps a better metaprogramming strategy could shortcut even more of the parsing and deparsing, but rearchitecting the DSL to optimize performance seems like a low priority right now.

> I often will also just check what a command looks like using plan$command[i] or plan %>% filter(target %>% str_detect("x")) %>% pull(command). How would that work?

We would need the plan to be an [active binding](https://yihui.name/en/2018/08/make-active-binding/) for that code to work verbatim. If not, it would something look like `run_the_dsl(plan) %>% filter(target %>% str_detect("x")) %>% pull(command)`. Either way, expansion is still not instantaneous.

> That being said, there is an opportunity here to lighten the load of the main script. If a lot of people start to use drake on HPCs, you could imagine the testing/launching nodes getting clogged up, though that seems like a distant prospect.

The plan itself is no longer sent to HPC nodes, but there are certainly other ways to reduce the data we send, e.g. worker affinities (re https://github.com/ropensci/drake/issues/672#issuecomment-479622413). Or were you thinking of something slightly different?

> I think overall I now disagree with #812 (comment) being the right way to go, as doing it well would require a huge number of subset and assignment cases being handled (see all the dplyr/base methods in r-spatial/sf, for example). I think I was too optimistic to think that it would just be print that would be affected.

With the help of an [active binding](https://yihui.name/en/2018/08/make-active-binding/), maybe not. As the benchmarks below indicate, we re-invoke `drake_plan()` whenever we refer to the `plan`.

``` r
library(drake)
library(microbenchmark)
library(stringr)
library(tidyverse)

makeActiveBinding(
  "plan",
  function(i) {
    drake_plan(
      x = target(y, transform = map(y = !!seq_len(1e4)))
    )
  },
  globalenv()
)

microbenchmark(
  expr = plan %>%
    filter(target %>% str_detect("1"))
)
#> Unit: seconds
#>  expr      min       lq     mean   median       uq      max neval
#>  expr 3.784161 3.848204 3.888898 3.866353 3.934228 4.223285   100
```

<sup>Created on 2019-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by kendonB** [comment]
> That reminds me: what does #800 look like for you now? Since we last spoke about it, I redirected the closure of config$sleep, which could get jobs going even faster.

The first target to the first worker gets allocated quite fast now (11 seconds!). It still takes a few minutes for all 200 workers to get their first worker but I'm not sure there's much you can do to speed that up.

> > That being said, there is an opportunity here to lighten the load of the main script. If a lot of people start to use drake on HPCs, you could imagine the testing/launching nodes getting clogged up, though that seems like a distant prospect.

> The plan itself is no longer sent to HPC nodes, but there are certainly other ways to reduce the data we send, e.g. worker affinities (re #672 (comment)). Or were you thinking of something slightly different?

I was thinking about a world where 500 big drake projects are being run from a launching/testing node on an HPC. Our one in NZ (NeSI), for example, has a 32 core 500 GB machine that scientists can log into to test code and launch jobs. You could imagine many projects' master memory clogging up one of these nodes. Like I said, I think we're a long way from that.

> With the help of an active binding, maybe not. As the benchmarks below indicate, we re-invoke drake_plan() whenever we refer to the plan.

Sounds great! Googlers (and maybe the manual) should note that they can use this workaround to get it to only run once if they want: `plan_2 <- force(plan)`.

**Comment by kendonB** [comment]
I usually can't get 500 jobs going but I just tried it (on a Sunday evening) and they all started at once. The first target got assigned after almost 5 minutes so there's definitely still room for improvement for these very large jobs. The assignment rate after the first target gets allocated is around 5/second so it looks like a few more minutes for all workers to be doing something.

**Comment by wlandau** [comment]
> The first target to the first worker gets allocated quite fast now (11 seconds!). It still takes a few minutes for all 200 workers to get their first worker but I'm not sure there's much you can do to speed that up...I usually can't get 500 jobs going but I just tried it (on a Sunday evening) and they all started at once. The first target got assigned after almost 5 minutes so there's definitely still room for improvement for these very large jobs. The assignment rate after the first target gets allocated is around 5/second so it looks like a few more minutes for all workers to be doing something.

I just proposed https://github.com/mschubert/clustermq/issues/138, which could help us find the new bottleneck. I hesitate to clog up `drake`'s own console log file for this since `clustermq` already has such detailed logs.

> I was thinking about a world where 500 big drake projects are being run from a launching/testing node on an HPC. Our one in NZ (NeSI), for example, has a 32 core 500 GB machine that scientists can log into to test code and launch jobs. You could imagine many projects' master memory clogging up one of these nodes. Like I said, I think we're a long way from that.

Good point, it is helpful to have this kind of scale in mind as we move forward.

**Comment by wlandau** [comment]
On a related note, I believe it is possible to send the master process to a compute node as well: that is, to use `srun` to submit a script that calls `drake` and have `drake` call `sbatch` through `clustermq`. That would go farther to conserve resources on the login node. I remember testing this out on SGE, and a naive attempt appeared to work. Perhaps the recommendations at https://github.com/ropenscilabs/drake-manual/blob/master/hpc.Rmd#L22 and https://github.com/ropenscilabs/drake-manual/blob/master/projects.Rmd#L92 need an update.

**Comment by kendonB** [comment]
Yes I don't see any reason why this wouldn't work using srun.

**Comment by wlandau** [comment]
Agreed. And from my initial work on [branch `812`](https://github.com/ropensci/drake/tree/812), I think it is definitely possible to remove the `plan` from `config`. It's just going to take a lot of refactoring to update the tests and double-check the edge cases.

**Comment by wlandau** [comment]
I think #840 covers what we need. Delayed expansion of the plan is no longer as urgent, and it may be prudent to wait for #685. May revisit.

**Comment by wlandau** [comment]
Dynamic branching delays the expansion of the layout.
