### ISSUE TITLE
Master process hangs upon oom error on SLURM with clustermq

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#813]
The content of https://github.com/ropensci/drake/issues/549 suggests that I should get a message on master upon an oom error.

I run:

```r
library(tidyverse)
library(drake)
options(clustermq.scheduler = "slurm", 
        clustermq.template = "slurm_clustermq.tmpl")

make(
  drake_plan(
    assign_massive_vector = {
      big_vector <- 1:1e15
      
      massive_vector = c(big_vector, big_vector, big_vector)
    }
  ),
  verbose = 4,
  jobs = 1,
  parallelism = "clustermq",
  template = list(memory = "5M",
                  # minutes
                  walltime = 5,
                  # partition = "prepost",
                  log_file = "make.log"),
  console_log_file = NULL)
```
And on the master I see (and it's hanging after the oom error):
```
Submitting 1 worker jobs (ID: 7358) ...
Warning in private$fill_options(...) :
  Add 'CMQ_AUTH={{ auth }}' to template to enable socket authentication
```

On the worker I see:
```r
/var/spool/slurm/job2958959/slurm_script: line 15: 138755 Killed                  Rscript -e 'clustermq:::worker("tcp://mahuika01:7358", v
erbose = TRUE)'
slurmstepd: error: Detected 1 oom-kill event(s) in step 2958959.batch cgroup.
```

**Comment by wlandau** [comment]
Unfortunately, there is nothing `drake` can do here. It looks like @mschubert plans to address this problem in https://github.com/mschubert/clustermq/issues/33.

**Comment by mschubert** [comment]
Also relevant: https://github.com/mschubert/clustermq/issues/110#issuecomment-449967789

> >28/400 workers ended with the following out of memory error
>
> Can you try adding a call to [`ulimit`](https://github.com/krlmlr/ulimit) at the beginning of your function and see if this works? This way it will produce an R error that will get sent back to the master process.
> 
> I used this in clustermq in the past, but since it's not on CRAN had to rely on the shell's ulimit instead (which should do the same, but sometimes fails).

**Comment by wlandau** [comment]
Oh, interesting. @kendonB, maybe in the template (e.g. [`slurm_clustermq.tmpl`](https://github.com/ropensci/drake/blob/master/inst/templates/hpc/slurm_clustermq.tmpl)) instead of 

```r
ulimit -v $(( 1024 * {{ memory | 4096 }} ))
CMQ_AUTH={{ auth }} R --no-save --no-restore -e 'clustermq:::worker("{{ master }}")'
```

you could try

```r
CMQ_AUTH={{ auth }} R --no-save --no-restore -e 'ulimit::memory_limit({{ memory | 4096 }}); clustermq:::worker("{{ master }}")'
```

**Comment by kendonB** [comment]
Tried this and no change in behavior

**Comment by mschubert** [comment]
Hm, interesting. I had memory limits fail on occasion, but not in a way that I could reproduce.

It is possible that there is some process overhead that is tracked by SLURM but not the shell/R, or that your job reserves some memory outside of the reach of ulimit.

Can you check how much memory you are over the limit (job log), and if you can get around this by setting e.g.:

```r
ulimit::memory_limit({{ memory | 4096 }}-100)
```

**Comment by mschubert** [comment]
Oh never mind, I didn't see you tested with a huge vector.

The issue here is a different one: your Slurm scheduler understands "5M", but `ulimit` does not. And R already uses more than that, so the limit would likely be ineffective too.

**Comment by kendonB** [comment]
@wlandau @mschubert turns out I had actually disabled ulimit in the first place as it had been failing since I was using "5G" etc instead of 5120.

Switched to just using the numeric argument and now can see the error message get through. Thanks!

**Comment by mschubert** [comment]
@kendonB Do you remember if you already had ulimit disabled for https://github.com/mschubert/clustermq/issues/110?

**Comment by kendonB** [comment]
It is likely that I didn't have ulimit on but I can't remember exactly. I wonder if it's worth having some code translate the "5G" etc that slurm understands to numeric MBs within the clustermq call?

**Comment by mschubert** [comment]
Yes, that makes sense. I'll likely add this when I'm moving ulimit to R and don't have to use a lot of bash magic (expected `v1.0`).
