### ISSUE TITLE
Reduce the object size of config$layout

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#815]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [x] Advanced users: verify that the bottleneck still persists in the current development version (i.e. `remotes::install_github("ropensci/drake")`) and mention the [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity) of the [Git commit you install](https://github.com/ropensci/drake/commits/master).

## Description

From https://github.com/ropensci/drake/issues/800#issuecomment-476926230, the `config$layout` is way too big. I think we can do better. The current format is a nested list structure, and most of the leaves are just character vectors. We can probably store the characters in contiguous memory arrays. Might be nice to have a reference class wrapper around it with `get()` methods to abstract it away.

**Comment by wlandau** [comment]
We might see gains in both memory and storage if `config$layout` is a `new.env(hash = hash, parent = emptyenv())`. We would have to loop over the layout differently internally, but that's not such a big deal.

**Comment by wlandau** [comment]
Similarly, each element of `config$layout` could be a `new.env(hash = FALSE, parent = emptyenv())`.

**Comment by wlandau** [comment]
Also, I am seeing that `config$layout[[target]]$deps_build` is a list with slots "globals" and "memory". We can probably convert this to higher-level `deps_build` and `deps_memory` character vector slots.

**Comment by wlandau** [comment]
Comparisons between environments and lists using `pryr::object_size()` are telling me that environments and lists are about equivalent.

**Comment by wlandau** [comment]
@kendonB, for the project in #800, what does `pryr::object_size(config$layout)` look like?

**Comment by wlandau** [comment]
What about `pryr::object_size(lapply(config$layout, function(x) x$trigger))`?

**Comment by wlandau** [comment]
## Benchmarks

### 10000 independent targets

``` r
library(drake)
library(pryr)
plan <- drake_plan(x = target(y, transform = map(y = !!seq_len(1e4))))
nrow(plan)
#> [1] 10000
config <- drake_config(plan)
pryr::object_size(config)
#> 13.7 MB
object_size(config$layout)
#> 12.4 MB
object_size(lapply(config$layout, function(x) x$trigger))
#> 721 kB
```

<sup>Created on 2019-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### 10002 targets with expansion and aggregation stages

``` r
library(drake)
library(pryr)
  library(drake)
  library(pryr)
  plan <- drake_plan(
    x = 1,
    y = target(f(x, i), transform = map(i = !!seq_len(1e4))),
    z = target(y, transform = combine(y))
  )
  nrow(plan)
#> [1] 10002
  config <- drake_config(plan)
  pryr::object_size(config)
#> 20.9 MB
  object_size(config$layout)
#> 17.5 MB
  object_size(lapply(config$layout, function(x) x$trigger))
#> 721 kB
```

<sup>Created on 2019-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>


### 4096 targets and up to 64 dependencies per target

``` r
library(drake)
library(pryr)
plan_more_deps <- function(n, max_deps) {
  plan <- drake_plan(target_1 = 1)
  for (i in seq_len(n - 1) + 1){
    target <- paste0("target_", i)
    dependencies <- paste0("target_", tail(seq_len(i - 1), max_deps))
    command <- paste0("max(", paste0(dependencies, collapse = ", "), ")")
    plan <- rbind(plan, data.frame(target = target, command = command))
  }
  plan
}
plan <- plan_more_deps(4096L, 64L)
plan
#> # A tibble: 4,096 x 2
#>    target    command                                                       
#>    <chr>     <expr>                                                        
#>  1 target_1  1                                                            …
#>  2 target_2  "max(target_1)"                                              …
#>  3 target_3  "max(target_1, target_2)"                                    …
#>  4 target_4  "max(target_1, target_2, target_3)"                          …
#>  5 target_5  "max(target_1, target_2, target_3, target_4)"                …
#>  6 target_6  "max(target_1, target_2, target_3, target_4, target_5)"      …
#>  7 target_7  "max(target_1, target_2, target_3, target_4, target_5, target…
#>  8 target_8  "max(target_1, target_2, target_3, target_4, target_5, target…
#>  9 target_9  "max(target_1, target_2, target_3, target_4, target_5, target…
#> 10 target_10 "max(target_1, target_2, target_3, target_4, target_5, target…
#> # … with 4,086 more rows
nrow(plan)
#> [1] 4096
config <- drake_config(plan)
pryr::object_size(config)
#> 12.7 MB
object_size(config$layout)
#> 12 MB
object_size(lapply(config$layout, function(x) x$trigger))
#> 329 kB
```

<sup>Created on 2019-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### A 4096-target plan with the maximum dependencies among targets

``` r
library(drake)
library(pryr)
saturated_plan <- function(n) {
  plan <- drake_plan(target_1 = 1)
  for (i in seq_len(n - 1) + 1){
    target <- paste0("target_", i)
    dependencies <- paste0("target_", seq_len(i - 1))
    command <- paste0("max(", paste0(dependencies, collapse = ", "), ")")
    plan <- rbind(plan, data.frame(target = target, command = command))
  }
  plan
}
plan <- saturated_plan(4096L)
plan
#> # A tibble: 4,096 x 2
#>    target    command                                                       
#>    <chr>     <expr>                                                        
#>  1 target_1  1                                                            …
#>  2 target_2  "max(target_1)"                                              …
#>  3 target_3  "max(target_1, target_2)"                                    …
#>  4 target_4  "max(target_1, target_2, target_3)"                          …
#>  5 target_5  "max(target_1, target_2, target_3, target_4)"                …
#>  6 target_6  "max(target_1, target_2, target_3, target_4, target_5)"      …
#>  7 target_7  "max(target_1, target_2, target_3, target_4, target_5, target…
#>  8 target_8  "max(target_1, target_2, target_3, target_4, target_5, target…
#>  9 target_9  "max(target_1, target_2, target_3, target_4, target_5, target…
#> 10 target_10 "max(target_1, target_2, target_3, target_4, target_5, target…
#> # … with 4,086 more rows
nrow(plan)
#> [1] 4096
config <- drake_config(plan)
pryr::object_size(config)
#> 216 MB
object_size(config$layout)
#> 215 MB
object_size(lapply(config$layout, function(x) x$trigger))
#> 329 kB
```

<sup>Created on 2019-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

## Conclusions

- Triggers take up a tiny fraction of space compared with the rest of the layout. I no longer think #824 is worth the trouble.
- The size of the layout can blow up if the number of dependencies is ridiculous, but otherwise, it is not so bad.
- The next suspect for a memory drain is the size of the commands in the plan. In these cases, users should make their commands short by offloading to custom functions. This is a usually a good practice anyway because it makes workflows cleaner and more readable, though it does have its limits, re https://github.com/ropensci/drake/issues/706.

## Decision

Close #815 and #824. Continue to implement #816.

**Comment by wlandau** [comment]
Closing, re https://github.com/ropensci/drake/issues/815#issuecomment-484130906.

**Comment by kendonB** [comment]
> @kendonB, for the project in #800, what does pryr::object_size(config$layout) look like? Are the units in #800 (comment) bytes?

Are you still interested in this? I see you have done your own benchmarking

**Comment by wlandau** [comment]
Yes, thank you, that would still help. The test cases in https://github.com/ropensci/drake/issues/815#issuecomment-484130906 are not as realistic as your project.
