### ISSUE TITLE
drake 7.1.0: Error: unused argument (layout = layout)

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#831]
Works with v7.0.0

I haven't found any argument named `layout` in my project so I assume its an internal bug?

```r
> clustermq:::worker("tcp://edi:7360")
Master: tcp://edi:7360
WORKER_UP to: tcp://edi:7360
> DO_SETUP (0.171s wait)
token from msg: set_common_data_token
> DO_CALL (0.000s wait)
Error in drake::cmq_build(target = target, meta = meta, deps = deps, layout = layout,  : 
  unused argument (layout = layout)
eval'd: drake::cmq_buildtargetmetadepslayoutconfig
slurmstepd: error: *** JOB 1811 ON edi CANCELLED AT 2019-04-10T13:19:17 ***
```

**Comment by wlandau** [comment]
Oooh that sounds egregious. Are your `SLURM` compute nodes are using a different local package library than the local process that calls `make()`? If you have `drake` 7.0.0 on the nodes and version 7.1.0 locally, that would cause the error you are seeing. If that does not solve the problem, would you post a reprex?

I did run a local HPC test suite before I submitted `drake` 7.1.0 to CRAN. I only have access to SGE, but the results *should* generalize, especially for this issue. The following works for me. 

```r
library(drake)
clean(destroy = TRUE)
load_mtcars_example()
options(clustermq.scheduler = "sge", clustermq.template = "sge_clustermq.tmpl")
print(my_plan)
make(my_plan, parallelism = "clustermq", jobs = 2, verbose = 2)
```

With `sge_clustermq.tmpl`: 

```r
# From https://github.com/mschubert/clustermq/wiki/SGE
#$ -N {{ job_name }}               # job name
#$ -t 1-{{ n_jobs }}               # submit jobs as array
#$ -j y                            # combine stdout/error in one file
#$ -o {{ log_file | /dev/null }}   # output file
#$ -cwd                            # use pwd as work dir
#$ -V                              # use environment variable
#$ -pe smp 1                       # request 1 core per job
module load R
ulimit -v $(( 1024 * {{ memory | 4096 }} ))
CMQ_AUTH={{ auth }} R --no-save --no-restore -e 'clustermq:::worker("{{ master }}")'
```

**Comment by pat-s** [comment]
> Oooh that sounds egregious. Are your SLURM compute nodes are using a different local package library than the local process that calls make()?

I don't think so as I load the R version using an environment module from a packrat managed R library:

```r
# packrat dir
cd ~/papers/2019-feature-selection
spack load r@3.5.2
```

This is basically just a wrapper around `module load`.
I also started a fresh R session after upgrading to 7.1.0 to make sure no twerks are going on.

I'll see if I can make a reprex later today :)

**Comment by wlandau** [comment]
Sounds good. Here is another thing you could try. Below, `drake::cmq_build()` on the workers should indeed have a `layout` argument.

```r
library(clustermq)
options(clustermq.scheduler = "slurm", clustermq.template = "your.tmpl")
f <- function(x) {
  list(
    version = packageVersion("drake"),
    lib = .libPaths(),
    si = sessionInfo(),
    cmq_build = deparse(drake::cmq_build)
  )
}
clustermq::Q(f, x = 1, n_jobs = 1)
#> Submitting 1 worker jobs (ID: 6924) ...
#> Running 1 calculations (1 calls/chunk) ...
#> Master: [1.5s 7.9% CPU]; Worker: [avg 34.2% CPU, max 247.1 Mb]
#> [[1]]
#> [[1]]$version
#> [1] 7.1.0.9000
#> 
#> [[1]]$lib
#> [1] <CENSORED>
#> [2] <CENSORED>
#> 
#> [[1]]$si
#> R version 3.5.2 (2018-12-20)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Red Hat Enterprise Linux
#> 
#> Matrix products: default
#> BLAS: <CENSORED>/R-3.5.2/lib64/R/lib/libRblas.so
#> LAPACK: <CENSORED>/R-3.5.2/lib64/R/lib/libRlapack.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base
#> 
#> loaded via a namespace (and not attached):
#> [1] compiler_3.5.2  magrittr_1.5    rzmq_0.9.6      clustermq_0.8.6
#> [5] rlang_0.3.2     purrr_0.3.2
#> 
#> [[1]]$cmq_build
#>  [1] "function (target, meta, deps, layout, config) "
#>  [2] "{"
#>  [3] "    config$layout <- list()"
#>  [4] "    config$layout[[target]] <- layout"
#>  [5] "    do_prework(config = config, verbose_packages = FALSE)"
#>  [6] "    if (identical(config$caching, \"master\")) {"
#>  [7] "        for (dep in names(deps)) {"
#>  [8] "            config$eval[[dep]] <- deps[[dep]]"
#>  [9] "        }"
#> [10] "    }"
#> [11] "    else {"
#> [12] "        manage_memory(targets = target, config = config, jobs = 1)"
#> [13] "    }"
#> [14] "    build <- build_target(target = target, meta = meta, config = config)"
#> [15] "    if (identical(config$caching, \"master\")) {"
#> [16] "        build$checksum <- mc_get_outfile_checksum(target, config)"
#> [17] "        return(build)"
#> [18] "    }"
#> [19] "    conclude_build(build = build, config = config)"
#> [20] "    list(target = target, checksum = mc_get_checksum(target, "
#> [21] "        config))"
#> [22] "}"
```

**Comment by wlandau** [comment]
@pat-s, are you still encountering this issue?

**Comment by pat-s** [comment]
I'll investigate later today, did not had time so far :)

**Comment by pat-s** [comment]
## Example1
Still getting the error.

```r
make(my_plan, parallelism = "clustermq", jobs = 2, verbose = 2, template = list(n_cpus=1, memory = 2000))
cache /home/patrick/.drake
analyze environment
trim schedule
construct priority queue
Submitting 2 worker jobs (ID: 6745) ...
target large
Error: argument "layout" is missing, with no default
```

## Example 2

```r
clustermq::Q(f, x = 1, n_jobs = 1, template=list(n_cpus=1, memory=2000))
Submitting 1 worker jobs (ID: 6603) ...
Running 1 calculations (1 calls/chunk) ...
Master: [1.8s 1.7% CPU]; Worker: [avg 87.5% CPU, max 248.7 Mb]
[[1]]
[[1]]$version
[1] ‘7.1.0’

[[1]]$lib
[1] "/home/patrick/papers/2019-feature-selection/packrat/lib/x86_64-pc-linux-gnu/3.5.2"
[2] "/home/patrick/papers/2019-feature-selection/packrat/lib-ext/x86_64-pc-linux-gnu/3.5.2"
[3] "/opt/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/r-3.5.2-u4rud7p6dekjwtit2bkl6sx6cghxhjjp/rlib/R/library"

[[1]]$si
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /opt/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/openblas-0.3.5-zncvk4jccaqyfl4z3vszaboeps6hyzta/lib/libopenblas_zen-r0.3.5.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.5.2  magrittr_1.5    tools_3.5.2     rzmq_0.9.4      clustermq_0.8.6 packrat_0.5.0   rlang_0.3.4
[8] purrr_0.3.0

[[1]]$cmq_build
 [1] "function (target, meta, deps, layout, config) "

```

**Comment by wlandau** [comment]
Is there a way to print a `traceback()`?

**Comment by wlandau** [comment]
Originally, you got:

```r
Error in drake::cmq_build(target = target, meta = meta, deps = deps, layout = layout,  : 
  unused argument (layout = layout)
```

But now, you have the opposite error:

```r
Error: argument "layout" is missing, with no default
```

What changed between now and then?

In the first error, the *new* call to `cmq_build()` invoked the *old* `cmq_build()` function. In the second one, the *old* call to `cmq_build()` invoked the *new* `cmq_build()` function. From your `.libPaths()`, three different installations of `drake` could be competing with one another. **Which version of `drake` is installed in each**?

```r
[[1]]$lib
[1] "/home/patrick/papers/2019-feature-selection/packrat/lib/x86_64-pc-linux-gnu/3.5.2"
[2] "/home/patrick/papers/2019-feature-selection/packrat/lib-ext/x86_64-pc-linux-gnu/3.5.2"
[3] "/opt/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/r-3.5.2-u4rud7p6dekjwtit2bkl6sx6cghxhjjp/rlib/R/library"
```

If this does not explain it, I am out of ideas. You may need to completely erase and reconstruct any package libraries that could be contributing to the problem, but I hope it does not come to that.

**Comment by pat-s** [comment]
> But now, you have the opposite error:

Nice catch! Did not see that yesterday. I just quickly ran the example and did not have much time then.

> What changed between now and then?

Nothing changed (at least nothing I would consider important to change anything in this process).

> "/home/patrick/papers/2019-feature-selection/packrat/lib-ext/x86_64-pc-linux-gnu/3.5.2"

Is empty. (and deleted now)

> "/opt/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/r-3.5.2-u4rud7p6dekjwtit2bkl6sx6cghxhjjp/rlib/R/library"

Has v7.0.0

> "/home/patrick/papers/2019-feature-selection/packrat/lib-ext/x86_64-pc-linux-gnu/3.5.2"

Has 7.1.0

Actually I expect the workers to also use the packrat library.


Note: Now I messed up everything somehow and cannot even pass the jobs to the scheduler anymore. Have to debug a bit. 
But it looks like it maybe indeed a lib problem here. 
I'll keep you informed (on it right now).

**Comment by pat-s** [comment]
Got it working now with v7.1.0.

Unfortunately, I cannot really say what the final problem was. I suspect that it was a R library clash even though I specifically use the `packrat` library also for the workers. 

In the end I also faced some other issues unrelated to `drake` on the nodes due to a recent update of the computes image.

I feel sorry for taking so much off your time for an issue which turned out to be a problem on my side (most likely a library clash). Thanks for debugging with me ;)

**Comment by wlandau** [comment]
@pat-s, thank you so much for digging further and updating me. Job submission and worker management are critical pieces of drake that need to stay working, especially in releases. Please let me know what else I can do as you get your resources back in order.
