### ISSUE TITLE
Allow for trailing comma in bind_plans

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#835]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

All in the title.

``` r
  library(drake)
bind_plans(
  drake_plan(x = 1),
)
#> Error in vapply(X = x, FUN = function(y) {: argument is missing, with no default
```

<sup>Created on 2019-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wlandau** [comment]
Now fixed.

...so `bind_plans()` is still useful even with the DSL?

**Comment by kendonB** [comment]
I used it as I wanted tidy_eval = FALSE for just part of a plan. Is there a way to do this without bind_plans?

**Comment by wlandau** [comment]
I have considered an optional `tidy_eval` argument of `target()`. Still not sure it's worth the trouble, but I could be convinced.

**Comment by kendonB** [comment]
I don't think it's worth it if you plan to keep bind_plans.

>

**Comment by wlandau** [comment]
As long as `drake` plans are data frames, `bind_plans()` is here to stay.
