### ISSUE TITLE
Thin out plans

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#853]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Proposal

Consider this plan:

``` r
library(drake)
drake_plan(
  x = data(),
  y = target(
    munge(x, i),
    transform = map(
      i = !!seq_len(1e4)
    )
  ),
  w = target(y, transform = map(y)),
  z = target(w, transform = combine(w, .by = i))
)
#> # A tibble: 30,001 x 2
#>    target command     
#>    <chr>  <expr>      
#>  1 x      data()      
#>  2 y_1L   munge(x, 1L)
#>  3 y_2L   munge(x, 2L)
#>  4 y_3L   munge(x, 3L)
#>  5 y_4L   munge(x, 4L)
#>  6 y_5L   munge(x, 5L)
#>  7 y_6L   munge(x, 6L)
#>  8 y_7L   munge(x, 7L)
#>  9 y_8L   munge(x, 8L)
#> 10 y_9L   munge(x, 9L)
#> # ... with 29,991 more rows
```

<sup>Created on 2019-04-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

`drake_plan(max_levels = 4L)` should reduce the number of targets created by `map()` and `cross()`. In the case of the plan above, `max_levels = 4L` should produce a plan equivalent to:

``` r
library(drake)
library(magrittr)
#> Warning: package 'magrittr' was built under R version 3.5.3
thin <- function(x) {
  i <- seq(from = 1, to = length(x), length.out = 4) %>%
    floor() %>%
    unique()
  x[i]
}
drake_plan(
  x = data(),
  y = target(
    munge(x, i),
    transform = map(
      i = !!thin(seq_len(1e4))
    )
  ),
  w = target(y, transform = map(y)),
  z = target(w, transform = combine(w, .by = i))
)
#> # A tibble: 13 x 2
#>    target     command         
#>    <chr>      <expr>          
#>  1 x          data()          
#>  2 y_1L       munge(x, 1L)    
#>  3 y_3334L    munge(x, 3334L) 
#>  4 y_6667L    munge(x, 6667L) 
#>  5 y_10000L   munge(x, 10000L)
#>  6 w_y_1L     y_1L            
#>  7 w_y_3334L  y_3334L         
#>  8 w_y_6667L  y_6667L         
#>  9 w_y_10000L y_10000L        
#> 10 z_10000L   list(w_y_10000L)
#> 11 z_1L       list(w_y_1L)    
#> 12 z_3334L    list(w_y_3334L) 
#> 13 z_6667L    list(w_y_6667L)
```

<sup>Created on 2019-04-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

## Advantages

For the purposes of exploring and testing out workflows, we can just focus on a few targets at first. Everything from `vis_drake_graph()` to `outdated()` to `make()` will be a whole lot faster. And when we are confident and ready to scale up, we can just unset `max_levels` and skip the work already done by `make()` in the scaled down version. This is a huge piece of what I was originally trying to achieve with the [`downsize` package](https://github.com/wlandau/downsize), and it goes even further by salvaging the work you already did in the testing phase.

cc @kendonB.

**Comment by wlandau** [comment]
...maybe `max_levels` should be called something different. Maybe `downsize` or `workflow_size` or `scale`?

**Comment by kendonB** [comment]
expansion_limit?

**Comment by wlandau** [comment]
Thanks, `expansion_limit` sounds much more evocative. I think we can shorten it to `max_expand`.
