### ISSUE TITLE
Detection of generalized cache dependencies in Rmarkdown

### ISSUE THREAD

**Issue by ha0ye** [ropensci/drake#854]
## Question

What is the ideal way to let drake know that a Rmarkdown report depends on dynamic targets?

## Example

I have an example repo at https://github.com/ha0ye/drake_examples
* some number of datasets
* some number of methods
* analyses (methods x datasets)
* an Rmarkdown report

Since the report is intended to be agnostic to the analyses, it looks in the cache for the names of the results objects and loads them in. I don't think this is evaluated properly by `deps_knitr()`, and so changes in the dependent targets don't cause the Rmarkdown to be re-knit when running `make()`.

## Possible solutions

It doesn't make sense to me that `deps_knitr()` should evaluate code to identify the dependencies (as this can lead to all kinds of incomputability/recursion disasters).

I think there are a couple work-arounds:
* put the code that compiles results together as part of the drake workflow in `pipeline.R`, and let the Rmarkdown depend on the combined results object
* pass the list of results as a static object to the Rmarkdown report (parameterized Rmarkdown maybe?), and build that into the dependencies somehow that `deps_knitr()` checks
* add the dependencies directly into the drake workflow in `pipeline.R` (I have to read up a bit more about this.

**Comment by wlandau** [comment]
@ha0ye, please see my fork at https://github.com/wlandau/drake_examples. To connect an R Markdown report to dependencies in the pipeline, the report must have calls to `loadd()` and `readd()` that explicitly mention the names of targets. I suggest you create additional targets to gather and summarize results and then `loadd()` those summaries into the report. Generally speaking, most of the computational work should be in functions and targets that call those functions. For the sake of clean code and short runtimes, R Markdown should do as little as possible.
