### ISSUE TITLE
Work Around R Windows Bug: Directories with Trailing Slashes Don't Work

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#855]
A long-standing bug in R for Windows is that slashes at the end of directory names aren't handled correctly.  What I'm reporting below is that R windows bug that is viewed as not to be fixed (https://bugs.r-project.org/bugzilla/show_bug.cgi?id=14721, see bottom of this issue report), but it causes problems with `drake` and has a simple work-around.

Directory names with trailing slashes appear not to exist while directories without trailing slashes work correctly.  Wherever this issue occurs in `drake`, wrapping the directory name with `file.path()` will chop off the trailing slash and make it work correctly.

``` r
library(drake)

dir.create("c:/tmp/t", recursive=TRUE, showWarnings=FALSE)
make(drake_plan(list.files(path=file_in("c:/tmp/t"))))
#> target drake_target_1
make(drake_plan(list.files(path=file_in("c:/tmp/t/"))))
#> Warning: missing input files:
#>   c:/tmp/t/
#> target drake_target_1
```

<sup>Created on 2019-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

The windows inconsistency illustrated:
```r
> file.exists("c:/tmp/")
[1] FALSE
> file.exists("c:/tmp")
[1] TRUE
```

**Comment by wlandau** [comment]
Thanks, @billdenney. Should be fixed now.
