### ISSUE TITLE
Is there a way to manually set the seed for targets?

### ISSUE THREAD

**Issue by ha0ye** [ropensci/drake#856]
After reading through #313, and trying it out myself, I see that I can set a global seed for an entire drake plan, and then drake will use that set reproducible seed for individual targets.

What I would like to do is override the seeds for individual targets, to assist with checking reproducibility of calculations inside and outside of running a drake plan.

For example, this doesn't work, because the seed I find with `diagnose(out)$seed` is not the same as that used outside of drake.
```
f <- function()
{
# [... some long calculation that uses random numbers and produces a large output...]
rnorm(1)
}

set.seed(known_seed)
out <- f()
known_hash <- digest::digest(out)

my_plan <- drake_plan(out = f())
clean(destroy = TRUE)
make(my_plan, seed = 42)
loadd(out)
stopifnot(digest::digest(out) == known_hash)
stopifnot(diagnose(out)$seed, known_seed)
```

Is there a way to manually set the seed for a specific target? My guess is no, because of how the global plan seed is used to generate seeds currently (i.e. this would require a different implementation for reproducibility).

Is my option then to use `diagnose(<target>)$seed` to find the specific seed I want, and then use that outside of drake to verify?

**Comment by wlandau-lilly** [comment]
Sorry @ha0ye, I do not plan to add special functionality to set individual target seeds. As you correctly point out, you can see a target's seed with `diagnose(<target>)$seed`, and there is nothing stopping you from using `set.seed()` to override `drake`'s target seeds. The following [`reprex`](https://github.com/tidyverse/reprex) demonstrates what I believe to be the correct behavior.

``` r
library(drake)
plan <- drake_plan(
  x = runif(1),
  y = runif(1)
)
make(plan)
#> target x
#> target y
readd(x)
#> [1] 0.8027186
readd(y)
#> [1] 0.5554144
diagnose(x)$seed
#> [1] 1063531837
diagnose(y)$seed
#> [1] 965938315
plan <- drake_plan(
  x = {
    set.seed(0)
    runif(1)
  },
  y = {
    set.seed(0)
    runif(1)
  }
)
make(plan)
#> target x
#> target y
readd(x)
#> [1] 0.8966972
readd(y)
#> [1] 0.8966972
diagnose(x)$seed
#> [1] 1063531837
diagnose(y)$seed
#> [1] 965938315
```

<sup>Created on 2019-05-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
