### ISSUE TITLE
expose_imports() and load_all()

### ISSUE THREAD

**Issue by rtaph** [ropensci/drake#859]
Hi there,

I am using drake inside a R package structure. I have my functions in the /R directory instead of sourcing scripts from a directory.

For a long time, this meant that I was having trouble getting targets to re-build when changes were made to my source code; they would not be detected as outdated unless I properly re-installed the package. This confused me because I had set `prework = "devtools::load_all()"`.

The fix was to run `devtools::load_all(quiet = TRUE)` before `expose_imports("pkgname")` in my `_drake.R` file. I believe the imports would otherwise come from the (outdated) installed version rather than from the loaded version via `devtools::load_all(quiet = TRUE)`. Is that right?

If so, might I suggest this be explained the documentation? Or instead that a prework argument be added to `expose_imports()`? The risk is that users might think their targets are up to date when in fact they are not based on their development directory.

**Comment by rtaph** [comment]
Sorry, I discovered #208 after posting.

**Comment by wlandau** [comment]
I just added new package-tracking functionality in [`targets`](https://github.com/wlandau/targets) `tar_option_set(imports = your_packages)` (https://github.com/wlandau/targets/issues/239, https://github.com/wlandau/targets/issues/241). See https://wlandau.github.io/targets-manual/practice.html#packages for details.
