### ISSUE TITLE
Accept targets as inputs to cross

### ISSUE THREAD

**Issue by vkehayas** [ropensci/drake#861]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

Hi,

Thanks for this lifesaver of a package!
I am a long-time user trying to catch-up with the new way of creating large plans.
This is a minimal example of what I would like to do:

```r
library(drake)

dPlan = drake_plan(
  kMu = c(0, 1, 10),
  kSD = c(1, 2, 3),
  x = target(rnorm(n = 1000, 
                   mean = mean_val, 
                   sd = sd_val),
             transform = cross(mean_val = kMu,
                               sd_val = kSD))
)
```

And I would expect it to expand to 

```
> dPlan
# A tibble: 9 x 2
  target command                             
  <chr>  <expr>                              
1 x_0_1  "rnorm(n = 1000, mean = 0, sd = 1) "
2 x_1_1  "rnorm(n = 1000, mean = 1, sd = 1) "
3 x_10_1 rnorm(n = 1000, mean = 10, sd = 1)  
4 x_0_2  "rnorm(n = 1000, mean = 0, sd = 2) "
5 x_1_2  "rnorm(n = 1000, mean = 1, sd = 2) "
6 x_10_2 rnorm(n = 1000, mean = 10, sd = 2)  
7 x_0_3  "rnorm(n = 1000, mean = 0, sd = 3) "
8 x_1_3  "rnorm(n = 1000, mean = 1, sd = 3) "
9 x_10_3 rnorm(n = 1000, mean = 10, sd = 3)  
```

which I can produce if I move `kMu`, `kSD` outside of `drake`'s control and use `!!`. But in my real plan these would be variables that are being used to build other targets as well and I would like them to trigger building the first plan whenever they change. Is this an abuse of `drake` or is there a way to achieve what I want? 

Apologies if there was a pre-existing issue I missed or if the answer relies on knowledge of the tidyverse (of which I have close to none).

**Comment by wlandau** [comment]
Definitely a good question. This is currently not supported in `drake`. It is by far the most challenging feature request, and there are long-term plans to try. See #685 for the main thread.
