### ISSUE TITLE
New Jenkins CI hook not working

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#863]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [x] Advanced users: verify that the bug still persists in the current development version (i.e. `remotes::install_github("ropensci/drake")`) and mention the [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity) of the [Git commit you install](https://github.com/ropensci/drake/commits/master).

## Description

A new Jenkins CI GitHub hook just appeared for rOpenSci packages. It is not yet working for `drake`.

![Screenshot_20190508_014152](https://user-images.githubusercontent.com/1580860/57352368-2f290900-7133-11e9-9bc9-f51b8c2f5b43.png)

The "Details" link directs me to http://172.104.227.59:8080/login?from=%2Fjob%2Fropensci%2Fjob%2Fdrake%2Fjob%2Fmaster%2F1%2Fdisplay%2Fredirect, where my Jenkins credentials cannot log me in.

cc @jeroen

**Comment by jeroen** [comment]
Oops sorry I am experimenting with a new CI, it doesn't work yet!

**Comment by wlandau** [comment]
The hook appears gone. Thanks, @jeroen.

**Comment by jeroen** [comment]
Hook should be back now (and hopefully working) :)

**Comment by wlandau** [comment]
Yup, it's back and working.

**Comment by jeroen** [comment]
I've updated the CI server to install the `r_packages` and `github_packages` from the `.travis` file. Your site now builds and is live on https://docs.ropensci.org/drake/

Build logs: http://jenkins.ropensci.org/blue/organizations/jenkins/drake/activity

**Comment by wlandau** [comment]
Oh cool! I might decide to migrate over from https://ropensci.github.io/drake/. Thanks!
