### ISSUE TITLE
Idea: Use roxygen to build plan documentation and link with graph visualisation

### ISSUE THREAD

**Issue by MilesMcBain** [ropensci/drake#868]
I checked out `drakeplanner` and it made me think that style of presentation could be really useful for understanding plans shared between collaborators.

What if we could use roxygen written for target functions to generate browsable plan documentation with the browsing driven by the graph visual: i.e. I click a node and then one of the `drakeplanner` style panes shows me the compiled help associated with the function.

**Comment by wlandau** [comment]
I like your thinking. Now that you mention it, `drake` is positioned to have its own inexpensive kind of literate programming. `drake_plan()` lets you supply custom columns, and one of these could be a docstring. (How important is `roxygen2` specifically?)

``` r
library(drake)
drake_plan(
  results = target(
    analyze(data),
    doc = "
      ## Purpose
      
      Data analysis
      
      ## Methods
      
      Hierarchical model with a Dirichlet process mixture prior.
      
      ## Value
      
      An `rstan` fit object.
    "
  )
)
#> # A tibble: 1 x 3
#>   target  command     doc                                                  
#>   <chr>   <expr>      <chr>                                                
#> 1 results analyze(da… "\n      ## Purpose\n      \n      Data analysis\n  …
```

<sup>Created on 2019-05-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

The docstrings could drive a new a new help box in `drakeplanner` as you suggested, and they could add structure to the existing `plan_to_notebook()` function. I wonder how much JavaScript it would take to make `vis_drake_graph()` browsable on its own without Shiny.

**Comment by MilesMcBain** [comment]
Well I've been using roxygen with my target functions although not inlined in the plan file. 

I tend not define targets inline very often as my plans get rather busy. So in a plan with say 20 targets maybe only 1 will be coded inline. I only feel comfortable doing it inline if the code is very simple. The rest of my targets call out to functions which contain my documentation in roxygen format.

Roxygen makes sense to me because it's the only way I've ever seen functions documented. I'd assume that would be the case for most people. It'd fit with the idea that `drake` lets you use what you already know about R to build workflows.

**Comment by wlandau** [comment]
At first, I was not sure what you meant by "target function", but now I think might understand. Correct me if I am wrong, but it seems like you are defining a dedicated function for each target or group of targets. `drake_plan()` can technically handle large arbitrary code chunks...

```r
drake_plan(
  x = {
    out <- mtcars %>%
      filter(cyl > 4) %>%
      group_by(cyl) %>%
      summarize(mpg = mean(mpg))
    more_munging(out)
  }
)
```

..but your way is much better.

```r
# plan.R
drake_plan(
  x = build_x(arg1, arg2),
  y = build_y(arg3, arg4),
  ...
)
```

with

```r
# some_of_the_functions.R

#' @title Build x
#' @description Method abc
#' @export
#' @param arg1 Argument details
#' @param arg2 Argument details
build_x <- function(arg1, arg2) {
  ...
}

# More functions...
```

Unfortunately, `drake` itself has no way to hold onto the `roxygen2` docstrings, and we cannot assume that commands in the plan are always concise function calls.

However, you can wrap your analysis in a package (e.g. [`drakepkg`](https://github.com/tiernanmartin/drakepkg)) and use `expose_imports()` to make sure `drake` detects your unexported functions.

As for the graph visuals, the closest thing we have so far is `vis_drake_graph(hover = TRUE)`. The hover text shows the commands of targets, the bodies of functions, and the content of flat files (first few lines only). Click events are open territory. I am not likely to work on them myself, but they could be a fun mini-project.

**Comment by mstr3336** [comment]
Hi @wlandau , I was wondering about what you said about click-events - I'd love to be able to add some onClick behaviour that lets users click-through to a functions documentation url, or something similar- 
Would you be open to exposing an API for allowing users to provide onClick handlers (probably tied to a custom column or something similar)?

The goal would be to allow use of the vis_drake_graph as a sort of "interactive" reference, where a viewer could click on a target on the graph and follow through to the man page, or even a blob of the source describing that transformation.

**Comment by wlandau** [comment]
I like that idea. It is already possible to define arbitrary custom columns you want, e.g. #943. We would just need `render_drake_graph()` and/or `drake_graph_info()` to look at the relevant columns.

**Comment by mstr3336** [comment]
Though I think that inlining documentation data as a custom column for targets in `drake_plan()` 
 would probably be the prettiest and most readable stylistically, 
Eg.

```r
plan <- drake_plan(
  diagnosis_handlers = preprocess_diagnosis(),
  common_handlers = preprocess_common(),
  diagnosis_prepr = target({
        data <- read_raw_df(file_in(whole_path), drop_cols = !!invalid_headers)
        data %<>% apply_handlers_simple(common_handlers, stem=stem, 
                                        .log_name = paste0(.id_chr, ".common_handles"))
        data %<>% 
          apply_handlers_simple(
            diagnosis_handlers, .log_name = .id_chr)

        # Save pre-processed result
        saveRDS(data, file_out(ignore(!!preprocessed$join(paste0(stem, "_", number, ".rds"))$show)))
        
        data
      }, transform = map(
        .data = !!dplyr::filter(fnames, stringr::str_detect(stem,"diagnosis")),
        .id = number,
        .tag_in = cluster_id),
     # Example of how this new interface might be given
     # For example give it a .md link to click through to that might be handled like pkgdown
     docs = "[SPEED.EXTRACT.pipeline::preprocess_diagnosis()]" 
  )
)

config <- drake_config(plan)

graph <- vis_drake_graph(config, on_click = some_function, on_click_arg_cols = c(docs))
```

(I think that could be a super cute and expressive way to do inline documentation, maybe)

personally I would prefer to avoid maintenance of documentation artefacts (ie, changing the url in the `docs` column) invalidating the corresponding target.
I'm not sure if custom columns would have the side effect of invalidating targets when you change them
I'm aware that there's mechanisms that allow you to customize rebuild triggers, & the `ignore()` function might be useful in this case, does this make sense?

A workaround could be to allow users to map node labels on the `graph_info` output of `drake_graph_info()` to doc data, and pass something to `render_drake_graph()` so that it knows what to do with that information.

I'm happy to try and put in some work on this feature, if you find it compelling enough to consider including in drake.

**Comment by wlandau** [comment]
I like the API sketch you have above, and I would be happy to review pull requests on it.

Not all columns can invalidate targets. The only ones with that power are `target`, `command`, `trigger`, and the upcoming `seed` column (#947).

I think it is easier to manipulating plans than `graph_info` lists. `graph_info` is a nice place to start tinkering, but not the ultimate destination I have in mind.

**Comment by mstr3336** [comment]
Hi Will - I know it's been like 4 months or something (my life turned upside down for a little while), but I'm going to put in a PR for a very basic implementation of this feature -

It's against a version of `drake` that's months old so I'll probably have to update the implementation if the source of `drake_graph_info` or `vis_drake_graph` have changed much. 

When you get time, if you can open [nothin.Rmd](https://github.com/ropensci/drake/blob/8e28131dbec668e2ee0d514185e225fb1eee06f8/inst/nothin.Rmd), I'll go ahead and implement something slightly more robust.

**Comment by wlandau** [comment]
Thanks @mstr3336, I will take a look. Glad things are calmer now for you.
