### ISSUE TITLE
Restrict environment of call to only those elements used

### ISSUE THREAD

**Issue by kendonB** [ropensci/drake#882]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [x] Advanced users: verify that the bug still persists in the current development version (i.e. `remotes::install_github("ropensci/drake")`) and mention the [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity) of the [Git commit you install](https://github.com/ropensci/drake/commits/master).

## Description

Both regression objects (e.g. `lm`) and `ggplot` objects capture their environment. When saving, these put everything onto disk, including junk that's not actually used in the creation of the object. It would be nice if `drake` saved users from this annoyance by restricting the evaluation environment for commands to only include those elements actually used. 

I'm not sure if this is a regression (in the comp sci sense) or not but I haven't noticed this issue before.

## Reproducible example

``` r
library(drake)

unlink(".test", recursive = TRUE)
cache = new_cache(".test")
extra_object = 1
plan = drake_plan(
  lm = lm(Sepal.Width ~ Sepal.Length, data = iris)
)
make(plan, cache = cache)
#> target lm
loadd(lm, cache = cache)
ls.str(name = attr(lm$terms, ".Environment"))
#> cache : Classes 'storr', 'R6' <storr>
#>   Public:
#>     archive_export: function (path, names = NULL, namespace = NULL) 
#>     archive_import: function (path, names = NULL, namespace = NULL) 
#>     check: function (full = TRUE, quiet = FALSE, progress = !quiet) 
#>     clear: function (namespace = self$default_namespace) 
#>     clone: function (deep = FALSE) 
#>     default_namespace: objects
#>     del: function (key, namespace = self$default_namespace) 
#>     destroy: function () 
#>     driver: driver_rds, R6
#>     duplicate: function (key_src, key_dest, namespace = self$default_namespace, 
#>     envir: environment
#>     exists: function (key, namespace = self$default_namespace) 
#>     exists_object: function (hash) 
#>     export: function (dest, list = NULL, namespace = self$default_namespace, 
#>     fill: function (key, value, namespace = self$default_namespace, use_cache = TRUE) 
#>     flush_cache: function () 
#>     gc: function () 
#>     get: function (key, namespace = self$default_namespace, use_cache = TRUE) 
#>     get_hash: function (key, namespace = self$default_namespace) 
#>     get_value: function (hash, use_cache = TRUE) 
#>     hash_object: function (object) 
#>     hash_raw: function (x) 
#>     import: function (src, list = NULL, namespace = self$default_namespace, 
#>     index_export: function (namespace = NULL) 
#>     index_import: function (index) 
#>     initialize: function (driver, default_namespace) 
#>     list: function (namespace = self$default_namespace) 
#>     list_hashes: function () 
#>     list_namespaces: function () 
#>     mget: function (key, namespace = self$default_namespace, use_cache = TRUE, 
#>     mget_hash: function (key, namespace = self$default_namespace) 
#>     mget_value: function (hash, use_cache = TRUE, missing = NULL) 
#>     mset: function (key, value, namespace = self$default_namespace, use_cache = TRUE) 
#>     mset_by_value: function (value, namespace = self$default_namespace, use_cache = TRUE) 
#>     mset_value: function (values, use_cache = TRUE) 
#>     repair: function (storr_check_results = NULL, quiet = FALSE, ..., force = FALSE) 
#>     serialize_object: function (object) 
#>     set: function (key, value, namespace = self$default_namespace, use_cache = TRUE) 
#>     set_by_value: function (value, namespace = self$default_namespace, use_cache = TRUE) 
#>     set_value: function (value, use_cache = TRUE) 
#>     traits: list 
#> extra_object :  num 1
#> lm : List of 12
#>  $ coefficients : Named num [1:2] 3.4189 -0.0619
#>  $ residuals    : Named num [1:150] 0.3967 -0.1157 0.0719 -0.0343 0.4905 ...
#>  $ effects      : Named num [1:150] -37.4445 -0.6255 0.0564 -0.0485 0.471 ...
#>  $ rank         : int 2
#>  $ fitted.values: Named num [1:150] 3.1 3.12 3.13 3.13 3.11 ...
#>  $ assign       : int [1:2] 0 1
#>  $ qr           :List of 5
#>  $ df.residual  : int 148
#>  $ xlevels      : Named list()
#>  $ call         : language lm(formula = Sepal.Width ~ Sepal.Length, data = iris)
#>  $ terms        :Classes 'terms', 'formula'  language Sepal.Width ~ Sepal.Length
#>  $ model        :'data.frame':   150 obs. of  2 variables:
#> plan : Classes 'drake_plan', 'tbl_df', 'tbl' and 'data.frame':   1 obs. of  2 variables:
#>  $ target : chr "lm"
#>  $ command:List of 1
```

<sup>Created on 2019-05-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       Pacific/Auckland            
#>  date     2019-05-26                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version    date       lib source                         
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                 
#>  backports     1.1.4      2019-04-10 [1] CRAN (R 3.6.0)                 
#>  base64url     1.4        2018-05-14 [1] CRAN (R 3.6.0)                 
#>  callr         3.2.0      2019-03-15 [1] CRAN (R 3.6.0)                 
#>  cli           1.1.0      2019-03-19 [1] CRAN (R 3.6.0)                 
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                 
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.0)                 
#>  devtools      2.0.2      2019-04-08 [1] CRAN (R 3.6.0)                 
#>  digest        0.6.19     2019-05-20 [1] CRAN (R 3.6.0)                 
#>  drake       * 7.3.0.9000 2019-05-25 [1] Github (ropensci/drake@f1b45c6)
#>  evaluate      0.13       2019-02-12 [1] CRAN (R 3.6.0)                 
#>  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                 
#>  glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                 
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.0)                 
#>  htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.6.0)                 
#>  igraph        1.2.4.1    2019-04-22 [1] CRAN (R 3.6.0)                 
#>  knitr         1.23       2019-05-18 [1] CRAN (R 3.6.0)                 
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.0)                 
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                 
#>  pillar        1.4.0      2019-05-11 [1] CRAN (R 3.6.0)                 
#>  pkgbuild      1.0.3      2019-03-20 [1] CRAN (R 3.6.0)                 
#>  pkgconfig     2.0.2      2018-08-16 [1] CRAN (R 3.6.0)                 
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                 
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.6.0)                 
#>  processx      3.3.1      2019-05-08 [1] CRAN (R 3.6.0)                 
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                 
#>  purrr         0.3.2      2019-03-15 [1] CRAN (R 3.6.0)                 
#>  R6            2.4.0      2019-02-14 [1] CRAN (R 3.6.0)                 
#>  Rcpp          1.0.1      2019-03-17 [1] CRAN (R 3.6.0)                 
#>  remotes       2.0.4      2019-04-10 [1] CRAN (R 3.6.0)                 
#>  rlang         0.3.4      2019-04-07 [1] CRAN (R 3.6.0)                 
#>  rmarkdown     1.12       2019-03-14 [1] CRAN (R 3.6.0)                 
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.6.0)                 
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                 
#>  storr         1.2.1      2018-10-18 [1] CRAN (R 3.6.0)                 
#>  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                 
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                 
#>  tibble        2.1.1      2019-03-16 [1] CRAN (R 3.6.0)                 
#>  tidyselect  * 0.2.5      2018-10-11 [1] CRAN (R 3.6.0)                 
#>  usethis       1.5.0      2019-04-07 [1] CRAN (R 3.6.0)                 
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.0)                 
#>  xfun          0.7        2019-05-14 [1] CRAN (R 3.6.0)                 
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.6.0)                 
#> 
#> [1] C:/Users/kmbel/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.0/library
```

</details>

## Expected output
May not be able to be this minimal but I'd expect something like this.
``` r
lm = lm(Sepal.Width ~ Sepal.Length, data = iris)
ls.str(name = attr(lm$terms, ".Environment"))
#> lm : List of 12
#>  $ coefficients : Named num [1:2] 3.4189 -0.0619
#>  $ residuals    : Named num [1:150] 0.3967 -0.1157 0.0719 -0.0343 0.4905 ...
#>  $ effects      : Named num [1:150] -37.4445 -0.6255 0.0564 -0.0485 0.471 ...
#>  $ rank         : int 2
#>  $ fitted.values: Named num [1:150] 3.1 3.12 3.13 3.13 3.11 ...
#>  $ assign       : int [1:2] 0 1
#>  $ qr           :List of 5
#>  $ df.residual  : int 148
#>  $ xlevels      : Named list()
#>  $ call         : language lm(formula = Sepal.Width ~ Sepal.Length, data = iris)
#>  $ terms        :Classes 'terms', 'formula'  language Sepal.Width ~ Sepal.Length
#>  $ model        :'data.frame':   150 obs. of  2 variables:
```

<sup>Created on 2019-05-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kendonB** [comment]
Fixing this will make any targets that depend on these types of objects out of date, but I think it's worth addressing. It's also possible that the particular memory strategy used could affect the up-to-dateness of objects(?), which is definitely a bug.

**Comment by kendonB** [comment]
Can confirm this is there in the cran version of drake:

<details>

<summary>CRAN</summary>

``` r
library(drake)

unlink(".test", recursive = TRUE)
cache = new_cache(".test")
extra_object = 1
plan = drake_plan(
  lm = lm(Sepal.Width ~ Sepal.Length, data = iris)
)
make(plan, cache = cache)
#> target lm
loadd(lm, cache = cache)
ls.str(name = attr(lm$terms, ".Environment"))
#> cache : Classes 'storr', 'R6' <storr>
#>   Public:
#>     archive_export: function (path, names = NULL, namespace = NULL) 
#>     archive_import: function (path, names = NULL, namespace = NULL) 
#>     check: function (full = TRUE, quiet = FALSE, progress = !quiet) 
#>     clear: function (namespace = self$default_namespace) 
#>     clone: function (deep = FALSE) 
#>     default_namespace: objects
#>     del: function (key, namespace = self$default_namespace) 
#>     destroy: function () 
#>     driver: driver_rds, R6
#>     duplicate: function (key_src, key_dest, namespace = self$default_namespace, 
#>     envir: environment
#>     exists: function (key, namespace = self$default_namespace) 
#>     exists_object: function (hash) 
#>     export: function (dest, list = NULL, namespace = self$default_namespace, 
#>     fill: function (key, value, namespace = self$default_namespace, use_cache = TRUE) 
#>     flush_cache: function () 
#>     gc: function () 
#>     get: function (key, namespace = self$default_namespace, use_cache = TRUE) 
#>     get_hash: function (key, namespace = self$default_namespace) 
#>     get_value: function (hash, use_cache = TRUE) 
#>     hash_object: function (object) 
#>     hash_raw: function (x) 
#>     import: function (src, list = NULL, namespace = self$default_namespace, 
#>     index_export: function (namespace = NULL) 
#>     index_import: function (index) 
#>     initialize: function (driver, default_namespace) 
#>     list: function (namespace = self$default_namespace) 
#>     list_hashes: function () 
#>     list_namespaces: function () 
#>     mget: function (key, namespace = self$default_namespace, use_cache = TRUE, 
#>     mget_hash: function (key, namespace = self$default_namespace) 
#>     mget_value: function (hash, use_cache = TRUE, missing = NULL) 
#>     mset: function (key, value, namespace = self$default_namespace, use_cache = TRUE) 
#>     mset_by_value: function (value, namespace = self$default_namespace, use_cache = TRUE) 
#>     mset_value: function (values, use_cache = TRUE) 
#>     repair: function (storr_check_results = NULL, quiet = FALSE, ..., force = FALSE) 
#>     serialize_object: function (object) 
#>     set: function (key, value, namespace = self$default_namespace, use_cache = TRUE) 
#>     set_by_value: function (value, namespace = self$default_namespace, use_cache = TRUE) 
#>     set_value: function (value, use_cache = TRUE) 
#>     traits: list 
#> extra_object :  num 1
#> lm : List of 12
#>  $ coefficients : Named num [1:2] 3.4189 -0.0619
#>  $ residuals    : Named num [1:150] 0.3967 -0.1157 0.0719 -0.0343 0.4905 ...
#>  $ effects      : Named num [1:150] -37.4445 -0.6255 0.0564 -0.0485 0.471 ...
#>  $ rank         : int 2
#>  $ fitted.values: Named num [1:150] 3.1 3.12 3.13 3.13 3.11 ...
#>  $ assign       : int [1:2] 0 1
#>  $ qr           :List of 5
#>  $ df.residual  : int 148
#>  $ xlevels      : Named list()
#>  $ call         : language lm(formula = Sepal.Width ~ Sepal.Length, data = iris)
#>  $ terms        :Classes 'terms', 'formula'  language Sepal.Width ~ Sepal.Length
#>  $ model        :'data.frame':   150 obs. of  2 variables:
#> plan : Classes 'drake_plan', 'tbl_df', 'tbl' and 'data.frame':   1 obs. of  2 variables:
#>  $ target : chr "lm"
#>  $ command:List of 1
```

<sup>Created on 2019-05-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       Pacific/Auckland            
#>  date     2019-05-26                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
#>  backports     1.1.4   2019-04-10 [1] CRAN (R 3.6.0)
#>  base64url     1.4     2018-05-14 [1] CRAN (R 3.6.0)
#>  callr         3.2.0   2019-03-15 [1] CRAN (R 3.6.0)
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.0)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
#>  devtools      2.0.2   2019-04-08 [1] CRAN (R 3.6.0)
#>  digest        0.6.19  2019-05-20 [1] CRAN (R 3.6.0)
#>  drake       * 7.3.0   2019-05-19 [1] CRAN (R 3.6.0)
#>  evaluate      0.13    2019-02-12 [1] CRAN (R 3.6.0)
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.0)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.0)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.6.0)
#>  igraph        1.2.4.1 2019-04-22 [1] CRAN (R 3.6.0)
#>  knitr         1.23    2019-05-18 [1] CRAN (R 3.6.0)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
#>  pillar        1.4.0   2019-05-11 [1] CRAN (R 3.6.0)
#>  pkgbuild      1.0.3   2019-03-20 [1] CRAN (R 3.6.0)
#>  pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.6.0)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.6.0)
#>  processx      3.3.1   2019-05-08 [1] CRAN (R 3.6.0)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.0)
#>  purrr         0.3.2   2019-03-15 [1] CRAN (R 3.6.0)
#>  R6            2.4.0   2019-02-14 [1] CRAN (R 3.6.0)
#>  Rcpp          1.0.1   2019-03-17 [1] CRAN (R 3.6.0)
#>  remotes       2.0.4   2019-04-10 [1] CRAN (R 3.6.0)
#>  rlang         0.3.4   2019-04-07 [1] CRAN (R 3.6.0)
#>  rmarkdown     1.12    2019-03-14 [1] CRAN (R 3.6.0)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
#>  storr         1.2.1   2018-10-18 [1] CRAN (R 3.6.0)
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
#>  tibble        2.1.1   2019-03-16 [1] CRAN (R 3.6.0)
#>  tidyselect  * 0.2.5   2018-10-11 [1] CRAN (R 3.6.0)
#>  usethis       1.5.0   2019-04-07 [1] CRAN (R 3.6.0)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
#>  xfun          0.7     2019-05-14 [1] CRAN (R 3.6.0)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.6.0)
#> 
#> [1] C:/Users/kmbel/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.0/library
```

</details>

**Comment by kendonB** [comment]
I'm now struggling to demonstrate that the environment actually gets written in the rds. I will reopen if I work out how to actually demonstrate this and the circumstances where it does get written.

**Comment by wlandau** [comment]
@kendonB, I do not think objects in that specific environment get stored. If I restart the R session, `ls.str()` seems to show whatever is in the new global environment.

```r
> library(drake)
> extra_object = 1
> plan = drake_plan(
+   x = lm(Sepal.Width ~ Sepal.Length, data = iris)
+ )
> make(plan)
target x

Restarting R session...

> local_var <- 123
> ls.str(name = attr(readd(x)$terms, ".Environment"))
local_var :  num 123
```

However, I have observed the general behavior you describe. Somewhere, `lm()` objects contain superfluous data that is stored during a naive `saveRDS()`. I noticed it in the original [GSP example](https://ropenscilabs.github.io/drake-manual/gsp.html). Model-fitting would gradually slow down, and I did not know why at first. But when I switched to [`biglm`](https://CRAN.R-project.org/package=biglm), targets ran at a constant (fast) speed.

So for linear regression, I recommend [`biglm`](https://CRAN.R-project.org/package=biglm). For `ggplot2` objects, if size or speed become a problem, I recommend `file_out()` files.

This general problem is really a bunch of special cases, and an attempt to catch all these cases in `drake` itself would probably cause more problems than it solves. However, I intend to work on a [multiformat `storr`](https://github.com/richfitz/storr/issues/103) which will be designed for special cases and could be configured to strip out superfluous data.

**Comment by kendonB** [comment]
Does drake evaluate objects in their own environment with only the required input objects? That would go a long way to addressing this issue (if there really is an issue) and would be a general approach.

**Comment by wlandau** [comment]
`drake` creates a special `config$eval` environment to evaluate commands and contain targets in memory. To make sure imported functions are reachable, `config$eval` needs to inherit from `config$envir` (the `envir` argument of `make()`) which is usually `globalenv()`. I do like your thinking, but because of the necessary inheritance, I am not sure we can hide global objects like `config` and `cache` unless you supply a custom environment.

```r
envir <- new.env(parent = globalenv()) # Inherit from globalenv() so packages are reachable.
library(drake)
library(...)
source("R/functions.R", local = envir)
plan <- drake_plan(...)
make(plan, envir = envir)
```

**Comment by wlandau** [comment]
Oops, just realized that last comment was self-contradictory. Regardless, it does still appear that sometimes unwanted objects get stored even though config$eval is not globalenv().

**Comment by kendonB** [comment]
@wlandau I have been noticing this problem again lately. I have ggplots that are in reality a few MB but get saved as multiple GBs via drake (including when they get read in, at least as `qs`). I have done something like this (at the last second when building the plot) as an awkward hack which avoids the problem:

```r
  env <- new.env(parent = globalenv())
  env$input <- input
  
  with(env, {
    output = make_output(input)
  })  
  return(env$output)
```

**Comment by wlandau** [comment]
From https://github.com/ropensci/drake/issues/882#issuecomment-496031531, perhaps the workaround can be made less awkward in some cases using `drake_envir()` (using 7845509d3bb2149c6ae3b72aa43a6755c95cd402). Maybe try something like the sketch below and find out if one of the targets consumes less memory than the others. Depending on if/how you use dynamic branching, your results may vary in practice.

``` r
library(drake)

plan <- drake_plan(
  ggplot = target(
    with(drake_envir(envir), make_ggplot()),
    transform = map(envir = !!eval(formals(drake_envir)$which))
  )
)

#> # A tibble: 4 x 2
#>   target            command                                       
#>   <chr>             <expr>                                        
#> 1 ggplot_targets    with(drake_envir("targets"), make_ggplot())   
#> 2 ggplot_dynamic    with(drake_envir("dynamic"), make_ggplot())   
#> 3 ggplot_subtargets with(drake_envir("subtargets"), make_ggplot())
#> 4 ggplot_imports    with(drake_envir("imports"), make_ggplot())

make(plan, memory_strategy = "autoclean")
```

<sup>Created on 2020-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

As I believe I mentioned before, `drake`'s internal hierarchy of environments (now 4, 2 of which are for dynamic branching) is too fundamental to undo now. Plus, it powers great solutions to bigger potential problems: it protects the calling environment from potential side effects of `make()`, and it makes dynamic branching fast and intuitive.

I am curious to know what the `ggplot2` developers think about this. Perhaps there is a `biglm`-like solution? `drake` may not be the only use case.

**Comment by kendonB** [comment]
See here:

https://github.com/tidyverse/ggplot2/issues/3619#issuecomment-552340703

I think that `drake` actually might be the ideal place to solve this issue by isolating the calling environment containing only the required inputs because drake actually knows what the required inputs are for a given target.

**Comment by kendonB** [comment]
I also feel like this is a bug if objects' hashes end up changing depending on what objects are loaded into the environment? You would ideally want to be able to guarantee you'd get the same hashes regardless of the `memory_strategy` used?

**Comment by wlandau** [comment]
Re https://github.com/ropensci/drake/issues/882#issuecomment-579985640, I look at it more of an inconvenience/limitation than a bug. Other R objects with environments are brittle in ways that `drake` cannot control. Example: #345.

**Comment by wlandau** [comment]
Re https://github.com/ropensci/drake/issues/882#issuecomment-579977863, I still hesitate to attack this at the level of `drake`'s internals. It is a very specific set of edge cases, and the try to shortcut `drake`'s internal hierarchy of environments, I strongly suspect it will lead to stranger and more dangerous edge cases. There were a lot of those in the early days when I was trying all sorts of ways to deal with environments in a robust, predictable, reproducible way.

I think a more useful course of action is to help people properly serialize their targets (or choose targets that can be properly serialized, re https://books.ropensci.org/drake/plans.html#how-to-choose-good-targets). That was certainly the way to go in #345 since R6 objects are just bad targets. And for Keras models, we have a [special format](https://books.ropensci.org/drake/plans.html#special-data-formats-for-targets) to save them properly. If we figure out a way to downsize ggplot2 objects no matter where they come from, maybe we can implement a `target(format = "ggplot")` option.

**Comment by wlandau** [comment]
And as for `lm`'s, I recommend `biglm`'s all the way, as in https://books.ropensci.org/drake/gsp.html.

**Comment by kendonB** [comment]
Ref: https://github.com/tidyverse/ggplot2/issues/3765

**Comment by wlandau** [comment]
Re https://github.com/tidyverse/ggplot2/issues/3765#issuecomment-580548401 and https://github.com/ropensci/drake/issues/1126#issuecomment-569845228, what about serializing ggplot objects to pre-rendered vector graphics? Most user think `ggsave()` covers this already, but `file_out()`s are annoying in `drake`. I wonder if it is possible to `ggsave()` to an in-memory text connection.

**Comment by kendonB** [comment]
The use case I'm thinking of it that you've got several sub plots (each a ggplot object) that you're putting into a larger figure. `patchwork` relies on the subplots being `ggplot` objects so serializing to vector graphics wouldn't work there. I think that for plots that are done the best thing is to just ggsave.

One idea could be an option for format = "none" which will just not store the target in disk and have the target just build when it's called rather than load it from memory. Could something like that work?

**Comment by wlandau** [comment]
`format = "none"` is actually already used internally, and it tells `drake` to just store the object in the `storr` without doing anything special.

https://github.com/ropensci/drake/blob/55808d81815c89913f6ee403634cb5980007450b/R/drake_meta_.R#L51

It would take a hack to make `drake` build the target and keep it in memory but not store it in the cache. You could probably do it yourself by setting `trigger(condition = TRUE)` in all your plots and manually assign the plots to `drake_envir("targets")`. Or better yet, rather than defining a target for every sub-plot, create a big target for each patchwork grid.

**Comment by wlandau** [comment]
For onlookers: sometimes it's best to avoid having too many targets: https://books.ropensci.org/drake/plans.html#how-to-choose-good-targets.

**Comment by kendonB** [comment]
> ```r
> #> 1 ggplot_targets    with(drake_envir("targets"), make_ggplot())   
> #> 2 ggplot_dynamic    with(drake_envir("dynamic"), make_ggplot())   
> #> 3 ggplot_subtargets with(drake_envir("subtargets"), make_ggplot())
> #> 4 ggplot_imports    with(drake_envir("imports"), make_ggplot())
> ```

Tried this one. The imports one doesn't build and the other three seem to take up the same amount of space based on `pryr::object_size`.

**Comment by brendanf** [comment]
I've just run into this with `nls` objects.  I ended up solving it by doing all the calculations I wanted with the model object (make a table of parameter values, generate predicted values, etc) in the same rule that fits the model, and saving all the individual results as a list, without actually returning the `nls` object.  It would be nice if there was a clean way to save model objects to disk without accidentally including a big environment (in my case dozens of ~50kb of models each wound up with a ~3Gb environment attached), but it seems like it's a difficult problem to solve in general.
