### ISSUE TITLE
Feature request: `r_deps_target()`

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#886]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

Could this function be implemented? I would like to avoid putting the config in `deps_target()` manually if I need to use this function.

**Comment by wlandau** [comment]
Sure, that's easy. I will see if I can make time to get to it tonight.

**Comment by wlandau** [comment]
Implemented.

**Comment by pat-s** [comment]
Thanks! Simplifies my work a lot :tada:
