### ISSUE TITLE
Combining `workflowr` and `drake`: A perfect match

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#888]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

Just a show case: I am recently using _workflowr_  and _drake_ together and it works just great.
I can now finally auto-publish all the reports produced with _drake_ in an easy way.

I know you are aware of the package. Maybe it can be linked somewhere in the manual? Or even be suggested as the best option to create reproducible reports?

Site: https://2019-feature-selection.pjs-web.de/index.html
drake plan: https://github.com/pat-s/2019-feature-selection/blob/5037fa77844351c03e82f1900188719f206c0c68/code/07-reports.R

**Comment by wlandau** [comment]
That's so cool! cc @jdblischak.

Maybe a note in the README and manual in the [section on similar work](https://github.com/ropensci/drake/blob/104f1fbdfbbdec7b8d1e0da222ddaaf4ee422d9c/README.Rmd#L367) with a link to your use case.

**Comment by jdblischak** [comment]
@pat-s This is awesome! Keep up the good work, and please let me know if you have any questions/comments/suggestions about how to use or improve workflowr.

**Comment by wlandau** [comment]
In https://github.com/ropensci/drake/commit/dc1d957054a36c81db4e9c683d841c341e2ac211, I rewrote the whole section on similar work, and I added references to `workflowr` and https://2019-feature-selection.pjs-web.de/index.html.

**Comment by dexterlemmer** [comment]
Your link (https://2019-feature-selection.pjs-web.de/index.html) gives a 404 error for me. Is it still available? Perhaps elsewhere?

**Comment by pat-s** [comment]
Yes, I just had to remove the custom domain due to Netlify limits: https://pat-s.github.io/2019-feature-selection/
