### ISSUE TITLE
Addin to call r_make()?

### ISSUE THREAD

**Issue by MilesMcBain** [ropensci/drake#892]
## Prework

- [*] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [*] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

I really like the `_drake.R` style setup and have a keybinding that calls `r_make()` for me that I use a lot. Maybe `drake` could have an RStudio addin for it?

**Comment by wlandau** [comment]
What a fantastic idea! Let's throw in addins for `r_vis_drake_graph()` and `r_outdated()` too.

**Comment by wlandau** [comment]
Implemented.

**Comment by MilesMcBain** [comment]
Wow. That was fast! :smiley:
