### ISSUE TITLE
Serialize caches instead of storing them in memory?

### ISSUE THREAD

**Issue by htlin** [ropensci/drake#903]
At the moment my plan has a cross transform of 4x2x5x5 parameters, and with several targets in the workflow, running the plan gets slower and slower over time - checking the memory consumption it gradually increases over time (up to around 10GB and it will mostly likely hang reaching my PC limit :)
So, I wonder instead of storing all target caches in memory, is it possible to serialize them on disk (and release memory), then reload them if necessary?

In fact I am starting to do some of that manually now, e.g. writing result data frames in CSV and then reading them back in the subsequent target, it seems to help my immediate memory issue but not sure if you have better ideas of doing it?

**Comment by wlandau** [comment]
I was working on this very problem today (#897 and #900) and I will have a lot more to say on memory in https://github.com/ropenscilabs/drake-manual/issues/95. For now, please have a look at the `memory_strategy` and `garbage_collection` arguments of `make()` and let me know if you have follow-up questions. For `cross()`, the `"memory"` and `"lookahead"` memory strategies should be fine, and those have been supported in `drake` for a long time. If you have a `combine()` step that loads everything at once, that's when it is time to use the `"unload"` or `"none"` memory strategy (both of which I implemented today) and manually `readd()`/`rm()/gc()` the targets you need.

**Comment by htlin** [comment]
Awesome, good to see you're working on this challenging issue! I will study them and get back when I have more questions, thanks!
