### ISSUE TITLE
Combine cascading drake plans

### ISSUE THREAD

**Issue by caewok** [ropensci/drake#904]
Pre-drake 7.0, I would create several drake plans, and combine them as needed. So, for example, I might re-use a data pre-processing plan as part of a larger series of plans. Something like:

> `preprocess_plan <- drake_plan(data_file = import_file_fn(), data = load_data_file_fn(data_file), processed_data = process_data_fn(data))`
> 
> `preliminary_analysis_plan <- drake_plan( preliminary_results = do_preliminary_analysis_fn(processed_data)) `
> 
> `full_analysis_plan <- drake_plan(full_analysis_results = do_full_analysis_fn(processed_data))`
> 
> `master_preprocess_plan <- bind_plans(preprocess_plan, preliminary_analysis_plan)`
> 
> `master_full_analysis_plan <- bind_plans(preprocess_plan, full_analysis_plan)`

This worked, because I could use `evaluate_plan` and wildcards to expand each of the two master plans as necessary, while only having one version of the preprocess_plan code. (I am, of course, hiding a lot of complexity and additional steps for purposes of this example.)

But with drake 7, the equivalent to `evaluate_plan` and wildcards is setting transform within target in `drake_plan`. This means that each call to `drake_plan` evaluates the transformation immediately. 

> `preliminary_analysis_plan <- drake_plan( preliminary_results = target(do_preliminary_analysis_fn(processed_data), transform = map(processed_data) `

As a result, the above preliminary_analysis_plan and full_analysis_plan both fail because `drake_plan` does not know about the processed_data variable. For example, imagine that the plan looked like this in drake 7:

This could be avoided if there was a way to combine the drake plans, and only then do the transformations. I saw that I could set the parameter transform=FALSE in `drake_plan.` That prevents `drake_plan` from throwing an error because it does not try to evaluate the processed_data, which it cannot otherwise find. And I can then combine two drake plans using `bind_plans`. But I don't see a way to convince drake to evaluate the transformations after binding two or more plans together. Is that possible? 

If not, is it possible to use tidy evaluation or something like `parse_quos` to essentially paste multiple steps into `drake_plan`? If I could insert multiple targets into `drake_plan`, it would work well, because then I could vary the other parameters of `drake_plan` for testing, etc. 

Any thoughts are appreciated. And thanks for all the work on drake 7—overall I think it is a strong improvement.

**Comment by wlandau** [comment]
I recommend that you work within a single call to `drake_plan()` and precompute the information you need to do so beforehand. Targets are meant to be long computations and things downstream. File names, for example, should not usually be return values of targets (e.g. `drake_plan(data_file = import_file_fn(), ...)`). It is usually fast and cheap to get those initial file names outside the plan and then insert them in the plan with tidy evaluation. The following example has tidy evaluation in both the command and the transformation of the first target.

``` r
library(drake)
 
# Toy example: 
get_files <- function() {
  c("file1.csv", "file2.csv")
}
  
files <- get_files() # Should be fast, no need for a special "files" target.

config_file <- "config.txt"

plan <- drake_plan(
  munged = target(
    munge(file_in(file), file_in(!!config_file)),
    transform = map(file = !!files, .id = FALSE)
  ),
  analysis = target(
    analyze(munged),
    transform = map(munged, .id = FALSE)
  ),
  summary = target(
    summarize(analysis),
    transform = map(analysis, .id = FALSE)
  ),
  results = target(
    dplyr::bind_rows(summary),
    transform = combine(summary, .id = FALSE)
  )
)

drake_plan_source(plan)
#> drake_plan(
#>   munged = munge(file_in("file1.csv"), file_in("config.txt")),
#>   munged_2 = munge(file_in("file2.csv"), file_in("config.txt")),
#>   analysis = analyze(munged),
#>   analysis_2 = analyze(munged_2),
#>   summary = summarize(analysis),
#>   summary_2 = summarize(analysis_2),
#>   results = dplyr::bind_rows(summary, summary_2)
#> )

config <- drake_config(plan)
vis_drake_graph(config)
```

![](https://i.imgur.com/K3OUIiZ.png)

<sup>Created on 2019-06-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

That said, some situations really do require a collections of subplans, so I exported `transform_plan()` in 70d3bcaad88b1cc942297b72ae971c81f2c57c43. I am trying to dissuade users from doing this, but without #685, sometimes it cannot be helped.k

``` r
library(drake)
plan1 <- drake_plan(
  y = target(
    f(x),
    transform = map(x = c(1, 2))
  ),
  transform = FALSE
)
plan2 <- drake_plan(
  z = target(
    g(y),
    transform = map(y, .id = x)
  ),
  transform = FALSE
)
plan <- bind_plans(plan1, plan2)
transform_plan(plan)
#> # A tibble: 4 x 2
#>   target command
#>   <chr>  <expr> 
#> 1 y_1    f(1)   
#> 2 y_2    f(2)   
#> 3 z_1    g(y_1) 
#> 4 z_2    g(y_2)
```

<sup>Created on 2019-06-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
