### ISSUE TITLE
Failed to launch and connect to R worker on local machine

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#905]
Getting this error below only when I submit more than 2 jobs (since today).

Not sure where the error originates from.
Can also be an issue on the local machine (I assume that right now).
However, we made no port changes or other adjustments that should have any effect here.
Also the _clustermq_ toy example (see below) still works.

Tested with: 
- _clustermq_ 0.8.6 - 0.8.8
- _drake_ 7.3.0 - master

Slurm 18.08.07 (recently updated from 18.08.06)

The `clustermq` toy example works fine with even > 1 job.

```r
# load the library and create a simple function
library(clustermq)
fx = function(x) x * 2

# queue the function call on your scheduler
Q(fx, x=1:3, n_jobs=3)
# list(2,4,6)
```

<details>
<summary>Details</summary>

```r
Submitting 2 worker jobs (ID: 7295) ...
target ps_xgboost_pca
target ps_svm

Error : Failed to launch and connect to R worker on local machine 'localhost' from local machine 'c0'.
 * The error produced by socketConnection() was: 'cannot open the connection'
 * In addition, socketConnection() produced 1 warning(s):
   - Warning #1: 'port 11364 cannot be opened' (which suggests that this port is either already occupied by another process or blocked by the firewall on your local machine)
 * The localhost socket connection that failed to connect to the R worker used port 11364 using a communication timeout of 2592000 seconds and a connection timeout of 120 seconds.
 * Worker launch call: '/opt/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/r-3.5.2-gmzjlr2a4zuzv7up2nhfmthzcfnlkb7a/rlib/R/bin/Rscript' --default-packages=datasets,utils,grDevices,graphics,stats,methods -e 'try(cat(Sys.getpid(),file="/tmp/RtmpeRnlaE/future.parent=18347.47ab3d6c6032.pid"))' -e 'parallel:::.slaveRSOCK()' MASTER=localhost PORT=11364 OUT=/dev/null TIMEOUT=2592000 XDR=TRUE.
 * Worker (PID 18420) was successfully killed: TRUE
 * Troubleshooting suggestions:
   - Suggestion #1: Set 'verbose=TRUE' to see more details.
   - Suggestion #2: Set 'outfile=NULL' to see output from worker.

In addition: Warning message:
replacing previous import ‘gdalUtils::gdal_rasterize’ by ‘sf::gdal_rasterize’ when loading ‘mapview’
Error: Failed to launch and connect to R worker on local machine 'localhost' from local machine 'c0'.
 * The error produced by socketConnection() was: 'cannot open the connection'
 * In addition, socketConnection() produced 1 warning(s):
   - Warning #1: 'port 11364 cannot be opened' (which suggests that this port is either already occupied by another process or blocked by the firewall on your local machine)
 * The localhost socket connection that failed to connect to the R worker used port 11364 using a communication timeout of 2592000 seconds and a connection timeout of 120 seconds.
 * Worker launch call: '/opt/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/r-3.5.2-gmzjlr2a4zuzv7up2nhfmthzcfnlkb7a/rlib/R/bin/Rscript' --default-packages=datasets,utils,grDevices,graphics,stats,methods -e 'try(cat(Sys.getpid(),file="/tmp/RtmpeRnlaE/future.parent=18347.47ab3d6c6032.pid"))' -e 'parallel:::.slaveRSOCK()' MASTER=localhost PORT=11364 OUT=/dev/null TIMEOUT=2592000 XDR=TRUE.
 * Worker (PID 18
```
</details>

@mschubert @wlandau 	
Can you tell whether the error message comes from one of your repos or from Slurm?

And sorry, didn't really know in which repo I should post this issue. Maybe its unrelated to both.

**Comment by wlandau** [comment]
This is a new one. Are you using `options(clustermq.scheduler = "multicore")` to generate the errors above? If so, what happens on SLURM?

PS: this seems different from #898.

**Comment by pat-s** [comment]
> This is a new one. Are you using options(clustermq.scheduler = "multicore") to generate the errors above? If so, what happens on SLURM?

No, this is a SLURM output.

As mentioned above, I tested it with older _clustermq_ and _drake_ versions and the errors stays the same. 
Right now I am unsure what the error source might be..

**Comment by wlandau** [comment]
Those errors seem very low-level. Did any other infrastructure change in the last day or so?

Also, what about a minimal example with `drake` included? `drake` invokes `clustermq` through a [different API](https://mschubert.github.io/clustermq/articles/technicaldocs.html#worker-api) than `Q()`, so there could still be problems I need to fix.

```r
library(drake)
options(clustermq.scheduler = "slurm")
load_mtcars_example()
make(my_plan, parallelism = "clustermq", jobs = 4)
```

**Comment by mschubert** [comment]
What makes you think this is related to either drake or clustermq?

I'm not using PSOCK clusters, and I think neither is drake. This has to come from somewhere else.

**Comment by pat-s** [comment]
> What makes you think this is related to either drake or clustermq?

Because I do not update other packages in my projects. Actually only _drake_ and this time also _clustermq_ since there were some issues with <0.8.8

We did a patch update for SLURM form 18.08.6 to 18.08.07 some days ago via the centOS repo - let's assume this is not the issue.

> I'm not using PSOCK clusters, and I think neither is drake. This has to come from somewhere else.

Me neither, only using `future::multiprocess` which should fallback to `multicore`. 

I also couldn't find anything that helped me so far.
Seeing that the _clustermq_ toy example works lets me suspect that everything is fine with SLURM and _clustermq_. 
Also that the process is working in the first place but only crashes once I specify > 1 "jobs" with _drake_ which actually uses the `--array` option in SLURM.

@wlandau Jep, will do the reprex tomorrow.

Thanks for your thoughts guys!

**Comment by mschubert** [comment]
If I'm not mistaken `future::multiprocess` *does not* fall back to `multicore` but rather uses sockets.

Have a look here, does that look like your error message? https://github.com/HenrikBengtsson/future/blob/fba7f76f75e2569a782963359a1db35d94cac73e/R/makeClusterPSOCK.R#L586

**Comment by pat-s** [comment]
> A multiprocess future is a future that uses multicore evaluation if supported, otherwise it uses multisession evaluation. 

But I was indeed using `multisession` which falls back to PSOCK.
So yeah it looks like somethings wrong here.

And indeed, the problematic line was

```r
drake_config(
  [...]
  prework = quote(future::plan(future::multiprocess, workers = 4))
)
```

Changing `future::multisession` to `future::multiprocess` solved the issues.

Which is weird because I used the former for weeks/months now without any issues.
I did not update the `future` package lately.

I think the only significant change that was done on the HPC recently is rolling back from using Linux kernel 5.x to 3.x (centOS default). 

summoning @henrikbengtsson. Do you have any idea what might be the issue here? Could it be the kernel change?

@mschubert 	@wlandau 
Sorry for the false positive call. Everything seems to be fine on your side :tada:

**Comment by wlandau** [comment]
@pat-s, what happens if you use `callr` futures instead, e.g.

```r
drake_config(
  [...]
  prework = quote(future::plan(future.callr::callr, workers = 4))
)
```

I have heard `callr` is more robust and dependable than `parallel`.

**Comment by pat-s** [comment]
We're having troubles with `callr` future in the past within some functions (with no clear pattern), that's why we used `multisession` in the first place.
I can't remember but I think there was an issue about it.

**Comment by HenrikBengtsson** [comment]
Quick feedback from me (future author):

1. The error in the 'details' section of https://github.com/ropensci/drake/issues/905#issue-455733444 originates from `future::makeClusterPSOCK()`, which is used when trying to set up `multisession` workers.
2. `future::makeClusterPSOCK()`, creates PSOCK clusters, and is basically an improvement of `parallel::makePSOCKcluster()`.
3. The error indicates that there are connection/port clashes happening on that machine. The risk for this to happens seems to increase when there are other R process using PSOCK clusters running on the same machine.  I see these happening sporadically too, e.g. CRAN checks on future, future.apply, doFuture, ... occasionally show these and then disappear at next round.  The design of PSOCK clusters is not really robust in this sense although some improvements have been done to R.  My `future::makeClusterPSOCK()` tries to give more informative error messages when this happens.
4. `plan(multicore)` is using processing forking, so naturally does not have the issue of port clashes and other issues with socket connections.
5. `plan(future.callr::callr`) does not rely on socket connections either and therefore avoids the above PSOCK problem.  I don't use it on a regular basis myself, but I'd expect it to work as well as `multisession` possibly with more overhead since each future launches a new background process.

@pat-s, for troubleshooting your HPC environment, see if:
```r
cl <- future::makeClusterPSOCK(1L, outfile = NULL)
```
works or not.  If it consistently fails for you, then you've ruled out a lot of other things.  If it fails all the time, not just occasionally, then it could be a firewall issue where ports are blocked.  If you're prevented from using PSOCK clusters (=`multisession` and `cluster`), I'd try with `multicore` and `future.callr::callr` which I expect to work.

**Comment by pat-s** [comment]
> The risk for this to happens seems to increase when there are other R process using PSOCK clusters running on the same machine.

This could happen since multiple jobs are being started on the same node (sometimes).

> @pat-s, for troubleshooting your HPC environment, see if:
> 
> cl <- future::makeClusterPSOCK(1L, outfile = NULL)

Works. It also worked for a long time without any problems.

> I'd try with multicore and future.callr::callr which I expect to work.

I prefer both anyways due to their instant startup.
However, some months ago I had problems with these running some functions from the _raster_ package. Occasionally. Without a pattern.
Switching to `multisession` did the trick back then.

Now it's the opposite way :laughing: 	
I do not care that much about switching around but it might be confusing for beginners.
But yeah, this "parallel" world is a complex castle on its own :duck: 	

Thanks for all of your input (!) and maybe this issue helps people stumbling across this error in the future.
