### ISSUE TITLE
Build drake targets over SSH via future.batchtools with nested futures

### ISSUE THREAD

**Issue by SimonCouv** [ropensci/drake#906]
## Prework

- [x ] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x ] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

Over the past weeks I have been piloting drake, both for projects run locally on my machine and on SGE and SLURM clusters. One feature/application which I could not find discussed anywhere is submitting jobs to a SGE/SLURM queue over SSH. 

The utility of such a setup might be limited in most cases, due to bandwith and latency limitations, but there might be a particular use case in which it makes sense, namely when the SSH connection is between nodes on the same cluster. Which in turn might be a solution to run drake in catch-22 HPC environments where

1. No long-running jobs are allowed on the login nodes, and
2. Jobs can only be submitted to the HPC scheduler/queue from the login node.

To explain the situation, let me first detail my configuration:

I am running drake on HPC clusters (SGE/SLURM), using the future backend and future.batchtools to submit to the HPC scheduler. My institutional policy is not to run long-running jobs on the login node, therefore I submit a "master drake job", which runs make.R, to the HPC scheduler. This "master drake job" then runs on a compute node, and in turns submits target-building jobs to the HPC scheduler, to be run on compute nodes as well.

**make.R**
```
source("src/imports_slurm.R")   # library() calls
future::plan(batchtools_sge(template = "src/sge_gradual.tmpl"))
plan_sge <- drake_plan(
  large_target = target(
    long_computation(file_in("input_data.csv"), parameter),
    transform = map(parameter=1:100)
  )
)
make(plan_sge, parallelism="future",caching="worker", jobs=20)
```

On one cluster (a SLURM cluster, but probably the decisive factor is admin policy), this works like a charm - of course with required changes to the batchtools calls compared to above script. On a different cluster (SGE), this setup fails because jobs can only be submitted to the HPC scheduler/queue from the login node, giving the catch-22 described earlier. The error message looks like this:

```
target large_target
Error: Listing of jobs failed (exit code 1);
cmd: 'qstat -u $USER -s rs'
output:
error: denied: host "nodexxx.my.institutional.domain" is neither submit nor admin host
```

A solution would be to SSH from the compute node where drake::make() is running, back to the login node on the same cluster, in the process of submitting target jobs. I confirmed that setting up this connection is possible: the sequence 'connect to login node -> request interactive session on compute node -> from interactive session, SSH back to login node' works fine. 

Therefore, I am looking for a way to schedule drake target jobs in similar way, and I believe nested futures would be the solution. I am aware that drake can be used with nested futures, e.g. here: https://github.com/ropensci/drake/issues/777, and that nested futures can be used to submit to a queue over SSH, e.g. here: HenrikBengtsson/future/issues/287. 

But what I cannot figure out is how to set up the drake plan in combination with (this use of) nested futures. Note that it is very different from within-target parallelism, in that in my use case the target corresponds to the second (deepest) layer of nested futures, not the first. As illustration of the concept: the solution could look something like this (although syntactically problematic).

**make.R**
```
login <- future::remote(workers = "login.my.institutional.domain")
sge <- future::tweak(future.batchtools::batchtools_sge,
                                 template = "src/sge_gradual.tmpl")
future::plan(list(login,sge))
plan_sge = drake_plan(
  large_target %<-% target(
    long_computation(file_in("input_data.csv"), parameter),
    transform = map(parameter=1:100)
  )
)
make(plan_sge, parallelism="future",caching="worker", jobs=20)
```

Where make.R would still be submitted to the queue just like described above.

For this to work would probably require changes in the drake API with something like a 'use.remote' argument for drake::make, or am I missing some more straightforward solution?

**Comment by wlandau** [comment]
> 1. No long-running jobs are allowed on the login nodes, and
> 2. Jobs can only be submitted to the HPC scheduler/queue from the login node.

How common is this catch-22? 

Your SSH workaround is clever, but to be honest, I do not think I would recommend it. Essentially, it is a way to manually hack / bypass the scheduler, which raises concerns about good citizenship. Would it be possible to negotiate with your sys admin?

**Comment by SimonCouv** [comment]
> How common is this catch-22?

I have no overview of HPC of how HPC clusters are typically configured. I'm afraid I cannot provide a general comment here. But probably restriction 1 (no long-running jobs on the login node) is quite general applicable and sensible, as running jobs on a login node can severly slow the connection for other users. Running the drake master is not resource intensive per se, so the impact of one user is limited, but if many users do this, I think it could lead to noticable slowdown. Not running drake (or other long-running jobs) on the login node could thus be considered good citizenship, especially in HPC clusters with many users sharing the login nodes. 

> Essentially, it is a way to manually hack / bypass the scheduler, which raises concerns about good citizenship.

Firstly, I agree that fair resource sharing and good citizenship should be primordial. However, what I propose is not to bypass the scheduler. All jobs are still submitted to the scheduler and treated just like they would be treated if one submitted them all manually.

I think the problem lies mostly in restriction 2 (job submission only from login nodes), and indeed the SSH workaround is a way to bypass this restriction, which raises concerns. I was focussed on not running drake on the login node (not good citizenship, for reasons above), and did not think enough about this. Much depends on whether this is a limitation inherent to SGE (which I assumed), or a deliberate admin policy. You are right, my 'more straightforward solution' is to contact the sys admin regarding this restriction 2, which I will do, thank you.

**Comment by SimonCouv** [comment]
> How common is this catch-22?

I have no overview of how HPC clusters are typically configured, I'm afraid I cannot provide a general comment here. But probably restriction 1 (no long-running jobs on the login node) is quite general applicable and sensible, as running jobs on a login node can severly slow the connection for other users. Running the drake master is not resource intensive per se, so the impact of one user is limited, but if many users do this, I think it could lead to noticable slowdown. Not running drake (or other long-running jobs) on the login node could thus be considered good citizenship, especially in HPC clusters with many users sharing the login nodes.

> Essentially, it is a way to manually hack / bypass the scheduler, which raises concerns about good citizenship.

Firstly, I agree that fair resource sharing and good citizenship should be primordial. However, what I propose is not to bypass the scheduler. In what I propose, all target jobs are still submitted to the scheduler (by drake) and treated just like they would be treated if one submitted them all manually, or via drake running on the login node for that matter.

I think the problem lies mostly in restriction 2 (job submission only from login nodes), and indeed the SSH workaround is a way to bypass this restriction, which raises concerns. I was focussed on not running drake on the login node (not good citizenship, for reasons above), and did not think enough about this. Much depends on whether this is a limitation inherent to SGE (which I assumed), or a deliberate admin policy. You are right, my 'more straightforward solution' is to contact the sys admin regarding this restriction 2, which I will do, thank you.

**Comment by wlandau** [comment]
As with all things having to do with nested futures, I will need some time to wrap my head around this one. In the meantime, here are a couple related topics:

- @mschubert's [`clustermq` package](https://github.com/mschubert/clustermq/) supports [ssh workers](https://mschubert.github.io/clustermq/articles/userguide.html#ssh-connector), and with the right configuration, you can invoke them with `make(parallelism = "clustermq")`.
- Early this year, @krlmlr and I worked on a package called [`workers`](https://github.com/wlandau/workers), which tries to be a more lightweight DAG manager. It uses decorated futures to contain preprocessing / postprocessing tasks. Maybe you can borrow this idea.

**Comment by mschubert** [comment]
> 1. No long-running jobs are allowed on the login nodes, and
> 2. Jobs can only be submitted to the HPC scheduler/queue from the login node.

Just my 2 cents: 1 is common, I haven't encountered 2 yet (except slurm using `srun`, but they should be started with `sbatch` if non-interactive anyway). Both 1 and 2 on one system is bad design because they obviously conflict.

I'm very much in favor of not having an error-prone workaround that circumvents bad configuration. Either allow medium-resource processes on the login node, allow job submission from jobs, or have a separate node that allows medium loads without jobs.

That's something the cluster admins should fix, not a tool.

**Comment by wlandau** [comment]
Yeah, I agree with @mschubert. Your workaround is interesting, but not something I would pursue when it comes to adding features to `drake`.
