### ISSUE TITLE
Error in `r_vis_drake_target()`: invalid 'y' type in 'x && y'

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#908]
Can't reproduce with a reprex. Hence I assume the error might reside in the cache?
Could it be that the cache is corrupt?
Already tried `drake_gc()` and `rescue_cache()`.

with v7.3.0

```r
r_vis_drake_graph()
Error in cache$exists(key = target) && diagnose(target = target, character_only = TRUE,  : 
  length y not 1
```

with v7.4.0 slightly different

```r
r_vis_drake_graph()
Error in cache$exists(key = target) && diagnose(target = target, character_only = TRUE,  : 
  invalid 'y' type in 'x && y'
```

**Comment by wlandau** [comment]
Do you mean `vis_drake_graph()`? If so, do you get the same error when you run `drake_graph_info()`?

**Comment by pat-s** [comment]
> Do you mean vis_drake_graph()

ah yes, typo. corrected it. 

> If so, do you get the same error when you run drake_graph_info()?

Yes.

**Comment by wlandau** [comment]
The traceback helps. I can think of a patch to try when I return to a computer. In the meantime, I think you can try vis_drake_graph(build_times = "none").

**Comment by pat-s** [comment]
`r_vis_drake_graph(build_times = "none")` works :tada:

**Comment by wlandau** [comment]
Great. I think I have a patch in ad77b2ab4c2ddc7f4a770dd8a2da4ffffdc95512. Care to give it a try without `build_times = "none"`?

**Comment by pat-s** [comment]
works again! :tada:
