### ISSUE TITLE
Build targets based on groups / wildcards

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#912]
Using the same logic that `r_vis_drake_graph()` but in this case to build targets by their group specifier.

Alternatively, a wildcard support similar to `make(targets = "target_*")` would be great.

I thought that this was for sure implemented already but could only find the graph support for groups.

**Comment by wlandau** [comment]
This is similar to https://github.com/ropensci/drake/issues/810, which unfortunately is not a good fit for the API. I think our best (but most difficult) approach is to move ahead with #685. In the meantime, you can use `drake_plan(trace = TRUE)` with transformations.

``` r
library(drake)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
plan <- drake_plan(
    x = target(
        a,
        transform = map(a = c(1, 2, 3))
    ),
    y = target(
        b,
        transform = map(b = c(4, 5, 6))
    ),
    trace = TRUE
)

plan
#> # A tibble: 6 x 6
#>   target command a     x     b     y    
#>   <chr>  <expr>  <chr> <chr> <chr> <chr>
#> 1 x_1    1       1     x_1   <NA>  <NA> 
#> 2 x_2    2       2     x_2   <NA>  <NA> 
#> 3 x_3    3       3     x_3   <NA>  <NA> 
#> 4 y_4    4       <NA>  <NA>  4     y_4  
#> 5 y_5    5       <NA>  <NA>  5     y_5  
#> 6 y_6    6       <NA>  <NA>  6     y_6

targets <- plan %>%
    filter(!is.na(x)) %>%
    pull(target)

targets
#> [1] "x_1" "x_2" "x_3"

make(plan, targets)
#> target x_1
#> target x_2
#> target x_3
```

<sup>Created on 2019-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
