### ISSUE TITLE
Feature request: `r_build_times()`

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#921]
:guitar:

**Comment by wlandau** [comment]
The `r_*()` family is designed to compensate for the brittleness of depending on in-memory objects, and every `r_*()` function needs an inner function that takes a `drake_config()` object as an argument. `build_times()` only needs the cache, so I do not believe an `r_build_times()` function would add value. But please let me know if I ever forgot about anything else that takes a `config`.

**Comment by pat-s** [comment]
Oh, you're right, it works without a `config` arg. :man_facepalming: 
I am not sure what I did/thought when trying it out, some confusion must have been going on in my head.
Living the `r_*` live to its fullest ;)
