### ISSUE TITLE
Feature request: Better progress log output

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#922]
When running multiple targets in parallel on a HPC, I often find myself in a situation in which I loose overview which targets finished and which (and how many) are still running (see image below). Searching in the log for targets names and checking their status is not practical if you have lots of targets.
I am running with `verbose = 2`.

#### FR 1
What do you think about adding some sort of indicator behind `"target <name>"` in the console output? So every time a new target starts, it could indicate `"<number of finished targets> / <total targets>"`. 
This would help solving the "how many are still running" problem without printing extra lines to the log stating that a target finished (I guess this would be too chatty). 
Regarding the "finished targets" output, this could go into a new verbosity level, may be `verbose = 3`: Here, targets also print to the console after they finished. In an optimal way using another color than running/started targets.

#### FR 2
For more sugar, a "checkbox" icon at the very end of all processes could indicate a successful execution of all targets. 
May be even with a short summary of how many targets failed (if `keep_going = TRUE`) and which ones. 
This would help in getting a quicker overview of what happened instead of having to look at `r_vis_drake_graph()` or `outdated()` again.

![2019-06-26-155738_screenshot](https://user-images.githubusercontent.com/8430564/60186243-ac1b5980-982b-11e9-95a8-6918b8ccd078.png)

Thanks for your reply upfront and have a great day Will :rocket:

**Comment by wlandau** [comment]
`drake` actually does keep track of progress. Rather than use log files, which can get both busy and brittle, it uses the cache. During or after `make()`, check out these functions:

```r
progress()
running()
failed()
```

And in `vis_drake_graph()`, the running targets appear in orange and the failed ones appear in red.

If you ever want to disable progress to shave off a tiny bit of runtime, you can set `log_progress = FALSE` in `make()` or `drake_config()`.

**Comment by pat-s** [comment]
Oh wow, I somehow missed these until now! :tada: 
Another "wow" moment with _drake_.

A related follow-up on this: Sometimes I run multiple "makes" in parallel. Despite the question if this is recommended, is there somehow a "history" of the "make" calls that `progress()` could query? I guess this is a complicated one and very very niche...

Some context to this:

1. I usually have some sort of benchmarking going on that runs for hours/days. At the same time, I have a second "drake_config" block that I call for sequential targets so that I can continue in my project.

2. These new `r_make()` calls then ofc are the calls taken by `progress()` and friends and I cannot query the "benchmarking" `r_make()` call from, let's say, two days before (which are actually the important ones in terms of progress).

I have absolutely no clue if this is possible at all. 
Thinking about it, one could attach an "id" to each `r_make()` call and let `progress()` query the status of any `r_make()` call in the past?

**Comment by wlandau** [comment]
Not sure I fully understand, but maybe the new `drake_history()` functionality could be useful. The history includes the elapsed runtime (of the command) and date/time of each run of each target. Does that help?

**Comment by pat-s** [comment]
This can be useful if I know which features to address.

What I meant was calling `progress()` not on the most recent make but on "older" ones (which might be still running).

**Comment by wlandau** [comment]
If you have simultaneous `make()`s, then presumably you have simultaneous caches, right? If so, you can supply a cache to `progress()` manually.

```r
cache <- drake_cache(path = your_path)
progress(cache = cache)
```

For a given cache, `drake` does not store the progress of previous `make()`s. The reason is that it would create too many tiny files in the cache and/or be too slow. That's why `make(history = TRUE)` avoids the cache and uses [`txtq`](https://github.com/wlandau/txtq). I am resistant to using [`txtq`](https://github.com/wlandau/txtq) because I think it is overkill for most use cases, but you can use it for your own targets.

**Comment by pat-s** [comment]
> If you have simultaneous make()s, then presumably you have simultaneous caches, right?

No, just one cache. 

I thought that _drake_ might store the `drake_config` used for any `r_*` calls somewhere -> the setting that `progress()` uses to query the status.

Probably it is overwritten if and thrown away once there was a new call to `drake_config()`, making it impossible to query the progress of previous `r_make()` calls.
If it is still not understandable for you, let me know and I'll try once more :+1: 	

Thinking about it, would it be possible that _drake_ saves, let's say the last three, "environments" of `r_*()` calls so that one could do something like `progress(id = 2)` (where 2 would be the second last call)? Does not need to be a number, maybe an explicit name would be better. 
I think all of this goes into the direction of asynchronous execution of `r_*()` calls and is probably very very niche...

**Comment by wlandau** [comment]
> I thought that drake might store the drake_config used for any r_* calls somewhere -> the setting that progress() uses to query the status.

`drake` used to store the `config` object locally, but it took up too much time and space, so I stopped it for `drake` >= 7.0.0.

> Probably it is overwritten if and thrown away once there was a new call to drake_config(), making it impossible to query the progress of previous r_make() calls.

`drake_config()` objects do not overwrite progress, but calls to `make(log_progress = TRUE)` do.

> Thinking about it, would it be possible that drake saves, let's say the last three, "environments" of r_*() calls so that one could do something like progress(id = 2) (where 2 would be the second last call)? Does not need to be a number, maybe an explicit name would be better.
I think all of this goes into the direction of asynchronous execution of r_*() calls and is probably very very niche...

Progress is intended to show what is going on with the current versions of the targets at this very moment. I do not see anticipate people wanting progress for old `make()` runs, and it would take a lot more storage and bookkeeping to track such information.

What I think we really want to focus on here is the history (`make(history = TRUE)`, `drake_history()`). It is `drake`'s first foray into the world of provenance and tracking, joining tools like MLflow and `archivist` in this domain, and there is a lot to explore.

**Comment by pat-s** [comment]
> What I think we really want to focus on here is the history (make(history = TRUE), drake_history()). This is drake's first foray into the world of provenance and tracking, joining tools like MLflow and archivist in this domain, and there is a lot to explore.

Ok. On the first look it did not look like that this new feature could help me in this particular case though?

**Comment by wlandau** [comment]
> Ok. On the first look it did not look like that this new feature could help me in this particular case though?

Not yet, but this is a new feature. There is room to experiment.

But back to https://github.com/ropensci/drake/issues/922#issuecomment-505913381: you can suppress progress logging with `log_progress = FALSE` in both `make()` and `drake_config()`. So you could leave it on for that long `r_make()` call and turn it off for the others. If you use other `r_*()` functions that all reference the same `_drake.R` by default, this may require you to select a custom alternative to `_drake.R` (see `?r_make()`). Does that help?
