### ISSUE TITLE
conda-forge

### ISSUE THREAD

**Issue by brendanf** [ropensci/drake#923]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

I am using Conda to manage my R packages as well as other dependencies.  At the moment, I have an r-drake package on my [personal Conda repository](https://anaconda.org/bfurneaux/r-drake), but before I update it to the new version, I thought I'd check if you have any concerns about me contributing a recipe to [Conda-Forge](https://conda-forge.org/docs/index.html).

**Comment by brendanf** [comment]
In particular, would you like me to add @wlandau to the maintainers list?

**Comment by wlandau** [comment]
Awesome, @brendanf! Thanks for setting this up.

Yes, it would be great to joint the recipe maintainers list. Is there a way to recognize the [other contributors](https://github.com/ropensci/drake/blob/d235e488ed7834888e8a75fd0fda1c5e77dd9b5b/DESCRIPTION#L26-L80) too?

**Comment by brendanf** [comment]
My understanding is that the maintainers list is for those who specifically maintain the conda recipe.  From [Conda Forge](https://conda-forge.org/docs/maintainer/adding_pkgs.html#maintainer-role):

> The maintainer’s job is to:
> 
> - Keep the feedstock updated by merging eventual maintenance PRs from conda-forge’s bots.
> - Keep the feedstock on par with new releases of the source package by
>     - Bumping the version number and checksum.
>     - Making sure that feedstock’s requirements stay accurate.
>     - Make sure the test requirements match those of the updated package.
> - Answer eventual questions about the package on the feedstock issue tracker.

I don't feel comfortable giving that responsibility to all the contributors, but they are all still credited in the DESCRIPTION file. (Which is installed along with the package.)

**Comment by wlandau** [comment]
Sure, that's fine. I was thinking more about recognition than responsibility.
