### ISSUE TITLE
Warning about make() in a subdirectory only once?

### ISSUE THREAD

**Issue by billdenney** [ropensci/drake#955]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

Could the warning below please be a once-per-session or perhaps once per session per directory set (working/cache directory pair) warning instead of an every-time warning?  (Related to #634)

```
Running make() in a subdirectory of your project. 
This could cause problems if your file_in()/file_out()/knitr_in() files are relative paths.
Please either [...]
```

**Comment by wlandau** [comment]
Is there a reason you would want to have nested `drake/` caches?

**Comment by billdenney** [comment]
They're not actually nested.  The issue is that I want to use the name ".drake" so that I know what the folder name is, but I'm running this on windows with the long-filename issue, so I have to put it in a shorter directory name:

```
1: Running make() in a subdirectory of your project. 
This could cause problems if your file_in()/file_out()/knitr_in() files are relative paths.
Please either
  (1) run make() from your drake project root, or
  (2) create a cache in your working directory with new_cache('path_name'), or
  (3) supply a cache of your own (e.g. make(cache = your_cache))
      whose folder name is not '.drake'.
  running make() from: C:/git/prj/Customers/a really long path name that I can't share
  drake project root:  c:/tmp/foo
  cache directory:     c:\tmp\foo\.drake\ 
```

If you say that the workaround is to name my cache "_drake", I'd understand.

**Comment by wlandau** [comment]
> They're not actually nested. 

Yes, sorry, I only glanced at the issue.

> If you say that the workaround is to name my cache "_drake", I'd understand.

I think the warning should stay persistent for the sake of reproducibility. A slight loss of convenience in certain use cases is worth it. Your workaround sounds like a nice solution.
