### ISSUE TITLE
Support for R6 / handling of modifications in place

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#961]
I am right now testing out how [mlr3](https://github.com/mlr-org/mlr3) plays together with _drake_.

As you know, R6 builds on the idea of modifying objects in place and only storing references to environments rather than really copying the object.

Since drake builds on the idea requiring a unique R object for every target, modifications in place using R6 member functions are problematic.

In theory one could write a wrapper function and apply all member function calls within including a clone of the object to have a new R object to assign the result to.
However, this practice becomes tedious for every member function call.

There are two problems in particular, one also applies to S3:

1. Handling of `$` assignments to existing targets (like `x$foo <- c()`)
2. Handling of R6 modifications in place

Here is an example to illustrate the problem (which applies to both cases)):

```r
library(drake)

drake_plan(
  param_set_svm = ParamSet$new(params = list(
    ParamDbl$new("cost", lower = -5, upper = 5),
    ParamDbl$new("gamma", lower = -5, upper = 3)
  )),
  
  param_set_svm$trafo = function(x, param_set) {
    x$cost = 2^x$cost
    x$gamma = 2^x$gamma
    return(x)
  }
)
```

If the user wants to set `param_set$trafo`, the object is modified in place.
Because this is clearly a new step in the pipeline, _drake_ requires a unique object for such an operation.
Would it be possible to catch such operations automatically from _drake_ s side by creating a new object called `param_set_trafo` following the scheme of <object-name_field>?
The `trafo` field of class `ParamSet` cannot be set during construction so I somehow need to do the `$trafo` call afterwards. 

This problems generalizes to any R6 class since often objects are returned in place.
How would _drake_ handle such cases?
There could be some internal temporary object creation going on that tracks this step in the graph.
However, the user would need to know how the follow-up target is named then to continue with it.
However, it would never officially appear in the code and hence the whole workflow/scripts would become unclear.

I found some discussions about in-place replacements 
https://github.com/ropenscilabs/drake-manual/issues/46#issuecomment-447617446
https://github.com/ropensci/drake/issues/722#issuecomment-461873145

(I am aiming to give a workshop on drake and mlr3 in September and worrying if both are a good match)  
(maybe this issue should be split in two)

**Comment by wlandau** [comment]
It would be nice to break immutability with a simpler and more general solution that also solves the [database problem](https://github.com/ropenscilabs/drake-manual/issues/46#issuecomment-447617446). But as you have realized, `drake` is far more function-oriented than object-oriented, so I doubt this is possible. And the complexity penalty from specialized infrastructure tailored to R6 seems more severe than the current user-side inconvenience.

> In theory one could write a wrapper function and apply all member function calls within including a clone of the object to have a new R object to assign the result to. However, this practice becomes tedious for every member function call...The trafo field of class ParamSet cannot be set during construction so I somehow need to do the $trafo call afterwards.

Correct me if I am wrong, but I do not think much adjustment is required. Instead of defining a wrapper function, you can aggregate commands together into blocks. The closure of the `trafo` function below different than in your original plan, but this sort of thing works in the general case.

```r
drake_plan(
  param_set_svm = {
    ParamSet$new(params = list(
      ParamDbl$new("cost", lower = -5, upper = 5),
      ParamDbl$new("gamma", lower = -5, upper = 3)
    )
    param_set_svm$trafo = function(x, param_set) {
      x$cost = 2^x$cost
      x$gamma = 2^x$gamma
      return(x)
    }
  }
)
```

> Because this is clearly a new step in the pipeline...

Well, maybe. Dividing work into targets is more of an art than a science. But broadly speaking, a target should be either

1. A long computation, or
2. An important data object you want to inspect after `make()` is done.

It is usually quick and cheap to modify R6 objects, and half-formed objects are usually forgettable. If I am right about that, it should be fine not create a target for each new modification.

**Comment by wlandau** [comment]
By the way, you mentioned S3. I recently addressed https://github.com/ropensci/drake/issues/959 this weekend, and although only user-defined generics are affected, I am wondering if it has implications for `mlr` workflows.

**Comment by wlandau** [comment]
Also, I am excited to hear about your workshop! Please keep me posted and let me know what I can do to help.

Seems we are both presenting at similar times. I originally created [`learndrake`](https://github.com/wlandau/learndrake) for [R/pharma](http://rinpharma.com/), and that is coming up on August 21.

**Comment by pat-s** [comment]
Ah! I read about `{ }` in the manual but could not get it working immediately.
This seems very nice - this way I could also include things like `future::plan()` without it being assigned as a target.

A small correction to your example above: Seems we need to declare explicit object names within the `{ }`:

```r
param_set_svm = {
  foo = ParamSet$new(params = list(
    ParamDbl$new("cost", lower = -5, upper = 5),
    ParamDbl$new("gamma", lower = -5, upper = 3)
  ))
  foo$trafo = function(x, param_set) {
    x$cost = 2^x$cost
    x$gamma = 2^x$gamma
    return(x)
  }
```

However then, the final object `param_set_svm` is only the second part in the blocks, i.e. the function and not an R6 class.

You can checkout [this repo](https://github.com/mlr-org/mlr-outreach/tree/master/2019_warsaw) for a reprex. Maybe I am overlooking something obvious?

> By the way, you mentioned S3. I recently addressed #959 this weekend, and although only user-defined generics are affected, I am wondering if it has implications for mlr workflows too.

Ok. I cannot really tell without trying if there are implications. Let's hope for the best for now and focus on mlr3 :D

> Also, I am excited to hear about your workshop! Please keep me posted and let me know what I can do to help.
> 
> Seems we are both presenting at similar times. I originally created learndrake for R/pharma, and that is coming up on August 21.

I took a look some weeks ago and it looked promising. 
After a closer look now, I think it could be very valuable for my workshop! I had binder in mind myself (or rstudio.cloud) and you already did all the work again ;)
I have 3.5h in total.
Doing an intro to _drake_ first and then adding one/some dedicated _mlr3_ examples might be the way I would want to go.
Would you accept a PR adding a section "08-use-cases" with a "mlr3" use case in it? This would optimally be tackled after the _drake_ basics have been explained.

**Comment by wlandau** [comment]
> A small correction to your example above: Seems we need to declare explicit object names within the { }

Thanks for pointing that out. Now fixed.

> However then, the final object param_set_svm is only the second part in the blocks, i.e. the function and not an R6 class.

Yes, we have to return the object itself at the end. That should also be fixed now.

> You can checkout this repo for a reprex. Maybe I am overlooking something obvious?

Nope, you're totally right. I just wasn't paying enough attention. Sorry to make you do all that!

> Ok. I cannot really tell without trying if there are implications. Let's hope for the best for now and focus on mlr3 :D

Yup, sounds good. Just something to keep in mind. I do want to make `drake` more OOP-aware, and there may be more quick fixes like #959.

 > Doing an intro to drake first and then adding one/some dedicated mlr3 examples might be the way I would want to go.

Sounds like a reasonable strategy. For `learndrake`, the flow is like this:

1. Talk for 20-30 minutes about `drake`, with a focus on the example I was going to cover: https://wlandau.github.io/learndrake. 
2. Set up the example. (In my case, Keras. Maybe you would want to introduce `mlr3` here.)
3. Add just enough `drake` to (2) to get going.
4. See what happens when you rerun repeated `make()`s over the lifecycle of a project (https://github.com/wlandau/learndrake/tree/master/inst/notebooks/3-flow and http://wlandau.shinyapps.io/learndrakeflow).
5. Advanced plans: http://wlandau.shinyapps.io/learndrakeplans

It does not cover everything, but it does dive deeply into the hardest parts of `drake`, and the focus on one single application helps a lot. I tested it on around 50 of my colleagues last month, and they learned well.

> Would you accept a PR adding a section "08-use-cases" with a "mlr3" use case in it? This would optimally be tackled after the drake basics have been explained.

I think it is important that `learndrake` itself sticks to a single example. What about an entire clone of `learndrake` dedicated to `mlr3`?

**Comment by pat-s** [comment]
> Yes, we have to return the object itself at the end. That should also be fixed now.

Ah too easy. Did so and it worked. Thanks.

> Nope, you're totally right. I just wasn't paying enough attention. Sorry to make you do all that!

Please no worries - I am asking you not the other way round :)

## drake and mlr3

I am running into problems when running the benchmarks now. The inputs seem to be fine and something must be going on when drake is calling the mlr3 functions. 
I tried to inspect a bit but have no clue where to start tbh.
At first I suspected its the future parallelization which might conflict but even sequentially `r_make()` throws errors.
So maybe there is some more adjustment needed on _drakes_ side?
The repo is updated so if you already cloned it you can just pull and call `r_make()`.

Also it looks like we need to set `lock_envir = FALSE` permanently for mlr3 workflows. 
I am not surprised by this since in mlr3 we mutate in place and this might violate the "do not assign to a locked envir" policy.

## workshop structure

Thanks for the input! I think both options would be fine in either way (new repo vs appending to _learndrake_ and making the latter similar to _drake-examples_).

Since it always depends on the audience and we might also need to introduce R6 and OO approaches, we might need to strip the drake part a bit.
So yes, maybe a new stripped version of learndrake might make most sense.
You can then optionally link to this one from _learndrake_ for example.

**Comment by wlandau** [comment]
I ran https://github.com/mlr-org/mlr-outreach/tree/master/2019_warsaw, but I have not been able to reproduce the errors you see. Things I tried

1. Run `r_make()` as-is.
2. Uncomment the `prework` to activate `future.callr` local parallelism.
3. Uncomment the `parallelism` and `jobs` arguments to activate multicore `clustermq` parallelism.
4. Switch the `clustermq` backend to SGE.

All attempts ran smoothly with no warnings or errors. Admittedly, I did set `folds` to 2 and `repeats` to 1 to treat the code as a fast reprex. Maybe the problem happens at scale or is only specific to your system. What errors are you getting specifically?

I used the GitHub versions of `drake`, `mlr3`, `mlr3learners`, and `mlr3tuning`.

```r
> drake_get_session_info()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS:  CENSORED/R-3.6.0/lib64/R/lib/libRblas.so
LAPACK: CENSORED/R-3.6.0/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] R.utils_2.9.0      R.oo_1.22.0        R.methodsS3_1.7.1  drake_7.5.2.9000  
[5] callr_3.3.1        mlr3learners_0.1.1 mlr3tuning_0.1.0   paradox_0.1.0     
[9] mlr3_0.1.1-9000   

loaded via a namespace (and not attached):
 [1] igraph_1.2.4.1    magrittr_1.5      R6_2.4.0          rlang_0.4.0      
 [5] storr_1.2.2       lgr_0.3.1         checkmate_1.9.4   data.table_1.12.2
 [9] cli_1.1.0         base64url_1.4     assertthat_0.2.1  digest_0.6.20    
[13] tibble_2.1.3      crayon_1.3.4      processx_3.4.1    txtq_0.1.4       
[17] ps_1.3.0          compiler_3.6.0    pillar_1.4.2      filelock_1.0.2   
[21] backports_1.1.4   mlr3misc_0.1.1    pkgconfig_2.0.2  
```

**Comment by wlandau** [comment]
Other comments:

- (3) and (4) run smoothly for me even with `lock_envir = TRUE`.
- Can we break up the benchmarks into one target per method? See https://github.com/mlr-org/mlr-outreach/issues/2. I am working on a sketch that uses `drake_plan()` instead of `code_to_plan()` so we can invoke the [DSL](https://ropenscilabs.github.io/drake-manual/plans.html#large-plans).

**Comment by wlandau** [comment]
I took a deeper look at your example, and I have strong recommendations for how to improve `mlr3` + `drake`. I posted a reprex to https://github.com/mlr-org/mlr-outreach/issues/2#issuecomment-516959361. Please let me know what you think.

**Comment by pat-s** [comment]
> Maybe the problem happens at scale or is only specific to your system. What errors are you getting specifically?

Uff. Everything up-to-date here. 

```r
target bm
INFO  [11:22:44.089] Benchmark with 4 resampling iterations 
INFO  [11:22:44.990] Applying learner 'autotuner' on task 'spam' (iter 2/2) 
INFO  [11:22:45.196] Evaluating 100 configurations 
INFO  [11:22:46.473] Benchmark with 300 resampling iterations 
INFO  [11:22:46.475] Applying learner 'classif.svm' on task 'spam' (iter 1/3) 
fail bm
Error : Target `bm` failed. Call `diagnose(bm)` for details. Error message:
  Learner 'autotuner' on task 'spam' failed to fit: Learner 'classif.svm' on task 'spam' failed to fit: attempt to apply non-function
Error: callr subprocess failed: Target `bm` failed. Call `diagnose(bm)` for details. Error message:
  Learner 'autotuner' on task 'spam' failed to fit: Learner 'classif.svm' on task 'spam' failed to fit: attempt to apply non-function
```

Seeing that it runs on your side is at least motivating :) 

> (3) and (4) run smoothly for me even with lock_envir = TRUE.

This is also good!

> Can we break up the benchmarks into one target per method? See mlr-org/mlr-outreach#2. I am working on a sketch that uses drake_plan() instead of code_to_plan() so we can invoke the DSL.

This is what I also recommend and apply in practice in my research projects.
I am also aiming to do this in the workshop but just got stuck while trying the approach above first :)

Let's switch over to https://github.com/mlr-org/mlr-outreach/issues/2 for further debugging related discussions.
