### ISSUE TITLE
creating a sequence of values in map() with `:` not identical to creating the sequence with `c()`

### ISSUE THREAD

**Issue by lorenzwalthert** [ropensci/drake#978]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [ ] Advanced users: verify that the bug still persists in the current development version (i.e. `remotes::install_github("ropensci/drake")`) and mention the [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity) of the [Git commit you install](https://github.com/ropensci/drake/commits/master).

## Description

The arguments to the `map()`  function are not interpreted the same way although the R expressions are equivalent.

## Reproducible example

Provide a minimal reproducible example with code and output that demonstrates the bug. The [`reprex`](https://github.com/tidyverse/reprex) package is extremely helpful for this.

``` r
library(drake)

drake_plan(
  trgt = target(
    1 + .i, 
    transform = map(i = c(1, 2, 3))
  )
)
#> # A tibble: 3 x 2
#>   target command
#>   <chr>  <expr> 
#> 1 trgt_1 1 + .i 
#> 2 trgt_2 1 + .i 
#> 3 trgt_3 1 + .i

drake_plan(
  trgt = target(
    1 + .i, 
    transform = map(i = 1:3)
  )
)
#> # A tibble: 2 x 2
#>   target command
#>   <chr>  <expr> 
#> 1 trgt_1 1 + .i 
#> 2 trgt_3 1 + .i
```

<sup>Created on 2019-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## Session info
<details>
``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.4.4 (2018-03-15)
#>  os       Ubuntu 18.04.2 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Zurich               
#>  date     2019-08-06                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.4.4)
#>  backports     1.1.4   2019-04-10 [1] CRAN (R 3.4.4)
#>  callr         3.2.0   2019-03-15 [1] CRAN (R 3.4.4)
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.4.4)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.4.4)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.4.4)
#>  devtools      2.0.2   2019-04-08 [1] CRAN (R 3.4.4)
#>  digest        0.6.20  2019-07-04 [1] CRAN (R 3.4.4)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.4.4)
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.4.4)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.4.4)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.4.4)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.4.4)
#>  knitr         1.23    2019-05-18 [1] CRAN (R 3.4.4)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.4.4)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.4.4)
#>  pkgbuild      1.0.3   2019-03-20 [1] CRAN (R 3.4.4)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.4.4)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.4.4)
#>  processx      3.4.1   2019-07-18 [1] CRAN (R 3.4.4)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.4.4)
#>  R6            2.4.0   2019-02-14 [1] CRAN (R 3.4.4)
#>  Rcpp          1.0.1   2019-03-17 [1] CRAN (R 3.4.4)
#>  remotes       2.0.4   2019-04-10 [1] CRAN (R 3.4.4)
#>  rlang         0.4.0   2019-06-25 [1] CRAN (R 3.4.4)
#>  rmarkdown     1.13    2019-05-22 [1] CRAN (R 3.4.4)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.4.4)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.4.4)
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.4.4)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.4.4)
#>  testthat      2.1.1   2019-04-23 [1] CRAN (R 3.4.4)
#>  usethis       1.5.0   2019-04-07 [1] CRAN (R 3.4.4)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.4.4)
#>  xfun          0.7     2019-05-14 [1] CRAN (R 3.4.4)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.4.4)
#> 
#> [1] /home/walor/R/x86_64-pc-linux-gnu-library/3.4
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

## Expected output
I'd expect ` map(i = 1:3)`  to give me a plan with 3 rows, as `map(i = c(1, 2, 3))` does.

**Comment by wlandau** [comment]
In the DSL, we need to be able to map over collections of targets and grouping variables.

``` r
library(drake)
drake_plan(
  data = target(
    download(x),
    transform = map(x = c("a", "b"))
  ),
  analysis = target(analyze(data), transform = map(data))
)
#> # A tibble: 4 x 2
#>   target          command        
#>   <chr>           <expr>         
#> 1 data_a          download("a")  
#> 2 data_b          download("b")  
#> 3 analysis_data_a analyze(data_a)
#> 4 analysis_data_b analyze(data_b)
```

<sup>Created on 2019-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

``` r
library(drake)
drake_plan(
  data = target(
    download(x),
    transform = map(x = c("a", "b"))
  ),
  # Map over a grouping variable instead:
  analysis = target(analyze(x), transform = map(x))
)
#> # A tibble: 4 x 2
#>   target     command      
#>   <chr>      <expr>       
#> 1 data_a     download("a")
#> 2 data_b     download("b")
#> 3 analysis_a analyze("a") 
#> 4 analysis_b analyze("b")
```

<sup>Created on 2019-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

``` r
library(drake)
drake_plan(
  simulated = simulate_data(),
  downloaded = download_data(),
  analysis = target(
    analyze(x),
    transform = map(x = c(downloaded, simulated))
  )
)
#> # A tibble: 4 x 2
#>   target              command            
#>   <chr>               <expr>             
#> 1 simulated           simulate_data()    
#> 2 downloaded          download_data()    
#> 3 analysis_downloaded analyze(downloaded)
#> 4 analysis_simulated  analyze(simulated)
```

<sup>Created on 2019-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

To accomplish this, `drake` treats arguments to `map()` as language objects. So unfortunately, in `map(i = 1:3)`, `1:3` gets treated as <code>\`:\`(1, 3)</code> unless you use tidy evaluation.

``` r
library(drake)
drake_plan(
  trgt = target(
    1 + i, 
    transform = map(i = !!(1:3))
  )
)
#> # A tibble: 3 x 2
#>   target  command
#>   <chr>   <expr> 
#> 1 trgt_1L 1 + 1L 
#> 2 trgt_2L 1 + 2L 
#> 3 trgt_3L 1 + 3L
```

<sup>Created on 2019-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Without tidy evaluation, `drake` does not evaluate what we supply to `map()`.

``` r
library(drake)
indices <- c(1, 2, 3)
drake_plan(
  trgt = target(
    1 + i, 
    transform = map(i = indices)
  )
)
#> # A tibble: 1 x 2
#>   target       command    
#>   <chr>        <expr>     
#> 1 trgt_indices 1 + indices
```

<sup>Created on 2019-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I do realize that the behavior with `1:3` is unexpected. However, it is consistent with the rest of the DSL. The end product of `drake_plan()` is code, so we always take symbols literally in the absence of tidy evaluation.

I do mention this particular edge case at https://ropenscilabs.github.io/drake-manual/plans.html#literal-arguments, but I realize it is quite buried and the whole DSL section needs to be refined, re https://github.com/ropenscilabs/drake-manual/issues/78.

**Comment by lorenzwalthert** [comment]
Thanks. The thing is that I tried tidy eval, but not with wrapping stuff into braces. Tidy eval only works with braces, which is surprising to me. Do you think we can fix that? I suppose this is the real edge case then.
``` r
library(drake)
indices <- c(1, 2, 3)
drake_plan(
  trgt = target(
    1 + i, 
    transform = map(i = !!1:3) # with tidy eval
  )
)
#> # A tibble: 2 x 2
#>   target command
#>   <chr>  <expr> 
#> 1 trgt_1 1 + 1  
#> 2 trgt_3 1 + 3
```

<sup>Created on 2019-09-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
Sorry, because of how `rlang` works, I do not think we can fix it without creating an edge case. Extra parentheses are required.

``` r
library(drake)
drake_plan(
  trgt = target(
    1 + i, 
    transform = map(i = !!(1:3))
  )
)
#> # A tibble: 3 x 2
#>   target  command
#>   <chr>   <expr> 
#> 1 trgt_1L 1 + 1L 
#> 2 trgt_2L 1 + 2L 
#> 3 trgt_3L 1 + 3L
```

<sup>Created on 2019-09-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

As a matter of good practice, I tend to recommend `seq()` and `seq_len()` anyway.

``` r
library(drake)
drake_plan(
  trgt = target(
    1 + i, 
    transform = map(i = !!seq_len(3))
  )
)
#> # A tibble: 3 x 2
#>   target  command
#>   <chr>   <expr> 
#> 1 trgt_1L 1 + 1L 
#> 2 trgt_2L 1 + 2L 
#> 3 trgt_3L 1 + 3L
```

<sup>Created on 2019-09-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lorenzwalthert** [comment]
Alright, thanks.
