### ISSUE TITLE
file_in() URL authentication

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#981]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

`file_in()` supports URLs, but there is currently no way to pass along credentials user may need to get eTAGs.

**Comment by wlandau** [comment]
cc @noamross

**Comment by noamross** [comment]
One possibility would be for `file_in()` to take an argument like `curl_options()` which would set the handle options for checking headers  (The `nobody` option I suggest in #982 would be the default but could be overridden).  You would still have to pass your authentication options again in the function call that reads from the URL, but that would be OK I think.

**Comment by noamross** [comment]
Or maybe `file_in` should just have a single, second `options` argument that gets the curl options or anything else that might be thrown at it in the future, which would be easier to carry forward as a property of the target.

**Comment by wlandau** [comment]
`drake` handles arguments to `file_in()` using static code analysis. It detects all the literal strings, puts them in a lightweight hash table, and then converts it into an unnamed character vector. In fact, the dependencies of a piece of code are represented as a list of character vectors.

``` r
drake:::analyze_code( # Walk the AST of some code.
  quote({
    base::sqrt(x)
    file_in("a")
    file_out("b")
  })
)
#> $globals
#> [1] "x"
#> 
#> $namespaced
#> [1] "n-MJQXGZJ2HJZXC4TU"
#> 
#> $file_in
#> [1] "p-ME"
#> 
#> $file_out
#> [1] "p-MI"
```

<sup>Created on 2019-08-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I hesitate to undermine this simplicity for the sake of authentication. On the other hand, we could add an argument to `make()` to allow users to supply credentials for each domain. Does that sound reasonable?

**Comment by noamross** [comment]
The thing that worries me is the variety of mechanisms that sites use for authentication.  But I think if one provides a handle, one could load it with tokens, cookies, passwords, or other header variables. 

Handles _could_ vary by different URLs within a domain, so maybe you can base the it on a partial match? e.g., 

```
curl_handles = list(
`https://ropensci.org/endpoint1/` = curl::new_handle(...),
`https://ropensci.org/endpoint2/` = curl::new_handle(...)
)
```

And `https://ropensci.org/endpoint1/` would apply to `https://ropensci.org/endpoint1/values`, etc.

If the user provides handles then we should probably _modify_ these handles to add the `nobody` option when rehashing the URL with something like:

```
if(!is.null(handle)) {
  handle <- curl::handle_setopt(handle, nobody = TRUE)
} else {
  handle <- new_handle(nobody = TRUE)
}
```

**Comment by wlandau** [comment]
I like your idea of supplying a named list of `curl` handles because it generalizes beyond authentication. And I think we can use partial matching as long as we explain it.

**Comment by wlandau** [comment]
With #982 merged, I think this issue is now actionable. The test case at https://httr.r-lib.org/reference/authenticate.html looks sufficient.

**Comment by wlandau** [comment]
I incorporated https://github.com/ropensci/drake/issues/981#issuecomment-519983040 into https://github.com/ropensci/drake/commit/0ba179b3cd830b8c0c96d573a013f70274d9fa93 covers it. Let's follow up again if it does not work for you.
