### ISSUE TITLE
Map and cross on lists computed within plan

### ISSUE THREAD

**Issue by riccardopinosio** [ropensci/drake#985]
Hello, I am wondering if there is a way to tell the map/cross functions within target() to loop on the elements of a list computed within plan().
Specifically, this applies myfun to each number from 1 to 10 and creates the corresponding targets:

```
parameters <- as.numeric(1:10)
plan <- drake_plan(
  v = target(myfun(i),
             transform = map(i = !!parameters))
)
```

However, this does not achieve the same, but just creates an expression `myfun(parameters)` for a single target `v_parameters`:

```
plan <- drake_plan(
  parameters = as.numeric(1:10),
  v = target(myfun(i),
             transform = map(i = parameters))
)
```

of course, in this case I could just do:

```
plan <- drake_plan(
  v = target(myfun(i),
             transform = map(i = !!as.numeric(1:10)))
)
```
But what if the parameter vector is actually a computed list from a previous expression,
i.e.:

```
plan <- drake_plan(
 parameters = function_that_yields_parameters(...)
  v = target(myfun(i),
             transform = map(i = parameters))
)
```

I'm not sure how to get what I want in this case. Suggestions?

**Comment by wlandau** [comment]
This is the goal of #685. It is a common request, and we are working on it. I put it aside for a while to work on efficiency and infrastructure, and I am OOO from Aug 20 - Sept 11, but I plan to pick it up after that.
