### ISSUE TITLE
add a package option to turn off adding `.gitignore` file

### ISSUE THREAD

**Issue by januz** [ropensci/drake#991]
I understand that for most use cases, it's a good standard to exclude `.drake` contents from version control.

However, I would like to check them in for certain projects in which I want to deliver the cache as part of the reproducible research compendium. I know that I can "just" remove the file after the first run, but I regularly forget to do so after deleting and running `make()` anew.

A package option like `pkgconfig::set_config("drake::write_gitignore" = FALSE)` would be greatly appreciated as I could just set it in `.onLoad()` for the respective projects and forget about it.

**Comment by wlandau** [comment]
I hear you, but because of how complicated `drake` has become, is hesitate to add new arguments to `make()` or `drake_config()`. For the research compendium, maybe automate the removal of .gitignore instead of doing it manually?

```r
# make.R: script that calls make() in the compendium
# ...
unlink(".drake/.gitignore")
make(plan)
```

**Comment by januz** [comment]
Alright, that's a good alternative!
