### ISSUE TITLE
IDEA: Simplify DSL

### ISSUE THREAD

**Issue by mik3y64** [ropensci/drake#993]
I am using the DSL a lot for creating large workflow. It's very good and much better than the old interface evaluate_plan(). One suggestion I'd like to see is to allow users **optionally** omit typing the `transform =` for each target to improve readability. New users can explicitly provide the keyword while for experienced drake users keywords such as map(), cross(), combine() are sufficient to signal the intentions.

```
# short names to tell get_data() what to download:
source <- c("census", "gapminder")

# the current version
drake_plan(
  data = target(
    get_data(from),
    transform = map(from = !!source, .id = FALSE)
  )
)

# what I'd like to see
drake_plan(
  data = target(
    get_data(from),
    map(from = !!source, .id = FALSE)
  )
)
```

 `transform` is a very common usage for large workflow and it makes sense to simplify the codes. My workflows require a lot of `transform` steps and every time I use it I wish I could omit it. It also makes reviewing large drake plan easier. New users can still explicitly provide keyword. It seems like there is no downside to this. What do you think?

Could this be done easily by changing from `target(command = NULL, ...)` 
to `target(command = NULL, transform = NULL, ...)` ?

**Comment by wlandau** [comment]
@mik3y64, I agree on all counts. Now implemented in https://github.com/ropensci/drake/commit/41f2493649b47f3c0be64fd7259a2e5ca3f2805a.

``` r
library(drake)
source <- c("census", "gapminder")
drake_plan(
  data = target(
    get_data(from),
    map(from = !!source, .id = FALSE)
  )
)
#> # A tibble: 2 x 2
#>   target command              
#>   <chr>  <expr>               
#> 1 data   get_data("census")   
#> 2 data_2 get_data("gapminder")
```

<sup>Created on 2019-08-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
